'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{EventEmitter}=require('node:events'),old=require('./android-idle-provider.cjs'),next=require('./android-provider-bounded-v2.cjs');
const origin='http://127.0.0.1:43210',id='android-tracks-0123456789abcdef',tick=()=>new Promise(r=>setImmediate(r));
async function model(provider,bytes=Buffer.from('fixture')){class Session extends EventEmitter{async send(method,p={}){calls.push({method,status:p.responseCode??null,reason:p.errorReason??null});return{};}async detach(){this.closed=true;}}const calls=[],root=new Session(),page=new Session(),api=await provider.install({newBrowserCDPSession:async()=>root},{context:()=>({newCDPSession:async()=>page})},{origin,id,bytes,sha:'a'.repeat(64),expectedScripts:{}});return{api,calls,page,root,request:async(url=origin+'/app.js',method='GET',headers={})=>{const before=calls.length;page.emit('Fetch.requestPaused',{requestId:'PRIVATE',request:{url,method,headers}});await tick();return calls.slice(before);}};}
test('frozen256 control still admits256 and fails257 exactly once',async()=>{const f=await model(old);for(let i=0;i<256;i++){const out=await f.request();assert.equal(out.filter(x=>x.method==='Fetch.continueRequest').length,1);}const out=await f.request();assert.equal(out.filter(x=>x.method==='Fetch.failRequest').length,1);assert.equal(f.api.network.requests,257);assert.deepEqual(f.api.network.errors,['PROVIDER_REQUEST_CAP']);await f.api.dispose();});
test('new512 boundary includes local/meta/OPTIONS/media and rejects513 without retry',async()=>{const f=await model(next);const forms=[[origin+'/app.js','GET',{}],['https://www.googleapis.com/drive/v3/files/'+id,'GET',{}],['https://www.googleapis.com/drive/v3/files/'+id,'OPTIONS',{'access-control-request-headers':'authorization'}],['https://www.googleapis.com/drive/v3/files/'+id+'?alt=media','GET',{Range:'bytes=0-1'}]];for(let i=0;i<512;i++){const out=await f.request(...forms[i%4]);assert.equal(out.some(x=>x.method==='Fetch.failRequest'),false);assert.equal(out.length,1);}assert.equal(f.api.network.local,128);assert.equal(f.api.network.metadata,128);assert.equal(f.api.network.preflights,128);assert.equal(f.api.network.range,128);const out=await f.request(...forms[3]);assert.equal(out.length,1);assert.equal(out[0].method,'Fetch.failRequest');assert.equal(f.api.network.requests,513);assert.equal(f.api.network.range,128);assert.deepEqual(f.api.network.errors,['PROVIDER_REQUEST_CAP']);await tick();assert.equal(f.api.network.requests,513);assert.equal((await f.api.dispose()).providerDetached,true);assert.equal(f.page.listenerCount('Fetch.requestPaused'),0);});
test('24MiB byte cap remains independent of larger request allowance',async()=>{const f=await model(next,Buffer.alloc(2*1024*1024));for(let i=0;i<12;i++)assert.equal((await f.request('https://www.googleapis.com/drive/v3/files/'+id+'?alt=media'))[0].method,'Fetch.fulfillRequest');assert.equal(f.api.network.mediaBytes,24*1024*1024);const out=await f.request('https://www.googleapis.com/drive/v3/files/'+id+'?alt=media');assert.equal(out[0].method,'Fetch.failRequest');assert.equal(f.api.network.mediaBytes,24*1024*1024);assert.equal(f.api.network.requests,13);assert.deepEqual(f.api.network.errors,['PROVIDER_BYTE_CAP']);await f.api.dispose();});
test('exact external target/owned origin boundary stays unchanged',async()=>{const f=await model(next);const out=await f.request('https://www.googleapis.com/drive/v3/files/PRIVATE_OTHER?alt=media');assert.equal(out[0].method,'Fetch.failRequest');assert.equal(f.api.network.range,0);assert.equal(f.api.network.blocked,1);assert.equal(JSON.stringify(f.api.network).includes('PRIVATE_OTHER'),false);await f.api.dispose();});
test('only provider cap changes; classification/RPC/fulfillment/executable/lifetime bytes otherwise equal',()=>{assert.equal(next.LIMITS.requests,512);assert.equal(old.LIMITS.requests,256);assert.equal(next.LIMITS.mediaBytes,old.LIMITS.mediaBytes);assert.equal(next.LIMITS.rpcMs,15000);const before=fs.readFileSync(__dirname+'/android-idle-provider.cjs','utf8'),after=fs.readFileSync(__dirname+'/android-provider-bounded-v2.cjs','utf8');assert.equal(after,before.replace('requests:256,','requests:512,'));const v6=fs.readFileSync(__dirname+'/android-runner-stable-v6.cjs','utf8'),v7=fs.readFileSync(__dirname+'/android-runner-stable-v7.cjs','utf8');assert.equal(v7,v6.replace("providerFactory=require('./android-idle-provider.cjs')","providerFactory=require('./android-provider-bounded-v2.cjs')").replace('android-stable-preparation-manifest.json','android-stable-v7-preparation-manifest.json').replace('android-actual-stable-tablet-tracks-result.json','android-actual-stable-v7-tablet-tracks-result.json'));});
