'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),gate=require('./android-stable-admission.cjs');
const fn=fs.readFileSync(path.join(__dirname,'android-observer-stable-v4.function.js'),'utf8');
async function fixture({pending=false}={}){let time=0,interval=null,callback=null,listeners=0;const id='android-tracks-SYNTHETIC';
 const controllerListeners=new Set(),regListeners=new Set(),workerListeners=new Set(),controller={state:'activated',addEventListener:(_,f)=>workerListeners.add(f),removeEventListener:(_,f)=>workerListeners.delete(f)};
 const registration={active:controller,installing:pending?{}:null,waiting:null,addEventListener:(_,f)=>regListeners.add(f),removeEventListener:(_,f)=>regListeners.delete(f)};
 const serviceWorker={controller,getRegistration:async()=>registration,addEventListener:(_,f)=>controllerListeners.add(f),removeEventListener:(_,f)=>controllerListeners.delete(f)};
 const v={currentTime:2,readyState:4,paused:true,videoWidth:640,videoHeight:360,error:null,hasAttribute:()=>false,requestVideoFrameCallback:f=>(callback=f,1),cancelVideoFrameCallback:()=>{callback=null;},addEventListener:()=>listeners++,removeEventListener:()=>listeners--,getVideoPlaybackQuality:()=>({totalVideoFrames:12})};
 const stats={generation:1,mapping:{commonShift:.2,sourceOrigin:.2},pipeline:{selectedAudioTrackId:3}},cue={startTime:0,endTime:4.8,text:'SYNTHETIC SUBTITLE'};
 const context={navigator:{serviceWorker},window:{__androidTracksMockOwned:true},location:{origin:'http://127.0.0.1:9999'},APP_VERSION:'1.22.0-rc.35',document:{visibilityState:'visible'},innerWidth:824,innerHeight:1191,devicePixelRatio:2.125,
 state:{authAccountKey:'android-tracks-synthetic-account',driveSessionGeneration:1,selected:{id},mediaSession:1,mediaBlobUrl:null},mediaSourceGeneration:1,q0Playback:null,q1RetirementResult:{settled:true},playerTracksRetirementResult:{settled:true},
 q1Playback:{kind:'general',controller:{signal:{aborted:false}},swController:controller,selectedAudioTrackId:3,player:{stats:()=>stats,sourceTime:()=>v.currentTime+.2}},
 playerTracksOwner:{current:()=>true,selectedAudioTrackId:3,inventory:{audioTracks:[{trackId:2,codec:'aac',route:'q1'},{trackId:3,codec:'aac',route:'q1'}]},subtitles:{selectedTrackId:4,tracks:[{trackId:4,supported:true}]}},
 playerSubtitleTextTrack:{mode:'showing',cues:[cue],activeCues:[cue]},el:{videoPlayer:v,playerTracksDialog:{open:true},playerAudioTrack:{value:'3'},playerSubtitleTrack:{value:'4'},playerSheet:{hidden:false}},
 getActiveMediaElement:()=>v,isCurrentMediaEvent:x=>x===v,playerTimeline:()=>({currentTime:v.currentTime,duration:6}),Date:{now:()=>time},setInterval:f=>(interval=f,1),clearInterval:()=>{interval=null;}};
 vm.createContext(context);let failure;try{await vm.runInContext('('+fn+')('+JSON.stringify({origin:context.location.origin,version:context.APP_VERSION,fixtureId:id})+')',context);}catch(e){failure=e;}
 return{api:context.window.__androidTracksObserver,context,v,stats,registration,failure,present:t=>{const f=callback;callback=null;f?.(0,{mediaTime:t,width:640,height:360});},advance:ms=>{time+=ms;interval?.();},listeners:()=>listeners+controllerListeners.size+regListeners.size+workerListeners.size,controllerChanged:()=>{for(const f of controllerListeners)f();},updateFound:()=>{for(const f of regListeners)f();}};
}
test('same generation before seek cannot qualify; fresh current mapped frame does',async()=>{const f=await fixture();f.api.arm('seek2',{target:2,requireAdvance:true,requireAudio3:true});f.present(2);assert.equal(f.api.read().phases[0].first,null);f.stats.generation=2;f.present(2);assert.equal(f.api.read().phases[0].first.clock,2);f.api.stop();assert.equal(f.listeners(),0);});
test('stable-source controller replacement rejects frame and immediately fails lifetime predicate',async()=>{const f=await fixture();f.api.arm('audio3',{target:2,requireAudio3:true});const next={state:'activated',addEventListener(){},removeEventListener(){}};f.context.navigator.serviceWorker.controller=next;f.registration.active=next;f.controllerChanged();f.present(2);const r=f.api.read();assert.equal(r.phases[0].first,null);assert.throws(()=>gate.assertLifetime(r,{errors:[],executingScripts:[],workerVersions:[]}),/LIFETIME_CONTROLLER_REPLACED/);f.api.stop();assert.equal(f.listeners(),0);});
test('pending initial installation rejects before any trace sink/listener is installed',async()=>{const f=await fixture({pending:true});assert.match(f.failure.message,/LIFETIME_REGISTRATION_ADMISSION/);assert.equal(f.api,undefined);assert.equal(f.context.window.__driveOriginalMediaTraceSink,undefined);assert.equal(f.listeners(),0);});
test('file/account/aborted owner drift cannot qualify even on same executing source',async()=>{for(const kind of ['file','account','abort']){const f=await fixture();f.api.arm('audio3',{target:2,requireAudio3:true});if(kind==='file')f.context.state.selected={id:'OTHER'};if(kind==='account')f.context.state.driveSessionGeneration=2;if(kind==='abort')f.context.q1Playback.controller.signal.aborted=true;f.present(2);assert.equal(f.api.read().phases[0].first,null);f.api.stop();}});
test('bounded lifetime lifecycle carries fixed states and removes every listener and sink',async()=>{const f=await fixture();for(let i=0;i<50;i++)f.updateFound();assert.equal(f.api.read().registrationEvents.length,32);f.api.arm('startup');for(let i=0;i<100;i++){f.present(2);f.api.read();}const r=f.api.read();assert.equal(r.phases[0].frames.length,32);assert.equal(r.phases[0].samples.length,64);assert.equal(JSON.stringify(r).includes('android-tracks-SYNTHETIC'),false);assert.equal(JSON.stringify(r).includes('SYNTHETIC SUBTITLE'),false);f.advance(240001);assert.equal(f.api.read().disposed,true);assert.equal(f.listeners(),0);assert.equal(f.context.window.__driveOriginalMediaTraceSink,undefined);});
test('every observed executable worker needs both exact scripts and literal VERSION',()=>{const n={executingScripts:[{worker:1,file:'sw.js',matched:true},{worker:1,file:'media/revision-pin.js',matched:true}],workerVersions:[{worker:1,versionMatched:true}]};assert.equal(gate.executingQualified(n),true);assert.equal(gate.executingQualified({...n,executingScripts:n.executingScripts.slice(0,1)}),false);assert.equal(gate.executingQualified({...n,workerVersions:[{worker:1,versionMatched:null}]}),false);assert.equal(gate.executingQualified({...n,executingScripts:[...n.executingScripts,{worker:2,file:'sw.js',matched:true}]}),false);});
test('mismatched executable bytes/version or noncurrent registration fail lifetime',()=>{const r={latest:{controllerSameInitial:true,controllerActivated:true,registrationActiveCurrent:true,lifetimeReady:true},controllerEvents:[]};assert.equal(gate.assertLifetime(r,{errors:[]}),true);for(const n of [{executingScripts:[{matched:false}]},{workerVersions:[{versionMatched:false}]},{errors:['OWNED_SCRIPT_SOURCE_UNAVAILABLE']}])assert.throws(()=>gate.assertLifetime(r,n),/LIFETIME_/);assert.throws(()=>gate.assertLifetime({latest:{...r.latest,registrationActiveCurrent:false}},{}),/LIFETIME_REGISTRATION/);});
test('immutable preparation rejects changed bytes/path/source before any device action',()=>{const bytes=Buffer.from('fixed'),item=file=>({file,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}),manifest={sourceCommit:'2c2b1244bee0f1a5e500318c83c6e126c5124e34',version:'1.22.0-rc.35',files:Array.from({length:5},(_,i)=>item('android-test'+i+'.cjs'))};assert.equal(gate.verifyPreparation(manifest,()=>bytes),true);assert.throws(()=>gate.verifyPreparation(manifest,()=>Buffer.from('changed')),/DRIFT/);assert.throws(()=>gate.verifyPreparation({...manifest,sourceCommit:'other'},()=>bytes),/REQUIRED/);assert.throws(()=>gate.verifyPreparation({...manifest,files:[{...manifest.files[0],file:'../private'},...manifest.files.slice(1)]},()=>bytes),/REQUIRED/);});
test('combined driver ordering preserves admission before token/media and captures failure before cleanup',()=>{const d=fs.readFileSync(path.join(__dirname,'android-runner-stable-v6.cjs'),'utf8');assert.ok(d.indexOf('stableGate.admit(')<d.indexOf("state.token='synthetic"));assert.ok(d.indexOf('owned passive lifetime observer BEFORE')<d.indexOf("state.token='synthetic"));assert.ok(d.indexOf('DIRECT_AND_SW_PROVIDER_UNQUALIFIED')<d.indexOf('started=Date.now()'));assert.ok(d.indexOf('executing replacement evidence BEFORE normal close')<d.indexOf('finally{\n  if(observer)'));assert.ok(!d.includes('selectOption('));assert.ok(!d.includes('registration.update('));assert.ok(!d.includes('preflightOnly'));assert.ok(d.includes('cleanup.playerRetired=await closePlayer()'));});
