'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),inputs=['qa/q2-audio-compatibility/synthetic-avc-ac3.mp4','qa/q2-audio-compatibility/eac3-source-build/synthetic-avc-eac3-stereo.mp4'];
const output=path.join(__dirname,'q2-dual-audio.mp4'),args=['-v','error','-y','-i',path.join(root,inputs[0]),'-i',path.join(root,inputs[1]),'-map','0:v','-map','0:a','-map','1:a','-c','copy','-disposition:a:0','default','-disposition:a:1','0','-metadata:s:a:0','language=eng','-metadata:s:a:1','language=kor','-movflags','+faststart',output];
cp.execFileSync('ffmpeg',args);const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const probe=f=>JSON.parse(cp.execFileSync('ffprobe',['-v','error','-show_streams','-show_packets','-show_data_hash','sha256','-of','json',f],{encoding:'utf8',maxBuffer:8*1024*1024}));
const originals=inputs.map(p=>({path:p,sha256:sha(fs.readFileSync(path.join(root,p))),probe:probe(path.join(root,p))})),result=probe(output);
assert.equal(result.streams.length,3);assert.equal(result.streams[0].has_b_frames,0);assert.equal(result.streams[0].color_space,'bt709');assert.equal(result.streams[0].color_range,'tv');assert.deepEqual(result.streams.slice(1).map(s=>[s.codec_name,s.sample_rate,s.channels,s.id]),[['ac3','48000',2,'0x2'],['eac3','48000',2,'0x3']]);
const packetView=p=>({pts:p.pts,dts:p.dts,duration:p.duration,size:p.size,data_hash:p.data_hash});for(const [source,index,target] of [[originals[0],0,0],[originals[0],1,1],[originals[1],1,2]])assert.deepEqual(result.packets.filter(p=>p.stream_index===target).map(packetView),source.probe.packets.filter(p=>p.stream_index===index).map(packetView));
fs.writeFileSync(path.join(__dirname,'q2-fixture-provenance.json'),JSON.stringify({scope:'Six-second existing qualified generated fixtures, streamcopy only; no user/cloud media.',ffmpeg:cp.execFileSync('ffmpeg',['-version'],{encoding:'utf8'}).split('\n')[0],args,inputs:originals.map(({path,sha256})=>({path,sha256})),output:{path:path.relative(root,output).replaceAll('\\','/'),bytes:fs.statSync(output).size,sha256:sha(fs.readFileSync(output))},streams:result.streams,packetIdentity:{video:144,ac3:188,eac3:188,allInputPayloadHashPtsDtsDurationSizePreserved:true},probe:result},null,2));console.log('prepared q2 dual streamcopy',sha(fs.readFileSync(output)));
