'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');const {summarize}=require('./partition-summary.cjs'),{attachAlreadyEnabledSession}=require('./range-offset-observer.cjs');const binding=require('./binding.json');
test('readiness brackets ignore old cumulative appends/ready until actual new generation',()=>{
 const sample=(at,generation,phase,appends)=>({at,sourceSame:true,accountSame:true,targetSame:true,visible:true,sourceGeneration:9,session:4,pipeline:{generation,phase,appends}});
 const p={label:'seek50',armedAt:1000,firstTargetFrame:{elapsedMs:1500},beforeInput:{generation:1,sourceGeneration:9,session:4},samples:[sample(1000,1,'ready',5),sample(1250,1,'ready',6),sample(1500,2,'opening',0),sample(1750,2,'buffering',0),sample(2000,2,'buffering',1),sample(2250,2,'ready',2)]};
 const s=summarize({phases:[p]},{records:[],inflight:[],overflowCount:0})[0];assert.equal(s.firstPipelineGenerationAdvance.upperMs,500);assert.equal(s.firstBuffering.upperMs,750);assert.equal(s.firstAppend.upperMs,1000);assert.equal(s.firstReady.upperMs,1250);assert.equal(s.readinessBracketScope,'NEW_GENERATION_ONLY');
 p.samples=[sample(1000,1,'ready',5),{...sample(1100,1,'ready',6),sourceGeneration:10,session:5},sample(1250,null,'ready',6)];const unknown=summarize({phases:[p]},{records:[],inflight:[],overflowCount:0})[0];assert.equal(unknown.firstAppend.upperMs,null);assert.equal(unknown.firstReady.upperMs,null);
});
function fixture(){const target={id:'PRIVATE_ID',name:'PRIVATE_NAME',size:100,mimeType:'video/mp2t',modifiedTime:'PRIVATE_DATE',parents:['PRIVATE_PARENT'],version:'1',headRevisionId:'PRIVATE_REV'},account={accountId:'PRIVATE_ACCOUNT',authAccountKey:'PRIVATE_KEY'},controller={state:'activated'},native={},stats={generation:2,phase:'ready',failure:null,disposed:false,probeInputReused:true};const player={stats:()=>stats},owner={player,kind:'ts',controller:{signal:{aborted:false}},swGeneration:9,session:4,account:account.authAccountKey,accountGeneration:3,swController:controller};
 const c={window:{__resumeReplayTarget30:{target,account},__resumeSwProof:{get:()=>({controller,version:binding.version,sourceCommit:binding.sourceCommit,sourceSHA256:binding.sourceSHA256})}},APP_VERSION:binding.version,navigator:{serviceWorker:{controller}},document:{visibilityState:'visible'},state:{...account,selected:target,driveSessionGeneration:3,mediaSession:4,frameCallbackId:1,mediaBlobUrl:'PRIVATE_BLOB'},el:{playerSheet:{hidden:false}},q1Playback:owner,q0Playback:null,q1Retirement:null,q1RetirementResult:null,mediaSourceGeneration:9,getActiveMediaElement:()=>native,isCurrentMediaEvent:v=>v===native};vm.createContext(c);
 const install=()=>vm.runInContext('('+fs.readFileSync(path.join(__dirname,'retained-stats.function.js'),'utf8')+')('+JSON.stringify(binding)+')',c);
 const retire=()=>{stats.source={readsStarted:3,readsCompleted:2,metadataRequests:7,rangeRequests:3,receivedBytes:1000,releasedBytes:1000};stats.bootstrap={readStart:564,sourceSize:10000,sourceOffset:1050,sourceReceived:486,secret:'PRIVATE_DATA'};stats.disposed=true;stats.phase='cancelled';owner.controller.signal.aborted=true;owner.retirement=Promise.resolve({settled:true});c.q1Retirement=owner.retirement;c.q1RetirementResult={settled:true};c.q1Playback=null;c.state.selected=null;c.state.mediaSession++;c.mediaSourceGeneration++;c.state.frameCallbackId=null;c.state.mediaBlobUrl=null;c.el.playerSheet.hidden=true;};return{c,stats,owner,install,retire};}
test('preclose snapshot is fixed/null, postretirement same generation exposes finite readStart; geometry UNKNOWN',()=>{const f=fixture(),before=f.install();assert.equal(before.preClose.pipeline.bootstrap.readStart,null);f.retire();const r=f.c.window.__rc31LatencyRetainedStats.retired();assert.equal(r.preClose.pipeline.bootstrap.readStart,null);assert.equal(r.preClose.pipeline.phase,'ready');assert.equal(r.postClose.pipeline.bootstrap.readStart,564);assert.equal(r.postClose.pipeline.probeInputReused,true);assert.equal(r.postClose.chosenWindowGeometry,'UNKNOWN');assert.ok(Object.values(r.postClose.fences).every(Boolean));assert.ok(!JSON.stringify(r).includes('PRIVATE_'));f.c.window.__rc31LatencyRetainedStats.stop();assert.throws(()=>f.c.window.__rc31LatencyRetainedStats.retired(),/DISPOSED/);});
test('same captured source generation/player/retirement reject stale positive numeric data',()=>{for(const change of [f=>{f.stats.generation++;},f=>{f.owner.player={stats:()=>f.stats};},f=>{f.c.q1Retirement={};},f=>{f.c.state.authAccountKey='changed';}]){const f=fixture();f.install();f.retire();change(f);assert.ok(Object.values(f.c.window.__rc31LatencyRetainedStats.retired().postClose.fences).some(v=>!v));}});
test('stale native event or wrong current source owner prevents retention',()=>{for(const change of [f=>{f.c.isCurrentMediaEvent=()=>false;},f=>{f.owner.swGeneration++;}]){const f=fixture();change(f);assert.throws(()=>f.install(),/OWNER_ADMISSION/);assert.equal(f.c.window.__rc31LatencyRetainedStats,undefined);}});
test('new one-listener offsets are immediate numeric only, bounded, stop never enables network or changes cookies',()=>{const s=new EventEmitter();s.send=()=>{throw Error('SEND_FORBIDDEN');};const r=attachAlreadyEnabledSession(s,'PRIVATE_ID',{boundMs:5000});r.mark('seek90');for(let n=0;n<70;n++)s.emit('Network.requestWillBeSent',{wallTime:1,requestId:'PRIVATE_REQ',request:{method:'GET',url:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/__drive_media/PRIVATE_ID?mediaOwner=q1&sourceGeneration=9&mediaSession=4&resourceKey=PRIVATE_KEY',headers:{Range:'bytes=564-262707',Authorization:'PRIVATE_TOKEN'}}});const out=r.stop();assert.equal(out.records.length,64);assert.equal(out.records[0].start,564);assert.equal(out.overflow,6);assert.equal(s.listenerCount('Network.requestWillBeSent'),0);assert.ok(!JSON.stringify(out).includes('PRIVATE_'));assert.equal(out.completedSourceReadsProven,false);assert.throws(()=>attachAlreadyEnabledSession(s,'x',{boundMs:360001}),/BOUND/);});
test('only additive numeric diagnostics and phase summary changed; source/action budgets and ownership remain',()=>{const d=fs.readFileSync(path.join(__dirname,'android-latency-partition.cjs'),'utf8'),old=fs.readFileSync(path.resolve(__dirname,'../rc31-passive-latency-partition/android-latency-partition.cjs'),'utf8');for(const p of ["waitFrame('startup',30000)","waitFrame(label,35000)",'overallBound=360000',"c.adb(['shell','input','swipe'",'FRESH_METADATA_MISMATCH','NATIVE_ASCII_SEARCH_UNSUPPORTED'])assert.ok(d.includes(p)&&old.includes(p));assert.ok(d.indexOf('retainedSource=true')<d.indexOf('await close();ownsPlayer=false'));assert.ok(d.includes('RETAINED_SOURCE_OWNER_UNCONFIRMED'));assert.ok(!d.includes('setCookieControls'));assert.equal(typeof require('./root-execute.cjs').execute,'function');});
