'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process'),vm=require('node:vm'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),source='7591044adc1149391265b0e56a93a47252088a47',base='https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/';
const git=f=>cp.execFileSync('git',['show',`${source}:${f}`],{cwd:root,maxBuffer:12*1024*1024});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const version=JSON.parse(git('version.json')).version,mod={exports:null};vm.runInNewContext(git('scripts/public-files.cjs').toString(),{module:mod});
const files=mod.exports,cachedFiles=vm.runInNewContext(git('sw.js').toString().match(/const SHELL_FILES = (\[[\s\S]*?\]);/)[1]).filter(f=>f!=='./').map(f=>f.replace(/^\.\//,''));
const result={source,version,expectedWorker:'1cb22ad7-f866-444a-9401-402187a37fc6',base,producerSha256:hash(fs.readFileSync(__filename)),originalProducerSha256:hash(fs.readFileSync(path.join(root,'qa/candidate-delivery-audit.cjs'))),originalResultSha256:hash(fs.readFileSync(path.join(root,'qa/candidate-rc23-delivery/results.json'))),scope:'Fresh anonymous isolated Chrome public shell only; no account/device/production/data access',passed:false,nominalDeadlineMs:45000,extraObservationLimitMs:90000,observations:[],responses:[],failures:[],workerEvents:[],pageErrors:[]};
let browser,context,page,interval;const started=performance.now(),at=()=>Math.round(performance.now()-started),safeURL=u=>{try{const x=new URL(u);return x.origin===new URL(base).origin?x.pathname:'[external]';}catch{return '[invalid]';}};
async function snapshot(){return page.evaluate(async()=>({version:typeof APP_VERSION==='undefined'?null:APP_VERSION,controlled:Boolean(navigator.serviceWorker.controller),controller:navigator.serviceWorker.controller?.scriptURL,registrations:(await navigator.serviceWorker.getRegistrations()).map(r=>({scope:r.scope,installing:r.installing?.state,waiting:r.waiting?.state,active:r.active?.state})),shells:await caches.keys(),cacheCounts:await Promise.all((await caches.keys()).map(async key=>({key,count:(await (await caches.open(key)).keys()).length}))),accountPresent:typeof state==='undefined'?null:Boolean(state.authAccountKey),candidate:globalThis.__DRIVE_ORIGINAL_RUNTIME__?.candidate,writes:typeof DRIVE_MUTATIONS_ENABLED==='undefined'?null:DRIVE_MUTATIONS_ENABLED}));}
(async()=>{
 assert.equal(cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root}).toString().trim(),source);
 const memory=JSON.parse(cp.execFileSync('powershell',['-NoProfile','-Command','Get-CimInstance Win32_OperatingSystem | Select-Object FreePhysicalMemory,FreeVirtualMemory | ConvertTo-Json -Compress'],{encoding:'utf8',windowsHide:true}));result.launchMemory=memory;
 assert(memory.FreePhysicalMemory>1048576&&memory.FreeVirtualMemory>1572864,'MEMORY_FLOOR');
 browser=await chromium.launch({channel:'chrome',headless:true});context=await browser.newContext();page=await context.newPage();
 page.on('pageerror',e=>result.pageErrors.push({at:at(),message:e.message}));context.on('requestfailed',r=>result.failures.push({at:at(),path:safeURL(r.url()),error:r.failure()?.errorText}));
 context.on('response',r=>{const u=new URL(r.url());if(u.origin===new URL(base).origin&&files.includes(u.pathname.slice(1)))result.responses.push({at:at(),path:u.pathname,status:r.status(),fromServiceWorker:r.fromServiceWorker()});});
 const cdp=await context.newCDPSession(page);for(const name of ['workerRegistrationUpdated','workerVersionUpdated','workerErrorReported'])cdp.on(`ServiceWorker.${name}`,e=>result.workerEvents.push({at:at(),type:name,data:e}));await cdp.send('ServiceWorker.enable');
 result.navigationStartedAt=at();await page.goto(base,{waitUntil:'domcontentloaded',timeout:45000});result.domContentLoadedAt=at();
 interval=setInterval(()=>snapshot().then(s=>result.observations.push({at:at(),...s})).catch(e=>result.observations.push({at:at(),error:e.message})),2000);
 try{await page.waitForFunction(expected=>typeof APP_VERSION!=='undefined'&&APP_VERSION===expected&&navigator.serviceWorker.controller,version,{timeout:45000});result.nominalColdPassed=true;}catch(e){result.nominalColdPassed=false;result.nominalFailure=e.message;result.nominalSnapshot=await snapshot();try{await page.waitForFunction(expected=>typeof APP_VERSION!=='undefined'&&APP_VERSION===expected&&navigator.serviceWorker.controller,version,{timeout:90000});result.lateControlled=true;}catch(e){result.extraFailure=e.message;}}
 result.cold=await snapshot();result.coldCompletedAt=at();
 if(!result.cold.controlled||result.cold.version!==version)return;
 assert.equal(result.cold.accountPresent,false);assert.equal(result.cold.candidate,true);assert.equal(result.cold.writes,false);assert.deepEqual(result.cold.shells,[`drive-original-shell-${version}`]);
 result.cached=[];for(const file of cachedFiles){const bytes=await page.evaluate(async({file,version})=>{const r=await(await caches.open(`drive-original-shell-${version}`)).match(new URL(file,location.href));return r?Array.from(new Uint8Array(await r.arrayBuffer())):null;},{file,version});assert(bytes&&Buffer.from(bytes).equals(git(file)),`CACHE_GIT:${file}`);result.cached.push({file,gitEqual:true,sha256:hash(Buffer.from(bytes))});}
 result.uncachedSourceDownloads=[];for(const file of files.filter(f=>/\.tgz$|\.tar\.gz\.part\d+$/.test(f))){const present=await page.evaluate(async({file,version})=>Boolean(await(await caches.open(`drive-original-shell-${version}`)).match(new URL(file,location.href))),{file,version});assert.equal(present,false);result.uncachedSourceDownloads.push({file,cached:false});}
 await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded',timeout:45000});await page.waitForFunction(expected=>typeof APP_VERSION!=='undefined'&&APP_VERSION===expected&&navigator.serviceWorker.controller,version,{timeout:45000});result.offline=await snapshot();assert.equal(result.offline.accountPresent,false);assert.deepEqual(result.pageErrors,[]);result.passed=result.nominalColdPassed;
})().catch(e=>{result.error=e.message;process.exitCode=1;}).finally(async()=>{clearInterval(interval);await context?.close();await browser?.close();result.ownedResourcesClosed=true;result.recordedAt=new Date().toISOString();result.elapsedMs=at();fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,nominalColdPassed:result.nominalColdPassed,lateControlled:result.lateControlled,cached:result.cached?.length,uncached:result.uncachedSourceDownloads?.length,elapsedMs:result.elapsedMs,error:result.error}));});
