import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import {disposableUiJob} from './job.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),md5=b=>crypto.createHash('md5').update(b).digest('hex'),root=new URL('../../',import.meta.url),here=new URL('./',import.meta.url);
function crc(b){let v=0xffffffff;for(const x of b){v^=x;for(let i=0;i<8;i++)v=(v>>>1)^((v&1)?0xedb88320:0);}return(v^0xffffffff)>>>0;}function chunk(type,data){const t=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);t.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([t,data])),data.length+8);return out;}function png(color){const head=Buffer.alloc(13);head.writeUInt32BE(2);head.writeUInt32BE(2,4);head[8]=8;head[9]=6;const pixels=Buffer.concat([Buffer.from([0]),...Array(2).fill(Buffer.from(color)),Buffer.from([0]),...Array(2).fill(Buffer.from(color))]);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
const fixtures=[[30,120,220,255],[210,70,45,255]].map((color,i)=>{const bytes=png(color);fs.writeFileSync(new URL(`fixture-${i+1}.png`,here),bytes);return {bytes:[...bytes],md5:md5(bytes),sha256:sha(bytes),width:2,height:2};});
const version=JSON.parse(fs.readFileSync(new URL('version.json',root))).version,appHash=sha(fs.readFileSync(new URL('app.js',root)));
const binding=process.env.RC29_SOURCE?{version:'1.22.0-rc.29',source:process.env.RC29_SOURCE,appHash}:null;
const factory=`(function(env,binding,options){return (${disposableUiJob.toString()})(env,binding,${JSON.stringify(fixtures)},options);})`;
fs.writeFileSync(new URL('factory.expression.js',here),factory);
fs.writeFileSync(new URL('build.json',here),JSON.stringify({actualRun:false,source29Pinned:!!binding&&version==='1.22.0-rc.29',binding,preparationAppHash:appHash,preparationVersion:version,factorySHA256:sha(factory),fixtures:fixtures.map(({bytes,...f},i)=>({path:`fixture-${i+1}.png`,bytes:bytes.length,...f})),contract:'Factory requires exact29 source/hash proof at execution; actual unrun. Fixtures are embedded immutable valid2x2 RGBA PNGs; no media bytes taken from originals.'},null,2)+'\n');
console.log(JSON.stringify({actualRun:false,source29Pinned:!!binding&&version==='1.22.0-rc.29',fixtureBytes:fixtures.map(f=>f.bytes.length),factorySHA256:sha(factory)}));
