import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {fixture,binding} from './fixture.mjs';
import {CAPS,ORIGIN} from './probe.mjs';
import {readHeaderState,readHeaderContinuity,clearHeaderContinuity,createHeaderContinuity,CONTINUITY_LIMIT} from './continuity.mjs';
import {build} from './build.mjs';
const renew=f=>{f.state.authGeneration++;f.state.tokenRevision++;f.state.driveSessionGeneration++;f.state.mediaSession++;f.state.expiresAt+=60000;f.state.token='PRIVATE_RENEWED';f.context.generation=f.state.driveSessionGeneration;};
const adopt=(f,j)=>{f.runtime.priorCapsule=j.continuity();f.runtime.options={phase:'videos',maxFiles:64};renew(f);};
function transient(f,index=1,permanent=false){const original=f.runtime.nativeFetch;let attempts=0,flight=0;f.runtime.nativeFetch=async(v,o)=>{const url=new URL(v);if(url.origin===ORIGIN&&url.pathname.endsWith('/'+f.files[index].id)){attempts++;flight=0;}if(url.origin!==ORIGIN&&url.pathname.endsWith('/'+f.files[index].id)&&++flight===1&&attempts>0&&(permanent||attempts===1))throw Object.assign(Error('PRIVATE_NETWORK'),{name:'TypeError'});return original(v,o);};return ()=>attempts;}
test('settled partial registry admits only immutable pre/post successes, private failed ledger and truthful queue',async()=>{
 const f=fixture(3),attempts=transient(f),job=f.make(),r=await job.run();assert.equal(r.complete,true);assert.equal(r.catalogStable,true);assert.equal(r.released,true);assert.equal(r.failure,null);assert.equal(r.files[1].failure,'POSTFLIGHT_FAILED');assert.equal(r.files[1].identityPreflight,true);assert.equal(r.files[1].identityPostflight,false);assert.deepEqual([r.coverage.classified,r.coverage.failed,r.coverage.queuedTotal],[2,1,1]);assert.equal(r.coverage.allEligiblePrefixesValidated,false);
 const privateState=readHeaderState(job.continuity(),f.context,binding);assert.deepEqual(privateState.records.map(r=>r.identity.fileId),[f.files[0].id,f.files[2].id]);assert.equal(privateState.attempts.find(a=>a.identity.fileId===f.files[1].id).count,1);assert.equal(attempts(),1);assert.deepEqual(Object.keys(job.continuity()),['schema']);assert(!JSON.stringify(r).includes('PRIVATE_'));assert(!JSON.stringify(job.continuity()).includes('PRIVATE_'));assert.equal(f.listeners.size,0);
});
test('one extra fresh transient attempt survives renewal, preserves successful proofs and then completes eligible prefixes',async()=>{
 const f=fixture(3),reads=transient(f),first=f.make();await first.run();const old=readHeaderState(first.continuity(),f.context,binding);adopt(f,first);f.calls.length=0;const next=f.make(),r=await next.run();assert.equal(reads(),2);assert.equal(r.mediaRequests,1);assert.equal(r.coverage.carriedImmutableByCatalog,2);assert.deepEqual([r.coverage.classified,r.coverage.failed,r.coverage.queuedTotal],[3,0,0]);assert.equal(r.coverage.allEligiblePrefixesValidated,true);assert.equal(r.wholeCorpusComplete,false);const state=readHeaderState(next.continuity(),f.context,binding);assert.equal(state.attempts.find(a=>a.identity.fileId===f.files[1].id).count,2);assert.equal(state.records[0].evidenceEpoch,old.records[0].evidenceEpoch);assert.equal(r.metadataRequests,18);assert(f.calls.filter(c=>c.url.origin!==ORIGIN).every(c=>c.init.headers.get('Authorization')==='Bearer PRIVATE_RENEWED'));
 adopt(f,next);const final=f.make(),s=await final.run();assert.equal(s.mediaRequests,0);assert.equal(s.coverage.classified,3);assert.equal(reads(),2);
});
test('persistent transient failure becomes exhausted after two attempts; other queued files continue and all-eligible stays false',async()=>{
 const f=fixture(130),reads=transient(f,1,true);f.runtime.options={phase:'videos',maxFiles:64};let capsule=null,last;
 for(let i=0;i<4;i++){f.runtime.priorCapsule=capsule;renew(f);const j=f.make();last=await j.run();assert.equal(last.complete,true);assert(last.mediaRequests<=64);assert(last.metadataRequests<=144);capsule=j.continuity();}
 assert.equal(reads(),2);assert.deepEqual([last.coverage.denominator,last.coverage.classified,last.coverage.failed,last.coverage.retryExhausted,last.coverage.queuedTotal],[130,129,1,1,0]);assert.equal(last.coverage.allEligiblePrefixesValidated,false);assert.equal(readHeaderState(capsule,f.context,binding).attempts.find(a=>a.identity.fileId===f.files[1].id).count,2);assert.equal(readHeaderContinuity(capsule,f.context,binding).length,129);
});
test('payload/protocol failures and missing immutable baseline are exhausted without an extra identical attempt',async()=>{
 for(const mode of ['payload','status','preflight']){const f=fixture(3),original=f.runtime.nativeFetch;let badCalls=0;f.runtime.nativeFetch=async(v,o)=>{const url=new URL(v),bad=url.pathname.endsWith('/'+f.files[1].id);if(bad&&((mode==='preflight'&&url.origin!==ORIGIN)||(mode!=='preflight'&&url.origin===ORIGIN))){badCalls++;if(mode==='preflight')throw Error('PRIVATE_PREFLIGHT');if(mode==='status')return new Response('PRIVATE_BAD',{status:200});return new Response(Buffer.from('<html>'+'.'.repeat(934)),{status:206,headers:{'Content-Range':'bytes 0-939/'+f.files[1].size,'Content-Length':'940','Accept-Ranges':'bytes','Cache-Control':'no-store'}});}return original(v,o);};const first=f.make(),r=await first.run();assert.equal(r.complete,true);assert.equal(r.coverage.retryPending,0);assert.equal(r.coverage.retryExhausted,1);assert.equal(r.coverage.failed,1);adopt(f,first);const next=f.make(),s=await next.run();assert.equal(s.mediaRequests,0);assert.equal(badCalls,1);assert.equal(s.coverage.failed,1);assert.equal(s.coverage.allEligiblePrefixesValidated,false);}
});
test('retry requires unchanged catalog identity and fresh strong checksum/revision before any new media',async()=>{
 for(const change of [f=>f.files[1].version='123456790',f=>f.files[1].sha256Checksum='f'.repeat(64),f=>f.files[1].headRevisionId='PRIVATE_DIFFERENT_REV']){const f=fixture(3);transient(f);const first=f.make();await first.run();adopt(f,first);change(f);f.calls.length=0;const next=f.make(),r=await next.run();assert.equal(r.complete,false);assert.equal(r.failure,'IDENTITY_MISMATCH');assert.equal(r.mediaRequests,0);assert.equal(next.continuity(),null);assert.equal(r.released,true);}
});
test('live identity drift is fatal despite bounded-probe postflight masking; no partial capsule published',async()=>{
 const f=fixture(3),original=f.runtime.nativeFetch;f.runtime.nativeFetch=async(v,o)=>{const r=await original(v,o);if(new URL(v).origin===ORIGIN)f.files[0].sha256Checksum='f'.repeat(64);return r;};const job=f.make(),r=await job.run();assert.equal(r.failure,'IDENTITY_MISMATCH');assert.equal(r.complete,false);assert.equal(job.continuity(),null);assert.equal(r.mediaRequests,1);assert.equal(r.released,true);
});
test('source/controller/account/current owner/catalog/cleanup failures stay fatal and cannot publish continuity',async()=>{
 for(const mutate of [f=>f.state.tokenRevision++,f=>f.runtime.getMediaSourceGeneration=()=>6,f=>f.runtime.navigator.serviceWorker.controller={},f=>f.state.authAccountKey='PRIVATE_OTHER']){const f=fixture(3),fetch=f.runtime.nativeFetch;f.runtime.nativeFetch=async(v,o)=>{const r=await fetch(v,o);if(new URL(v).origin===ORIGIN)mutate(f);return r;};const j=f.make(),r=await j.run();assert.equal(r.complete,false);assert.equal(r.failure,'OWNER_CHANGED');assert.equal(j.continuity(),null);assert.equal(r.mediaRequests,1);assert.equal(r.released,true);assert.equal(f.listeners.size,0);}
 const f=fixture(3);f.dependencies.compareInventory=()=>{throw Error('PRIVATE_DRIFT');};const j=f.make(),r=await j.run();assert.equal(r.failure,'CATALOG_DRIFT');assert.equal(j.continuity(),null);assert.equal(r.released,true);
 const g=fixture(3);let releases=0;g.runtime.nativeFetch=async()=>({status:200,body:{getReader:()=>({read:()=>Promise.reject(new DOMException('PRIVATE_READ','AbortError')),cancel:()=>Promise.reject(new DOMException('PRIVATE_CANCEL','AbortError')),releaseLock(){releases++;}})}});const q=g.make(),s=await q.run();assert.equal(s.failure,'CLEANUP_FAILED');assert.equal(q.continuity(),null);assert.equal(s.mediaRequests,0);assert.equal(releases,1);assert.equal(s.released,true);
});
test('foreign/forged/old/account/root/source/hash handles fail before metadata or media and cannot reset attempt limits',async()=>{
 const f=fixture(3),j=f.make();await j.run();const handle=j.continuity();for(const change of [g=>g.context.rootId='PRIVATE_OTHER',g=>g.state.authAccountKey='PRIVATE_OTHER',g=>{g.dependencies.binding={...binding,sourceCommit:'b'.repeat(40)};g.runtime.getSWIdentity=()=>({...binding,sourceCommit:'b'.repeat(40),controller:g.runtime.navigator.serviceWorker.controller});}]){const g=fixture(3);g.runtime.priorCapsule=handle;change(g);const q=g.make(),r=await q.run();assert.equal(r.failure,'CONTINUITY_REJECTED');assert.equal(g.calls.length,0);assert.equal(q.continuity(),null);}
 assert.throws(()=>readHeaderState({schema:handle.schema},f.context,binding),/CONTINUITY_REJECTED/);const old=await import('../rc31-corpus-content-continuity/continuity.mjs');const oldHandle=old.createHeaderContinuity(f.context,binding,readHeaderContinuity(handle,f.context,binding));assert.throws(()=>readHeaderState(oldHandle,f.context,binding),/CONTINUITY_REJECTED/);assert.throws(()=>readHeaderState(handle,f.context,{...binding,sourceSHA256:{...binding.sourceSHA256,'app.js':'a'.repeat(64)}}),/CONTINUITY_REJECTED/);clearHeaderContinuity(handle);assert.throws(()=>readHeaderState(handle,f.context,binding),/CONTINUITY_REJECTED/);
});
test('capsule copy ownership, max8192 registry, max2 attempts, unchanged byte/request/file/job budgets and reserve',async()=>{
 const f=fixture(80);f.runtime.options={phase:'videos',maxFiles:64};const before=f.files[0].data.slice(),j=f.make(),r=await j.run();assert.equal(r.mediaRequests,64);assert.equal(r.mediaBytes,60160);assert.equal(r.metadataRequests,144);assert(r.batches.every(b=>b.attempted===8));assert(f.files[0].data.equals(before));assert.deepEqual([CAPS.files,CAPS.metadataRequests,CAPS.metadataBytes,CAPS.fileMs,CAPS.runMs],[64,512,67108864,50000,600000]);const state=readHeaderState(j.continuity(),f.context,binding);state.records[0].content.sha256Checksum='f'.repeat(64);state.attempts[0].count=0;assert.equal(readHeaderState(j.continuity(),f.context,binding).attempts[0].count,1);assert.equal(readHeaderState(j.continuity(),f.context,binding).records[0].content.sha256Checksum,'e'.repeat(64));assert.throws(()=>createHeaderContinuity(f.context,binding,[],[{...state.attempts[0],count:3}]),/CONTINUITY_LIMIT/);assert.throws(()=>createHeaderContinuity(f.context,binding,[],Array.from({length:CONTINUITY_LIMIT+1},()=>state.attempts[0])),/CONTINUITY_LIMIT/);
 const g=fixture(20),fetch=g.runtime.nativeFetch;g.runtime.nativeFetch=async(v,o)=>{const s=await fetch(v,o);if(new URL(v).origin===ORIGIN)g.setClock(550000);return s;};const s=await g.make().run();assert.equal(s.mediaRequests,1);assert.equal(s.inventoryRuns,2);assert.equal(s.coverage.queuedTotal,19);assert.equal(s.complete,true);
});
test('metadata limits remain fatal with no automatic retry or registry',async()=>{
 const f=fixture(3);f.runtime.nativeFetch=async()=>new Response('x'.repeat(CAPS.metadataResponseBytes+1));const j=f.make(),r=await j.run();assert.equal(r.failure,'METADATA_LIMIT');assert.equal(r.metadataRequests,1);assert.equal(j.continuity(),null);assert.equal(r.mediaRequests,0);
 const g=fixture(3),original=g.dependencies.inventoryRunner;g.dependencies.inventoryRunner=async args=>{for(let i=0;i<292;i++)await args.driveFetch('https://www.googleapis.com/drive/v3/about');return original(args);};const q=g.make(),s=await q.run();assert.equal(s.failure,'METADATA_LIMIT');assert.equal(s.metadataRequests,512);assert.equal(s.mediaRequests,0);assert.equal(q.continuity(),null);
});
test('missing immutable validator exhausts only its file, preserving other validated entries without retry',async()=>{
 const f=fixture(3);f.files[1].headRevisionId=null;f.files[1].sha256Checksum=null;const j=f.make(),r=await j.run();assert.equal(r.complete,true);assert.deepEqual([r.coverage.classified,r.coverage.failed,r.coverage.retryExhausted,r.coverage.queuedTotal],[2,1,1,0]);assert.equal(r.mediaRequests,2);assert.equal(readHeaderContinuity(j.continuity(),f.context,binding).length,2);adopt(f,j);const q=f.make(),s=await q.run();assert.equal(s.mediaRequests,0);assert.equal(s.coverage.failed,1);
});
test('generated frozen factory executes real inherited inventory/facade plus partial continuation in a synthetic lexical app',async()=>{
 const f=fixture(3),controller=f.runtime.navigator.serviceWorker.controller,s=f.state,self={};Object.assign(s,{accountMediaState:{liked:[]},accountStateWriterId:'PRIVATE_WRITER',accountStateRevision:1,accountStateLoaded:true,accountStateSyncPromise:null,accountStateSyncTimer:null,accountStateSyncRetryTimer:null,accountStateSyncError:null,playbackSession:3});let identityReads=0,transport=0;
 const sandbox={state:s,APP_VERSION:binding.version,DRIVE_MUTATIONS_ENABLED:false,ACCOUNT_STATE_WRITES_ENABLED:true,navigator:f.runtime.navigator,location:f.runtime.location,document:f.runtime.document,top:self,self,q1RetirementResult:f.runtime.getQ1RetirementResult(),q1Playback:null,mediaSourceGeneration:5,playerMediaPriorityActive:false,hasUsableToken:()=>true,accountMediaStatesEqual:(a,b)=>JSON.stringify(a)===JSON.stringify(b),window:{addEventListener(){},removeEventListener(){}},URL,Headers,TextDecoder,Uint8Array,AbortController,DOMException,performance,setTimeout,clearTimeout,fetch:async(v,o)=>{transport++;const url=new URL(v);if(url.origin!==ORIGIN){if(url.pathname.endsWith('/files'))return Response.json({files:f.files.map(row=>({...row,data:undefined})),incompleteSearch:false});if(url.pathname.endsWith('/'+f.context.rootId))return Response.json(f.pass.rootBefore);if(url.pathname.endsWith('/'+f.files[1].id)&&url.searchParams.get('fields').includes('headRevisionId')&&++identityReads===2)throw Error('PRIVATE_TRANSIENT');}return f.runtime.nativeFetch(v,o);}};
 const a=await build(),entry=vm.runInNewContext(a.factory,sandbox),proof={get:()=>({...binding,controller})},ctx=JSON.stringify({accountKey:s.accountId,generation:s.driveSessionGeneration,rootId:f.context.rootId,priorityFileId:f.context.priorityFileId});
 async function settle(job){for(let n=0;n<200&&!job.poll().done;n++)await new Promise(r=>setImmediate(r));assert.equal(job.poll().done,true);return job.poll().summary;}
 const j=entry(ctx,proof,null,{phase:'videos',maxFiles:64}),r=await settle(j);assert.equal(r.complete,true,JSON.stringify(r));assert.equal(r.inventoryRuns,2);assert.deepEqual([r.coverage.classified,r.coverage.failed,r.coverage.queuedTotal],[2,1,1]);assert.equal(r.writeRequests,0);assert(!JSON.stringify(r).includes('PRIVATE_'));const prior=j.continuity();assert(prior);s.tokenRevision++;s.token='PRIVATE_RENEWED';const q=entry(ctx,proof,prior,{phase:'videos',maxFiles:64}),next=await settle(q);assert.equal(next.mediaRequests,1);assert.equal(next.coverage.classified,3);assert.equal(next.coverage.failed,0);assert.equal(next.coverage.carriedImmutableByCatalog,2);assert.equal(next.inventoryRuns,2);
 const before=transport,other=vm.runInNewContext(a.factory,sandbox),foreign=other(ctx,proof,prior,{phase:'videos',maxFiles:64}),bad=await settle(foreign);assert.equal(bad.failure,'CONTINUITY_REJECTED');assert.equal(transport,before);assert.equal(entry.clearContinuity(prior),true);entry.clearContinuity(q.continuity());
});
test('deterministic new installer pins immutable32 and exact inherited facade/producers, no global side effects or private imports',async()=>{
 const a=await build(),b=await build();assert.equal(a.expression,b.expression);assert.equal(a.provenance.actualExecution,false);assert.equal(a.provenance.historicalActual63NotImported,true);assert.equal(a.provenance.metadataFileDeadlineMs,10000);const box={setTimeout,clearTimeout},entry=vm.runInNewContext(a.expression,box);assert.deepEqual(Object.keys(box),['setTimeout','clearTimeout']);const controller={state:'activated'},proof={get:()=>({...binding,controller})},ctx=JSON.stringify({accountKey:'PRIVATE_ACCOUNT',rootId:'PRIVATE_ROOT',priorityFileId:'PRIVATE_FILE',generation:1});const r=entry(ctx,proof);assert(!JSON.stringify(r.read()).includes('PRIVATE_'));assert.equal(r.read().jobs.length,0);assert.equal(r.read().freshRegistry,true);r.cleanup();assert.equal(r.read().disposed,true);assert.throws(()=>entry(ctx,{get:()=>({...binding,sourceCommit:'b'.repeat(40),controller})}),/RUNNER_PROOF/);
});
