import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import vm from 'node:vm';
import {disposableUiJob as originalJob} from '../rc31-disposable-ui-preparation/job.mjs';
import {disposableUiJob as correctedJob} from './job.mjs';
const base = new URL('../rc31-disposable-ui-preparation/', import.meta.url);
const original = fs.readFileSync(new URL('facade.function.js', base), 'utf8');
const facade = fs.readFileSync(new URL('../rc31-disposable-refresh-facade/facade.function.js', import.meta.url), 'utf8');
const originalFactoryBytes=fs.readFileSync(new URL('factory.expression.js',base));
const factoryBytes=fs.readFileSync(new URL('./factory.expression.js',import.meta.url));
const factoryHash = 'de300ac0103fd5928fc3c7550d4b9e8abe7a6718019d46abf9ea30a17b344e9b';
const run='11111111-1111-4111-8111-111111111111',binding={version:'1.22.0-rc.31',source:'a'.repeat(40),appHash:'b'.repeat(64)},fixtures=[1,2].map(i=>{const bytes=fs.readFileSync(new URL(`fixture-${i}.png`,base));return {bytes:[...bytes],md5:crypto.createHash('md5').update(bytes).digest('hex')};});
function backend({failPost=0,unknownChild=false,foreignTag=false,storageFailure=false}={}){const storage=new Map(),files=new Map(),calls=[];let post=0;const root={id:'fixture-root',version:'1',mimeType:'application/vnd.google-apps.folder',trashed:false,ownedByMe:true,capabilities:{canAddChildren:true}},owner={accountId:'fixture-account',accountKey:'fixture-key',auth:1,data:1,token:'fixture-secret',revision:1,controller:{state:'activated'},signal:new AbortController().signal,version:binding.version,source:binding.source,appHash:binding.appHash,safe:true,driveWrite:true};const env={read:()=>({...owner}),uuid:()=>run,storage:{getItem:k=>storage.get(k)??null,setItem(k,v){if(storageFailure)throw Error('storage');storage.set(k,v);}},lifecycle:new EventTarget(),fetch:async(address,options)=>{const u=new URL(address),id=u.pathname.split('/').at(-1);calls.push({method:options.method,url:u.pathname});if(id==='root')return Response.json(root);if(id==='generateIds')return Response.json({space:'drive',ids:['fixture-folder-a','fixture-folder-b','fixture-image-1','fixture-image-2']});if(options.method==='POST'){post++;const saved=JSON.parse(storage.get(`drive-original.qa.disposable.${run}.recovery`));assert.equal(saved.planned[post-1].sent,true);assert.equal(saved.created.length,post-1);let meta;if(options.body instanceof Blob){const raw=Buffer.from(await options.body.arrayBuffer()),text=raw.toString('latin1');meta=JSON.parse(text.match(/\r\n\r\n(\{.*?\})\r\n--/s)[1]);const start=text.indexOf('Content-Type: image/png\r\n\r\n')+27,end=text.lastIndexOf('\r\n--'),png=raw.subarray(start,end);assert.deepEqual(png,Buffer.from(fixtures[Number(meta.appProperties.qaRole.at(-1))-1].bytes));meta.size=String(png.length);meta.md5Checksum=crypto.createHash('md5').update(png).digest('hex');}else meta=JSON.parse(options.body);Object.assign(meta,{version:'1',trashed:false,ownedByMe:true,capabilities:{canAddChildren:true,canTrash:true,canUntrash:true,canMoveItemWithinDrive:true}});files.set(meta.id,meta);if(post===failPost)throw Error('response-loss');return Response.json({id:meta.id});}if(u.pathname==='/drive/v3/files'){const parent=u.searchParams.get('q').match(/^'([^']+)'/)[1];return Response.json({incompleteSearch:false,files:[...files.values()].filter(f=>f.parents[0]===parent&&!f.trashed).map(f=>structuredClone(f)).concat(unknownChild?[{id:'original-unknown',ownedByMe:true,trashed:false,parents:[parent],appProperties:{qaRun:run}}]:[])});}const found=files.get(id);if(!found)return Response.json({}, {status:404});if(options.method==='PATCH'){const body=JSON.parse(options.body);if('trashed'in body)found.trashed=body.trashed;if(u.searchParams.has('addParents'))found.parents=[u.searchParams.get('addParents')];found.version=String(Number(found.version)+1);}const meta=structuredClone(found);if(foreignTag)meta.appProperties.qaRun='foreign';return Response.json(meta);}};return {env,owner,storage,calls,files,start:options=>disposableUiJob(env,binding,fixtures,options)};}
function fixture(config={}) {
  const b=backend(config), owner=b.owner, aborter=new AbortController(); owner.signal=aborter.signal;
  const state={authStatus:'online',accountStateLoaded:true,accountStateLoadingPromise:null,accountStateAbortController:{signal:owner.signal}};
  for(const [key,field] of Object.entries({accountId:'accountId',authAccountKey:'accountKey',authGeneration:'auth',driveSessionGeneration:'data',token:'token',tokenRevision:'revision'}))Object.defineProperty(state,key,{get:()=>owner[field],set:value=>{owner[field]=value;}});
  let hook=()=>{},activated=null;
  const env={APP_VERSION:binding.version,DRIVE_MUTATIONS_ENABLED:false,navigator:{serviceWorker:{controller:owner.controller},onLine:true},state,location:{origin:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev'},top:1,self:1,document:{visibilityState:'visible'},window:b.env.lifecycle,crypto:{randomUUID:()=>run},localStorage:b.env.storage,hasAuthCapability:()=>owner.driveWrite,hasUsableToken:()=>true,playerMediaPriorityActive:false,q1Playback:null,q1RetirementResult:{settled:true},activateDisposableDriveMutationLease:options=>{activated=options;return Object.freeze({close(){}});},fetch:async(address,options)=>{hook(address,options);return b.env.fetch(address,options);},URLSearchParams,AbortController,AbortSignal,Blob,TextDecoder,setTimeout,clearTimeout};
  const proof={get:()=>({version:binding.version,sourceCommit:owner.source,sourceSHA256:{'app.js':owner.appHash},controller:env.navigator.serviceWorker.controller})};
  const factory=vm.runInNewContext(factoryBytes.toString(),env);
  const open=(options)=>vm.runInNewContext('('+facade+')',env)(factory,binding,proof,options);
  const openOriginal=(options)=>vm.runInNewContext('('+facade+')',env)(vm.runInNewContext(originalFactoryBytes.toString(),env),binding,proof,options);
  return {...b,env,state,proof,open,openOriginal,aborter,hook:fn=>{hook=fn;},activated:()=>activated};
}
const priorJob=fs.readFileSync(new URL('job.mjs',base),'utf8'),newJob=fs.readFileSync(new URL('./job.mjs',import.meta.url),'utf8');
const helper=" const stableMetadata=value=>JSON.stringify((function sort(item){if(Array.isArray(item))return item.map(sort);if(item!==null&&typeof item==='object')return Object.fromEntries(Object.keys(item).sort().map(key=>[key,sort(item[key])]));return item;})(value));\n";
const reverseKeys=value=>Array.isArray(value)?value.map(reverseKeys):value!==null&&typeof value==='object'?Object.fromEntries(Object.keys(value).reverse().map(k=>[k,reverseKeys(value[k])])):value;
async function createdFixture(){const f=fixture(),job=f.openOriginal();try{assert.equal((await job.create()).passed,true);}finally{job.clear();}return f;}
function changingReads(f,transform){const fetch=f.env.fetch,seen=new Map();f.env.fetch=async(address,options)=>{const response=await fetch(address,options),meta=await response.json(),id=new URL(address).pathname.split('/').at(-1);if(f.files.has(id)&&options.method==='GET'){const n=(seen.get(id)||0)+1;seen.set(id,n);return Response.json(transform(meta,n,id));}return Response.json(meta,{status:response.status});};}
test('new job differs solely by complete structural serialization; factory adds explicit recovery admission',()=>{
  assert.equal(crypto.createHash('sha256').update(originalFactoryBytes).digest('hex'),factoryHash);
  assert.equal(newJob,priorJob.replace(' const error=code=>',helper+' const error=code=>').replace('JSON.stringify(baseline)!==JSON.stringify(result)','stableMetadata(baseline)!==stableMetadata(result)'));
  assert.ok(factoryBytes.toString().includes("if(!options||typeof options.recoveryRun!=='string')throw Error('QA31_RECOVERY_ONLY')"));
  assert.equal(factoryBytes.toString(),originalFactoryBytes.toString().replace(originalJob.toString(),correctedJob.toString()).replace('(function(env,binding,options){return ',"(function(env,binding,options){if(!options||typeof options.recoveryRun!=='string')throw Error('QA31_RECOVERY_ONLY');return "));
  for(const text of ['Date.now()-start<120000','setTimeout(()=>local.abort(),15000)','++requests>80','++writes>16','length>65536||bytes>1048576'])assert.ok(factoryBytes.toString().includes(text));
});
test('new factory denies creation/no explicit recovery before storage or network',()=>{const f=fixture();for(const options of [undefined,{}, {recoveryRun:null},{recoveryRun:2}])assert.throws(()=>f.open(options),/QA31_RECOVERY_ONLY/);assert.equal(f.calls.length,0);assert.equal(f.storage.size,0);assert.throws(()=>f.open({recoveryRun:run}),/ledger/);assert.equal(f.calls.length,0);});
test('same raw metadata with shuffled nested object keys captures stable complete receipts',async()=>{const f=await createdFixture();changingReads(f,(meta,n)=>n===2?reverseKeys(meta):meta);const job=f.open({recoveryRun:run});f.state.accountStateLoadingPromise=Promise.resolve();try{const result=await job.capture();assert.equal(result.passed,true);assert.equal(result.verified,4);assert.equal(result.snapshotStable,true);assert.equal(result.requests,13);assert.equal(result.writes,0);assert.equal(JSON.parse(job.privateText()).snapshot.length,4);}finally{job.clear();}});
test('every actual value, added/removed field, array order/type/version/checksum/tag/parent drift denies capture',async()=>{
  const modes=['value','added','removed','array-order','type','version','checksum','tag','parent'];
  for(const mode of modes){const f=await createdFixture();changingReads(f,(meta,n,id)=>{meta.extension={ordered:['a','b'],kind:1,value:'same'};if(n!==2||id!=='fixture-image-1')return meta;if(mode==='value')meta.extension.value='different';if(mode==='added')meta.extension.extra=true;if(mode==='removed')delete meta.extension.value;if(mode==='array-order')meta.extension.ordered.reverse();if(mode==='type')meta.extension.kind='1';if(mode==='version')meta.version='2';if(mode==='checksum')meta.md5Checksum='changed';if(mode==='tag')meta.appProperties.qaRun='foreign';if(mode==='parent')meta.parents=['fixture-folder-b'];return meta;});const job=f.open({recoveryRun:run});try{const result=await job.capture();assert.equal(result.passed,false,mode);assert.ok(['drift','metadata','png_receipt'].includes(result.code),mode+':'+result.code);assert.equal(result.writes,0);assert.equal(job.summary().created,4);}finally{job.clear();}}
});
test('recovery still uses known ledger IDs and exact tagged PNG cleanup; no DELETE or POST',async()=>{const f=await createdFixture(),before=f.calls.length;const job=f.open({recoveryRun:run});try{await assert.rejects(job.create(),/ledger/);assert.equal(f.calls.length,before);const result=await job.cleanup({mode:'trash-all-recoverable'});assert.equal(result.passed,true);assert.equal(result.writes,4);assert.ok([...f.files.values()].every(row=>row.trashed));assert.ok(f.calls.slice(before).every(c=>['GET','PATCH'].includes(c.method)));}finally{job.clear();}});
