const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const root=path.resolve(__dirname,'../..'),leaf=__dirname,sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const inspect=rel=>{const b=fs.readFileSync(path.join(root,rel));return {path:rel,bytes:b.length,sha256:sha(b)};};
const historical=['qa/q2-audio-compatibility/sourcebuilt-evidence-manifest.json','qa/q2-audio-compatibility/eac3-source-build/evidence-manifest.json','qa/q2-audio-product-preparation/evidence-manifest.json'].map(p=>{const m=JSON.parse(fs.readFileSync(path.join(root,p)));return{...inspect(p),bindings:m.files.length,mismatches:m.files.filter(x=>sha(fs.readFileSync(path.join(root,x.path)))!==x.sha256).map(x=>x.path)};});
fs.writeFileSync(path.join(leaf,'historical-integrity.json'),JSON.stringify(historical,null,2)+'\n');
const runtime=['media/audio-runtime.mjs','media/audio-adapter.mjs','media/audio-worker.mjs','media/audio-worker-client.mjs','media/audio-codec.mjs','media/audio-codec.wasm','media/audio-codec.LICENSE.txt','media/audio-codec-build.json','media/audio-general-pipeline.mjs','media/audio-general-worker.mjs','scripts/build-audio-compat.cjs','tests/audio-compat-lifecycle.mjs','tests/audio-compat-general.mjs'];
const build=JSON.parse(fs.readFileSync(path.join(root,'media/audio-codec-build.json'))),sourceInputs=build.preferredSource.map(x=>x.path).filter(x=>!runtime.includes(x));
sourceInputs.push('qa/q2-audio-compatibility/eac3-source-build/codec.mjs','qa/q2-audio-compatibility/eac3-source-build/codec.wasm');
for(const n of fs.readdirSync(path.join(root,'qa/q2-audio-compatibility/eac3-source-build/notices')))sourceInputs.push('qa/q2-audio-compatibility/eac3-source-build/notices/'+n);
const backendProof=['README.md','native-audit.cjs','native-fixture.html','native-fixture.mjs','prepare-packets.py','packets.json','native-results.json','node-results.txt','historical-integrity.json','process-cleanup.json','evidence-manifest.json'].map(n=>'qa/q2-audio-product-preparation/'+n).filter(n=>fs.existsSync(path.join(root,n)));
const qaNames=['README.md','native.cjs','native.mjs','native-results.json','native-run.log','oracle.py','oracle-ac3-results.json','oracle-eac3-results.json','oracle-sar-results.json','node-results.txt','fixture-provenance.json','record-fixtures.py','finalize.cjs','historical-integrity.json','process-cleanup.json','synthetic-avc-ac3-sar.mp4','synthetic-bframes-ac3.mp4','synthetic-long-ac3.mp4','output-ac3.mp4','output-eac3.mp4','output-sar.mp4','output-long.mp4','attempt-final-config.log','attempt-final-config.mjs','attempt-origin-shift/pipeline.mjs','attempt-origin-shift/oracle-ac3-results.json','attempt-origin-shift/oracle-eac3-results.json'];
const fixtureInputs=['qa/q2-audio-compatibility/synthetic-avc-ac3.mp4','qa/q2-audio-compatibility/eac3-source-build/synthetic-avc-eac3-stereo.mp4','qa/q2-audio-compatibility/eac3-source-build/synthetic-avc-eac3-51.mp4','qa/q2-audio-compatibility/eac3-source-build/synthetic-corrupt-eac3.mp4'];
const groups={ownedRuntimeBuildTests:runtime.map(inspect),coordinatedAdmissionChange:[inspect('media/general-admission.mjs')],ownedQa:qaNames.map(n=>inspect('qa/q2-general-product-integration/'+n)),previousBackendProof:backendProof.map(inspect),preferredSourceBuildRelinkInputs:[...new Set(sourceInputs)].map(inspect),syntheticFixtureDependencies:fixtureInputs.map(inspect)};
const report={generatedManifestFiles:['qa/q2-general-product-integration/commit-files.json','qa/q2-general-product-integration/evidence-manifest.json'],scope:'Explicit curated commit review list; no staging or commit performed',excluded:['qa/q2-audio-compatibility/build-investigation/work/** (multi-GB installed SDK/cache)','qa/q2-audio-compatibility/source-build/configure-attempt-2.log (raw environment PATH)','Historical implementation scaffolds not listed here','Unrelated account/private/browser diagnostics'],rootOwnedPublicationDependencies:fs.readdirSync(path.join(root,'licenses')).filter(n=>n.startsWith('audio-source-')).map(n=>'licenses/'+n),groups};
fs.writeFileSync(path.join(leaf,'commit-files.json'),JSON.stringify(report,null,2)+'\n');
const native=JSON.parse(fs.readFileSync(path.join(leaf,'native-results.json')));if(native.pageErrors.length||native.results.some(r=>!r.passed))throw Error('NATIVE_FAILURE');
for(const name of ['ac3','eac3','sar']){const oracle=JSON.parse(fs.readFileSync(path.join(leaf,'oracle-'+name+'-results.json')));if(oracle.failed||oracle.outputSha256!==sha(fs.readFileSync(path.join(leaf,'output-'+name+'.mp4'))))throw Error('ORACLE_BINDING');}
const files=[...new Map(Object.values(groups).flat().map(x=>[x.path,x])).values(),inspect('qa/q2-general-product-integration/commit-files.json')];
fs.writeFileSync(path.join(leaf,'evidence-manifest.json'),JSON.stringify({scope:'Local Q2 actual general-worker preparation; root owns publication and app activation',checks:{native:13,nodeCombined:26,independentOracle:24},historical,files},null,2)+'\n');console.log(JSON.stringify({files:files.length,bytes:files.reduce((a,x)=>a+x.bytes,0),historical:historical.map(x=>({manifest:x.path,bindings:x.bindings,mismatches:x.mismatches}))}));
