'use strict';
// Loading paint calibration through product functions; ordinary demo image lifecycle separately.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=path.resolve(root,'../maintenance/tools/minimal-loading');fs.mkdirSync(out,{recursive:true});
const hashes=Object.fromEntries(['app.js','styles.css','index.html'].map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,n))).digest('hex')]));
const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const n=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html',f=path.resolve(root,n);if(!f.startsWith(root+path.sep)||/^(qa|memory|worker|node_modules)\//.test(n)||!types[path.extname(n)]||!fs.existsSync(f))return res.writeHead(404).end();res.writeHead(200,{'Content-Type':types[path.extname(n)],'Cache-Control':'no-store'});res.end(fs.readFileSync(f));});
const rows=[];
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
 try{for(const [width,height,mobile] of [[1440,900,false],[390,844,true],[320,568,true],[844,390,true]]){
  const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const cdp=await context.newCDPSession(page);
  await page.goto(`${base}/?demo=1`);await page.waitForFunction(()=>typeof state!=='undefined'&&state.demo&&!el.libraryView.hidden);await page.evaluate(()=>{state.currentFolderId='root';state.filter='all';state.query='';startDemoMode();});await page.locator('[data-file-id="demo-image-1"] .file-card-open').click();await page.waitForFunction(()=>el.imageViewer.complete&&el.imageViewer.naturalWidth>0&&el.mediaLoading.hidden);
  const read=()=>page.evaluate(()=>({hidden:el.mediaLoading.hidden,text:el.mediaLoading.innerText.trim().replace(/\s+/g,' '),percent:el.mediaLoadingPercent.textContent,progress:{hidden:el.mediaLoadingProgress.hidden,value:el.mediaLoadingProgress.getAttribute('value')},seek:el.mediaLoading.classList.contains('seek-loading')}));
  const capture=async(name,percent=null)=>{
   await page.waitForTimeout(name==='compact-seek'?1000:220);const result=await read();assert.equal(result.hidden,false);assert.match(result.text,/^로딩 중(?: \d+%)?$/,'only user-requested status+numeric percentage');if(percent!==null){assert.match(result.text,new RegExp(`\\b${percent}%$`));assert.equal(Number(result.progress.value),percent);assert.equal(result.progress.hidden,false);}else{assert(!/\d+%/.test(result.text),'unknown percentage not invented');assert.equal(result.progress.value,null);}
   const ax=(await cdp.send('Accessibility.getFullAXTree')).nodes.filter(n=>!n.ignored).map(n=>({role:n.role?.value,name:n.name?.value}));assert(!ax.some(n=>/임시 디스크|메모리 저장|원본 응답|현재 위치 이후|버퍼 \d|준비 중/.test(n.name||'')),'no loading implementation text in AX');
   const barVisible=await page.locator('#mediaLoadingProgress').isVisible();assert.equal(barVisible,percent!==null&&name!=='compact-seek','bar appears for measured ordinary state, stays compact for seek');
   const box=await page.locator('#mediaLoading').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<=height,'overlay fits viewport');await page.screenshot({path:path.join(out,`${width}x${height}-${name}.png`)});rows.push({viewport:{width,height,mobile},name,proof:'Product function loading/progress painted calibration; not real Drive transfer',...result,barVisible,ax:ax.filter(n=>/로딩|%|진행/.test(n.name||'')),box});
  };
  await page.evaluate(()=>{state.isSeeking=false;state.mediaTransportStarted=false;showMediaLoading();});await capture('unknown');
  await page.evaluate(()=>updateOriginalBufferProgress(400,1000));await capture('measured-bytes',40);
  await page.evaluate(()=>{showMediaLoading();el.videoPlayer.hidden=false;el.videoPlayer.dataset.mediaSession=String(state.mediaSession);state.mediaAttempt='range';Object.defineProperties(el.videoPlayer,{currentTime:{configurable:true,value:5},duration:{configurable:true,value:20},buffered:{configurable:true,value:{length:1,start:()=>0,end:()=>6.5}}});updateNativeLoadingProgress();});await capture('buffer',50);
  await page.evaluate(()=>{for(const key of ['currentTime','duration','buffered'])delete el.videoPlayer[key];el.videoPlayer.hidden=true;state.isSeeking=true;state.mediaTransportStarted=true;showMediaLoading();setMediaLoadingProgress(75);});await capture('compact-seek',75);
  const reset=await page.evaluate(()=>{state.isSeeking=false;state.mediaTransportStarted=false;openMediaSource(state.files.find(f=>f.id==='demo-image-1'));return{hidden:el.mediaLoading.hidden,percent:el.mediaLoadingPercent.textContent,value:el.mediaLoadingProgress.getAttribute('value'),seek:el.mediaLoading.classList.contains('seek-loading')};});assert.equal(reset.value,null);assert.equal(reset.seek,false);assert(!/\d+%/.test(reset.percent));
  await page.waitForFunction(()=>el.imageViewer.complete&&el.imageViewer.naturalWidth>0&&el.mediaLoading.hidden);rows.push({viewport:{width,height,mobile},name:'new-source-reset-and-image-ready',proof:'Ordinary openMediaSource demo-image source lifecycle and native image load event',reset,ready:await read()});
  await page.evaluate(()=>{showMediaLoading();showMediaError('로컬 검사 오류');});assert.equal((await read()).hidden,true);assert(await page.locator('#mediaError').isVisible());rows.push({viewport:{width,height,mobile},name:'error-retirement',proof:'Product recovery function calibration',loadingHidden:true});assert.deepEqual(errors,[]);await context.close();
 }
 const result={completed:true,hashes,proof:'Isolated local Chrome; 4 viewport emulation; product loading-function calibration; ordinary demo image source lifecycle. No account, production, physical device, actual transfer-rate or native-video seek acceptance.',rows};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({...result,rows:rows.map(({ax,...r})=>r)},null,2));console.log(JSON.stringify({completed:true,out,scenarios:rows.length}));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({hashes,rows,error:e.stack},null,2));console.error(e);process.exitCode=1;});
