import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import cp from 'node:child_process';import {fileURLToPath} from 'node:url';
import {streamGeneralQ1} from '../../media/general-pipeline.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)),rows=[];
for(const name of ['rotation','vfr','multiaudio','subtitle']){
 const bytes=fs.readFileSync(path.join(dir,name+'.mp4')),chunks=[],row={name,passed:false},source={identity:{size:bytes.length},read:async({start,end})=>new Uint8Array(bytes.subarray(start,end+1)),abort:async()=>({settled:true})};rows.push(row);
 try{row.result=await streamGeneralQ1({source,onChunk:async({bytes})=>chunks.push(bytes)});const file=path.join(dir,name+'-q1-output.mp4');fs.writeFileSync(file,Buffer.concat(chunks));const output=JSON.parse(cp.execFileSync('ffprobe',['-v','error','-show_streams','-show_packets','-show_data_hash','sha256','-of','json',file],{encoding:'utf8',maxBuffer:16*1024*1024})),input=JSON.parse(fs.readFileSync(path.join(dir,name+'-input-probe.json')));fs.writeFileSync(path.join(dir,name+'-output-probe.json'),JSON.stringify(output,null,2));
 const failures=[];for(const type of ['video','audio']){const a=input.packets.filter(p=>p.codec_type===type),b=output.packets.filter(p=>p.codec_type===type);if(a.length!==b.length){failures.push(type+'_packet_count');continue;}const [an,ad]=input.streams.find(s=>s.codec_type===type).time_base.split('/').map(BigInt),[bn,bd]=output.streams.find(s=>s.codec_type===type).time_base.split('/').map(BigInt),shifts=new Set();for(let i=0;i<a.length;i++){if(a[i].data_hash!==b[i].data_hash)failures.push(type+'_data_hash_'+i);if(BigInt(a[i].duration)*an*bd!==BigInt(b[i].duration)*bn*ad)failures.push(type+'_duration_'+i);shifts.add(String(BigInt(b[i].pts)*bn*ad-BigInt(a[i].pts)*an*bd));}row[type+'ClockShiftNumerators']=[...shifts];row[type+'ClockShiftDenominator']=String(ad*bd);if(shifts.size!==1)failures.push(type+'_nonconstant_pts_shift');}
 row.rotationInput=input.streams.find(s=>s.codec_type==='video')?.side_data_list;row.rotationOutput=output.streams.find(s=>s.codec_type==='video')?.side_data_list;row.rotationMatrixNote='Muxer adds translation to place the rotated image in its display rectangle; compare rotation angle and actual native output dimensions, not raw matrix equality.';if((row.rotationInput?.find(s=>s.rotation!==undefined)?.rotation??0)!==(row.rotationOutput?.find(s=>s.rotation!==undefined)?.rotation??0))failures.push('rotation_angle_changed');row.failures=failures;row.passed=failures.length===0;row.outputSha256=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
 }catch(error){row.failure={code:error.message,cleanup:error.cleanup};row.status='explicit-unsupported';}
 fs.writeFileSync(path.join(dir,'packet-oracle-results.json'),JSON.stringify(rows,null,2));
}
console.log(JSON.stringify(rows.map(({name,passed,failure,failures})=>({name,passed,failure,failures}))));
