'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const here=__dirname,delivery=path.resolve(here,'../candidate-rc38-delivery'),binding=require(path.join(delivery,'source-binding.cjs')),driver=require('./driver.cjs');
test('unbound delivery and actual admission reject before any operation or result reservation',async()=>{assert.equal(binding.optionalSource(),'UNKNOWN');assert.throws(()=>require(path.join(delivery,'delivery-guard.cjs')).assertSource(),/RC38_ROOT_SOURCE_BINDING_REQUIRED/);assert.throws(()=>binding.requireBinding(),/RC38_ROOT_SOURCE_BINDING_REQUIRED/);
 await assert.rejects(driver.run('--admit','actual-00000000-0000-4000-8000-000000000000.json'),/RC38_ROOT_SOURCE_BINDING_REQUIRED/);assert.equal(fs.existsSync(path.join(here,'actual-00000000-0000-4000-8000-000000000000.json')),false);});
test('unbound actor helper, connector guard and proof factories reject before browser globals',async()=>{for(const name of ['browser.function.js','connector-file-guard.function.js']){const fn=vm.runInNewContext('('+fs.readFileSync(path.join(here,name),'utf8')+')');await assert.rejects(async()=>fn(null,null),/SOURCE_BINDING_REQUIRED/);}
 for(const name of ['pc-source-proof.function.js','android-current-proof.function.js']){const fn=vm.runInNewContext('('+fs.readFileSync(path.join(delivery,name),'utf8')+')');await assert.rejects(fn({sourceCommit:'UNKNOWN',version:'1.22.0-rc.38'}),/RC38_SOURCE_PIN_REQUIRED/);}});
test('final producer binding validates exact mock producer bytes and rejects drift or wrong committed version',()=>{const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),bytes=Buffer.from('exact mocked producer'),mockRoot=path.resolve(delivery,'../..'),producer=path.join(mockRoot,'qa/candidate-rc38-delivery/mock.cjs');let drift=false,version='1.22.0-rc.38';
 const prep=Buffer.from(JSON.stringify({version,sourceCommit:'UNKNOWN',actualExecution:false,producers:[{file:'qa/candidate-rc38-delivery/mock.cjs',sha256:sha(bytes)}]}));const mockFS={readFileSync:file=>file===producer?(drift?Buffer.from('changed'):bytes):prep};
 const module={exports:{}},fakeRequire=name=>name==='node:fs'?mockFS:name==='node:child_process'?{execFileSync:(_exe,args)=>args[0]==='cat-file'?'commit\n':JSON.stringify({version})}:require(name);
 vm.runInNewContext(fs.readFileSync(path.join(delivery,'source-binding.cjs'),'utf8'),{require:fakeRequire,module,__dirname:delivery,process:{argv:[]},Buffer});
 const record={schema:'rc38-root-runtime-source-binding/1',version,sourceCommit:'a'.repeat(40),preparationSHA256:sha(prep)};assert.equal(module.exports.validate(record).sourceCommit,record.sourceCommit);drift=true;assert.throws(()=>module.exports.validate(record),/PRODUCER_CHANGED/);drift=false;version='1.22.0-rc.37';assert.throws(()=>module.exports.validate(record),/BOUND_VERSION_MISMATCH/);assert.throws(()=>module.exports.validate({...record,sourceCommit:'UNKNOWN'}),/BINDING_INVALID/);});
test('unbound preparation retains bounds, fixture and refuses copied legacy schema',()=>{const p=driver.preparation();assert.equal(p.manifest.sourceCommit,'UNKNOWN');assert.equal(p.manifest.actualEligible,false);assert.equal(p.manifest.fixture.bytes,759643);assert.equal(p.manifest.fixture.initialAudioTrackId,2);assert.equal(p.manifest.fixture.selectedAudioTrackId,3);
 assert.deepEqual([p.manifest.initialFrameMs,p.manifest.metadataAbortMs,p.manifest.rpcDeadlineMs,p.manifest.overallMs,p.manifest.cleanupMs],[15000,10000,25000,180000,40000]);assert.throws(()=>driver.validateInput({schema:'rc37-android-exact-created-context/1'}),/PRIVATE_CONTEXT_SHAPE/);});
