'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'browser-frame-qualified.function.js'),'utf8');
const run='12345678-1234-4123-8123-123456789abc',tuple={primaries:'bt709',transfer:'bt709',matrix:'bt709',fullRange:false};
function mock({pc=false}={}){const calls=[],eventMap=new Map(),frameCallbacks=new Map();let wallClock=100000,closedFrames=0,frameNext=0,metadataChange=false,monotonic=0,onGET=null,deadlineTimer=null,clockValues=[];
  const ctrl={state:'activated'},signal=new AbortController().signal,metadata={id:'mock-disposable-file-only',name:'DriveOriginal-QA-'+run+'-test-video-1',mimeType:'video/mp4',ownedByMe:true,trashed:false,parents:['mock-root-only'],version:'5',headRevisionId:'mock-revision-only',modifiedTime:'mock-date',size:'759643',md5Checksum:'4a49dfa52d67d5b4b391fe9bb7f836ae',sha256Checksum:'bc831b81953010036a7d931100dfd264fa14d8e22633b6518268f6c6dbfc2e2f',appProperties:{qaRun:run,qaRole:'test-video-1',qaFixtureSHA256:'bc831b81953010036a7d931100dfd264fa14d8e22633b6518268f6c6dbfc2e2f'},capabilities:{canTrash:true,canDownload:true}};
  const emitter={addEventListener:(name,fn)=>{if(!eventMap.has(name))eventMap.set(name,new Set());eventMap.get(name).add(fn);},removeEventListener:(name,fn)=>eventMap.get(name)?.delete(fn)};
  const video={...emitter,readyState:2,videoWidth:320,videoHeight:180,paused:true,error:null,hasAttribute:()=>false,
    requestVideoFrameCallback:fn=>{const id=++frameNext;frameCallbacks.set(id,fn);return id;},cancelVideoFrameCallback:id=>frameCallbacks.delete(id)};
  class Worker{constructor(){this.listeners=new Set();this.sent=[];}addEventListener(name,fn){this.listeners.add(fn);}removeEventListener(name,fn){this.listeners.delete(fn);}postMessage(m){this.sent.push(m);}terminate(){this.done=true;}emit(m){for(const fn of this.listeners)fn({data:m});}}
  const ctx={window:{Worker},APP_VERSION:'1.22.0-rc.38',location:{origin:'https://mock.invalid',href:'https://mock.invalid/'},navigator:{serviceWorker:{controller:ctrl,getRegistration:async()=>({active:ctrl,scope:'https://mock.invalid/'})}},document:{visibilityState:'visible'},
    state:{accountId:'mock-account-only',authAccountKey:'mock-key-only',authGeneration:4,driveSessionGeneration:7,accountStateAbortController:{signal},selected:null,authStatus:'online',accountStateLoaded:true,mediaSession:0,currentFolderId:'root',query:''},
    q0Playback:null,q1Playback:null,q0PinnedSource:null,playerTracksOwner:null,q1RetirementResult:{settled:true},playerTracksRetirementResult:{settled:true},mediaSourceGeneration:0,
    el:{playerSheet:{hidden:true},videoPlayer:video,playerTracksDialog:{open:false},playerAudioTrack:{...emitter,value:'',disabled:false}},URL,URLSearchParams,AbortController,AbortSignal,Uint8Array,TextDecoder,
    performance:{now:()=>{if(clockValues.length)monotonic=clockValues.shift();return monotonic;}},setTimeout:(fn,ms)=>{if(ms===180000)deadlineTimer=fn;const timer=setTimeout(fn,ms);timer.unref();return timer;},clearTimeout,Date:class extends Date{static now(){return wallClock;}},DRIVE_API:'https://www.googleapis.com/drive/v3',
    capturePlaybackSnapshot:()=>({time:video.currentTime??0.5,paused:video.paused}),hasUsableToken:()=>true,getActiveMediaElement:()=>video,isCurrentMediaEvent:()=>true,hasVerifiedOriginalTransport:()=>true,
    driveFetch:async u=>{calls.push(u);if(onGET)await onGET();const m=structuredClone(metadata);if(metadataChange)m.version='6';return new Response(JSON.stringify(m));},
    VideoFrame:class{constructor(){this.format=ctx.q1Playback?'RGBA':'I420';this.colorSpace=tuple;this.visibleRect={width:320,height:180};}close(){closedFrames++;}},
    openPlayer:file=>{ctx.state.selected=file;ctx.state.mediaSession=1;ctx.mediaSourceGeneration=1;ctx.state.mediaDecodeVerified=true;ctx.el.playerSheet.hidden=false;ctx.q0Playback={fileId:file.id,session:1,account:'mock-key-only',accountGeneration:7,swGeneration:1,swController:ctrl,controller:new AbortController()};ctx.q0PinnedSource={mock:true};}};
  const input={schema:pc?'rc38-pc-exact-created-context/1':'rc38-android-exact-created-context/1',account:{accountId:'mock-account-only'},metadata,qaRunId:run};vm.createContext(ctx);
  const install=async v=>vm.runInContext('('+(pc?fs.readFileSync(path.join(__dirname,'pc-browser-frame-qualified.function.js'),'utf8'):source)+')('+JSON.stringify(v||input)+','+JSON.stringify({sourceCommit:'a'.repeat(40),version:'1.22.0-rc.38'})+')',ctx);
  const frame=(mediaTime=0.5)=>{const [id,fn]=frameCallbacks.entries().next().value;frameCallbacks.delete(id);fn(0,{width:320,height:180,mediaTime,presentedFrames:1});};
  const close=()=>{ctx.state.selected=null;ctx.q0Playback=null;ctx.q1Playback=null;ctx.playerTracksOwner=null;ctx.q0PinnedSource=null;ctx.el.playerSheet.hidden=true;};
  const successor=()=>{const config={codec:'avc1.64000D',codedWidth:320,codedHeight:180,description:new Uint8Array([1,2,3])};ctx.q0Playback=null;ctx.mediaSourceGeneration=2;ctx.state.mediaTransportVerified=true;ctx.state.mediaTransportStarted=true;ctx.state.mediaPlaybackMode='original-repackaged';ctx.state.lastPresentedMediaTime=0.5;ctx.playerTracksOwner.selectedAudioTrackId=3;ctx.playerTracksOwner.nativeColorObservation={basis:'observed-native-frame',format:'I420',colorSpace:tuple};ctx.q1Playback={kind:'general',fileId:metadata.id,session:1,account:'mock-key-only',accountGeneration:7,swGeneration:2,swController:ctrl,controller:new AbortController(),selectedAudioTrackId:3,player:{stats:()=>({generation:1,outputColorObservation:{basis:'observed-native-frame',colorSpace:tuple}})}};
    const worker=new ctx.window.Worker('/media/general-worker.mjs',{type:'module'});worker.postMessage({kind:'start',generation:1,identity:{...metadata,fileId:metadata.id,accountKey:'mock-key-only',accountGeneration:7,canDownload:true}});worker.emit({kind:'window',generation:0,value:{selectedAudioTrackId:3,videoConfig:config,outputVideoConfig:{...config,colorSpace:tuple}}});assert.equal((pc?ctx.window.__rc38PcActualAAC:ctx.window.__rc38AndroidActualAAC).read().statsReady,false);
    worker.emit({kind:'window',generation:1,value:{selectedAudioTrackId:3,videoConfig:config,outputVideoConfig:{...config,colorSpace:tuple}}});return worker;};
  return {ctx,input,install,frame,successor,close,calls,metadata,advance:ms=>{monotonic+=ms;wallClock+=ms;},clockValues:(...values)=>clockValues=values,fireDeadline:()=>deadlineTimer(),setGET:fn=>onGET=fn,
    change:trusted=>{for(const fn of eventMap.get('change')||[])fn({type:'change',isTrusted:trusted});},setMetadataChange:()=>metadataChange=true,closedFrames:()=>closedFrames,eventCount:()=>[...eventMap.values()].reduce((n,s)=>n+s.size,0),callbackCount:()=>frameCallbacks.size};}
function nativeDefaultInventory(m){m.ctx.playerTracksOwner={current:()=>true,cleanupOk:true,switching:false,inventory:{defaultAudioTrackId:2,audioTracks:[{trackId:2,codec:'aac',route:'q1'},{trackId:3,codec:'aac',route:'q1'}]}};m.ctx.el.playerAudioTrack.value='2';}

module.exports={mock,nativeDefaultInventory,tuple};
