import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {createCorpusTracksProbe,BINDING,VERSION,ORIGIN,CAPS} from './probe.mjs';
import {summarizeRepeatedInventory} from '../v2-07a-root-inventory/root-inventory.mjs';
import {box,cat,moovFixture} from '../v2-07a-iso-tracks-rc11/fixtures.mjs';
import {build} from './build.mjs';
import {selectRiskRepresentatives,RepresentativeSelectionError} from '../v2-07a-representative-selection/representative-selector.mjs';
import {planDeepCohorts,safeReferences} from './selection.mjs';
import {sanitizeFailureDiagnostic} from './diagnostics.mjs';
import {createMoovWindowCache} from './moov-window-cache.mjs';
import {normalizeProbeIdentity} from '../v2-07a-bounded-probe/bounded-probe.mjs';
const base=new URL('./',import.meta.url),hash=x=>createHash('sha256').update(x).digest('hex'),cases=[];let coalescingEvidence=null;
const canaryPaths=(v,path='')=>typeof v==='string'?(v.includes('PRIVATE_')?[path]:[]):v&&typeof v==='object'?Object.entries(v).flatMap(([k,x])=>canaryPaths(x,path+'.'+k)):[];
const old=await readFile(new URL('../rc16-corpus-tracks/probe.test.mjs',base),'utf8');
const factory=vm.runInNewContext(old.slice(old.indexOf('const hash='),old.indexOf("\ntest('"))+'\nfixture;',{Buffer,AbortController,Response,URL,Date,createHash,cat,box,moovFixture,createCorpusTracksProbe,VERSION,ORIGIN});
function fixture(){
 const f=factory(),controller=f.runtime.navigator.serviceWorker.controller;
 f.runtime.getSWIdentity=()=>({...BINDING,controller});
 f.rows.forEach((r,i)=>Object.assign(r,{mandatoryReasons:[i===0?'priority':'metadata-stratum'],coveredCategories:['extension:.'+r.extension]}));
 const root={id:f.context.rootId,version:'1',modifiedTime:'PRIVATE_DATE',mimeType:'application/vnd.google-apps.folder',trashed:false,capabilities:{canListChildren:true}};
 f.pass={accountBefore:f.state.accountId,accountAfter:f.state.accountId,rootBefore:root,rootAfter:root,items:f.files.map((x,i)=>({id:x.id,name:'PRIVATE_NAME_'+i,version:f.rows[i].version,size:f.rows[i].size,modifiedTime:f.rows[i].modifiedTime,mimeType:x.mime,fileExtension:x.ext,parents:[root.id],trashed:false,capabilities:{canDownload:true,canReadRevisions:true}})),shortcutTargets:[],pageCount:1,traversedFolderCount:1,duplicateReferenceCount:0,unresolvedShortcutTargetCount:0,staleShortcutTargetMimeCount:0,incompleteSearchCount:0,paginationCycleCount:0};
 const report=summarizeRepeatedInventory({firstPass:f.pass,secondPass:f.pass,priorityFileId:f.context.priorityFileId,canonicalRootResolvedFromPriorityParent:true});
 f.dependencies.inventoryRunner=async({driveFetch})=>{await(await driveFetch('https://www.googleapis.com/drive/v3/about')).json();return {report,privatePasses:{secondPass:f.pass}};};
 return f;
}
async function check(name,fn){await fn();cases.push({name,passed:true});}
await check('real-maintained-selector-schema-to-plan-and-probe-positive',async()=>{
 const f=fixture(),selected=selectRiskRepresentatives({pass:f.pass,priorityFileId:f.context.priorityFileId,expectedPriorityVersion:f.context.priorityVersion});
 const plan=planDeepCohorts(selected,f.context,1);assert(plan.plan.length>0&&plan.plan.length<=8);assert.equal(safeReferences(selected).length,selected.privateManifest.selected.length);
 for(const row of selected.privateManifest.selected){assert.equal(typeof row.version,'string');assert.equal(typeof row.size,'string');assert.equal(typeof row.modifiedTime,'string');assert(Array.isArray(row.visibleReferences));assert(Array.isArray(row.mandatoryReasons));assert(Array.isArray(row.coveredCategories));}
 f.dependencies.selector=selectRiskRepresentatives;const r=await f.make().run();assert.equal(r.complete,true);assert.equal(r.failureDiagnostic,null);assert(r.files.some(x=>x.kind==='iso-bmff'&&x.tracks?.status==='parsed'));assert(r.files.some(x=>x.kind==='webm'&&x.tracks?.status==='parsed'));assert.equal(r.released,true);assert(f.calls.every(x=>x.init.method==='GET'));
});
await check('real-representative-schema-missing-metadata-is-distinct-invalid-identity',async()=>{
 const f=fixture();delete f.pass.items[0].size;const selected=selectRiskRepresentatives({pass:f.pass,priorityFileId:f.context.priorityFileId,expectedPriorityVersion:f.context.priorityVersion});
 assert.throws(()=>planDeepCohorts(selected,f.context,1),e=>e.code==='INVALID_IDENTITY');
 const error=Object.assign(Error('PRIVATE_METADATA'),{name:'BoundedProbeError',code:'INVALID_IDENTITY'}),safe=sanitizeFailureDiagnostic(error,'selection-plan');assert.equal(safe.code,'INVALID_IDENTITY');assert(!JSON.stringify(safe).includes('PRIVATE_METADATA'));
});
await check('allowlisted-selector-exception-and-stage-survive-generic-failure',async()=>{
 const f=fixture();f.dependencies.selector=()=>{throw new RepresentativeSelectionError('PRIORITY_FENCE_MISMATCH','PRIVATE_ID_PRIVATE_URL_PRIVATE_TOKEN');};const r=await f.make().run();assert.equal(r.failure,'PROBE_FAILED');assert.equal(r.failureDiagnostic.exceptionClass,'RepresentativeSelectionError');assert.equal(r.failureDiagnostic.code,'PRIORITY_FENCE_MISMATCH');assert.equal(r.failureDiagnostic.phase,'selection-select');assert.equal(r.released,true);assert.equal(r.mediaRequests,0);assert(!JSON.stringify(r).includes('PRIVATE_'));
 const g=fixture();g.dependencies.selectionWitness=()=>{throw new TypeError('PRIVATE_ORIGINAL');};const s=await g.make().run();assert.equal(s.failureDiagnostic.exceptionClass,'TypeError');assert.equal(s.failureDiagnostic.phase,'selection-witness');assert.equal(s.failureDiagnostic.code,'unclassified');assert.equal(s.mediaRequests,0);assert.equal(s.released,true);assert(!JSON.stringify(s).includes('PRIVATE_'));
});
await check('diagnostic-redacts-unknown-message-code-phase-stack-urls-and-function-names',async()=>{
 const raw={name:'TypeError',code:'PRIVATE_CODE',message:'PRIVATE_MESSAGE',stack:'TypeError: PRIVATE_MESSAGE\n    at execute (https://PRIVATE_HOST/PRIVATE_TOKEN.js:876:42)\n    at PRIVATE_FUNCTION (file:///PRIVATE_NAME:999:7)'};const safe=sanitizeFailureDiagnostic(raw,'PRIVATE_PHASE');assert.deepEqual(safe.frames,[{function:'execute',line:876}]);assert.equal(safe.code,'unclassified');assert.equal(safe.phase,'unclassified');assert(!JSON.stringify(safe).includes('PRIVATE_'));assert(!JSON.stringify(safe).includes('https:'));assert(!JSON.stringify(safe).includes('file:'));
});
await check('safe-reference-redacts-real-selector-rare-ge4-ids-and-arbitrary-mismatch-metadata',async()=>{
 const f=fixture();f.pass.items[1].size='4294967297';f.pass.items[8].mimeType='image/PRIVATE_MIME';f.pass.items[8].fileExtension='PRIVATE_EXTENSION';const selected=selectRiskRepresentatives({pass:f.pass,priorityFileId:f.context.priorityFileId,expectedPriorityVersion:f.context.priorityVersion});
 const refs=safeReferences(selected);assert.deepEqual(canaryPaths(refs),[]);assert(refs.some(r=>r.mandatoryReasons.includes('ge4gib')));assert(refs.some(r=>r.metadataRiskCategories.includes('mimeMismatch:metadata-extension-mime')));const row=selected.privateManifest.selected[0];row.mandatoryReasons.push('PRIVATE_ARBITRARY');row.coveredCategories.push('PRIVATE_UNKNOWN');assert.deepEqual(canaryPaths(safeReferences(selected)),[]);
});
await check('real-maintained-bounded-probe-iso-sparse-ebml-positive',async()=>{
 const f=fixture(),r=await f.make().run();assert.equal(r.complete,true);assert.equal(r.catalogStable,true);assert.equal(r.inventoryRuns,2);assert(r.files.some(x=>x.kind==='iso-bmff'&&x.tracks?.status==='parsed'));assert(r.files.some(x=>x.kind==='webm'&&x.tracks?.status==='parsed'));assert(r.mediaRequests>0);assert(r.files.length<=8);assert(r.files.every(x=>x.mediaRequests<=64&&x.mediaBytes<=CAPS.mediaBytes));assert.equal(r.probeDenominators.probedRepresentatives,r.files.length);assert.equal(r.probeDenominators.unprobedRepresentatives,f.rows.length-r.files.length);assert(f.calls.every(x=>x.init.method==='GET'));assert(f.calls.filter(x=>x.url.origin===ORIGIN).every(x=>{const [,a,b]=/^bytes=(\d+)-(\d+)$/.exec(x.init.headers.Range);return +a!==0||+b!==Number(x.url.searchParams.get('size'))-1;}));assert.equal(r.released,true);assert.equal(f.listeners.size,0);assert(!JSON.stringify(r).includes('PRIVATE_'));
});
await check('probe-source-current-reject-before-request',async()=>{for(const change of [f=>f.runtime.appVersion='wrong',f=>f.runtime.getSWIdentity=()=>({...BINDING,sourceCommit:'wrong'}),f=>f.runtime.document.visibilityState='hidden']){const f=fixture();change(f);const r=await f.make().run();assert.equal(r.complete,false);assert.equal(f.calls.length,0);assert.equal(r.released,true);}});
await check('probe-account-change-aborts-before-next-body',async()=>{const f=fixture(),fetch=f.runtime.nativeFetch;f.runtime.nativeFetch=async(u,o)=>{const r=await fetch(u,o);if(new URL(u).origin===ORIGIN)f.state.tokenRevision++;return r;};const r=await f.make().run();assert.equal(r.complete,false);assert.equal(f.calls.filter(x=>x.url.origin===ORIGIN).length,1);assert.equal(r.released,true);assert.equal(f.listeners.size,0);});
await check('probe-cancel-error-cleanup-terminal',async()=>{const f=fixture();let release;f.runtime.nativeFetch=()=>new Promise(resolve=>release=resolve);const job=f.make(),promise=job.run();job.cancel();release({body:{cancel:()=>Promise.reject(Error('PRIVATE_ERROR'))}});const r=await promise;assert.equal(r.failure,'CLEANUP_FAILED');assert.equal(r.released,true);assert.equal(r.mediaRequests,0);assert.equal(f.listeners.size,0);assert(!JSON.stringify(r).includes('PRIVATE_'));});
await check('metadata-only-does-not-read-media',async()=>{const f=fixture();f.runtime.mode='metadata-only';const r=await f.make().run();assert.equal(r.complete,true);assert.equal(r.mediaRequests,0);assert.equal(r.inventoryRuns,2);});
const entrySource=await readFile(new URL('entry.function.js',base),'utf8');
function targetFixture(){
 const f=fixture(),s=f.state,c=f.runtime.navigator.serviceWorker.controller,self={};Object.assign(s,{accountStateLoaded:true,accountStateWriterId:'PRIVATE_WRITER',accountStateRevision:1,accountMediaState:{favorites:{}},accountStateSyncPromise:null,accountStateSyncTimer:null,accountStateSyncRetryTimer:null,accountStateSyncError:null,playbackSession:1,currentFolderId:'root',rootFolderId:f.context.rootId,folderStack:[],query:'',filter:'all',folderRenderLimit:8,folders:[],files:[structuredClone(f.pass.items[0])]});delete s.files[0].version;
 const button={closest:()=>({dataset:{fileId:f.rows[0].fileId}}),isConnected:true,contains:()=>false,getBoundingClientRect:()=>({x:10,y:10,width:100,height:40,left:10,right:110,top:10,bottom:50})},listeners=new Map();
 const env={APP_VERSION:VERSION,DRIVE_MUTATIONS_ENABLED:false,ACCOUNT_STATE_WRITES_ENABLED:true,state:s,navigator:f.runtime.navigator,location:f.runtime.location,top:self,self,document:{visibilityState:'visible',querySelectorAll:()=>[button],elementFromPoint:()=>button},mediaSourceGeneration:5,q1Playback:null,q1RetirementResult:f.runtime.getQ1RetirementResult(),playerMediaPriorityActive:false,hasUsableToken:()=>true,accountMediaStatesEqual:(a,b)=>JSON.stringify(a)===JSON.stringify(b),innerWidth:1000,innerHeight:800,devicePixelRatio:1,URL,AbortController,Uint8Array,TextDecoder,setTimeout,clearTimeout,window:{addEventListener:(t,fn)=>listeners.set(t,fn),removeEventListener:(t)=>listeners.delete(t)},fetch:async(u,o)=>{f.calls.push({url:new URL(u),init:o});if(env.onRead)await env.onRead();return Response.json(env.freshOverride??f.pass.items[0]);},buildBreadcrumbItems:(stack,id,name)=>[{id:'root',name:'내 드라이브'},...stack,{id,name}]};
 const create=(_runtime,witness)=>{witness(f.selection,f.pass);return {poll:()=>({done:true,summary:{catalogStable:true,released:true}}),cancel:()=>({cancelled:true})};},facade=function(){return this({});},proof={get:()=>({...BINDING,controller:c})};
 const entry=vm.runInNewContext('('+entrySource+')',env)(create,facade,BINDING);entry('{}',proof,{cohort:1,mode:'probe'});return {...f,env,entry,proof,button,listeners};
}
await check('ui-without-version-qualified-by-one-fresh-exact-get-no-injection',async()=>{const f=targetFixture(),r=await f.entry.target('representative-1');assert.equal(r.ready,true);assert.equal(r.x,60);assert.equal(r.uiVersionClaimed,false);assert.equal(r.metadataRequests,1);assert.equal(f.calls.length,1);assert.equal(f.state.files[0].version,undefined);assert.equal(f.calls[0].init.method,'GET');assert.equal(f.calls[0].url.pathname,'/drive/v3/files/'+f.rows[0].fileId);assert.equal(f.listeners.size,0);assert(!JSON.stringify(r).includes('PRIVATE_'));});
await check('target-denies-fresh-version-parent-mime-size-and-modified-drift',async()=>{for(const [key,value]of Object.entries({version:'changed',parents:['OTHER'],mimeType:'video/other',size:'99',modifiedTime:'changed'})){const f=targetFixture();f.env.freshOverride={...f.pass.items[0],[key]:value};const r=await f.entry.target('representative-1');assert.equal(r.ready,false);assert.equal(r.reason,'TARGET_IDENTITY_CHANGED');assert.equal(f.calls.length,1);assert.equal(f.listeners.size,0);}});
await check('target-before-and-after-owner-fences',async()=>{for(const [phase,change]of [['before',f=>f.state.tokenRevision++],['before',f=>f.state.accountStateWriterId='changed'],['before',f=>f.env.navigator.serviceWorker.controller={}],['after',f=>f.state.accountMediaState={favorites:{changed:true}}]]){const f=targetFixture();if(phase==='before')change(f);else f.env.onRead=()=>change(f);const r=await f.entry.target('representative-1');assert.equal(r.ready,false);assert.equal(r.reason,'OWNER_CHANGED');assert.equal(f.calls.length,phase==='before'?0:1);assert.equal(f.listeners.size,0);}});
await check('target-ui-mismatch-and-obscured-normal-card-denied',async()=>{const f=targetFixture();f.state.files[0].size='99';assert.equal((await f.entry.target('representative-1')).reason,'CURRENT_UI_METADATA_UNQUALIFIED');assert.equal(f.calls.length,0);const g=targetFixture();g.env.document.elementFromPoint=()=>({});assert.equal((await g.entry.target('representative-1')).reason,'TARGET_OBSCURED');});
await check('target-cancel-bounded-body-limit-and-registry-cleanup',async()=>{const f=targetFixture();f.env.fetch=async()=>new Response('x'.repeat(32769));assert.equal((await f.entry.target('representative-1')).reason,'TARGET_METADATA_LIMIT');assert.equal(f.listeners.size,0);const g=targetFixture();g.env.onRead=()=>g.listeners.get('pagehide')?.();assert.equal((await g.entry.target('representative-1')).reason,'TARGET_CANCELLED');assert.equal(g.listeners.size,0);g.entry.cleanup();assert.equal((await g.entry.target('representative-1')).ready,false);});
await check('normal-known-folder-card-step-private-mapping-and-unknown-denial',async()=>{
 const f=targetFixture(),folder={id:'PRIVATE_FOLDER',name:'PRIVATE_FOLDER_NAME',mimeType:'application/vnd.google-apps.folder',version:'1',modifiedTime:'PRIVATE_DATE',parents:[f.context.rootId],trashed:false};f.pass.items[0].parents=[folder.id];f.pass.items.push(folder);f.state.files=[];f.state.folders=[{...folder}];delete f.state.folders[0].version;f.entry('{}',f.proof,{cohort:1,mode:'metadata-only'});
 f.env.freshOverride=folder;f.button.querySelector=()=>({textContent:folder.name});f.env.document.querySelectorAll=selector=>selector==='#folderStrip .folder-row'?[f.button]:[];
 const r=await f.entry.navigationTarget('representative-1');assert.equal(r.ready,true);assert.equal(r.kind,'normal-folder-card');assert.equal(f.calls.length,1);assert(!JSON.stringify(r).includes('PRIVATE_'));assert.equal(f.state.currentFolderId,'root');f.state.currentFolderId='OUTSIDE';assert.equal((await f.entry.navigationTarget('representative-1')).reason,'CURRENT_FOLDER_OUTSIDE_INVENTORY');
});
await check('known-inventory-root-breadcrumb-coordinate-only',async()=>{
 const f=targetFixture(),folder={id:'PRIVATE_SIBLING',name:'PRIVATE_SIBLING_NAME',mimeType:'application/vnd.google-apps.folder',version:'1',modifiedTime:'PRIVATE_DATE',parents:[f.context.rootId],trashed:false};f.pass.items.push(folder);f.state.currentFolderId=folder.id;f.state.currentFolderName=folder.name;f.entry('{}',f.proof,{cohort:1,mode:'metadata-only'});f.env.freshOverride=f.pass.rootBefore;f.button.tagName='BUTTON';f.button.textContent='내 드라이브';f.env.document.querySelectorAll=selector=>selector==='#breadcrumbTrail .crumb'?[f.button,{tagName:'SPAN'}]:[];
 const r=await f.entry.navigationTarget('representative-1');assert.equal(r.ready,true);assert.equal(r.kind,'normal-breadcrumb');assert.equal(f.calls.length,1);assert(!JSON.stringify(r).includes('PRIVATE_'));
});
await check('wide-catalog-does-not-disqualify-target-but-chain-nine-and-cycle-deny',async()=>{
 const wide=targetFixture();for(let i=0;i<8;i++)wide.pass.items.push({id:'PRIVATE_EXTRA_'+i,name:'PRIVATE_FOLDER_'+i,mimeType:'application/vnd.google-apps.folder',version:'1',modifiedTime:'PRIVATE_DATE',parents:[wide.context.rootId],trashed:false});wide.entry('{}',wide.proof,{cohort:1,mode:'metadata-only'});assert.equal((await wide.entry.target('representative-1')).ready,true);
 for(const count of [7,8]){const f=targetFixture(),path=[];for(let i=0;i<count;i++){const row={id:'PRIVATE_CHAIN_'+i,name:'PRIVATE_CHAIN_NAME_'+i,mimeType:'application/vnd.google-apps.folder',version:'1',modifiedTime:'PRIVATE_DATE',parents:[i?'PRIVATE_CHAIN_'+(i-1):f.context.rootId],trashed:false};path.push(row);f.pass.items.push(row);}f.pass.items[0].parents=[path.at(-1).id];f.state.files=[];f.state.folders=[{...path[0]}];f.env.freshOverride=path[0];f.button.querySelector=()=>({textContent:path[0].name});f.env.document.querySelectorAll=selector=>selector==='#folderStrip .folder-row'?[f.button]:[];f.entry('{}',f.proof,{cohort:1,mode:'metadata-only'});const r=await f.entry.navigationTarget('representative-1');assert.equal(r.ready,count===7);assert.equal(f.calls.length,count===7?1:0);if(count===8)assert.equal(r.reason,'KNOWN_ANCESTORS_UNQUALIFIED');}
 const cycle=targetFixture(),a={id:'PRIVATE_CYCLE_A',name:'PRIVATE_CYCLE',mimeType:'application/vnd.google-apps.folder',version:'1',modifiedTime:'PRIVATE_DATE',parents:['PRIVATE_CYCLE_B'],trashed:false},b={...a,id:'PRIVATE_CYCLE_B',parents:[a.id]};cycle.pass.items.push(a,b);cycle.pass.items[0].parents=[a.id];cycle.entry('{}',cycle.proof,{cohort:1,mode:'metadata-only'});assert.equal((await cycle.entry.navigationTarget('representative-1')).reason,'KNOWN_ANCESTORS_UNQUALIFIED');assert.equal(cycle.calls.length,0);
});
const built=await build();new vm.Script(built.expression);const absent=vm.runInNewContext(built.expression,{});assert.equal(absent('{}',{get:()=>({version:'wrong'})},{cohort:1,mode:'probe'}).poll().summary.failure,'SOURCE_BINDING_REJECTED');
const deliveredParent=await readFile(new URL('../rc28-deeper-target-qualification/factory.expression.js',base),'utf8');assert.equal(hash(deliveredParent),'0edf8cd548e0bca96f9994ecf2b3a72d4307396cec3bd1cc940ed3b2a03da33c');
await check('serialized-parent-reference-error-new-selection-binding-positive',async()=>{
 const isolate=expression=>{const start=expression.indexOf('const selection=(()=>{'),marker=expression.includes('\nconst diagnostics=')?'\nconst diagnostics=':'\nconst probe=',end=expression.indexOf(marker,start+1);return vm.runInNewContext(expression.slice(start,end)+'\nselection;',{bounded:{normalizeProbeIdentity}});},f=fixture(),selected=selectRiskRepresentatives({pass:f.pass,priorityFileId:f.context.priorityFileId,expectedPriorityVersion:f.context.priorityVersion});
 let failure;try{isolate(deliveredParent).planDeepCohorts(selected,f.context,1);}catch(e){failure=e;}assert.equal(failure.name,'ReferenceError');assert.match(failure.message,/normalizeProbeIdentity is not defined/);assert.equal(sanitizeFailureDiagnostic(failure,'selection-plan').exceptionClass,'ReferenceError');
 const repaired=isolate(built.expression).planDeepCohorts(selected,f.context,1);assert(repaired.plan.length>0&&repaired.plan.length<=8);assert.equal(repaired.summary.representatives,selected.privateManifest.selected.length);
});
await check('full-generated-factory-real-inventory-selector-plan-iso-ebml-positive',async()=>{
 const f=targetFixture();f.env.Headers=Headers;f.env.performance=performance;f.env.fetch=async(url,options)=>{const u=new URL(url);if(u.origin===ORIGIN)return f.runtime.nativeFetch(url,options);f.calls.push({url:u,init:options});if(u.pathname.endsWith('/about'))return Response.json({user:{permissionId:f.state.accountId}});if(u.pathname==='/drive/v3/files')return Response.json({incompleteSearch:false,files:f.pass.items});if(u.pathname.endsWith('/'+f.context.rootId))return Response.json(f.pass.rootBefore);const item=f.pass.items.find(x=>u.pathname.endsWith('/'+x.id));assert(item);return Response.json(item);};
 const entry=vm.runInNewContext(built.expression,f.env),job=entry(JSON.stringify({accountKey:f.state.accountId,generation:f.state.driveSessionGeneration,rootId:f.context.rootId,priorityFileId:f.context.priorityFileId}),f.proof,{cohort:1,mode:'probe'});
 for(let i=0;i<1000&&!job.poll().done;i++)await new Promise(resolve=>setTimeout(resolve,1));const r=job.poll().summary;assert(r,JSON.stringify(job.poll()));assert.equal(r.complete,true,JSON.stringify(r.failureDiagnostic));assert.equal(r.failureDiagnostic,null);assert.equal(r.inventoryRuns,2);assert(r.files.some(x=>x.kind==='iso-bmff'&&x.tracks?.status==='parsed'));assert(r.files.some(x=>x.kind==='webm'&&x.tracks?.status==='parsed'));assert.equal(r.released,true);assert(f.calls.every(x=>x.init.method==='GET'));assert.deepEqual(canaryPaths(r),[],JSON.stringify(canaryPaths(r)));entry.cleanup();
});

await check('immutable-29-source-rejects-28-app-and-proof',async()=>{
 const priorPin=JSON.parse(await readFile(new URL('../rc28-deeper-selection-diagnostic/binding.json',base)));const f=fixture();f.runtime.appVersion=priorPin.version;f.runtime.getSWIdentity=()=>({...priorPin,controller:f.runtime.navigator.serviceWorker.controller});const r=await f.make().run();assert.equal(r.failure,'RUNTIME_REJECTED');assert.equal(f.calls.length,0);
 const g=targetFixture(),entry=vm.runInNewContext(built.expression,g.env),job=entry('{}',{get:()=>({...priorPin,controller:g.runtime.navigator.serviceWorker.controller})},{cohort:1,mode:'probe'});assert.equal(job.poll().summary.failure,'SOURCE_BINDING_REJECTED');assert.equal(g.calls.length,0);
 const previous=await readFile(new URL('../rc28-deeper-selection-diagnostic/factory.expression.js',base));assert.equal(hash(previous),'9f2106e80560f69a1b2d886306ab9e346313ac1464e6f697f63c4ce7a3894ba4');
});
await check('moov-cache-coalesces-bounds-copies-release-current-and-byte-request-caps',async()=>{
 const calls=[],bytes=new Uint8Array(40000).fill(7),box={offset:1000,endExclusive:31000,size:30000,headerBytes:8},controller=new AbortController();let current=true;
 const make=(extra={})=>createMoovWindowCache({box,fileSize:40000,signal:controller.signal,checkCurrent:()=>{if(!current)throw Object.assign(Error('PRIVATE_OWNER'),{code:'OWNER_CHANGED'});},read:async r=>{calls.push(r);return bytes.subarray(Number(r.start),Number(r.end)+1);},...extra});
 const c=make();const a=await c.read({start:1100,end:1107});a.fill(0);assert.equal((await c.read({start:1150,end:1157}))[0],7);assert.equal(c.metrics().requests,1);assert(c.metrics().cacheHits>0);assert(calls.every(r=>r.start>=1008&&r.end<31000&&r.end-r.start+1<=16384));await assert.rejects(c.read({start:31000,end:31001}),e=>e.code==='SPARSE_INVALID_BOUNDS');current=false;await assert.rejects(c.read({start:1150,end:1157}),e=>e.code==='OWNER_CHANGED');current=true;c.release();assert(c.metrics().released);await assert.rejects(c.read({start:1150,end:1157}),e=>e.code==='SPARSE_CACHE_RELEASED');
 const limited=make({maxBytes:10});await assert.rejects(limited.read({start:1100,end:1107}),e=>e.code==='SPARSE_BYTE_LIMIT');assert.equal(limited.metrics().requests,0);limited.release();
 const requests=make({maxRequests:1});await requests.read({start:1100,end:1107});await assert.rejects(requests.read({start:30000,end:30007}),e=>e.code==='SPARSE_REQUEST_LIMIT');requests.release();
 let release;const late=make({read:()=>new Promise(resolve=>release=resolve)}),pending=late.read({start:1100,end:1107});late.release();release(new Uint8Array(15000));await assert.rejects(pending,e=>e.code==='SPARSE_CACHE_RELEASED');assert.equal(late.metrics().receivedBytes,0);
 const aborted=make();controller.abort();await assert.rejects(aborted.read({start:1100,end:1107}),e=>e.code==='SPARSE_ABORTED');aborted.release();
});
async function generatedRun({sparse=false,timeout=false,timeoutWindow=false,cleanupFailure=false,postflightDrift=false,finalCatalogDrift=false}={}){
 const f=targetFixture();f.env.Headers=Headers;f.env.performance=performance;let cancelled=0,failedId=null,firstMedia=true,identityReads=0,modelMs=0,listOrdinal=0;
 if(sparse){for(const file of f.files.filter(x=>x.mime==='video/mp4')){file.data=cat(box('ftyp',Buffer.from('isom'),Buffer.alloc(4)),box('free',Buffer.alloc(1200)),box('moov',...Array.from({length:20},()=>box('free',Buffer.alloc(1000))),moovFixture({audio:true}).subarray(8)),box('mdat',Buffer.alloc(4000)));const item=f.pass.items.find(x=>x.id===file.id);item.size=String(file.data.length);item.videoMediaMetadata={durationMillis:'7200000'};}Object.assign(f.state.files[0],f.pass.items[0]);delete f.state.files[0].version;}
 // Fast clock is test-only: the maintained 40s read-phase timer is accelerated,
 // leaving its 50s lifetime/postflight window intact. Production limits unchanged.
 if(timeout)f.env.setTimeout=(fn,ms,...args)=>setTimeout(fn,ms===40000&&firstMedia?100:ms,...args);
 f.env.fetch=async(url,options)=>{const u=new URL(url);if(u.origin===ORIGIN){modelMs+=900;await new Promise(resolve=>setTimeout(resolve,1));const range=/^bytes=(\d+)-(\d+)$/.exec(options.headers.Range);if(timeout&&firstMedia&&(!timeoutWindow||Number(range[2])-Number(range[1])+1>1000)){firstMedia=false;failedId=u.pathname.split('/').at(-1);f.calls.push({url:u,init:options});return new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(100));},cancel(){cancelled++;if(cleanupFailure)return Promise.reject(Error('PRIVATE_CANCEL_ERROR'));}}),{status:206,headers:{'Content-Range':`bytes ${range[1]}-${range[2]}/${u.searchParams.get('size')}`,'Content-Length':String(Number(range[2])-Number(range[1])+1),'Accept-Ranges':'bytes','Cache-Control':'no-store'}});}return f.runtime.nativeFetch(url,options);}
 f.calls.push({url:u,init:options});if(u.pathname.endsWith('/about'))return Response.json({user:{permissionId:f.state.accountId}});if(u.pathname==='/drive/v3/files'){listOrdinal++;return Response.json({incompleteSearch:false,files:finalCatalogDrift&&listOrdinal>2?f.pass.items.map((x,i)=>i===0?{...x,modifiedTime:'changed'}:x):f.pass.items});}if(u.pathname.endsWith('/'+f.context.rootId))return Response.json(f.pass.rootBefore);const item=f.pass.items.find(x=>u.pathname.endsWith('/'+x.id));assert(item);if(item.id===failedId&&++identityReads===1&&postflightDrift)return Response.json({...item,version:'changed'});return Response.json(item);};
 const entry=vm.runInNewContext(built.expression,f.env),job=entry(JSON.stringify({accountKey:f.state.accountId,generation:f.state.driveSessionGeneration,rootId:f.context.rootId,priorityFileId:f.context.priorityFileId}),f.proof,{cohort:1,mode:'probe'});
 for(let i=0;i<2000&&!job.poll().done;i++)await new Promise(resolve=>setTimeout(resolve,1));assert(job.poll().done);return {f,entry,r:job.poll().summary,cancelled,modelMs,failedId};
}
await check('serialized-full-factory-many-sparse-boxes-remote-rtt-model-coalesced',async()=>{
 const {f,entry,r,modelMs}=await generatedRun({sparse:true});assert.equal(r.complete,true,JSON.stringify(r.failureDiagnostic));assert.equal(r.inventoryRuns,2);assert.equal(r.catalogStable,true);const iso=r.files.filter(x=>x.kind==='iso-bmff');assert(iso.length>0);assert(iso.every(x=>x.complete&&x.tracks.status==='parsed'&&x.metadataWindows.released&&x.metadataWindows.requests<=2&&x.mediaRequests<=6));assert(modelMs<40000);coalescingEvidence={modeledPerGETMs:900,modeledCohortMediaMs:modelMs,isoFiles:iso.length,isoMediaRequests:iso.map(x=>x.mediaRequests),isoMediaBytes:iso.map(x=>x.mediaBytes),isoWindowRequests:iso.map(x=>x.metadataWindows.requests),tableParsing:false,windowsReleased:true};assert(r.files.every(x=>x.mediaBytes<=CAPS.mediaBytes&&x.mediaRequests<=64));
 for(const call of f.calls.filter(x=>x.url.origin===ORIGIN)){const file=f.files.find(x=>call.url.pathname.endsWith('/'+x.id));const [,a,b]=/^bytes=(\d+)-(\d+)$/.exec(call.init.headers.Range).map(Number);if(file.mime==='video/mp4'){const moovStart=1224,moovEnd=file.data.length-4008;assert(!(+a===moovStart&&+b===moovEnd-1));assert(+b<moovEnd||(+a>=moovEnd&&+b<moovEnd+8));}}
 assert.equal(r.allFilesComplete,true);assert.equal(r.filesDeferred,0);assert.deepEqual(canaryPaths(r),[]);assert(f.calls.every(x=>x.init.method==='GET'));entry.cleanup();
});
await check('serialized-timeout-retained-next-sample-final-catalog-target-fences',async()=>{
 const {f,entry,r,cancelled,failedId}=await generatedRun({timeout:true});assert.equal(r.failure,null,JSON.stringify(r.failureDiagnostic));assert.equal(r.complete,true);assert.equal(r.catalogStable,true);assert.equal(r.inventoryRuns,2);assert.equal(r.files[0].failure,'FILE_TIMEOUT');assert.equal(r.files[0].complete,false);assert.equal(r.files[0].disposition,'deferred');assert.equal(r.files[0].identityPostflight,true);assert.equal(r.files[0].ownedReadCleanupSettled,true);assert(r.files.slice(1).some(x=>x.complete));assert.equal(r.filesDeferred,1);assert.equal(r.filesComplete,r.files.length-1);assert.equal(r.allFilesComplete,false);assert.equal(cancelled,1);assert.deepEqual(canaryPaths(r),[]);
 f.state.files=[structuredClone(f.pass.items.find(x=>x.id===failedId))];delete f.state.files[0].version;f.button.closest=()=>({dataset:{fileId:failedId}});const target=await entry.target(r.files[0].representative);assert.equal(target.ready,true,JSON.stringify(target));f.state.tokenRevision++;assert.equal((await entry.target(r.files[0].representative)).reason,'OWNER_CHANGED');entry.cleanup();assert.equal((await entry.target(r.files[0].representative)).ready,false);
});
await check('serialized-timeout-cleanup-or-identity-failure-terminal-no-final-catalog',async()=>{
 for(const extra of [{cleanupFailure:true},{postflightDrift:true}]){const {f,entry,r}=await generatedRun({timeout:true,...extra});assert.equal(r.complete,false);assert.equal(r.catalogStable,false);assert.equal(r.inventoryRuns,1);assert.equal(r.files.length,1);assert.equal(r.files[0].identityPostflight,false);assert(['CLEANUP_FAILED','POSTFLIGHT_FAILED'].includes(r.failure),r.failure);assert.equal((await entry.target('representative-1')).reason,'FINAL_CATALOG_UNQUALIFIED');assert.deepEqual(canaryPaths(r),[]);assert(f.calls.every(x=>x.init.method==='GET'));entry.cleanup();}
});


await check('serialized-window-read-timeout-releases-cache-and-retains-file',async()=>{
 const {entry,r,cancelled}=await generatedRun({sparse:true,timeout:true,timeoutWindow:true});assert.equal(r.complete,true,JSON.stringify(r.failureDiagnostic));const deferred=r.files.find(x=>x.failure==='FILE_TIMEOUT');assert(deferred);assert.equal(deferred.metadataWindows.released,true);assert.equal(deferred.identityPostflight,true);assert.equal(deferred.ownedReadCleanupSettled,true);assert.equal(r.filesDeferred,1);assert.equal(r.catalogStable,true);assert.equal(cancelled,1);assert(r.files.every(x=>x.mediaRequests<=64&&x.mediaBytes<=CAPS.mediaBytes));assert.deepEqual(canaryPaths(r),[]);entry.cleanup();
});
await check('serialized-retained-file-does-not-mask-final-catalog-drift',async()=>{
 const {entry,r}=await generatedRun({timeout:true,finalCatalogDrift:true});assert.equal(r.complete,false);assert.equal(r.catalogStable,false);assert.equal(r.failure,'CATALOG_DRIFT');assert.equal(r.inventoryRuns,2);assert.equal(r.files[0].failure,'FILE_TIMEOUT');assert.equal(r.files[0].identityPostflight,true);assert.equal((await entry.target('representative-1')).reason,'FINAL_CATALOG_UNQUALIFIED');assert.deepEqual(canaryPaths(r),[]);entry.cleanup();
});
await check('terminal-summary-failure-never-qualifies-target-even-if-catalog-was-stable',async()=>{
 const f=targetFixture();let failure='CLEANUP_FAILED';const create=(_runtime,witness)=>{witness(f.selection,f.pass);return {poll:()=>({done:true,summary:{catalogStable:true,released:true,failure}}),cancel:()=>({cancelled:true})};};const entry=vm.runInNewContext('('+entrySource+')',f.env)(create,function(){return this({});},BINDING);entry('{}',f.proof,{cohort:1,mode:'probe'});assert.equal((await entry.target('representative-1')).reason,'FINAL_CATALOG_UNQUALIFIED');assert.equal(f.calls.length,0);failure=null;assert.equal((await entry.target('representative-1')).ready,true);entry.cleanup();
});
await writeFile(new URL('factory.expression.js',base),built.expression);await writeFile(new URL('provenance.json',base),JSON.stringify({...built.provenance,schema:'drive-original.rc29-deeper-coalesced-probe-build/1',derivativeOf:'qa/rc28-deeper-selection-diagnostic',readOnlyProbeModeEnabled:true,targetMetadataRequestCap:38,navigationMetadataRequestCap:8,targetResponseBytes:32768,targetMs:10000,actualExecution:false},null,2)+'\n');
const files=['entry.function.js','probe.mjs','selection.mjs','facade.function.js','binding.json','build.mjs','verify.mjs','factory.expression.js','provenance.json','diagnostics.mjs','moov-window-cache.mjs','README.md'];
const fileSHA256=Object.fromEntries(await Promise.all(files.map(async p=>[p,hash(await readFile(new URL(p,base)))])));
const frozenFiles=['entry.function.js','probe.mjs','selection.mjs','facade.function.js','binding.json','build.mjs','factory.expression.js','provenance.json'];
const frozenParentSHA256=Object.fromEntries(await Promise.all(frozenFiles.map(async p=>[p,hash(await readFile(new URL('../rc28-deeper-format-preparation/'+p,base)))])));
await writeFile(new URL('local-verification.json',base),JSON.stringify({schema:'drive-original.rc29-deeper-coalesced-probe-local/1',cases,passed:cases.length,actualRequests:0,actualRequestScope:'Drive/browser/account execution',actualExecution:false,productEdits:false,fileSHA256,frozenParentSHA256,deliveredParentExpressionSHA256:hash(deliveredParent),deliveredDiagnosticExpressionSHA256:'9f2106e80560f69a1b2d886306ab9e346313ac1464e6f697f63c4ce7a3894ba4',coalescingEvidence,observedParentIssue:{safeActualObservationFromRoot:true,mediaRequests:51,mediaBytes:1332,failure:'FILE_TIMEOUT',supportedExplanation:'tiny-range-request-granularity',actualNetworkTimingMeasuredThisUnit:false,codecProductCauseEstablished:false,parentPreserved:true},originalUIVersionAvailable:false,uiVersionInjected:false,codecHdrPresence:'partial-unknown',guidanceLookup:{performedThisUnit:false}},null,2)+'\n');
await writeFile(new URL('curated-savepoint.json',base),JSON.stringify({exactOwnedFiles:[...files,'local-verification.json','curated-savepoint.json'].map(p=>'qa/rc29-deeper-coalesced-probe/'+p),commitOwner:'root',actualResultsExcluded:true},null,2)+'\n');console.log(JSON.stringify({passed:cases.length,expressionSHA256:hash(built.expression),expressionBytes:Buffer.byteLength(built.expression),actualRequests:0}));
