'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const fixtureModule={exports:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'app.test.js'),'utf8').split('\ntest(')[0]+'\nmodule.exports=loadAppContext;', {require,__dirname,module:fixtureModule,AbortController,Blob,DOMException,Headers,Map,Math,Promise,Response,Set,URL,URLSearchParams,clearInterval,clearTimeout,console,fetch,performance,setInterval,setTimeout});
const run=(c,s)=>vm.runInContext(s,c);
const existing=fs.readFileSync(path.join(__dirname,'general-app-routing.test.js'),'utf8');
const fixture=vm.runInNewContext(existing.slice(existing.indexOf('function pinnedProbeFixture('),existing.indexOf('\nfor(const change of ["mediaSourceGeneration++"'))+'\npinnedProbeFixture', {fixtureModule,run,fs,path,__dirname,queueMicrotask,Promise,Uint8Array});
const png=fs.readFileSync(path.join(__dirname,'../qa/rc16-image-format/alpha.png'));
const turn=()=>new Promise(setImmediate);
function imageFixture(bytes=png){const f=fixture({bytes});const reads=[];let finishRetirement;
 const retirement=new Promise(r=>finishRetirement=r),open=f.c.fakeSourceModule.openDriveQ1Source;
 f.c.fakeSourceModule.openDriveQ1Source=async(...args)=>{const source=await open(...args),read=source.read;source.read=async q=>{reads.push({start:q.start,end:q.end});return read(q);};return source;};
 run(f.c,`state.accountId='account';state.playbackSession=4;el.playerSheet={hidden:false};globalThis.imageStarts=[];globalThis.videoActions=[];
 confirmQ1WorkerRetirement=()=>workerRetirement;clearDirectMediaSources=()=>{retireQ0Playback();retireQ1Playback(null);mediaSourceGeneration++;probeClears++;};
 beginMediaViewObservation=()=>{};setNativeVideoActionsAvailable=v=>videoActions.push(v);startOriginalRangePlayback=(file,kind,session)=>{imageStarts.push({kind,session});return true;};`);
 f.c.workerRetirement=retirement;
 return {...f,reads,finishRetirement:(value=true)=>finishRetirement(value)};}
async function throughAbort(f,settled=true){await f.reading;f.releaseRead();await f.aborting;f.releaseAbort({settled});await run(f.c,'probeOwner.setupDone');await turn();}
test('verified raster handoff waits for source abort and Q0 worker retirement, retaining exact pin',async()=>{const f=imageFixture();await f.reading;f.releaseRead();await f.aborting;await turn();assert.equal(f.c.imageStarts.length,0);f.releaseAbort({settled:true});assert.equal(await run(f.c,'probeOwner.setupDone'),'image/png');await turn();assert.equal(f.c.imageStarts.length,0);assert.equal(run(f.c,'state.mediaAttempt'),'image-routing');f.finishRetirement();await turn();assert.equal(f.c.imageStarts.length,1);assert.equal(f.c.imageStarts[0].kind,'image');assert.deepEqual(f.reads,[{start:0,end:11},{start:0,end:63}]);assert.equal(run(f.c,'currentVerifiedOriginalImage().pin===q0PinnedSource'),true);assert.equal(run(f.c,'isVideoPresentation()'),false);assert(f.c.videoActions.length>0);assert(f.c.videoActions.every(v=>v===false),'verified image must never enable video actions');});
for(const change of ["state.selected={id:'other'}","state.mediaSession++","state.playbackSession++","state.accountId='other'","state.authAccountKey='other'","state.driveSessionGeneration++","mediaSourceGeneration++","initialMediaRouteGeneration++","navigator.serviceWorker.controller={}","q0PinnedSource={}"])
test('retirement cannot hand an image to changed lifetime: '+change,async()=>{const f=imageFixture();await throughAbort(f);run(f.c,change);f.finishRetirement();await turn();assert.equal(f.c.imageStarts.length,0);assert.equal(run(f.c,'currentVerifiedOriginalImage()'),null);});
for(const change of ["state.selected={id:'other'}","state.mediaSession++","state.authAccountKey='other'","state.driveSessionGeneration++","mediaSourceGeneration++","navigator.serviceWorker.controller={}","q0PinnedSource={}"])
test('probe result cannot hand off after source invalidation: '+change,async()=>{const f=imageFixture();await f.reading;run(f.c,change);f.releaseRead();await f.aborting;f.releaseAbort({settled:true});await run(f.c,'probeOwner.setupDone');f.finishRetirement();await turn();assert.equal(f.c.imageStarts.length,0);});
test('uncertain source cleanup stays terminal and cannot start image',async()=>{const f=imageFixture();await throughAbort(f,false);f.finishRetirement();await turn();assert.equal(f.c.imageStarts.length,0);assert.equal(run(f.c,'probeOwner.cleanupOk'),false);assert.equal(run(f.c,'state.mediaAttempt'),'failed');});
for(const [name,bytes] of [['HTML',Buffer.from('<!doctype html><html>not an image</html>')],['JSON',Buffer.from('{"error":"not image"}')],['truncated PNG',png.subarray(0,16)]])
test('negative original bytes cannot become an image owner: '+name,async()=>{const f=imageFixture(bytes);await throughAbort(f);f.finishRetirement();await turn();assert.equal(f.c.imageStarts.length,0);assert.equal(run(f.c,'currentVerifiedOriginalImage()'),null);if(name==='truncated PNG')assert.equal(run(f.c,'state.mediaAttempt'),'failed');});
test('valid ISO native path adds no image header read or owner transition',async()=>{const bytes=Buffer.from([0,0,0,12,102,116,121,112,0,0,0,0,...new Array(88).fill(0)]),f=imageFixture(bytes);let probes=0;f.c.fakeProbeModule={probePinnedGeneralAudio:async()=>{probes++;return {route:'native'};}};await f.reading;f.releaseRead();await run(f.c,'probeOwner.setupDone');await turn();assert.equal(probes,1);assert.deepEqual(f.reads,[{start:0,end:11}]);assert.equal(f.c.imageStarts.length,0);assert.equal(run(f.c,'isVideoPresentation()'),true);});
for(const [fixtureName,mime] of [['alpha.png','image/png'],['animated.webp','image/webp'],['animated.gif','image/gif'],['raster.bmp','image/bmp']])
test('maintained raster structural header supports bounded dispatch: '+fixtureName,()=>{const f=imageFixture(),bytes=fs.readFileSync(path.join(__dirname,'../qa/rc16-image-format',fixtureName));f.c.header=bytes.subarray(0,64);f.c.size=bytes.length;f.c.mime=mime;assert.equal(run(f.c,'isValidOriginalImageHeader(header,size,mime)'),true);});
test('verified selected lifetime clears on reset and never rewrites declared metadata',async()=>{const f=imageFixture();await throughAbort(f);f.finishRetirement();await turn();assert.equal(run(f.c,'state.selected.mimeType'),'video/mp4');run(f.c,"clearMediaSeekWatchdog=clearMediaFrameWatchdog=cancelVideoFrameSampling=cleanupOriginalTempStorage=clearDrivePreview=()=>{};el.mediaError={hidden:false};el.drivePreview={removeAttribute(){},hidden:false};el.mediaLoading={hidden:false};for(const key of ['openDriveButton','retryMediaButton','bufferOriginalButton','compatPlayerButton','mediaLoadingText'])el[key]={};resetMediaElements()");assert.equal(run(f.c,'currentVerifiedOriginalImage()'),null);assert.equal(run(f.c,'verifiedOriginalImage'),null);});

test('native code4 first waits for the delayed pinned probe instead of a competing video retry',async()=>{const f=imageFixture();f.c.window.setTimeout=fn=>setTimeout(fn,0);run(f.c,`globalThis.videoRetries=0;el.videoPlayer={hidden:false,getAttribute:()=>'/original',error:{code:4}};clearMediaSeekWatchdog=clearMediaFrameWatchdog=()=>{};navigator.onLine=true;hasUsableToken=()=>true;retryOriginalStream=()=>videoRetries++;`);await f.reading;const handling=run(f.c,"handleMediaElementError('video')");await new Promise(r=>setTimeout(r,10));assert.equal(f.c.videoRetries,0);assert.equal(f.c.imageStarts.length,0);f.releaseRead();await f.aborting;f.releaseAbort({settled:true});await run(f.c,'probeOwner.setupDone');assert.equal(f.c.videoRetries,0);f.finishRetirement();await handling;await turn();assert.equal(f.c.imageStarts.length,1);});

test('uncertain Q0 worker retirement cannot present a validated raster',async()=>{const f=imageFixture();await throughAbort(f);f.finishRetirement(false);await turn();assert.equal(f.c.imageStarts.length,0);assert.equal(run(f.c,'state.mediaAttempt'),'failed');assert.equal(run(f.c,'currentVerifiedOriginalImage()'),null);assert.equal(run(f.c,'q1RetirementResult.settled'),false);});
for(const change of ["state.selected={id:'other',mimeType:'video/mp4'}","state.authAccountKey='other'","q0PinnedSource={}"])
test('a verified hint cannot cross a later selected/account/pin owner: '+change,async()=>{const f=imageFixture();await throughAbort(f);f.finishRetirement();await turn();assert.equal(run(f.c,'isVideoPresentation()'),false);run(f.c,change);assert.equal(run(f.c,'currentVerifiedOriginalImage()'),null);assert.equal(run(f.c,'isVideoPresentation()'),true);});

test('classified worker buffer recovery retains the verified image kind',async()=>{const f=imageFixture();await throughAbort(f);f.finishRetirement();await turn();run(f.c,`globalThis.bufferKinds=[];clearMediaSeekWatchdog=clearMediaFrameWatchdog=()=>{};offerOriginalBufferFallback=async(file,kind)=>bufferKinds.push(kind);state.mediaRetryCount=1;`);await run(f.c,"recoverFromMediaProxyError({status:503,reason:'upstream-http',fileId:'f'})");assert.deepEqual(Array.from(f.c.bufferKinds),['image']);});
test('verified image range retry preserves its pin/lifetime and existing single retry budget',async()=>{const f=imageFixture();await throughAbort(f);f.finishRetirement();await turn();const session=run(f.c,'state.mediaSession');assert.equal(run(f.c,"retryOriginalStream(state.selected,state.mediaSession,'retry')"),true);assert.equal(f.c.imageStarts.at(-1).kind,'image');assert.equal(run(f.c,'state.mediaSession'),session);assert.equal(run(f.c,'state.mediaRetryCount'),1);assert.equal(run(f.c,'currentVerifiedOriginalImage().mimeType'),'image/png');assert.equal(run(f.c,"retryOriginalStream(state.selected,state.mediaSession,'retry')"),false);});
test('ISO format decision releases code4 before optional audio capability work completes',async()=>{const bytes=Buffer.from([0,0,0,12,102,116,121,112,0,0,0,0,...new Array(88).fill(0)]),f=imageFixture(bytes);let finishProbe;f.c.fakeProbeModule={probePinnedGeneralAudio:()=>new Promise(r=>finishProbe=r)};f.c.window.setTimeout=fn=>setTimeout(fn,0);run(f.c,`globalThis.videoRetries=0;el.videoPlayer={hidden:false,getAttribute:()=>'/original',error:{code:4}};clearMediaSeekWatchdog=clearMediaFrameWatchdog=()=>{};navigator.onLine=true;hasUsableToken=()=>true;retryOriginalStream=()=>videoRetries++;`);await f.reading;const handling=run(f.c,"handleMediaElementError('video')");f.releaseRead();await handling;assert.equal(f.c.videoRetries,1);finishProbe({route:'native'});await run(f.c,'probeOwner.setupDone');});
