'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const rawNames={cold:'discriminator-2026-09-29T23-03-10-729Z.json',firstCycles:'cycles-2026-09-29T23-03-53-055Z.json',frameOrder:'q0-discriminator-2026-09-29T23-05-40-999Z.json',q0:'q0-discriminator-2026-09-29T23-07-11-844Z.json',cycles:'cycles-2026-09-29T23-07-35-708Z.json',strictEnd:'long-2026-09-29T23-08-49-924Z.json',longTail:'long-2026-09-29T23-11-34-447Z.json',readiness:'trend-q1-2026-09-29T23-14-21-095Z.json',q1Trend:'trend-q1-2026-09-29T23-15-54-240Z.json',q2Trend:'trend-q2-2026-09-29T23-16-48-033Z.json'};
const reports=Object.fromEntries(Object.entries(rawNames).map(([key,name])=>[key,JSON.parse(fs.readFileSync(path.join(__dirname,name)))]));
const snapshots={cold:'producer-initial-cold.cjs',firstCycles:'producer-first-cycle-failure.cjs',frameOrder:'producer-frame-order-discriminator.cjs',q0:'producer-frame-join.cjs',cycles:'producer-frame-join.cjs',strictEnd:'producer-frame-join.cjs',longTail:'producer-long-tail.cjs',readiness:'producer-trend-initial.cjs',q1Trend:'qualify.cjs',q2Trend:'qualify.cjs'};
const publicSource='ee0ac8449e37a982ab2204b5b65e472a6e04b6f4';
const pin=reports.cycles.producerStart;
for(const [name,expected] of Object.entries(pin))assert.equal(hash(execFileSync('git',['show',`${publicSource}:${name}`],{cwd:root,maxBuffer:80*1024*1024})),expected,`PUBLIC_GIT_PIN:${name}`);
for(const [key,r] of Object.entries(reports)){
 assert.deepEqual(r.producerStart,pin);assert.deepEqual(r.producerEnd,pin);assert.equal(r.browserClosed,true);
 assert.equal(hash(fs.readFileSync(path.join(__dirname,snapshots[key]))),r.harness['qualify.cjs'],`EXACT_PRODUCER:${key}`);
}
for(const key of ['cold','q0','cycles','longTail','q1Trend','q2Trend'])assert.equal(reports[key].passed,true,key);
for(const key of ['firstCycles','frameOrder','strictEnd','readiness'])assert.equal(reports[key].passed,false,key);
assert.equal(reports.cycles.results.length,50);assert.equal(reports.cycles.results.reduce((n,x)=>n+x.seeks.length,0),150);
assert.ok(reports.cycles.results.every(x=>x.seeks.every(s=>Number.isFinite(s.target)&&Number.isFinite(s.mediaTime)&&Math.abs(s.target-s.mediaTime)<=1/24+.004)));
assert.equal(reports.frameOrder.failedSeek.frames[0].mediaTime,1);assert.equal(reports.frameOrder.failedSeek.frames[0].seeking,true);assert.equal(reports.frameOrder.failedSeek.seeking,false);
assert.equal(reports.readiness.failedSeek.target,null);assert.equal(reports.readiness.failureObservation.stats.failure,null);
const q1Review=JSON.parse(fs.readFileSync(path.join(__dirname,'long-q1-end-review.json')));assert.equal(q1Review.passed,true);assert.equal(q1Review.rawSha256,hash(fs.readFileSync(path.join(__dirname,rawNames.strictEnd))));
const resources=r=>r.resources.map(x=>({phase:x.phase,privateMiB:x.chromePrivateBytes/1048576,workingSetMiB:x.chromeWorkingSetBytes/1048576,commitAvailableGiB:x.host.commitAvailableGiB,physicalAvailableGiB:x.host.physicalAvailableGiB,processes:x.processes.map(p=>({type:p.type,pid:p.pid,observed:p.observed,privateMiB:p.privateBytes/1048576}))}));
const count=r=>({cycles:r.results.length,seeks:r.results.reduce((n,x)=>n+(x.seeks?.length??0),0),passed:r.passed});
const summary={scope:'Bounded synthetic actual app/SW lifecycle and72-second native playback observations on fixed rc15 public source; no device/account/corpus/native-memory-ceiling acceptance.',publicSource,publicFileCount:Object.keys(pin).length,browser:reports.cycles.browser,
 producer:hash(fs.readFileSync(__filename)),reports:rawNames,exactQaProducers:snapshots,cold:count(reports.cold),q0Discriminator:count(reports.q0),mixedCycles:{...count(reports.cycles),routeCounts:Object.fromEntries(['q1','q2','q0'].map(route=>[route,reports.cycles.results.filter(x=>x.route===route).length])),closedResources:reports.cycles.results.at(-1).after.resources},
 long:{q1:{readOnlyPrecisionReview:'long-q1-end-review.json',elapsedMs:q1Review.observedSourceEnd.elapsedMs,time:q1Review.observedSourceEnd.time,frames:q1Review.observedSourceEnd.frames,missingPostLongAppRetirement:true},q2:reports.longTail.results[0],q0:reports.longTail.results[1]},
 nativeTrends:{q1:{...count(reports.q1Trend),resources:resources(reports.q1Trend)},q2:{...count(reports.q2Trend),resources:resources(reports.q2Trend)},mixed:resources(reports.cycles)},
 retainedFailures:['First mixed Q0 timeout lacked before-close state and cannot be retrospectively assigned an exact cause.','Later Q0 discriminator confirms target frame arrived before seeking became false; QA incorrectly demanded both in the same callback.','First long Q1 reached native ended with all1728frames but strict equality rejected1microsecond endpoint quantization.','First Q1 trend computed a non-finite target while latest owner was opening; QA now waits for latest mapping and finite duration.'],
 unresolved:['Native renderer private-memory growth persists after15s idle despite zero app/SW/worker/URL owners; plateau, allocator/decoder/worker contribution and mobile costs are unproved.','Historical cold GENERAL_PIPELINE_FAILED decoder-open/OtherError1of4 remains unexplained;3fresh Q2 passes do not erase it.','72-second fixture is bounded longer playback, not multi-hour or299-second regression proof.','No post-long Q1 app/SW retirement was observed; its browser close and separate50cycle retirement proof remain distinct.'],checksPassed:true,fullQualification:false};
fs.writeFileSync(path.join(__dirname,'summary.json'),JSON.stringify(summary,null,2)+'\n');
const files=fs.readdirSync(__dirname).filter(n=>!n.endsWith('.mp4')&&!['evidence-manifest.json','curated-savepoint.json'].includes(n));
const manifest={scope:summary.scope,publicSource,publicProductHashes:pin,files:Object.fromEntries(files.map(n=>[n,{sha256:hash(fs.readFileSync(path.join(__dirname,n))),bytes:fs.statSync(path.join(__dirname,n)).size}])),dependencies:Object.fromEntries(['qa/host-resource-snapshot.py','qa/q1-product-audit.cjs','qa/q1-q2-app-integration/native-retirement-smoke.cjs','qa/faststart-h264-aac.mp4','qa/q2-audio-compatibility/synthetic-avc-ac3.mp4'].map(n=>[n,{sha256:hash(fs.readFileSync(path.join(root,n)))}])),regenerableFixtures:JSON.parse(fs.readFileSync(path.join(__dirname,'fixture-provenance.json'))).fixtures.map(f=>({path:f.path,sha256:f.sha256,bytes:f.bytes})),excluded:['Regenerable72-second MP4 binaries','Installed Playwright/Chrome/FFmpeg SDK/cache','Private account/original media; none used']};
fs.writeFileSync(path.join(__dirname,'evidence-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'curated-savepoint.json'),JSON.stringify({files:files.map(n=>'qa/rc15-lifecycle-qualification/'+n).concat(['qa/rc15-lifecycle-qualification/evidence-manifest.json','qa/rc15-lifecycle-qualification/curated-savepoint.json']),excluded:manifest.excluded},null,2)+'\n');
console.log('Fixed Git52public bytes, all10raw before/after fences, exact10producer bindings, counts, retained discriminators, native endpoint review and safe curation PASS');
