'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const h=require('./pc-cold-admission.cjs');
const empty=()=>({timeOrigin:1,closed:true,ownersEmpty:true,retirementSettled:true,appBuffersEmpty:true,nativeEmpty:true,selectedEmpty:true,foreground:true,online:true});
test('all idle byte owners/native buffers must be absent; cache flag alone insufficient',()=>{assert(h.qualifyIdle(empty()));for(const k of Object.keys(empty()).filter(k=>k!=='timeOrigin'))assert.equal(h.qualifyIdle({...empty(),[k]:false}),false);assert.equal(h.qualifyCold({cacheDisabledCommandAcknowledged:true}).qualified,false);});
test('inert root execution and exclusive-session admission',async()=>{let sent=0;const s={send:async()=>{sent++;}};await assert.rejects(h.prepareOwnedPage(s),/ROOT_EXECUTION/);await assert.rejects(h.attachOwnedSourceWorker(s),/ROOT_EXECUTION/);assert.equal(sent,0);});
test('cache scope command acknowledgement and owned restoration on cleanup',async()=>{const calls=[],s={send:async(method,params)=>{calls.push([method,params]);if(method==='Runtime.evaluate')return {result:{value:empty()}};return {};}};const p=await h.prepareOwnedPage(s,{execute:true,freshExclusiveSession:true});assert(p.cacheDisabledCommandAcknowledged);assert.match(p.installExpression('protectedInput','binding'),/installColdAdmission/);const stop=await p.stop();assert(stop.cacheRestoredToOwnedSessionDefault&&stop.ownedPageNetworkDisabled);assert.deepEqual(calls.filter(c=>c[0]==='Network.setCacheDisabled').map(c=>c[1].cacheDisabled),[true,false]);});
test('pre-reload nonempty state fails without enabling cache bypass',async()=>{const methods=[],s={send:async method=>{methods.push(method);return {result:{value:{...empty(),nativeEmpty:false}}};}};await assert.rejects(h.prepareOwnedPage(s,{execute:true,freshExclusiveSession:true}),/PRIOR_OWNER/);assert.deepEqual(methods,['Runtime.evaluate']);});
test('page passive fences, fresh reload, prohibited buffer and timer cleanup',()=>{
 const controller={},id='synthetic-test',target={id,size:2**30,mimeType:'video/mp4',headRevisionId:'r',sha256Checksum:'a'.repeat(64),version:'1'},binding={sourceCommit:h.SOURCE,version:h.VERSION,sourceSHA256:{a:'1',b:'2',c:'3'}};
 let cleared=0;const c={URL,window:{__resumeSwProof:{get:()=>({...binding,controller})}},performance:{timeOrigin:2,getEntriesByType:()=>[{type:'reload'}]},APP_VERSION:h.VERSION,location:{href:'https://example.test/',origin:'https://example.test'},navigator:{serviceWorker:{controller},onLine:true},document:{visibilityState:'visible'},state:{accountId:'a',authAccountKey:'k',authGeneration:1,driveSessionGeneration:1},el:{playerSheet:{hidden:true},videoPlayer:{getAttribute:()=>null,currentSrc:'',srcObject:null,querySelectorAll:()=>[],readyState:0,networkState:0,buffered:{length:0}}},q0Playback:null,q1Playback:null,q0PinnedSource:null,q0ControlWait:null,playerTracksOwner:null,q1RetirementResult:{settled:true},playerTracksRetirementResult:{settled:true},pendingPlaybackRestore:null,hasUsableToken:()=>true,isCurrentQ0Playback:()=>true,isCurrentMediaEvent:()=>true,mediaSourceGeneration:1,setInterval:()=>1,setTimeout:()=>2,clearInterval:()=>cleared++,clearTimeout:()=>cleared++};vm.createContext(c);const f=vm.runInContext('('+h.installColdAdmission.toString()+')',c);assert.throws(()=>f({target},binding,2),/FRESH_DOCUMENT/);f({target},binding,1);c.q0Playback={};assert.equal(c.window.__pcColdAdmission.sample().routeObserved,false);assert.equal(c.window.__pcColdAdmission.read().failure,null);c.state.mediaTempStorage={};assert.equal(c.window.__pcColdAdmission.sample().failure,'COLD_NON_Q0_BUFFER_PATH');c.state.mediaTempStorage=null;assert.equal(c.window.__pcColdAdmission.sample().failure,'COLD_NON_Q0_BUFFER_PATH');assert(c.window.__pcColdAdmission.stop().privateOwnerReleased);assert.equal(cleared,2);});
test('protocol-boundary failure clears owned worker session without touching page cache',async()=>{const calls=[],s={send:async(method)=>{calls.push(method);return {targetInfos:[]}},on(){},off(){}};await assert.rejects(h.attachOwnedSourceWorker(s,{execute:true,id:'fixture',size:2**30,revision:'r'}),/PAGE_TARGET_COUNT/);assert.deepEqual(calls,['Target.getTargets']);});
test('cold qualification requires every independent proof and complete uncached worker records',()=>{
 // Reuse only the immutable safe reduced Network shape; no original-body replay.
 const saved=JSON.parse(require('node:fs').readFileSync(require('node:path').join(__dirname,'../rc32-q0-byte-acceptance/actual-android-q0-byte-attempt3-safe.json'),'utf8'));
 const n=saved.steps.map(s=>s.network).filter(n=>n?.live===0&&n?.rows?.length===2).at(-1);assert(n);
 const a={sourceCommit:h.SOURCE,version:h.VERSION,freshDocument:true,nativeEmptyAtAdmission:true,appOwnedBufferEmptyAtAdmission:true,routeObserved:true,current:true,failure:null};
 const o={admission:a,cacheDisabledCommandAcknowledged:true,workerUnchanged:true,metadataQualified:true,byteObserverQualified:true,normalCloseQualified:true,networkEvidence:n};assert.equal(h.qualifyCold(o).qualified,true);
 for(const k of ['cacheDisabledCommandAcknowledged','workerUnchanged','metadataQualified','byteObserverQualified','normalCloseQualified'])assert.equal(h.qualifyCold({...o,[k]:false}).qualified,false);
 for(const k of ['freshDocument','nativeEmptyAtAdmission','appOwnedBufferEmptyAtAdmission','routeObserved','current'])assert.equal(h.qualifyCold({...o,admission:{...a,[k]:false}}).qualified,false);
 assert.equal(h.qualifyCold({...o,admission:{...a,sourceCommit:'wrong'}}).qualified,false);
 for(const change of [r=>r.cache=true,r=>r.terminal=false]){const bad=structuredClone(n);change(bad.rows[0]);assert.equal(h.qualifyCold({...o,networkEvidence:bad}).qualified,false);}
});
