import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {boxClocks} from './independent.mjs';
const leaf=path.dirname(fileURLToPath(import.meta.url));const oracle=JSON.parse(fs.readFileSync(path.join(leaf,'oracle-results.json'))),native=JSON.parse(fs.readFileSync(path.join(leaf,'native-results.json'))),single=JSON.parse(fs.readFileSync(path.join(leaf,'native-one-picture-color-results.json')));
const cases=[];
for(const row of native.observations.filter(r=>r.nativeOriginalComparison)){
 const source=path.join(leaf,row.name+'.mp4'),clock=boxClocks(source),probe=JSON.parse(fs.readFileSync(path.join(leaf,'oracle-'+row.name+'-source-ffprobe.json'))),video=probe.streams.find(x=>x.codec_type==='video'),id=Number(video.id),packets=probe.packets.filter(p=>p.stream_index===video.index),scale=Number(clock.edits[id].scale),edit=clock.edits[id].shift.map(Number),samples=clock.tracks[id].map((p,i)=>({decodeIndex:i,sourcePts:Number(p.pts)/scale+edit[0]/edit[1],sourceDts:Number(p.dts)/scale+edit[0]/edit[1],codedPacketHash:packets[i]?.data_hash}));
 const candidate=pts=>{const s=samples.reduce((a,b)=>Math.abs(a.sourcePts-pts)<Math.abs(b.sourcePts-pts)?a:b);return {...s,reportedPtsError:pts-s.sourcePts,exactWithinMicrosecond:Math.abs(pts-s.sourcePts)<1e-6};};
 cases.push({name:row.name,comparisonKind:'native direct original versus native MSE; canvas pixels captured within rVFC',samples:row.nativeOriginalComparison.map(c=>c.control?c:({movieTarget:c.movieTime,originalReportedMediaTime:c.original.mediaTime,remuxedReportedMediaTime:c.remuxed.mediaTime,mappedOriginalClock:c.remuxed.mediaTime+row.window.commonShift,originalTimestampCandidate:candidate(c.original.mediaTime),remuxTimestampCandidate:candidate(c.remuxed.mediaTime+row.window.commonShift),rgbEqual:c.samePixels,pixelError:c.pixelError})),identityLimit:'Dynamic timestamp candidates are not independent decoded picture identity. Only the one-picture fixture has an unambiguous encoded picture index (0).'});
}
const first=single.observations[0].nativeOriginalComparison[0],singleOracle=oracle.observations.find(o=>o.name==='one-picture-color');
const report={scope:'Bounded causal trial; distinguish container preservation, FFmpeg timestamp rewriting, native playback, native frame selection, and native color interpretation.',containerCasesPassed:oracle.passed,containerCasesFailed:oracle.failed,rawClockArithmetic:'Independent stts/ctts/elst and tfdt/trun parser uses rational integer comparisons; no tolerance. MPEG-TS source clocks independently read by FFprobe.',defaultFfprobeMovieClockDisagreements:oracle.observations.filter(o=>o.tracks.some(t=>!t.exactPtsRational||!t.exactDtsRational)).map(o=>o.name),nativePlaybackCases:native.observations.filter(o=>o.decoded?.length===3).length,nativeUnsupported:native.observations.filter(o=>o.failure?.message.startsWith('NATIVE_CODEC_UNSUPPORTED')).map(o=>({name:o.name,error:o.failure.message})),singlePicture:{encodedPictureCount:singleOracle.rawPixels.frames,encodedPictureIndex:0,sourceDeclaredColor:{matrix:'bt709',primaries:'bt709',transfer:'bt709',fullRange:false},rawDecodedPixelsEqual:singleOracle.rawPixels.equal,originalNativeColor:first.original.nativeColor,remuxNativeColor:first.remuxed.nativeColor,mappedPtsError:first.sourcePtsDifference,originalRgbSha256:first.original.hash,remuxRgbSha256:first.remuxed.hash,pixelError:first.pixelError,directVersusDirect:single.observations[0].nativeOriginalComparison.at(-1)},cases,conclusion:'Original bytes/config/clocks are preserved in these fixtures. Direct playback resolves declared BT.709 to SMPTE170M whereas MSE resolves BT.709; matching the direct RGB by changing metadata would violate preservation. Native dynamic frame selection and cross-route color interpretation are not certified equivalent; component-level cause and broader device behavior remain unknown.',nextDiscriminator:'Replay known per-frame identity with separately decoded reference images, distinguishing MSE VFR selection from the direct demuxer edit/CTTS rewrite. Do not shift tracks independently or remove genuine color declarations.'};
fs.writeFileSync(path.join(leaf,'native-diagnosis.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({containerPassed:report.containerCasesPassed,nativePlaybackCases:report.nativePlaybackCases,defaultFfprobeMovieClockDisagreements:report.defaultFfprobeMovieClockDisagreements,singlePictureColor:first.original.nativeColor,remuxColor:first.remuxed.nativeColor}));
