import fs from 'node:fs';import {spawnSync} from 'node:child_process';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const call=(tool,args)=>{const r=spawnSync(tool,['-v','error',...args],{maxBuffer:16*1024*1024});assert.equal(r.status,0,r.stderr?.toString());return r.stdout;};
const gcd=(a,b)=>b?gcd(b,a%b):a, rat=(n,d=1n)=>{const g=gcd(n<0?-n:n,d);return [n/g,d/g];};
const add=(a,b)=>rat(a[0]*b[1]+b[0]*a[1],a[1]*b[1]),neg=a=>[-a[0],a[1]],eq=(a,b)=>a[0]*b[1]===b[0]*a[1];
const readBoxes=(b,start=0,end=b.length)=>{const out=[];for(let p=start;p<end;){let n=b.readUInt32BE(p),h=8;if(n===1){n=Number(b.readBigUInt64BE(p+8));h=16;}if(!n)n=end-p;assert.ok(n>=h&&p+n<=end);out.push({type:b.toString('ascii',p+4,p+8),start:p+h,end:p+n});p+=n;}return out;};
const child=(b,p,t)=>readBoxes(b,p.start,p.end).find(x=>x.type===t);
// Independent container edit arithmetic; this never calls Mediabunny.
export function editOffsets(file){if(file.endsWith('.ts'))return null;const b=fs.readFileSync(file),moov=readBoxes(b).find(x=>x.type==='moov');if(!moov)return null;const mv=child(b,moov,'mvhd'),movieScale=BigInt(b.readUInt32BE(mv.start+(b[mv.start]===1?20:12))),out={};
 for(const t of readBoxes(b,moov.start,moov.end).filter(x=>x.type==='trak')){const tk=child(b,t,'tkhd'),id=b.readUInt32BE(tk.start+(b[tk.start]===1?20:12)),md=child(b,child(b,t,'mdia'),'mdhd'),scale=BigInt(b.readUInt32BE(md.start+(b[md.start]===1?20:12))),ed=child(b,t,'edts'),el=ed&&child(b,ed,'elst');let shift=rat(0n);if(el){const v=b[el.start],count=b.readUInt32BE(el.start+4);let content=0;for(let k=0;k<count;k++){const p=el.start+8+k*(v?20:12),duration=v?b.readBigUInt64BE(p):BigInt(b.readUInt32BE(p)),time=v?b.readBigInt64BE(p+8):BigInt(b.readInt32BE(p+4));const rate=b.readInt32BE(p+(v?16:8));assert.equal(rate,65536);if(time===-1n){assert.equal(content,0);shift=add(shift,rat(duration,movieScale));}else{assert.equal(content++,0);shift=add(shift,neg(rat(time,scale)));}}}out[id]={shift,scale};}return out;}
const probeRaw=file=>JSON.parse(call('ffprobe',[...(file.endsWith('.ts')?[]:['-ignore_editlist','1']),'-show_packets','-show_streams','-of','json',file]));
const time=(p,s,f)=>{const [n,d]=s.time_base.split('/').map(BigInt);return rat(BigInt(p[f])*n,d);};
// Exact sample-table / fragment clocks. FFmpeg itself rewrites negative ctts
// DTS even with ignore_editlist=1, so that option is not a raw box oracle.
export function boxClocks(file){if(file.endsWith('.ts'))return null;const b=fs.readFileSync(file),top=readBoxes(b),moov=top.find(x=>x.type==='moov'),edits=editOffsets(file),out={},defaults={};
 for(const trak of readBoxes(b,moov.start,moov.end).filter(x=>x.type==='trak')){const tk=child(b,trak,'tkhd'),id=b.readUInt32BE(tk.start+(b[tk.start]===1?20:12)),stbl=child(b,child(b,child(b,trak,'mdia'),'minf'),'stbl');out[id]=[];const stts=child(b,stbl,'stts'),ctts=child(b,stbl,'ctts');let dts=0n;for(let i=0;i<b.readUInt32BE(stts.start+4);i++){const p=stts.start+8+i*8,count=b.readUInt32BE(p),duration=BigInt(b.readUInt32BE(p+4));for(let n=0;n<count;n++){out[id].push({pts:dts,dts,duration});dts+=duration;}}if(ctts){let sample=0;for(let i=0;i<b.readUInt32BE(ctts.start+4);i++){const p=ctts.start+8+i*8,count=b.readUInt32BE(p),offset=BigInt(b[ctts.start]===1?b.readInt32BE(p+4):b.readUInt32BE(p+4));for(let n=0;n<count;n++)out[id][sample++].pts+=offset;}assert.equal(sample,out[id].length);}}
 const mvex=child(b,moov,'mvex');if(mvex)for(const trex of readBoxes(b,mvex.start,mvex.end).filter(x=>x.type==='trex'))defaults[b.readUInt32BE(trex.start+4)]={duration:b.readUInt32BE(trex.start+12)};
 for(const moof of top.filter(x=>x.type==='moof'))for(const traf of readBoxes(b,moof.start,moof.end).filter(x=>x.type==='traf')){const tfhd=child(b,traf,'tfhd'),tfdt=child(b,traf,'tfdt');const flags=b.readUInt32BE(tfhd.start)&0xffffff,id=b.readUInt32BE(tfhd.start+4);let p=tfhd.start+8;if(flags&1)p+=8;if(flags&2)p+=4;let duration=defaults[id]?.duration;if(flags&8){duration=b.readUInt32BE(p);p+=4;}let dts=b[tfdt.start]===1?b.readBigUInt64BE(tfdt.start+4):BigInt(b.readUInt32BE(tfdt.start+4));for(const run of readBoxes(b,traf.start,traf.end).filter(x=>x.type==='trun')){const flags=b.readUInt32BE(run.start)&0xffffff,count=b.readUInt32BE(run.start+4);let p=run.start+8;if(flags&1)p+=4;if(flags&4)p+=4;for(let n=0;n<count;n++){let delta=duration;if(flags&256){delta=b.readUInt32BE(p);p+=4;}if(flags&512)p+=4;if(flags&1024)p+=4;let cto=0;if(flags&2048){cto=b[run.start]===1?b.readInt32BE(p):b.readUInt32BE(p);p+=4;}assert.ok(delta!==undefined);out[id].push({dts,pts:dts+BigInt(cto),duration:BigInt(delta)});dts+=BigInt(delta);}}}
 return {edits,tracks:out};}
export function rawClockProof(source,output,windowOrigin){const a=probeRaw(source),b=probeRaw(output),ae=editOffsets(source),be=editOffsets(output);let origin;
 const ac=boxClocks(source),bc=boxClocks(output);for(const [probe,raw] of [[a,ac],[b,bc]])if(raw){probe.packets=[];for(const s of probe.streams)for(const p of raw.tracks[Number(s.id)]??[])probe.packets.push({...p,stream_index:s.index});}
 for(const s of a.streams){const edit=ae?.[Number(s.id)]?.shift??rat(0n);for(const p of a.packets.filter(p=>p.stream_index===s.index)){const t=add(time(p,s,'pts'),edit);if(Math.abs(Number(t[0])/Number(t[1])-windowOrigin)<1e-10){origin=t;break;}}if(origin)break;}assert.ok(origin,'RAW_MOVIE_ORIGIN');
 return a.streams.filter(s=>['video','audio'].includes(s.codec_type)).map(s=>{const t=b.streams.find(t=>t.codec_type===s.codec_type),x=a.packets.filter(p=>p.stream_index===s.index),y=b.packets.filter(p=>p.stream_index===t.index);assert.equal(x.length,y.length);const sourceEdit=ae?.[Number(s.id)]?.shift??rat(0n),outputEdit=be?.[Number(t.id)]?.shift??rat(0n);const exact=f=>x.every((p,i)=>eq(add(add(time(p,s,f),sourceEdit),neg(origin)),add(time(y[i],t,f),outputEdit)));return {type:s.codec_type,packets:x.length,ptsExact:exact('pts'),dtsExact:exact('dts'),sourceEdit:sourceEdit.map(String),outputEdit:outputEdit.map(String)};});}
function nals(bytes){const starts=[];for(let i=0;i+3<bytes.length;i++){let n=bytes[i]===0&&bytes[i+1]===0&&bytes[i+2]===1?3:bytes[i]===0&&bytes[i+1]===0&&bytes[i+2]===0&&bytes[i+3]===1?4:0;if(n){starts.push([i,i+n]);i+=n-1;}}return starts.map(([_,start],i)=>{let end=starts[i+1]?.[0]??bytes.length;while(bytes[end-1]===0)end--;const b=bytes.subarray(start,end);return {type:b[0]&31,hash:sha(b)};});}
function aac(bytes){const out=[];for(let p=0;p<bytes.length;){assert.ok(bytes[p]===255&&(bytes[p+1]&0xf6)===0xf0);const n=((bytes[p+3]&3)<<11)|(bytes[p+4]<<3)|(bytes[p+5]>>5),header=bytes[p+1]&1?7:9;assert.ok(n>header&&p+n<=bytes.length);out.push(sha(bytes.subarray(p+header,p+n)));p+=n;}return out;}
export function codedProof(source,output,audioCodec){const opts=f=>f.endsWith('.ts')?[]:['-ignore_editlist','1'];const raw=f=>nals(call('ffmpeg',[...opts(f),'-i',f,'-map','0:v:0','-c:v','copy','-bsf:v','h264_mp4toannexb','-f','h264','pipe:1']));const a=raw(source),b=raw(output),hashes=(xs,fn)=>xs.filter(fn).map(x=>x.hash),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);const result={codedPictureNalsEqual:same(hashes(a,n=>n.type>=1&&n.type<=5),hashes(b,n=>n.type>=1&&n.type<=5)),nonParameterNalsEqual:same(hashes(a,n=>![7,8].includes(n.type)),hashes(b,n=>![7,8].includes(n.type))),parameterSetPopulationEqual:same([...new Set(hashes(a,n=>[7,8].includes(n.type)))].sort(),[...new Set(hashes(b,n=>[7,8].includes(n.type)))].sort())};
 if(audioCodec==='aac'){const raw=f=>aac(call('ffmpeg',[...opts(f),'-i',f,'-map','0:a:0','-c:a','copy','-f','adts','pipe:1']));result.aacPayloadsEqual=same(raw(source),raw(output));}return result;}
export function rawPixelsEqual(source,output){const raw=f=>call('ffmpeg',[...(f.endsWith('.ts')?[]:['-ignore_editlist','1']),'-noautorotate','-i',f,'-map','0:v:0','-fps_mode','passthrough','-f','framemd5','-']).toString().split('\n').filter(l=>l&&!l.startsWith('#')).map(l=>l.split(',').at(-1).trim());const a=raw(source),b=raw(output);return {frames:a.length,equal:JSON.stringify(a)===JSON.stringify(b)};}
