const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright');const leaf=__dirname,root=path.resolve(leaf,'../..');
const fixtures={ts:'qa/v2-07b-ts-q1/synthetic-bframes-audiolead.ts',seed:'qa/faststart-h264-aac.mp4',bAc3:'qa/q2-audio-compatibility/synthetic-bframes-unspecified-color.mp4'};
for(const n of ['b-vfr-audiolead','b-vfr-aac','b-vfr-rotate','b-trim-negative','b-empty-edit','b-negative-cto','b-rotate90','one-picture-color'])fixtures[n]='qa/q1-clock-color-integrity/'+n+(n.endsWith('audiolead')?'.ts':'.mp4');
let browser;const observations=[],requests=[];const sourceHash=()=>Object.fromEntries(['native.mjs','q1-pipeline.mjs','common-source.mjs','vendor/mediabunny.min.mjs'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(leaf,f))).digest('hex')]));
const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/')return res.writeHead(200,{'Content-Type':'text/html'}).end('<video muted playsinline width="640" height="360"></video><script type="module" src="/qa/q1-clock-color-integrity/native.mjs"></script>');
 const original=/^\/original\/([^/]+)$/.exec(u.pathname);if(original){const file=path.join(root,fixtures[original[1]]),size=fs.statSync(file).size,r=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range??'');const a=r?+r[1]:0,b=r&&r[2]?+r[2]:size-1;res.writeHead(r?206:200,{'Content-Type':'video/mp4','Content-Length':b-a+1,'Accept-Ranges':'bytes',...(r?{'Content-Range':`bytes ${a}-${b}/${size}`}:{})});return fs.createReadStream(file,{start:a,end:b}).pipe(res);}
 const m=/^\/fixture\/([^/]+)\/(metadata|range)$/.exec(u.pathname);if(m){const f=fixtures[m[1]];if(!f)throw Error('FIXTURE');const file=path.join(root,f),size=fs.statSync(file).size;
 if(m[2]==='metadata')return res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify({id:m[1],size:String(size),mimeType:f.endsWith('.ts')?'video/mp2t':'video/mp4',headRevisionId:'fixed',modifiedTime:'2026-09-29T00:00:00Z',trashed:false,capabilities:{canDownload:true}}));
 const r=/^bytes=(\d+)-(\d+)$/.exec(req.headers.range??'');if(!r)throw Error('RANGE');const a=+r[1],b=+r[2];if(a<0||b>=size||b<a||b-a>=1048576)throw Error('RANGE_BOUND');const bytes=Buffer.alloc(b-a+1),fd=fs.openSync(file,'r');try{fs.readSync(fd,bytes,0,bytes.length,a);}finally{fs.closeSync(fd);}requests.push({name:m[1],start:a,end:b});return res.writeHead(206,{'Content-Range':`bytes ${a}-${b}/${size}`,'Content-Length':bytes.length}).end(bytes);}
 const file=path.resolve(root,'.'+u.pathname);if(!file.startsWith(root+path.sep)||!file.endsWith('.mjs'))return res.writeHead(404).end();res.writeHead(200,{'Content-Type':'text/javascript'}).end(fs.readFileSync(file));
 }catch(e){res.writeHead(500).end(e.message);}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let version,error;try{browser=await chromium.launch({channel:'chrome',headless:true});version=browser.version();const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.runIntegrity);
 for(const name of (process.env.Q1_NATIVE_CASE?[process.env.Q1_NATIVE_CASE]:Object.keys(fixtures))){const r=await page.evaluate(n=>window.runIntegrity(n),name);observations.push(r);console.log(JSON.stringify({name,passed:r.passed,failure:r.failure?.message,frames:r.decoded?.map(d=>d.frames)}));}
 if(!process.env.Q1_NATIVE_CASE)observations.push(await page.evaluate(()=>window.runIntegrity('ts',{abortAppend:true})));
 }catch(e){error=e.stack;}finally{await browser?.close();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(leaf,process.env.Q1_NATIVE_CASE?'native-'+process.env.Q1_NATIVE_CASE+'-results.json':'native-results.json'),JSON.stringify({recordedAt:new Date().toISOString(),scope:'isolated native Chrome local synthetic fixtures only',browserVersion:version,error,sourceHashes:sourceHash(),observations,requests},null,2));}})();
