import {rawClockProof,codedProof,rawPixelsEqual} from './independent.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import assert from 'node:assert/strict'; import {fileURLToPath} from 'node:url'; import {spawnSync} from 'node:child_process';
import {openDriveQ1Source} from '../../media/drive-source.mjs'; import {remuxQ1} from './q1-pipeline.mjs';
const leaf=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(leaf,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const probes=[]; const probe=file=>{const r=spawnSync('ffprobe',['-v','error','-show_streams','-show_packets','-show_data_hash','sha256','-of','json',file],{encoding:'utf8',maxBuffer:8*1024*1024});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);};
for(const [name,relative] of [['bframe-ts','qa/v2-07b-ts-q1/synthetic-bframes-audiolead.ts'],['seed-mp4','qa/faststart-h264-aac.mp4'],['q2-bframe-mp4','qa/q2-audio-compatibility/synthetic-bframes-unspecified-color.mp4'],['declared-color-no-b-control','qa/q2-audio-compatibility/synthetic-avc-ac3.mp4'],['b-vfr-audiolead','qa/q1-clock-color-integrity/b-vfr-audiolead.ts'],['b-vfr-aac','qa/q1-clock-color-integrity/b-vfr-aac.mp4'],['b-vfr-rotate','qa/q1-clock-color-integrity/b-vfr-rotate.mp4'],['b-trim-negative','qa/q1-clock-color-integrity/b-trim-negative.mp4'],['b-empty-edit','qa/q1-clock-color-integrity/b-empty-edit.mp4'],['b-negative-cto','qa/q1-clock-color-integrity/b-negative-cto.mp4'],['b-rotate90','qa/q1-clock-color-integrity/b-rotate90.mp4'],['one-picture-color','qa/q1-clock-color-integrity/one-picture-color.mp4'],['b-subpixel-sar','qa/q1-clock-color-integrity/b-subpixel-sar.mp4']]) {
 const inputPath=path.join(root,relative),data=fs.readFileSync(inputPath),metadata={id:name,size:String(data.length),mimeType:name.includes('ts')?'video/mp2t':'video/mp4',modifiedTime:'2026-09-29T00:00:00Z',headRevisionId:'fixed',trashed:false,capabilities:{canDownload:true}};
 const source=await openDriveQ1Source({fileId:name,accountKey:'synthetic-oracle',accountGeneration:1,isCurrent:()=>true,readMetadata:async()=>metadata,readRange:async({start,end})=>new Response(data.subarray(start,end+1),{status:206,headers:{'Content-Range':`bytes ${start}-${end}/${data.length}`,'Content-Length':String(end-start+1)}})});
 const chunks=[],remux=await remuxQ1({source,onWindow:({videoConfig})=>{},onChunk:({bytes})=>chunks.push(bytes)}),output=Buffer.concat(chunks),outputPath=path.join(leaf,`oracle-${name}.mp4`);fs.writeFileSync(outputPath,output);
 const before=probe(inputPath),after=probe(outputPath);fs.writeFileSync(path.join(leaf,`oracle-${name}-source-ffprobe.json`),JSON.stringify(before,null,2)+'\n');fs.writeFileSync(path.join(leaf,`oracle-${name}-output-ffprobe.json`),JSON.stringify(after,null,2)+'\n');
 const tracks=[];
 const sourceOriginTrack=before.streams.find(a=>before.packets.some(p=>p.stream_index===a.index&&Math.abs(Number(p.pts)*Number(a.time_base.split('/')[0])/Number(a.time_base.split('/')[1])-remux.windowOrigin)<1e-10));
 assert.ok(sourceOriginTrack,'window origin must equal an independently probed source PTS');
 const sourceOriginPacket=before.packets.find(p=>p.stream_index===sourceOriginTrack.index&&Math.abs(Number(p.pts)*Number(sourceOriginTrack.time_base.split('/')[0])/Number(sourceOriginTrack.time_base.split('/')[1])-remux.windowOrigin)<1e-10);
 const [on,od]=sourceOriginTrack.time_base.split('/').map(BigInt), ot=BigInt(sourceOriginPacket.pts)*on;

 for(const type of ['video','audio']) {
  const a=before.streams.find(s=>s.codec_type===type),b=after.streams.find(s=>s.codec_type===type);if(!a&&!b)continue; assert.ok(a&&b);
  const x=before.packets.filter(p=>p.stream_index===a.index),y=after.packets.filter(p=>p.stream_index===b.index);assert.equal(x.length,y.length);
  const [an,ad]=a.time_base.split('/').map(BigInt),[bn,bd]=b.time_base.split('/').map(BigInt);
  const exactClock=field=>x.every((p,i)=>(BigInt(y[i][field])*bn*ad*od)==((BigInt(p[field])*an*od-ot*ad)*bd));
  const tick=Math.max(...[a,b].map(s=>{const [n,d]=s.time_base.split('/').map(Number);return n/d;}));
  const differences=x.map((p,i)=>({index:i,sourcePts:Number(p.pts_time),sourceDts:Number(p.dts_time),outputPts:Number(y[i].pts_time),outputDts:Number(y[i].dts_time),ptsError:Number(y[i].pts_time)-(Number(p.pts_time)-remux.windowOrigin),dtsError:Number(y[i].dts_time)-(Number(p.dts_time)-remux.windowOrigin),sourceDuration:p.duration_time??null,outputDuration:y[i].duration_time??null}));
  const fields=['codec_name','profile','width','height','coded_width','coded_height','level','extradata_hash','pix_fmt','has_b_frames','color_range','color_space','color_transfer','color_primaries','chroma_location','sample_aspect_ratio'];
  const metadataDiff=Object.fromEntries(fields.filter(k=>(a[k]??null)!==(b[k]??null)).map(k=>[k,{source:a[k]??null,output:b[k]??null}]));
  tracks.push({type,exactPtsRational:exactClock('pts'),exactDtsRational:exactClock('dts'),packets:x.length,sourceHasBFrames:a.has_b_frames??null,sourceColorRange:a.color_range??null,encodedPacketHashesEqual:x.every((p,i)=>p.data_hash===y[i].data_hash),tick,allPtsWithinTick:differences.every(p=>Math.abs(p.ptsError)<=tick+1e-6),allDtsWithinTick:differences.every(p=>Math.abs(p.dtsError)<=tick+1e-6),ptsErrorRange:[Math.min(...differences.map(p=>p.ptsError)),Math.max(...differences.map(p=>p.ptsError))],dtsErrorRange:[Math.min(...differences.map(p=>p.dtsError)),Math.max(...differences.map(p=>p.dtsError))],metadataDiff,differences});
 }
 const frameHashes=file=>{const r=spawnSync('ffmpeg',['-v','error','-i',file,'-map','0:v:0','-fps_mode','passthrough','-f','framemd5','-'],{encoding:'utf8',maxBuffer:2*1024*1024});assert.equal(r.status,0,r.stderr);return r.stdout.split('\n').filter(l=>l&&!l.startsWith('#')).map(l=>l.split(',').at(-1).trim());};
 const sourceFrames=frameHashes(inputPath),outputFrames=frameHashes(outputPath);
 const rawClocks=rawClockProof(inputPath,outputPath,remux.windowOrigin),coded=codedProof(inputPath,outputPath,before.streams.find(t=>t.codec_type==='audio')?.codec_name),rawPixels=rawPixelsEqual(inputPath,outputPath);
 const rotationEqual=(before.streams[0].side_data_list?.find(x=>x.rotation!=null)?.rotation??0)===(after.streams[0].side_data_list?.find(x=>x.rotation!=null)?.rotation??0);
 probes.push({name,sourceRotation:before.streams[0].side_data_list?.find(x=>x.rotation!=null)?.rotation??0,outputRotation:after.streams[0].side_data_list?.find(x=>x.rotation!=null)?.rotation??0,rawClocks,coded,rawPixels,rotationEqual,decodedFrameCount:sourceFrames.length,decodedPixelHashesEqual:sourceFrames.length===outputFrames.length && sourceFrames.every((v,i)=>v===outputFrames[i]),colorExperiment:name==='seed-color-presence-experiment'?'Remove defaulted decoderConfig colorSpace only for oracle-proven unspecified-color seed; not an automatic admission/product fix':null,input:{path:relative,sha256:sha(data)},output:{path:path.basename(outputPath),sha256:sha(output)},windowOrigin:remux.windowOrigin,cleanup:remux.cleanup,metrics:{reads:remux.reads,peakBufferedPacketBytes:remux.peakBufferedPacketBytes,peakPendingAcks:remux.peakPendingAcks},tracks});
}
const checks=Object.fromEntries(probes.map(p=>[p.name,p.rawPixels.equal && p.rotationEqual && p.rawClocks.every(t=>t.ptsExact&&t.dtsExact) && Object.values(p.coded).every(Boolean) && p.tracks.every(t=>!Object.keys(t.metadataDiff).filter(k=>k!=='extradata_hash').length)]));
assert.equal(probes.find(p=>p.name==='b-rotate90').sourceRotation,90);assert.equal(probes.find(p=>p.name==='one-picture-color').rawPixels.frames,1);
const report={recordedAt:new Date().toISOString(),producerSha256:sha(fs.readFileSync(fileURLToPath(import.meta.url))),sourceHashes:Object.fromEntries(['q1-pipeline.mjs','common-source.mjs','timeline-policy.mjs','independent.mjs','vendor/mediabunny.min.mjs'].map(f=>[f,sha(fs.readFileSync(path.join(leaf,f)))])),checks,passed:Object.values(checks).filter(Boolean).length,failed:Object.values(checks).filter(x=>!x).length,observations:probes};
fs.writeFileSync(path.join(leaf,'oracle-results.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify(probes.map(p=>({name:p.name,windowOrigin:p.windowOrigin,pixels:p.decodedPixelHashesEqual,tracks:p.tracks.map(({differences,...t})=>t)})),null,2));
