'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),commit='e57d7b5b3154a2a838d01f631cf71fa063044280',hash=x=>crypto.createHash('sha256').update(x).digest('hex'),read=f=>fs.readFileSync(path.join(__dirname,f));
const snapshot=JSON.parse(read('snapshot-provenance.json')),fixture=JSON.parse(read('fixture-provenance.json'));
assert.equal(snapshot.sourceCommit,commit);const pinned=Object.fromEntries(snapshot.files.map(f=>{assert.equal(f.sha256,hash(execFileSync('git',['show',`${commit}:${f.path}`],{cwd:root,maxBuffer:80*1024*1024})));return [f.path,f.sha256];}));
const raws=fs.readdirSync(__dirname).filter(f=>/^long-.*\.json$/.test(f)).sort();assert.equal(raws.length,2,'BOTH_ATTEMPTS_RETAINED');
const attempts=raws.map(file=>{const r=JSON.parse(read(file));assert.equal(r.sourceCommit,commit);assert.deepEqual(r.producerStart,pinned);assert.deepEqual(r.producerEnd,pinned);assert.equal(r.snapshotProvenanceSha256,hash(read('snapshot-provenance.json')));assert.equal(r.fixtureProvenanceSha256,hash(read('fixture-provenance.json')));
 const producer=r.adapterSha256===hash(read('longrun.cjs'))?'longrun.cjs':'producer-first-worker-filter.cjs',gate=r.workerGateSha256===hash(read('worker-gate.js'))?'worker-gate.js':'producer-first-worker-gate.js';assert.equal(r.adapterSha256,hash(read(producer)));assert.equal(r.workerGateSha256,hash(read(gate)));assert.equal(r.audioObserverSha256,hash(read('audio-observer.js')));
 return {file,producer,gate,passed:r.passed,browser:r.browser,sourceCommit:commit,publicFiles:snapshot.files.length,publicBytesVerified:true,failure:r.failure??null,scope:r.scope,lastSourceClock:r.results[0]?.samples.at(-1)?.time};});
const pass=attempts.find(x=>x.passed);assert.ok(pass,'FULL_420S_PASS_REQUIRED');const r=JSON.parse(read(pass.file)),trial=r.results[0];assert.equal(trial.passed,true);assert.equal(trial.end.ended,true);assert.equal(trial.end.paused,true);assert.equal(trial.end.time,420);assert.ok(trial.elapsedMs>=410000&&trial.elapsedMs<460000);assert.ok(trial.frames.count>=9500);assert.equal(trial.frames.backwards,0);assert.equal(trial.frames.motion.filter(x=>['seeking','seeked'].includes(x.type)).length,0);
for(const mark of [295,299,301,360,419])assert.ok(trial.frames.checkpoints[mark]);
const selectedWorker=r.audioWorkers.find(x=>x.generation===trial.start.stats.generation);assert.ok(selectedWorker);assert.equal(trial.audioEnd.workerId,selectedWorker.id);assert.equal(trial.audioEnd.closed,true);assert.equal(trial.audioEnd.outputGaps,0);assert.equal(trial.audioEnd.outputBackwards,0);assert.equal(trial.audioEnd.inputBackwards,0);assert.ok(trial.audioEnd.lastOutput.timestamp/1000000>=419.9);
assert.equal(trial.end.stats.pipeline.audioMetrics.decodedFrames,420*48000);assert.equal(trial.end.stats.pipeline.audioMetrics.failures,0);assert.equal(trial.end.stats.pipeline.audioCleanup.settled,true);assert.equal(trial.end.stats.pipeline.audioCleanup.liveContexts,0);assert.equal(trial.end.stats.worker.terminated,true);assert.equal(trial.after.retirement.settled,true);for(const key of ['activeOwners','cleanupFences','q0Pins','q0Acquisitions'])assert.equal(trial.after.sw[key],0);assert.equal(trial.after.resources.activeWorkers,0);assert.equal(trial.after.resources.activeUrls,0);
assert.equal(trial.end.stats.worker.bytes,fixture.bytes,'COMPLETE_ORIGINAL_BYTES');assert.equal(trial.end.stats.pipeline.reads.bytes,fixture.bytes);assert.deepEqual(trial.end.stats.pipeline.admission.samples,[10080,13125]);assert.equal(trial.end.stats.pipeline.packets,23205);assert.equal(trial.end.stats.phase,'buffered-to-end');assert.equal(trial.end.stats.worker.activeReads,0);assert.equal(trial.end.stats.worker.pendingChunks,0);assert.equal(trial.end.stats.worker.pendingWindows,0);
const resource=r.resources.map(x=>({phase:x.phase,totalPrivateMiB:x.chromePrivateBytes/1048576,renderers:x.processes.filter(p=>p.type==='renderer').map(p=>({pid:p.pid,privateMiB:p.privateBytes/1048576})),commitHeadroomGiB:x.host.commitAvailableGiB,physicalHeadroomGiB:x.host.physicalAvailableGiB}));
const summary={sourceCommit:commit,immutableSnapshot:true,publicFileCount:snapshot.files.length,attempts,fixture:{sha256:fixture.sha256,bytes:fixture.bytes,movieDuration:fixture.originalProbe.format.duration,streams:fixture.originalProbe.streams.map(s=>({codec:s.codec_name,type:s.codec_type,duration:s.duration,sampleRate:s.sample_rate,channels:s.channels,frames:s.nb_frames})),audioPackets:fixture.audioPackets},
 result:{file:pass.file,browser:r.browser,elapsedMs:trial.elapsedMs,initialSourceClock:trial.start.time,endSourceClock:trial.end.time,endNativeTime:trial.end.nativeTime,endNativeDuration:trial.end.nativeDuration,presentedCallbacks:trial.frames.count,totalNativeFrames:trial.end.frames,frameCheckpoints:trial.frames.checkpoints,lastFrame:trial.frames.last,motionEvents:trial.frames.motion,audioEnd:trial.audioEnd,audioWorkers:r.audioWorkers,stats:trial.end.stats,settledClose:trial.after,network:trial.network,networkCap:r.networkCap,nativeObservations:r.nativeObservations,resource,minCommitHeadroomGiB:Math.min(...resource.map(x=>x.commitHeadroomGiB)),minPhysicalHeadroomGiB:Math.min(...resource.map(x=>x.physicalHeadroomGiB))},
 limits:['One synthetic admitted AVC+AC3 profile in installed isolated desktop Chrome; no account/device/corpus-wide/production acceptance.','AudioEncoder timestamps prove native encoded audio clocks, not audible speaker output or exact PCM fidelity.','QA adds only an initial owned-worker inspector handshake; product bytes/messages/native calls unchanged.','Zero Network response budgets do not guarantee all instrumentation/native caching is absent.','The old cold decoder-open failure remains separate and unexplained.']};
fs.writeFileSync(path.join(__dirname,'summary.json'),JSON.stringify(summary,null,2)+'\n');
const curated=[...raws,'longrun.cjs','producer-first-worker-filter.cjs','worker-gate.js','producer-first-worker-gate.js','audio-observer.js','fixtures.py','snapshot-public.cjs','fixture-provenance.json','snapshot-provenance.json','attempt-first-filter-stop.txt','summarize.cjs','README.md','summary.json'];
const dependencies=['qa/rc15-lifecycle-qualification/qualify.cjs','qa/rc15-lifecycle-qualification/resource-snapshot.py','qa/host-resource-snapshot.py','qa/q1-q2-app-integration/native-retirement-smoke.cjs','qa/q1-product-audit.cjs'];
const manifest={sourceCommit:commit,publicSha256:pinned,files:curated.map(f=>({path:`qa/rc16-q2-longrun/${f}`,sha256:hash(read(f)),bytes:read(f).length})),dependencies:dependencies.map(f=>({path:f,sha256:hash(fs.readFileSync(path.join(root,f)))})),excluded:['public snapshot (exact Git-regenerable51 files)','synthetic-420s-ac3.mp4 (35MB synthetic fixture, exact command/version/hash/probe retained)','node_modules/SDK/cache/private profiles/accounts/original media']};
fs.writeFileSync(path.join(__dirname,'evidence-manifest.json'),JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(__dirname,'curated-savepoint.txt'),[...curated.map(f=>`qa/rc16-q2-longrun/${f}`),'qa/rc16-q2-longrun/evidence-manifest.json','qa/rc16-q2-longrun/curated-savepoint.txt'].join('\n')+'\n');console.log(JSON.stringify({attempts:attempts.length,sourceCommit:commit,elapsedMs:trial.elapsedMs,end:trial.end.time,callbacks:trial.frames.count,audioFrames:trial.end.stats.pipeline.audioMetrics.decodedFrames,curatedFiles:curated.length+2}));
