'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(path.join(__dirname,p))),raw=p=>fs.readFileSync(path.join(__dirname,'private',p));
const mapping=[['read-control-plane.cjs','control-plane.json'],['read-metric-schema.cjs','metric-schema.json'],['read-sql-metrics.cjs','sql-metrics.json'],['read-sql-usage.cjs','sql-usage.json'],['synthetic-owner.mjs','synthetic-owner.json']];
let requests=0,privateBytes=0;
for(const [producer,output] of mapping){const r=read(output);assert.equal(r.complete,true);assert.equal(r.producerSHA256,sha(fs.readFileSync(path.join(__dirname,producer))));assert.equal(r.logsRead??false,false);assert.equal(r.settingsWrites??0,0);const events=r.endpoints||(r.endpoint?[r.endpoint]:[]);requests+=events.length;for(const [i,e] of events.entries()){let filename;if(output==='control-plane.json')filename=`${i+1}-${e.category}.json`;else if(output==='sql-usage.json')filename='sql-row-and-namespace-usage.json';else filename=e.category+'.json';const b=raw(filename);assert.equal(b.length,e.bytes);assert.equal(sha(b),e.rawSHA256);privateBytes+=b.length;} }
const cp=read('control-plane.json');assert.equal(cp.workerVersion,'b1021a42-fb32-47d5-92be-7fd92736faf7');assert.equal(cp.publicSource,'3ebd97df80144fb8ebbaf1f945394a796d4425b8');assert.ok(Object.values(cp.identity).every(Boolean));assert.equal(cp.auth.credentialStoreUnchanged,false);assert.equal(cp.candidateRequests,0);assert.equal(cp.subscriptions.readSucceeded,false);assert.equal(cp.settings.script.enabled,null);assert.equal(cp.settings.script.observabilityExplicitNull,true);assert.equal(cp.settings.combined.logpush,false);assert.equal(cp.settings.combined.tailConsumersPresent,false);assert.equal(cp.account.defaultUsageModel,'standard');
const sql=read('sql-usage.json');assert.equal(sql.storage.limitReached,false);assert.equal(sql.storage.namespaceGroupCount,1);assert.equal(sql.storage.sumOfNamespaceMaxStoredBytes,425984);assert.equal(sql.rows[0].rowsRead,116);assert.equal(sql.rows[0].rowsWritten,58);
const synth=read('synthetic-owner.json');assert.equal(synth.cases.length,13);assert.ok(synth.cases.every(c=>c.passed));assert.equal(synth.networkRequests,0);assert.equal(synth.realSessionWrites,0);assert.equal(synth.providerRefreshAttempts,1);assert.equal(synth.providerRevokeCalls,0);
for(const [file,hash]of Object.entries(synth.sourceHashes))assert.equal(sha(fs.readFileSync(path.resolve(__dirname,'../..',file))),hash);
assert.equal(requests,13);
const files=['.gitignore','README.md',...mapping.flat(), 'verify.cjs','verification.json','curated-savepoint.json'];
for(const file of files.filter(p=>fs.existsSync(path.join(__dirname,p)))){const text=fs.readFileSync(path.join(__dirname,file),'utf8');assert.equal(/Bearer\s+[A-Za-z0-9_.-]{20,}|ya29\.[A-Za-z0-9_-]+|oauth_token\s*=\s*["'][^"']+["']/.test(text),false);}
const r={schema:'drive-original.rc21-hosting-security-verification/1',recordedAt:new Date().toISOString(),passed:true,readOnlyControlPlaneRequests:requests,candidateRequests:0,syntheticCases:13,privateResponseBytes:privateBytes,privateRawHashesMatched:true,producerHashesMatched:true,sourceHashesMatched:true,effectiveObservabilityProven:false,selectedFreePlanProven:false,hostedAuthenticatedSecurityProven:false};fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(r,null,2)+'\n');fs.writeFileSync(path.join(__dirname,'curated-savepoint.json'),JSON.stringify({schema:'drive-original.curated-savepoint/1',ownedPaths:files.map(f=>'qa/rc21-hosting-security/'+f),excluded:['qa/rc21-hosting-security/private/'],commitOwner:'root'},null,2)+'\n');console.log(JSON.stringify(r));
