'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const here=__dirname,root=path.resolve(here,'../..'),SOURCE='d3f78f321a804f582668dde1b7cd3e0f949b24c9',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=file=>{const r=spawnSync('git',['show',SOURCE+':'+file],{cwd:root,maxBuffer:64*1024*1024});if(r.status!==0)throw Error('IMMUTABLE_SOURCE_READ');return r.stdout;};
const sw=git('sw.js').toString(),names=[...sw.match(/const SHELL_FILES = \[([\s\S]*?)\];/)[1].matchAll(/'\.\/([^']*)'/g)].map(m=>m[1]).filter(Boolean);if(names.length!==50||new Set(names).size!==50||!names.includes('media/native-color.mjs'))throw Error('CACHE_BINDING_COUNT');
const sourceSHA256=Object.fromEntries(['app.js','sw.js','version.json','media/native-color.mjs','media/revision-pin.js','index.html'].map(f=>[f,sha(git(f))]));const binding={sourceCommit:SOURCE,version:'1.22.0-rc.36',origin:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev',publicationVerified:false,preparationOnly:true,sourceSHA256,cache:names.map(file=>({file,sha256:sha(git(file))}))};fs.writeFileSync(path.join(here,'android-binding.json'),JSON.stringify(binding,null,2)+'\n');
function read(file,expected){const b=fs.readFileSync(path.join(here,'../rc35-cold-q0',file));if(sha(b)!==expected)throw Error('MAINTAINED_PRODUCER_CHANGED');return b.toString();}
let baseline=read('android-update-baseline.expression.js','44c85a725ed14255f1a8f00c1d6bd51a249bf6159122ff2ca43ce247cdd7d0bd').replaceAll('rc35','rc36').replaceAll('Rc35','Rc36').replaceAll('1.22.0-rc.34','1.22.0-rc.35').replace('hashedAccountWriterProjectionCacheSaved: true,','hashedAccountWriterProjectionCacheSaved: true, hashes:{account:hashes[0],accountKey:hashes[1],writer:hashes[2],projection:hashes[3],privateCache:hashes[4]}, snapshotStable:true,');fs.writeFileSync(path.join(here,'android-baseline.expression.js'),baseline);
let proof=read('android-update-source-proof.expression.js','b3083590371fa99d7fbb95449fa16e09ca70a2ffd26568c1c13464720aa30ba7');proof=proof.slice(0,proof.indexOf('})({'))+'})('+JSON.stringify(binding)+','+JSON.stringify(binding.cache)+')\n';proof=proof.replaceAll('rc35-android-update-baseline','rc36-android-update-baseline').replace("['app.js','sw.js','version.json']",JSON.stringify(Object.keys(sourceSHA256)));fs.writeFileSync(path.join(here,'android-proof.expression.js'),proof);
let driver=read('android-update-execute-attempt2.cjs','fbe158f3439dad9fd0566373584895897b9fe9a830e4f8f038567fbbf41e3f08');
driver=driver.replace('android-update-baseline.expression.js','android-baseline.expression.js').replace('44c85a725ed14255f1a8f00c1d6bd51a249bf6159122ff2ca43ce247cdd7d0bd',sha(Buffer.from(baseline))).replace('android-update-source-proof.expression.js','android-proof.expression.js').replace('b3083590371fa99d7fbb95449fa16e09ca70a2ffd26568c1c13464720aa30ba7',sha(Buffer.from(proof))).replace("!['1.22.0-rc.34','1.22.0-rc.35'].includes(safe.version)","safe.version!=='1.22.0-rc.35'").replaceAll('1.22.0-rc.35','__NEXT_VERSION__').replaceAll('1.22.0-rc.34','1.22.0-rc.35').replaceAll('__NEXT_VERSION__','1.22.0-rc.36');
// The common admission must remain old version35; only postclick conditions use36.
driver=driver.replace('"safe.version!==\'1.22.0-rc.36\'"','"safe.version!==\'1.22.0-rc.35\'"');
driver=driver.replaceAll('../rc35-cold-q0/android-update-actual-attempt2-safe.json','../candidate-rc36-delivery/android-update-actual-result.json').replaceAll('rc35-android-update-baseline','rc36-android-update-baseline').replaceAll('__qaRc35AndroidUpdate','__qaRc36AndroidUpdate').replaceAll('2c2b1244bee0f1a5e500318c83c6e126c5124e34',SOURCE).replace('result.matchedCache!==49','result.matchedCache!==50').replace('result.matchedCacheAliases!==50','result.matchedCacheAliases!==51').replace('result.network.length!==3','result.network.length!==6');
driver=driver.replace("if(process.argv[2]!=='--execute-once')", "if(process.argv[2]!=='--execute-once'||process.argv[3]!=='"+SOURCE+"')");
driver=driver.replace("if(source.split(needle).length!==2)","if(source.split(needle).length!==2)");
driver=driver.replace("source.replace(needle,", "source.replace(\"const context={report,\",\"const context={report,setNormalForceFlag:async()=>{try{await nativeSession.send('ServiceWorker.setForceUpdateOnPageLoad',{forceUpdateOnPageLoad:false});}catch{throw Error('NORMAL_FORCE_FLAG_UNSUPPORTED');}return{acknowledged:true,forceUpdateOnPageLoad:false}},\").replace(needle,");
driver=driver.replace("m.exports(__filename,output,async c=>{", "const binding=JSON.parse(fs.readFileSync(path.join(__dirname,'android-binding.json'))),readiness=JSON.parse(fs.readFileSync(path.join(__dirname,'source-readiness.json')));if(!readiness.passed||readiness.sourceCommit!=='"+SOURCE+"'||readiness.version!=='1.22.0-rc.36'||readiness.cacheAssets!==50||!/^[a-f0-9-]{36}$/.test(readiness.workerVersion||'')||!Object.entries(binding.sourceSHA256).every(([file,sha])=>(readiness.fixedSourceAssetBindings||[]).some(row=>row.file===file&&row.sha256===sha)))throw Error('VERIFIED_DELIVERY_GO_REQUIRED');\nm.exports(__filename,output,async c=>{");
driver=driver.replace("await c.unmaskNativeVisibility();await c.releaseMcpForNativeLifecycle();", "await c.unmaskNativeVisibility();await c.releaseMcpForNativeLifecycle();c.step('normal debugger force flag acknowledged BEFORE admission',await c.setNormalForceFlag());if(c.report.model!=='SM-X800')throw Error('ACTUAL_DEVICE_MODEL');");
driver=driver.replace("!window.__qaRc36AndroidUpdate&&!localStorage", "!window.__resumeSwProof&&!window.__androidTracksObserver&&!window.__qaRc35AndroidUpdate&&!window.__qaRc36AndroidUpdate&&!localStorage");
driver=driver.replace("queryEmpty:!String(state.query||'').trim()})`);\n  c.step('final update state'", "queryEmpty:!String(state.query||'').trim(),online:state.authStatus==='online',accountReady:!!state.accountStateLoaded&&hasUsableToken(),accountIdle:!state.accountIdentityPending&&!state.accountStateLoadingPromise&&!state.accountStateSyncPromise&&!state.accountStateSyncTimer&&!state.accountStateSyncRetryTimer,retirementSettled:q1RetirementResult?.settled===true,controllerActivated:navigator.serviceWorker.controller?.state==='activated'})`);\n  c.step('final update state'");
driver=driver.replace("||!final.bannerHidden||!final.closed)","||!final.bannerHidden||!final.closed||!final.online||!final.accountReady||!final.accountIdle||!final.retirementSettled||!final.controllerActivated)");
driver=driver.replace("try{c.step('owned update cleanup',await c.evaluateNative(","try{const cleanup=await c.evaluateNative(").replace("tabClosed:false};}`));}","tabClosed:false};}`);c.step('owned update cleanup',cleanup);if(!cleanup.ownedBaselineAbsent||!cleanup.ownedListenersAbsent||!cleanup.ownedSourceProofRemoved)throw Error('UPDATE_OWNED_CLEANUP_UNCONFIRMED');}");
fs.writeFileSync(path.join(here,'android-update.cjs'),driver);
module.exports={SOURCE,binding};
