'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),here=__dirname,root=path.resolve(here,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const binding=JSON.parse(fs.readFileSync(path.join(here,'android-binding.json'))),driver=fs.readFileSync(path.join(here,'android-update.cjs'),'utf8');new vm.Script(driver);new vm.Script(fs.readFileSync(path.join(here,'android-baseline.expression.js'),'utf8'));new vm.Script(fs.readFileSync(path.join(here,'android-proof.expression.js'),'utf8'));assert.equal(binding.cache.length,50);assert.equal(binding.publicationVerified,false);assert(binding.cache.some(r=>r.file==='media/native-color.mjs'));assert(!driver.includes('forceUpdateOnPageLoad:true'));
const assets=new Map();for(const file of new Set([...binding.cache.map(r=>r.file),...Object.keys(binding.sourceSHA256)])){const r=spawnSync('git',['show',binding.sourceCommit+':'+file],{cwd:root,maxBuffer:64*1024*1024});assert.equal(r.status,0);assets.set(file,r.stdout);}
async function scenario(kind){let work,compiled,clicks=0,flag=false;class FakeModule{constructor(){this.exports=(producer,out,fn)=>{work=fn;};}static _nodeModulePaths(){return[];}_compile(s){compiled=s;}}
 const readiness={passed:true,sourceCommit:binding.sourceCommit,version:binding.version,workerVersion:'00000000-0000-0000-0000-000000000000',cacheAssets:50,fixedSourceAssetBindings:Object.entries(binding.sourceSHA256).map(([file,sha256])=>({file,sha256}))};
 const fakeFs={...fs,readFileSync:(p,...a)=>String(p).endsWith('source-readiness.json')?JSON.stringify(readiness):fs.readFileSync(p,...a)};
 vm.runInNewContext(driver,{require:n=>n==='node:fs'?fakeFs:n==='node:module'?FakeModule:require(n),__dirname:here,__filename:path.join(here,'android-update.cjs'),module:{},process:{argv:['node','driver','--execute-once',binding.sourceCommit]}});assert(compiled.includes('forceUpdateOnPageLoad:false'));assert(compiled.includes("safe.version!=='1.22.0-rc.35'"));
 const controller={state:'activated',scriptURL:binding.origin+'/sw.js'},reg={active:controller,waiting:null,installing:null},store=new Map(),handlers=new Map(),pagehandlers=new Map();
 const button={disabled:false,hidden:false,getBoundingClientRect:()=>({x:100,y:100,width:100,height:50})};const state={selected:null,accountId:'private-fixture-account',authAccountKey:'private-fixture-key',accountStateWriterId:'private-fixture-writer',authGeneration:1,driveSessionGeneration:1,accountMediaState:{fixture:{favorite:false,viewedAt:1}},authStatus:'online',accountStateLoaded:true,currentFolderId:'root',query:''};
 const page={APP_VERSION:'1.22.0-rc.35',state,q0Playback:null,q1Playback:null,playerTracksOwner:null,q1RetirementResult:{settled:true},hasUsableToken:()=>true,accountStateCacheKey:()=> 'private-cache',document:{visibilityState:'visible',elementFromPoint:()=>({closest:()=>button}),addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:n=>handlers.delete(n)},navigator:{serviceWorker:{controller,getRegistration:async()=>reg}},el:{bannerUpdateButton:button,updateBanner:{hidden:false},updateBannerText:{textContent:'v1.22.0-rc.36: generated'},applyUpdateButton:{hidden:false}},innerWidth:824,innerHeight:1191,devicePixelRatio:2.125,crypto:crypto.webcrypto,TextEncoder,URL,AbortController,setTimeout,clearTimeout,Date,localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},addEventListener:(n,f)=>pagehandlers.set(n,f),removeEventListener:n=>pagehandlers.delete(n),caches:{keys:async()=>['drive-original-shell-1.22.0-rc.36'],open:async()=>({match:async name=>{const b=assets.get(name==='/'?'index.html':name.slice(1));return b?new Response(b):undefined;}})},fetch:async p=>new Response(assets.get(p.slice(1)))};page.window=page;store.set('private-cache','private generated fixture cache');if(kind==='foreign')page.__resumeSwProof={};const context=vm.createContext(page);const steps=[];
 const c={report:{model:'SM-X800',physicalScreen:'Physical size: 1752x2800'},unmaskNativeVisibility:async()=>{},releaseMcpForNativeLifecycle:async()=>{},setNormalForceFlag:async()=>{if(kind==='unsupported')throw Error('NORMAL_FORCE_FLAG_UNSUPPORTED');flag=true;return{acknowledged:true,forceUpdateOnPageLoad:false};},evaluateNative:async s=>{if(!s.includes('ownedBaselineAbsent'))assert(flag);return vm.runInContext('('+s+')()',context);},step:(name,data)=>steps.push({name,data}),adb:()=>{assert(flag);clicks++;handlers.get('click')?.({isTrusted:kind!=='untrusted',target:{closest:()=>true}});pagehandlers.get('pagehide')?.({isTrusted:true});page.APP_VERSION='1.22.0-rc.36';page.el.updateBanner.hidden=true;page.el.applyUpdateButton.hidden=true;if(kind==='drift')state.accountMediaState.fixture.favorite=true;},wait:async()=>{}};
 let failure=null;try{await work(c);}catch(e){failure=e.message;}
 if(kind==='pass'){assert.equal(failure,null);const p=steps.find(s=>s.name==='source cache and preservation proof').data;assert.equal(p.matchedCache,50);assert.equal(p.matchedCacheAliases,51);assert.equal(p.network.length,6);assert(Object.values(p.preserved).filter(v=>typeof v==='boolean').every(Boolean));assert.equal(clicks,1);}else{assert(failure);if(['foreign','unsupported'].includes(kind))assert.equal(clicks,0);}
 assert(!store.has('drive-original.qa.rc36-android-update-baseline'));assert.equal(handlers.size,0);assert.equal(pagehandlers.size,0);return{scenario:kind,passed:true,expectedFailure:failure,nativeTapCalls:clicks};
}
(async()=>{const checks=[];for(const k of ['pass','untrusted','drift','foreign','unsupported'])checks.push(await scenario(k));const names=['android-prepare.cjs','android-binding.json','android-baseline.expression.js','android-proof.expression.js','android-update.cjs','android-checks.cjs'];const files=names.map(file=>{const b=fs.readFileSync(path.join(here,file));return{file,bytes:b.length,sha256:sha(b)};});const m={schema:'android36-update-preparation/1',sourceCommit:binding.sourceCommit,version:binding.version,preparationOnly:true,deviceConnected:false,actualExecuted:false,checks,files,maintainedCommon:{file:'qa/rc32-ts-device-replay/android-common.cjs',sha256:'c6822041c663495142b71356db26caed3270722dafa6d37a449713a659cc1286'},bounds:{wholeUnitMs:120000,postClickReloadMs:60000,publicGetCount:6,publicGetMs:10000,cacheDistinct:50,cacheWithRootAlias:51},executingSWScriptHash:'UNKNOWN_NOT_CAPTURED_BY_PAGE_ONLY_COMMON'};const p=path.join(here,'android-preparation-manifest.json');fs.writeFileSync(p,JSON.stringify(m,null,2)+'\n');console.log(JSON.stringify({checks,manifestSha256:sha(fs.readFileSync(p)),fileCount:files.length}));})().catch(e=>{console.error(e.code||e.message||'PREPARATION_CHECK_FAILED');process.exitCode=1;});
