'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const leaf=__dirname,root=path.resolve(leaf,'../..'),base=path.join(root,'qa/rc16-image-format/painted-eight-driver.cjs');
let s=fs.readFileSync(base,'utf8').replace(/\r\n/g,'\n');
s=s.replace("const names=['app.js','sw.js','index.html','styles.css','media/revision-pin.js'];","const names=['app.js','sw.js','index.html','styles.css','version.json','manifest.webmanifest','media/revision-pin.js'];");
s=s.replace('rc16 unchanged product bytes','rc18 WebP card-only patch product bytes');
const a=s.indexOf('const cases=['),b=s.indexOf('\nconst server=',a);s=s.slice(0,a)+"const cases=[{name:'animated-webp',fixture:'animated.webp',mime:'image/webp',animated:true},{name:'animated-gif',fixture:'animated.gif',mime:'image/gif',animated:true},{name:'png-alpha',fixture:'alpha.png',mime:'image/png'},{name:'bmp',fixture:'raster.bmp',mime:'image/bmp'}];"+s.slice(b);
s=s.replace("fs.readFileSync(path.join(__dirname,trial.fixture))","fs.readFileSync(path.join(root,'qa/rc16-image-format',trial.fixture))");
s=s.replace("r.card=await page.evaluate(()=>({kind:document.querySelector('#qaCardHost canvas,#qaCardHost img').tagName,isGif:isGifFile(qaFile)}));","r.card=await page.evaluate(()=>({kind:document.querySelector('#qaCardHost canvas,#qaCardHost img').tagName,isGif:isGifFile(qaFile),label:document.querySelector('#qaCardHost .file-card-gif-placeholder')?.textContent}));assert.equal(r.card.kind,trial.animated?'CANVAS':'IMG');assert.equal(r.card.isGif,trial.fixture==='animated.gif');if(trial.animated)assert.equal(r.card.label,trial.fixture==='animated.gif'?'GIF':'WEBP');");
s=s.replace('r.card.static=r.card.uniqueColors.length===1;','r.card.static=r.card.uniqueColors.length===1;assert.equal(r.card.static,true);assert.equal(r.card.uniqueColors[0],\'255,0,0,255\');assert.ok(r.card.samples.at(-1).t>2000);');
s=s.replace("assert.equal(r.viewerPaintedColors.length,2);","assert.deepEqual(r.viewerPaintedColors.sort(),['0,0,255,255','255,0,0,255']);r.paintedTransitions=r.viewerPaintedSamples.filter((s,i,a)=>!i||s.pixel.join(',')!==a[i-1].pixel.join(','));assert.ok(r.paintedTransitions.length>=4,'native viewer loops retained');");
s=s.replace("assert.equal(r.presentation.events.filter(e=>e.type==='viewed').length,1);","assert.equal(r.presentation.events.filter(e=>e.type==='viewed').length,1);assert.equal(r.presentation.events.find(e=>e.type==='viewed').document,'visible');assert.equal(r.presentation.events.find(e=>e.type==='viewed').complete,true);assert.equal(r.presentation.events.find(e=>e.type==='viewed').visible,true);");
s=s.replace('report.completed=true;','report.completed=true;report.fixtureProducer={path:\'qa/rc16-image-format/fixture-producers.json\',sha256:sha(fs.readFileSync(path.join(root,\'qa/rc16-image-format/fixture-producers.json\')))};');
fs.writeFileSync(path.join(leaf,'qualification.cjs'),s);
fs.writeFileSync(path.join(leaf,'harness-producers.json'),JSON.stringify({basePath:'qa/rc16-image-format/painted-eight-driver.cjs',baseSha256:crypto.createHash('sha256').update(fs.readFileSync(base)).digest('hex'),buildSha256:crypto.createHash('sha256').update(fs.readFileSync(__filename)).digest('hex'),baselineRunnerPath:'qa/rc16-image-format/card-regression-preparation.cjs',baselineRunnerSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'qa/rc16-image-format/card-regression-preparation.cjs'))).digest('hex')},null,2));

