'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require('../node_modules/playwright');
const root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const names=['app.js','sw.js','index.html','styles.css','version.json','manifest.webmanifest','media/revision-pin.js'];
const hashes=()=>Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(root,n)))]));
const report={scope:'rc18 WebP card-only patch product bytes, actual app/SW/native image with synthetic provider only. Installed isolated Chrome serial cases; no account/device/full-corpus evidence.',producerStart:hashes(),driverSha256:sha(fs.readFileSync(__filename)),results:[]};
const save=()=>{report.producerEnd=hashes();fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(report,null,2));};
const cases=[{name:'animated-webp',fixture:'animated.webp',mime:'image/webp',animated:true},{name:'animated-gif',fixture:'animated.gif',mime:'image/gif',animated:true},{name:'png-alpha',fixture:'alpha.png',mime:'image/png'},{name:'bmp',fixture:'raster.bmp',mime:'image/bmp'}];
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local'),f=path.resolve(root,'.'+u.pathname+(u.pathname==='/'?'index.html':''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return res.writeHead(404).end();res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.mjs':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.svg':'image/svg+xml','.png':'image/png','.gif':'image/gif','.webp':'image/webp','.bmp':'image/bmp'})[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(f).pipe(res);});
function memory(){const m=JSON.parse(execFileSync('powershell',['-NoProfile','-Command','Get-CimInstance Win32_OperatingSystem | Select-Object FreePhysicalMemory,FreeVirtualMemory | ConvertTo-Json -Compress'],{encoding:'utf8'}));assert.ok(m.FreePhysicalMemory>1024*1024,'physical below1GiB');assert.ok(m.FreeVirtualMemory>1.5*1024*1024,'available virtual below1.5GiB');return m;}
async function samples(page,target,ms=2200){return page.evaluate(async({target,ms})=>{const element=target==='viewer'?el.imageViewer:document.querySelector('#qaCardHost canvas,#qaCardHost img');const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=96;canvas.height=64;const values=[],start=performance.now();while(performance.now()-start<ms){ctx.clearRect(0,0,96,64);ctx.drawImage(element,0,0,96,64);values.push({t:performance.now()-start,pixel:Array.from(ctx.getImageData(48,32,1,1).data),alpha:Array.from(ctx.getImageData(36,28,1,1).data),corner:Array.from(ctx.getImageData(0,0,1,1).data)});await new Promise(r=>setTimeout(r,50));}return values;},{target,ms});}

function pngPixel(bytes){const chunks=[];let offset=8,color;while(offset<bytes.length){const length=bytes.readUInt32BE(offset),type=bytes.toString('ascii',offset+4,offset+8),data=bytes.subarray(offset+8,offset+8+length);if(type==='IHDR'){assert.equal(data.readUInt32BE(0),1);assert.equal(data.readUInt32BE(4),1);assert.equal(data[8],8);color=data[9];}if(type==='IDAT')chunks.push(data);offset+=length+12;}assert.ok(color===2||color===6);const row=require('node:zlib').inflateSync(Buffer.concat(chunks));assert.ok(row[0]>=0&&row[0]<=4);return [...row.subarray(1,color===6?5:4),...(color===2?[255]:[])];}
async function paintedSamples(page,target,ms=2200){const box=await page.locator(target==='viewer'?'#imageViewer':'#qaCardHost canvas,#qaCardHost img').boundingBox(),values=[],start=Date.now();while(Date.now()-start<ms){const bytes=await page.screenshot({clip:{x:Math.floor(box.x+box.width/2),y:Math.floor(box.y+box.height/2),width:1,height:1}});values.push({t:Date.now()-start,pixel:pngPixel(bytes),pngSha256:sha(bytes)});await new Promise(r=>setTimeout(r,60));}return values;}

(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;try{for(const trial of cases){const r={name:trial.name,passed:false,memory:memory()};report.results.push(r);save();let browser;try{const bytes=fs.readFileSync(path.join(root,'qa/rc16-image-format',trial.fixture)),checksum=sha(bytes);r.fixture={path:'qa/rc16-image-format/'+trial.fixture,bytes:bytes.length,sha256:checksum,declaredMime:trial.mime,fileName:trial.fileName||trial.fixture};
 browser=await chromium.launch({channel:'chrome',headless:true});report.browser=browser.version();const context=await browser.newContext({viewport:{width:1280,height:800}});r.providerRequests=[];r.blockedExternal=[];
 await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===origin)return route.continue();if(u.origin!=='https://www.googleapis.com'){r.blockedExternal.push(u.origin);return route.fulfill({status:403,body:'{}'});}r.providerRequests.push({path:u.pathname,range:req.headers().range||null});const h={'access-control-allow-origin':'*','access-control-expose-headers':'content-range,content-length,content-type'};
 if(u.pathname.endsWith('/download'))return route.fulfill({status:200,headers:h,contentType:'application/json',body:JSON.stringify({name:'synthetic/op',done:true,response:{'@type':'type.googleapis.com/google.apps.drive.v3.DownloadFileResponse',partialDownloadAllowed:true,downloadUri:'https://www.googleapis.com/drive/v3/files/fixture/revisions/A?alt=media'}})});
 if(!u.searchParams.has('alt'))return route.fulfill({status:200,headers:h,contentType:'application/json',body:JSON.stringify({id:'fixture',headRevisionId:'A',size:String(bytes.length),mimeType:trial.mime,modifiedTime:'A',sha256Checksum:checksum,trashed:false,capabilities:{canDownload:true,canReadRevisions:true}})});
 const m=/bytes=(\d+)-(\d*)/.exec(req.headers().range||''),a=m?+m[1]:0,b=m&&m[2]?Math.min(+m[2],bytes.length-1):bytes.length-1;await new Promise(resolve=>setTimeout(resolve,100));return route.fulfill({status:m?206:200,headers:{...h,'content-length':String(b-a+1),...(m?{'content-range':`bytes ${a}-${b}/${bytes.length}`}:{})},contentType:trial.mime,body:bytes.subarray(a,b+1)});
 });
 const page=await context.newPage();r.errors=[];page.on('pageerror',e=>r.errors.push(e.name));await page.goto(origin);await page.waitForFunction(()=>navigator.serviceWorker.controller&&typeof openMediaSource==='function');
 await page.evaluate(({trial,size,origin})=>{state.token='synthetic';state.expiresAt=Date.now()+3600000;state.tokenRevision=1;state.authAccountKey='account';state.driveSessionGeneration=1;state.authCapabilities={version:1,driveRead:true,driveWrite:false,appData:false};state.demo=false;state.accountId='synthetic-image-account';state.accountIdentityPending=false;state.accountMediaState.viewed={};window.qaEvents=[];const originalMark=markFileViewed;markFileViewed=function(id){qaEvents.push({type:'viewed',t:performance.now(),complete:el.imageViewer.complete,width:el.imageViewer.naturalWidth,visible:!el.playerSheet.hidden,document:document.visibilityState});return originalMark(id);};el.imageViewer.addEventListener('load',()=>qaEvents.push({type:'load',t:performance.now()}));window.qaFile={id:'fixture',name:trial.fileName||trial.fixture,mimeType:trial.mime,size:String(size),capabilities:{canDownload:true},thumbnailLink:origin+'/qa/rc16-image-format/'+trial.fixture};window.qaCardHost=document.createElement('div');qaCardHost.id='qaCardHost';document.body.prepend(qaCardHost);qaCardHost.append(createFileCard(qaFile,0));},{trial,size:bytes.length,origin});
 await page.waitForFunction(()=>{const e=document.querySelector('#qaCardHost canvas,#qaCardHost img');return e&&(e.tagName==='CANVAS'?e.width>1:e.complete&&e.naturalWidth>0);},null,{timeout:12000});
 r.card=await page.evaluate(()=>({kind:document.querySelector('#qaCardHost canvas,#qaCardHost img').tagName,isGif:isGifFile(qaFile),label:document.querySelector('#qaCardHost .file-card-gif-placeholder')?.textContent}));assert.equal(r.card.kind,trial.animated?'CANVAS':'IMG');assert.equal(r.card.isGif,trial.fixture==='animated.gif');if(trial.animated)assert.equal(r.card.label,trial.fixture==='animated.gif'?'GIF':'WEBP');if(trial.animated){r.card.canvasSamples=await samples(page,'card',50);r.card.samples=await paintedSamples(page,'card');r.card.uniqueColors=[...new Set(r.card.samples.map(s=>s.pixel.join(',')))];r.card.static=r.card.uniqueColors.length===1;assert.equal(r.card.static,true);assert.equal(r.card.uniqueColors[0],'255,0,0,255');assert.ok(r.card.samples.at(-1).t>2000);}
 await page.evaluate(()=>{el.playerSheet.hidden=false;state.pendingPlay=false;openMediaSource(qaFile);});r.beforeDecode=await page.evaluate(()=>({viewed:getViewedIdSet().has('fixture'),loading:!el.mediaLoading.hidden}));assert.equal(r.beforeDecode.viewed,false);
 await page.waitForFunction(()=>el.imageViewer.complete&&el.imageViewer.naturalWidth>0&&!el.imageViewer.hidden&&el.mediaLoading.hidden,null,{timeout:12000}).catch(async e=>{r.displayFailure=await page.evaluate(()=>({attempt:state.mediaAttempt,mode:state.mediaPlaybackMode,viewed:getViewedIdSet().has('fixture'),imageHidden:el.imageViewer.hidden,naturalWidth:el.imageViewer.naturalWidth,videoHidden:el.videoPlayer.hidden,error:!el.mediaError.hidden,iframeSrc:el.drivePreview.getAttribute('src')}));throw e;});
 await page.waitForFunction(()=>getViewedIdSet().has('fixture'));r.presentation=await page.evaluate(()=>({width:el.imageViewer.naturalWidth,height:el.imageViewer.naturalHeight,mode:state.mediaPlaybackMode,attempt:state.mediaAttempt,ready:el.imageViewer.classList.contains('is-ready'),events:qaEvents,rect:el.imageViewer.getBoundingClientRect().toJSON(),iframe:el.drivePreview.getAttribute('src')}));assert.equal(r.presentation.width,trial.width||96);assert.equal(r.presentation.height,trial.height||64);assert.ok(['original-range','original-sequential'].includes(r.presentation.mode));assert.equal(r.presentation.events.filter(e=>e.type==='viewed').length,1);assert.equal(r.presentation.events.find(e=>e.type==='viewed').document,'visible');assert.equal(r.presentation.events.find(e=>e.type==='viewed').complete,true);assert.equal(r.presentation.events.find(e=>e.type==='viewed').visible,true);assert.ok(r.presentation.events.find(e=>e.type==='viewed').t>=r.presentation.events.find(e=>e.type==='load').t);
 r.originalResponse=await page.evaluate(async()=>{const response=await fetch(el.imageViewer.src);const bytes=await response.arrayBuffer();return{mime:response.headers.get('content-type'),bytes:bytes.byteLength,sha256:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('')};});assert.equal(r.originalResponse.sha256,checksum);
 r.viewerSamples=await samples(page,'viewer',trial.animated?2200:50);r.viewerColors=[...new Set(r.viewerSamples.map(s=>s.pixel.join(',')))];if(trial.animated){r.viewerPaintedSamples=await paintedSamples(page,'viewer');r.viewerPaintedColors=[...new Set(r.viewerPaintedSamples.map(s=>s.pixel.join(',')))];assert.deepEqual(r.viewerPaintedColors.sort(),['0,0,255,255','255,0,0,255']);r.paintedTransitions=r.viewerPaintedSamples.filter((s,i,a)=>!i||s.pixel.join(',')!==a[i-1].pixel.join(','));assert.ok(r.paintedTransitions.length>=4,'native viewer loops retained');}else assert.equal(r.viewerColors.length,1);if(trial.fixture!=='raster.bmp'&&trial.fixture!=='large.png')assert.equal(r.viewerSamples[0].alpha[3],0);
 await page.screenshot({path:path.join(__dirname,trial.name+'.png')});await page.keyboard.press('Escape');await page.waitForFunction(()=>el.playerSheet.hidden);await page.evaluate(()=>q1Retirement);r.closed=await page.evaluate(()=>({cleanup:q1RetirementResult,imageSrc:el.imageViewer.getAttribute('src'),blob:state.mediaBlobUrl,selected:state.selected,preview:el.drivePreview.getAttribute('src')}));assert.equal(r.closed.cleanup.settled,true);assert.equal(r.closed.imageSrc,null);assert.equal(r.closed.blob,null);assert.equal(r.closed.selected,null);
 await page.evaluate(()=>{el.playerSheet.hidden=false;openMediaSource(qaFile);});await page.waitForFunction(()=>el.imageViewer.complete&&el.imageViewer.naturalWidth>0&&el.mediaLoading.hidden);r.reopen=await page.evaluate(()=>({width:el.imageViewer.naturalWidth,mode:state.mediaPlaybackMode}));assert.equal(r.reopen.width,trial.width||96);assert.ok(['original-range','original-sequential'].includes(r.reopen.mode));await page.evaluate(()=>closePlayer());await page.evaluate(()=>q1Retirement);assert.deepEqual(r.errors,[]);r.passed=true;save();console.log(trial.name,'PASS',r.card.static===false?'LIST_ANIMATES':'');
 }catch(e){r.failure={name:e.name,message:e.message.split('\n')[0],actual:e.actual,expected:e.expected,stack:e.stack.split('\n').slice(0,4)};save();console.log(trial.name,'FAIL',r.failure.message);}finally{await browser?.close();r.browserClosed=true;save();}}
 assert.deepEqual(report.producerStart,hashes());report.completed=true;report.fixtureProducer={path:'qa/rc16-image-format/fixture-producers.json',sha256:sha(fs.readFileSync(path.join(root,'qa/rc16-image-format/fixture-producers.json')))};report.passed=report.results.every(r=>r.passed&&r.card.static!==false);save();}finally{await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);save();process.exitCode=1;});
