'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),cp=require('node:child_process');
const actor=require('./android-q3-native-timing.cjs'),base=require('./android-q3-actor.cjs');
const helper=fs.readFileSync(path.join(__dirname,'android-q3-native-timing.function.js'),'utf8'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function fixture(){
 let clock=0,token=0;const nativeCalls=[],channels=[],created=[],revoked=[],timers=new Map();
 class NativeWorker{constructor(url,options){this.url=String(url);this.options=options;this.args=Array.from(arguments);this.newTarget=new.target;this.messages=[];nativeCalls.push(this);}postMessage(data,transfer){this.messages.push({data,transfer});}}NativeWorker.marker='original';
 class TestURL extends URL{static createObjectURL(blob){const url=`blob:local-native-test-${++token}`;created.push({url,blob});return url;}static revokeObjectURL(url){revoked.push(url);}}
 class Channel{constructor(){this.port1={onmessage:null,start(){},close(){this.closed=true;}};this.port2={close(){this.closed=true;}};channels.push(this);}}
 const target={id:'local-owned-target',name:'fixture',size:'18075476',mimeType:'video/mp4',modifiedTime:'fixed',parents:['local-parent'],version:'1',headRevisionId:'local-revision',sha256Checksum:'local-checksum'};
 const identity={accountId:'local-account',authAccountKey:'local-key',authGeneration:1,driveSessionGeneration:2},sourceSHA256={a:'1',b:'2',c:'3',d:'4',e:'5'},controller={state:'activated'},holder={metadata:target,account:identity};
 const proof={get:()=>({version:'1.22.0-rc.33',sourceCommit:'5174485b3c17d047259701bbdd889f9b0740f555',controller,sourceSHA256})};
 const owned={cleanupStarted:false,identity,sourceSHA256,refs:{__q3ActualTarget33:holder,__resumeSwProof:proof}};
 const context={window:{Worker:NativeWorker,__q3ActorOwned33:owned,__q3ActualTarget33:holder,__resumeSwProof:proof},state:{...identity,authStatus:'online',selected:null,mediaSession:3},q0Playback:null,q0PinnedSource:null,q1Playback:null,mediaSourceGeneration:4,APP_VERSION:'1.22.0-rc.33',navigator:{serviceWorker:{controller}},location:{origin:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev',href:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/'},document:{visibilityState:'visible'},el:{playerSheet:{hidden:true},videoPlayer:{readyState:4,videoWidth:640,videoHeight:360,currentTime:2,paused:false},streamModeLabel:{hidden:true},streamModeText:{textContent:'호환 변환 · 영상 손실 압축'}},URL:TestURL,Blob,MessageChannel:Channel,TextEncoder,Uint8Array,crypto:crypto.webcrypto,performance:{now:()=>clock},setTimeout:fn=>{timers.set(++token,fn);return token;},clearTimeout:id=>timers.delete(id)};
 const pipeline='export const local=1;',workerTemplate='import "__Q3_PIPELINE_BLOB__";';
 const install=vm.runInNewContext(helper,context),ownership=vm.runInNewContext(`(${base.ownershipExpression()})`,context);install({pipeline,workerTemplate,pipelineSha256:hash(pipeline),workerTemplateSha256:hash(workerTemplate),remainingMs:100000},ownership);
 const api=context.window.__q3NativeTiming33;
 const select=()=>{context.state.selected={...target};context.el.playerSheet.hidden=false;const stats={generation:1,status:{level:'Q3'}};context.q1Playback={kind:'general',fileId:target.id,controller:{signal:{aborted:false}},player:{stats:()=>stats}};};
 const phase=(extra={})=>({phase:'flush',decoded:10,encoded:11,phaseTimes:{readMs:1,decodeCopyMs:2,frameEncodeCallMs:3,flushMs:4,muxMs:5,ackMs:6,encodeOutputMs:7,encodeOutputs:11},reads:{requests:3,cacheHits:20},readRpcRequests:3,readRpcMs:9,...extra});
 return{context,api,select,phase,NativeWorker,nativeCalls,channels,created,revoked,timers,setClock:n=>{clock=n;},owned};
}
test('exact one-shot factory preserves normal Workers/prototype/descriptor, records scalar data despite hidden label, then closes ports/revokes blobs',async()=>{
 const f=fixture(),original=Object.getOwnPropertyDescriptor(f.context.window,'Worker');await f.api.install();const Wrapper=f.context.window.Worker;
 assert.equal(Wrapper.marker,'original');const other=new Wrapper(new URL('/media/general-worker.mjs',f.context.location.href),{type:'module'});assert.ok(other instanceof f.NativeWorker);assert.match(other.url,/general-worker/);assert.equal(f.api.read().wrapped,0);
 const oneArg=new Wrapper('/plain-worker.js');assert.equal(oneArg.args.length,1);assert.equal(oneArg.newTarget,f.NativeWorker);
 class Derived extends Wrapper{}const options={type:'module',name:'unchanged'};const derived=new Derived('/other-module.mjs',options,'preserved-extra');assert.equal(derived.newTarget,Derived);assert.ok(derived instanceof Derived);assert.deepEqual(derived.args,['/other-module.mjs',options,'preserved-extra']);
 // Actual start emits starting/increments the SW generation before opening its
 // reader and constructing Worker. Capture admits that new generation, then pins it.
 f.select();f.context.mediaSourceGeneration++;f.context.state.mediaSession++;const w=new Wrapper(new URL('/media/video-q3-worker.mjs',f.context.location.href),{type:'module'});assert.ok(w instanceof f.NativeWorker);assert.match(w.url,/^blob:/);assert.equal(w.messages[0].data.kind,'q3-owned-timing-port');assert.deepEqual(Object.getOwnPropertyDescriptor(f.context.window,'Worker'),original);
 for(let i=0;i<100;i++){f.setClock(i*1000);f.channels[0].port1.onmessage({data:f.phase({decoded:i,encoded:i+1})});}const r=f.api.read();assert.equal(r.samples.length,64);assert.equal(r.wrapped,1);assert.equal(r.restored,true);assert.equal(r.failure,null);assert.equal(r.currentOwner,true);assert.equal(r.native.lossyLabelVisible,false);assert.equal(r.latest.phaseTimes.flushMs,4);assert.doesNotMatch(JSON.stringify(r),/local-owned-target|local-account|local-key|local-parent|local-revision/);assert.equal(r.complete,false);assert.equal(r.performanceAcceptance,'NOT_QUALIFIED');
 f.api.beginCleanup();f.context.q1Playback=null;f.context.state.selected=null;f.context.el.playerSheet.hidden=true;f.channels[0].port1.onmessage({data:f.phase({phase:'worker-terminal',error:'Q3_CANCELLED',sourceCleanupSettled:true})});assert.equal(f.api.read().terminal.sourceCleanupSettled,true);
 const clean=await f.api.stop();assert.equal(actor.timingCleanupConfirmed(clean),true);assert.equal(clean.wrapperRestored,true);assert.equal(clean.blobsRevoked,true);assert.equal(clean.portsClosed,true);assert.equal(f.revoked.length,2);assert.equal(f.timers.size,0);assert.ok(f.channels[0].port1.closed&&f.channels[0].port2.closed);
});
test('foreign account/target/controller/generation cannot intercept exact Q3 Worker or adopt later phase',async()=>{
 for(const change of [f=>{f.context.state.accountId='other';},f=>{f.context.state.selected.id='other';f.context.q1Playback.fileId='other';},f=>{f.context.navigator.serviceWorker.controller={state:'activated'};}]){const f=fixture();await f.api.install();f.select();change(f);assert.throws(()=>new f.context.window.Worker(new URL('/media/video-q3-worker.mjs',f.context.location.href),{type:'module'}),/TIMING_FACTORY_OWNER/);assert.equal(f.nativeCalls.length,0);await f.api.stop();}
 const f=fixture();await f.api.install();f.select();new f.context.window.Worker(new URL('/media/video-q3-worker.mjs',f.context.location.href),{type:'module'});f.context.mediaSourceGeneration++;f.channels[0].port1.onmessage({data:f.phase()});assert.equal(f.api.read().failure,'TIMING_CURRENT_OWNER');assert.equal(f.api.read().latest,null);await f.api.stop();
});
test('owned wrapper cleanup does not overwrite a foreign replacement and idle mismatch makes no blobs',async()=>{
 const f=fixture();await f.api.install();const foreign=function(){};f.context.window.Worker=foreign;const clean=await f.api.stop();assert.equal(f.context.window.Worker,foreign);assert.equal(clean.wrapperRestored,false);assert.equal(actor.timingCleanupConfirmed(clean),false);
 const g=fixture();g.select();await assert.rejects(g.api.install(),/TIMING_IDLE_INSTALL/);assert.equal(g.created.length,0);await g.api.stop();
});
test('worker phase instrumentation posts at most once/sec except final and exposes RPC/cache scalars without buffers',()=>{
 const p=actor.prepare('local-native-timing-guards');cp.execFileSync(process.execPath,['--check','--input-type=module'],{input:p.pipeline});cp.execFileSync(process.execPath,['--check','--input-type=module'],{input:p.workerTemplate});
 assert.match(p.pipeline,/hardwareAcceleration:'prefer-software'/);assert.doesNotMatch(p.pipeline,/no-preference/);assert.match(p.pipeline,/metrics,rpc.metrics/);assert.match(p.workerTemplate,/now-qaLastSent>=1000/);assert.match(p.workerTemplate,/record\.kind==='read'/);assert.match(p.workerTemplate,/stopImmediatePropagation/);
 let clock=0,listener;const messages=[],context={performance:{now:()=>clock},self:{addEventListener:(_,fn)=>{listener=fn;}},result:{cleanup:{settled:true},reads:{requests:3}},error:null,closed:{settled:true}};
 const prefix=p.workerTemplate.slice(p.workerTemplate.indexOf('let qaPort='),p.workerTemplate.indexOf('let controller, generation'));vm.runInNewContext(prefix,context);listener({data:{kind:'q3-owned-timing-port'},ports:[{postMessage:r=>messages.push(r)}],stopImmediatePropagation(){}});
 const metrics={decoded:10,encoded:11,phaseTimes:{readMs:1}},reads={requests:3,cacheHits:20};for(clock=0;clock<3000;clock+=100)context.__q3TailPhase('read',metrics,reads);assert.equal(messages.length,3);
 const final=p.workerTemplate.slice(p.workerTemplate.indexOf('if(qaLast)qaPort?.postMessage'),p.workerTemplate.indexOf("send({ kind: 'terminal'"));vm.runInNewContext(final,context);assert.equal(messages.length,4);assert.equal(messages.at(-1).phase,'worker-terminal');assert.equal(messages.at(-1).sourceCleanupSettled,true);assert.doesNotMatch(JSON.stringify(messages),/buffer|bytes.*\[/);
});
test('inert plan/no private read, no seek/pause/EOF/cancel product calls; failed admission leaves real state untouched',async()=>{
 const read=fs.readFileSync;fs.readFileSync=function(file,...args){if(String(file).includes('q3-target-cua1-1-private'))throw Error('PRIVATE_FORBIDDEN');return read.call(this,file,...args);};try{const p=actor.plan('local-native-only');assert.equal(p.actualOperationPerformed,false);assert.equal(p.actionMs,100000);assert.equal(p.cleanupEndFromInvocationMs,145000);assert.equal(p.observationsEndFromInvocationMs,85000);assert.equal(p.complete,false);}finally{fs.readFileSync=read;}
 const code=fs.readFileSync(path.join(__dirname,'android-q3-native-timing.cjs'),'utf8');assert.doesNotMatch(code,/arm\('seek|arm\('cancel|tap\('pause|\.play\(|\.seek\(|dispatchEvent|maintainOwnedControls/);
 let privateRead=false;const c={report:{model:'SM-X800',android:'16',physicalScreen:'Physical size: 1752x2800'},step:()=>{},unmaskNativeVisibility:async()=>{},releaseMcpForNativeLifecycle:async()=>{},evaluateNative:async()=>({identity:false}),adb:()=>{throw Error('FORBIDDEN_NATIVE_INPUT');}};await assert.rejects(actor.run(c,{output:{},binding:{}},{progress:()=>{},readPrivate:()=>{privateRead=true;throw Error('PRIVATE_FORBIDDEN');}}),/TIMING_IDLE_ADMISSION/);assert.equal(privateRead,false);
});
