import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import vm from 'node:vm';
import {createRequire} from 'node:module';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {q3DisposableJob} from './disposable-job.mjs';
const base=new URL('./',import.meta.url),binding=JSON.parse(fs.readFileSync(new URL('disposable-binding.json',base))),fixture=JSON.parse(fs.readFileSync(new URL('disposable-build.json',base))).fixture;
delete fixture.path;
const bytes=fs.readFileSync(new URL('../q3-product-integration/synthetic-640-180s.mp4',base)),blob=new Blob([bytes],{type:'video/mp4'}),run='11111111-1111-4111-8111-111111111111',canonical=x=>JSON.stringify(Object.fromEntries(Object.entries(x).sort()));
const sha=x=>crypto.createHash('sha256').update(new Uint8Array(x)).digest('hex');
const safe=v=>{const raw=JSON.stringify(v);for(const x of ['PRIVATE_','Bearer','https://www.googleapis.com','sha256Checksum','metadata'])assert(!raw.includes(x),x);};
function fixtureEnv({losePost=0,losePatch=0,unknownChild=false,foreign=false,lateFailure=false,cancelFailure=false,storageFailure=false,driftPostflight=false}={}){
 const storage=new Map(),files=new Map(),calls=[],lifecycle=new EventTarget(),owner={accountId:'PRIVATE_ACCOUNT',accountKey:'PRIVATE_ACCOUNTKEY',auth:1,data:1,token:'PRIVATE_TOKEN',revision:1,expiry:Date.now()+3600000,writer:'PRIVATE_WRITER',projection:'{}',href:'PRIVATE_HREF',controller:{state:'activated'},signal:new AbortController().signal,version:binding.version,source:binding.source,hashes:canonical(binding.sourceSHA256),mediaSession:1,sourceGeneration:1,retirement:{settled:true},safe:true,driveWrite:true};
 const root={id:'PRIVATE_ROOT',version:'1',mimeType:'application/vnd.google-apps.folder',trashed:false,ownedByMe:true,modifiedTime:'PRIVATE_DATE',capabilities:{canAddChildren:true}},ids=['PRIVATE_FOLDER','PRIVATE_VIDEO'];let post=0,patch=0,release=null,metadataVideoReads=0;
 const env={read:()=>({...owner}),uuid:()=>run,sha256:async raw=>sha(raw),storage:{getItem:k=>storage.get(k)??null,setItem(k,v){if(storageFailure)throw Error('PRIVATE_STORAGE');storage.set(k,v);}},lifecycle,fetch:async(address,options)=>{
  const u=new URL(address),id=u.pathname.split('/').at(-1);calls.push({method:options.method,pathname:u.pathname});assert.equal(options.redirect,'error');assert.equal(options.credentials,'omit');
  if(id==='root')return Response.json(root);if(id==='generateIds')return Response.json({space:'drive',ids});
  if(options.method==='POST'){
   post++;const ledger=JSON.parse(storage.get(`drive-original.qa.disposable.${run}.recovery`));assert.equal(ledger.planned[post-1].sent,true);assert.equal(ledger.planned.length,2);assert(storage.get('drive-original.qa.disposable.q3-180s.'+fixture.sha256+'.run'));let meta;
   if(options.body instanceof Blob){const raw=Buffer.from(await options.body.arrayBuffer()),prefix=raw.subarray(0,1200).toString('latin1');meta=JSON.parse(prefix.match(/\r\n\r\n(\{.*?\})\r\n--/s)[1]);const mark=Buffer.from('Content-Type: video/mp4\r\n\r\n'),start=raw.indexOf(mark)+mark.length,payload=raw.subarray(start,start+fixture.bytes);assert.deepEqual(payload,bytes);assert.equal(sha(payload),fixture.sha256);assert.equal(options.body.size,raw.length);meta.size=String(payload.length);meta.md5Checksum=fixture.md5;meta.sha256Checksum=fixture.sha256;meta.headRevisionId='PRIVATE_REVISION';}
   else meta=JSON.parse(options.body);
   Object.assign(meta,{version:'1',modifiedTime:'PRIVATE_DATE',trashed:false,ownedByMe:true,capabilities:{canAddChildren:true,canTrash:true,canDownload:true}});files.set(meta.id,meta);
   if(post===losePost)throw Error('PRIVATE_RESPONSE_LOSS');if(lateFailure&&post===2)return new Promise(resolve=>release=resolve);
   return Response.json({id:'POST_RESPONSE_NOT_RECEIPT'});
  }
  if(u.pathname==='/drive/v3/files'){const parent=u.searchParams.get('q').match(/^'([^']+)'/)[1];return Response.json({incompleteSearch:false,files:[...files.values()].filter(x=>x.parents[0]===parent&&!x.trashed).map(x=>structuredClone(x)).concat(unknownChild?[{id:'PRIVATE_ORIGINAL_UNKNOWN'}]:[])});}
  const found=files.get(id);if(!found)return Response.json({}, {status:404});
  if(options.method==='PATCH'){patch++;assert.equal(options.body,'{"trashed":true}');assert(!u.searchParams.has('addParents'));assert(!u.searchParams.has('removeParents'));found.trashed=true;found.version=String(Number(found.version)+1);if(id===ids[1])files.get(ids[0]).version='2';if(patch===losePatch)throw Error('PRIVATE_PATCH_RESPONSE_LOSS');}
  const meta=structuredClone(found);if(foreign)meta.appProperties.qaRun='PRIVATE_FOREIGN';if(driftPostflight&&id===ids[1]&&++metadataVideoReads>1)meta.sha256Checksum='wrong';return Response.json(meta);
 }};
 return {env,owner,storage,files,calls,lifecycle,start:opts=>q3DisposableJob(env,binding,fixture,opts),post:()=>post,patch:()=>patch,late:()=>release?.({body:{cancel:()=>cancelFailure?Promise.reject(Error('PRIVATE_CANCEL')):Promise.resolve()}})};
}
test('actual immutable18MB bytes through persisted exactly2 POSTs then fresh receipts/capture/cleanup',async()=>{
 const f=fixtureEnv(),job=f.start();const result=await job.create(blob);assert.equal(result.passed,true);assert.equal(result.writes,2);assert.equal(result.created,2);assert.equal(f.post(),2);safe(result);assert(!job.privateText().includes('PRIVATE_TOKEN'));assert.throws(()=>f.start(),e=>e.code==='existing_run');
 const recovered=f.start({recoveryRun:run}),capture=await recovered.capture();assert.equal(capture.passed,true);assert.equal(capture.captureStable,true);assert.equal(capture.writes,0);safe(capture);const target=recovered.privateTarget();assert.equal(target.metadata.sha256Checksum,fixture.sha256);assert.equal(target.metadata.size,String(bytes.length));assert.equal(target.account.accountId,f.owner.accountId);assert(!JSON.stringify(target).includes('PRIVATE_TOKEN'));
 const cleanup=f.start({recoveryRun:run}),end=await cleanup.cleanup();assert.equal(end.passed,true,end.code);assert.equal(end.writes,2);assert.equal(f.patch(),2);assert([...f.files.values()].every(x=>x.trashed));assert(!f.calls.some(x=>x.method==='DELETE'));safe(end);await job.clear();await recovered.clear();await cleanup.clear();
});
test('unknown upload outcome GET-only recovery never recreates; durable pointer denies duplicate creator',async()=>{
 const f=fixtureEnv({losePost:2}),job=f.start(),result=await job.create(blob);assert.equal(result.passed,false);assert.equal(result.submitted,2);assert.equal(result.created,1);assert.throws(()=>f.start(),e=>e.code==='existing_run');const n=f.calls.length,recovered=f.start({recoveryRun:run}),capture=await recovered.capture();assert.equal(capture.passed,true);assert.equal(capture.created,2);assert(f.calls.slice(n).every(x=>x.method==='GET'));assert.equal(f.post(),2);safe(result);safe(capture);await job.clear();await recovered.clear();
});
test('wrong bytes, source, grant, storage, owner drift reject before upload',async()=>{
 const f=fixtureEnv(),job=f.start();assert.equal((await job.create(new Blob([new Uint8Array(5)]))).code,'fixture_hash');assert.equal(f.calls.length,0);await job.clear();
 const changed=new Uint8Array(bytes);changed[100]^=1;const g=fixtureEnv(),bad=g.start();assert.equal((await bad.create(new Blob([changed]))).code,'fixture_hash');assert.equal(g.calls.length,0);await bad.clear();
 for(const mutate of [x=>x.owner.driveWrite=false,x=>x.owner.source='a'.repeat(40),x=>x.owner.controller=null,x=>x.owner.safe=false]){const x=fixtureEnv();mutate(x);assert.throws(()=>x.start());assert.equal(x.calls.length,0);}
 const s=fixtureEnv({storageFailure:true}),blocked=s.start();assert.equal((await blocked.create(blob)).passed,false);assert.equal(s.post(),0);await blocked.clear();
 const d=fixtureEnv(),drift=d.start(),fetch=d.env.fetch;d.env.fetch=async(u,o)=>{const r=await fetch(u,o);if(o.method==='POST')d.owner.revision++;return r;};assert.equal((await drift.create(blob)).passed,false);assert.equal(d.post(),1);await drift.clear();
});
test('unknown descendants, changed hashes or forged ledger deny every cleanup PATCH',async()=>{
 for(const config of [{unknownChild:true},{driftPostflight:true}]){const f=fixtureEnv(config),job=f.start();assert.equal((await job.create(blob)).passed,true);const cleanup=f.start({recoveryRun:run});assert.equal((await cleanup.cleanup()).passed,false);assert.equal(f.patch(),0);await job.clear();await cleanup.clear();}
 const f=fixtureEnv(),job=f.start();assert.equal((await job.create(blob)).passed,true);const key=`drive-original.qa.disposable.${run}.recovery`,ledger=JSON.parse(f.storage.get(key));ledger.planned[1].id='PRIVATE_ORIGINAL';f.storage.set(key,JSON.stringify(ledger));const n=f.calls.length;assert.throws(()=>f.start({recoveryRun:run}),e=>e.code==='ledger');assert.equal(f.calls.length,n);await job.clear();
});
test('late response cancellation is awaited; failure is terminal; raw errors redacted',async()=>{
 for(const cancelFailure of [false,true]){const f=fixtureEnv({lateFailure:true,cancelFailure}),job=f.start(),pending=job.create(blob);for(let i=0;i<1000&&f.post()<2;i++)await new Promise(r=>setTimeout(r,1));assert.equal(f.post(),2);job.cancel();f.late();const r=await pending;assert.equal(r.passed,false);assert.equal(r.code,cancelFailure?'cleanup_failed':'cancelled');assert.equal(r.ownedCleanupSettled,!cancelFailure);assert.equal(f.post(),2);safe(r);const recovered=f.start({recoveryRun:run});assert.equal((await recovered.capture()).passed,true);await job.clear();await recovered.clear();}
});
test('serialized generated factory processes real immutable blob and recovery',async()=>{
 const expression=fs.readFileSync(new URL('disposable-factory.expression.js',base),'utf8'),factory=vm.runInNewContext(expression,{AbortController,AbortSignal,Blob,URL,URLSearchParams,Uint8Array,TextDecoder,setTimeout,clearTimeout});const f=fixtureEnv(),job=factory(f.env,binding,{});assert.equal((await job.create(blob)).passed,true);const recovered=factory(f.env,binding,{recoveryRun:run});assert.equal((await recovered.capture()).captureStable,true);assert.equal(recovered.privateTarget().metadata.sha256Checksum,fixture.sha256);await job.clear();await recovered.clear();
});
test('lost cleanup response recovers observed trash state and never repeats that PATCH',async()=>{
 const f=fixtureEnv({losePatch:1}),job=f.start();assert.equal((await job.create(blob)).passed,true);const first=f.start({recoveryRun:run});assert.equal((await first.cleanup()).passed,false);assert.equal(f.patch(),1);assert(f.files.get('PRIVATE_VIDEO').trashed);const recovered=f.start({recoveryRun:run});assert.equal((await recovered.cleanup()).passed,true);assert.equal(f.patch(),2);assert([...f.files.values()].every(x=>x.trashed));await job.clear();await first.clear();await recovered.clear();
});
test('source-bound facade installs private fresh target only, preserves detached holder until explicit release',async()=>{
 const f=fixtureEnv(),expression=fs.readFileSync(new URL('disposable-factory.expression.js',base),'utf8'),facadeSource=fs.readFileSync(new URL('disposable-facade.function.js',base),'utf8');
 const state={accountId:f.owner.accountId,authAccountKey:f.owner.accountKey,authGeneration:1,driveSessionGeneration:1,token:f.owner.token,tokenRevision:1,expiresAt:f.owner.expiry,accountStateWriterId:f.owner.writer,accountMediaState:{favorites:{}},accountStateLoaded:true,accountStateLoadingPromise:null,accountStateAbortController:new AbortController(),accountStateSyncPromise:null,accountStateSyncTimer:null,accountStateSyncRetryTimer:null,accountStateSyncError:null,authStatus:'online',demo:false,accountIdentityPending:false,bulkAction:null,selected:null,mediaSession:1,mediaAttempt:'idle',mediaAbortController:null,pendingOriginalBuffer:null,pendingPlay:false,mediaTransportStarted:false};
 const controller={state:'activated',scriptURL:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/sw.js'},context={state,APP_VERSION:binding.version,DRIVE_MUTATIONS_ENABLED:false,navigator:{onLine:true,serviceWorker:{controller}},location:{origin:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev',href:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/'},top:1,self:1,document:{visibilityState:'visible'},mediaSourceGeneration:1,q1RetirementResult:{settled:true},q0Playback:null,q1Playback:null,playerMediaPriorityActive:false,hasUsableToken:()=>true,hasAuthCapability:()=>true,crypto:{randomUUID:()=>run,subtle:crypto.webcrypto.subtle},localStorage:f.env.storage,window:f.lifecycle,fetch:f.env.fetch,Blob,AbortController,AbortSignal,Uint8Array,URL,URLSearchParams,TextDecoder,setTimeout,clearTimeout};
 const proof={get:()=>({version:binding.version,sourceCommit:binding.source,sourceSHA256:{...binding.sourceSHA256,'extra-shell-asset':'e'.repeat(64)},controller})},factory=vm.runInNewContext(expression,context),facade=vm.runInNewContext('('+facadeSource+')',context),creator=facade(factory,binding,proof,{});
 assert.equal((await creator.create(blob)).passed,true);const recovered=facade(factory,binding,proof,{recoveryRun:run});assert.equal((await recovered.capture()).passed,true);const installed=recovered.installTarget();safe(installed);assert.equal(context.__q3ActualTarget33.metadata.sha256Checksum,fixture.sha256);assert.equal(context.__q3ActualTarget33.account.authAccountKey,state.authAccountKey);assert(!JSON.stringify(context.__q3ActualTarget33).includes('PRIVATE_TOKEN'));assert.throws(()=>recovered.installTarget());await recovered.clear();assert(context.__q3ActualTarget33);assert.equal(recovered.clearTarget().privateTargetReleased,true);assert.equal(context.__q3ActualTarget33,undefined);await creator.clear();
 const n=f.calls.length;assert.throws(()=>facade(factory,{...binding,source:'a'.repeat(40)},proof,{}));assert.equal(f.calls.length,n);
});
test('installed1.10.1 actual filePaths schema discriminates singular/multiple/stale/foreign inputs without MCP launch',()=>{
 const require=createRequire(import.meta.url),{toolArgs,snapshotInputUIDs,validateUploadArgs}=require('./disposable-pc-owned-operator.cjs'),realPath=fileURLToPath(new URL('../q3-product-integration/synthetic-640-180s.mp4',base));
 const inputToolPath=path.join(process.env.LOCALAPPDATA,'npm-cache/_npx/15c61037b1978c83/node_modules/chrome-devtools-mcp/build/src/tools/input.js'),toolDefinitionPath=path.join(path.dirname(inputToolPath),'ToolDefinition.js');assert.equal(JSON.parse(fs.readFileSync(path.resolve(path.dirname(inputToolPath),'../../../package.json'),'utf8')).version,'1.10.1');const inputSource=fs.readFileSync(inputToolPath,'utf8'),section=inputSource.slice(inputSource.indexOf('export const uploadFile ='),inputSource.indexOf('blockedByDialog: true',inputSource.indexOf('export const uploadFile =')));assert.match(section,/filePaths:\s*zod\s*\.array\(zod\.string\(\)\)\s*\.min\(1\)/);assert(!/filePath:/.test(section));const properties=Object.fromEntries([...section.slice(section.indexOf('schema: {')).matchAll(/^        ([A-Za-z]+):/gm)].map(m=>[m[1],{}]));assert.deepEqual(Object.keys(properties).sort(),['filePaths','includeSnapshot','uid']);assert.match(fs.readFileSync(toolDefinitionPath,'utf8'),/pageId: zod.number\(\)/);properties.pageId={};const schemas=new Map([['upload_file',{inputSchema:{properties}}]]),args=toolArgs('upload_file',{uid:'12_7',filePaths:[realPath]},1,schemas);assert.equal(args.pageId,1);assert.equal(args.includeSnapshot,false);
 const set=snapshotInputUIDs({content:[{type:'text',text:'uid=12_6 StaticText "Q3 disposable fixture input"\nuid=12_7 button "Q3 disposable fixture input"\nuid=12_8 button "Original upload"'}]});assert.deepEqual([...set],['12_7']);validateUploadArgs(args,set,Date.now());
 for(const bad of [{...args,filePaths:[path.resolve(realPath,'../../PRIVATE_ORIGINAL.mp4')]},{...args,uid:'12_8'}])assert.throws(()=>validateUploadArgs(bad,set,Date.now()),/EXACT_FRESH_QA_FIXTURE_INPUT_REQUIRED/);assert.throws(()=>validateUploadArgs(args,set,Date.now()-31000));assert.throws(()=>validateUploadArgs(args,new Set(['12_7','12_8']),Date.now()));assert.throws(()=>toolArgs('delete_file',{},1,schemas));for(const bad of [{...args,filePaths:[]},{...args,filePaths:[realPath,realPath]},{...args,filePaths:[realPath,'PRIVATE_ORIGINAL']},{...args,filePaths:realPath},{...args,filePath:realPath},{uid:args.uid,filePath:realPath}])assert.throws(()=>validateUploadArgs(bad,set,Date.now()));assert.throws(()=>toolArgs('upload_file',{uid:'12_7',filePath:realPath},1,schemas),/OWNED_TOOL_ARGUMENT_UNKNOWN/);
 const operator=fs.readFileSync(new URL('disposable-pc-owned-operator.cjs',base),'utf8');assert(operator.includes("args:[{uid}]"));assert(operator.includes("op:'close',closed:report.ownedMcpClosed===true"));assert(!operator.includes('--isolated'));assert(operator.includes('--autoConnect'));
});
