const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const here=__dirname,root=path.resolve(here,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const source=process.argv[2];if(source!=='5174485b3c17d047259701bbdd889f9b0740f555')throw Error('EXPLICIT_FIXED33_FULL_SHA_REQUIRED');
const git=p=>execFileSync('git',['show',source+':'+p],{cwd:root,windowsHide:true,maxBuffer:32*1024*1024});
const app=git('app.js'),sw=git('sw.js'),version=git('version.json');
if(!app.includes("const APP_VERSION = '1.22.0-rc.33'")||!sw.includes("const VERSION = '1.22.0-rc.33'")||JSON.parse(version).version!=='1.22.0-rc.33')throw Error('FIXED33_VERSION_REQUIRED');
const fixturePath=path.join(root,'qa/q3-product-integration/synthetic-640-180s.mp4'),bytes=fs.readFileSync(fixturePath);
const fixture={bytes:bytes.length,sha256:sha(bytes),md5:crypto.createHash('md5').update(bytes).digest('hex')};
if(fixture.bytes!==18075476||fixture.sha256!=='cda53855c53bf1d608491eb96aa3abb0ff774cca2aa24cfe01447e295c07ed7a')throw Error('EXACT_FIXTURE_REQUIRED');
const binding={version:'1.22.0-rc.33',source,sourceSHA256:{'app.js':sha(app),'sw.js':sha(sw),'version.json':sha(version)}};
const text=fs.readFileSync(path.join(here,'disposable-job.mjs'),'utf8').replace(/^export /m,'');
const factory=`(function(env,binding,options){${text}\nreturn q3DisposableJob(env,binding,${JSON.stringify(fixture)},options);})\n`;
const shell=sw.toString().match(/const SHELL_FILES = \[([\s\S]*?)\];/);if(!shell)throw Error('SHELL_INVENTORY_REQUIRED');
const shellPaths=[...shell[1].matchAll(/'\.\/([^']*)'/g)].map(m=>m[1]||'index.html');
if(shellPaths.length!==47||new Set(shellPaths).size!==46)throw Error('EXACT47_SHELL_REQUIRED');
const shellSHA256=Object.fromEntries([...new Set(shellPaths)].map(p=>[p,sha(git(p))]));
const hashes=Object.fromEntries(['disposable-job.mjs','disposable-facade.function.js','disposable-build.cjs'].map(p=>[p,sha(fs.readFileSync(path.join(here,p)))]));
fs.writeFileSync(path.join(here,'disposable-binding.json'),JSON.stringify(binding,null,2)+'\n');
fs.writeFileSync(path.join(here,'disposable-factory.expression.js'),factory);
fs.writeFileSync(path.join(here,'disposable-build.json'),JSON.stringify({actualExecution:false,binding,fixture:{path:'qa/q3-product-integration/synthetic-640-180s.mp4',...fixture},factorySHA256:sha(factory),factoryBytes:Buffer.byteLength(factory),producerSHA256:hashes,exact47ShellSHA256:shellSHA256,parentCreator:'qa/rc31-disposable-ui-preparation/job.mjs',parentCreatorSHA256:sha(fs.readFileSync(path.join(root,'qa/rc31-disposable-ui-preparation/job.mjs'))),contract:'Exactly1 task-created folder +1 immutable video;2generated IDs/2POST; no product lease/global write changes; persisted intent before POST; GET-only unknown-outcome recovery; fresh SHA256/MD5 receipt; separately recoverable trash only; root owns actual execution'},null,2)+'\n');
console.log(JSON.stringify({source,version:binding.version,factorySHA256:sha(factory),factoryBytes:Buffer.byteLength(factory),fixtureSHA256:fixture.sha256,fixtureBytes:fixture.bytes,actualExecution:false}));
