'use strict';
// Root-launched only. No playback, browser controls, configuration or process shutdown.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),{performance}=require('node:perf_hooks');
const MAX_SECONDS=360,INTERVAL_MS=5000,MAX_RECORDS=72;
const ADB=path.resolve(__dirname,'../../../maintenance/tools/scrcpy-v4.1/scrcpy-win64-v4.1/adb.exe');
function number(value){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;}
function pcParse(raw){let x;try{x=JSON.parse(raw);}catch{return{available:false,error:'PC_JSON'};}const count=number(x.count),cpu=number(x.cpuSeconds),working=number(x.workingBytes),privateBytes=number(x.privateBytes),disk=number(x.diskFreeBytes);return{available:count!==null&&count>0&&cpu!==null&&working!==null&&privateBytes!==null,chromeProcessCount:count,cpuSeconds:cpu,workingBytes:working,privateBytes,diskFreeBytes:disk,error:count===0?'CHROME_UNAVAILABLE':cpu===null||working===null||privateBytes===null?'PC_COUNTER_UNAVAILABLE':null};}
function cpuDelta(before,after,elapsedMs){if(!before||!before.available||!after.available||elapsedMs<=0)return{available:false,cpuDeltaSeconds:null,cpuPercent:null,reason:'BASELINE_UNAVAILABLE'};if(after.cpuSeconds<before.cpuSeconds||after.chromeProcessCount!==before.chromeProcessCount)return{available:false,cpuDeltaSeconds:null,cpuPercent:null,reason:'AGGREGATE_RESET_OR_PROCESS_COUNT_CHANGED'};const d=after.cpuSeconds-before.cpuSeconds;return{available:true,cpuDeltaSeconds:d,cpuPercent:d/(elapsedMs/1000)*100,reason:null};}
function androidParse(memory,thermal,battery){const pss=/^\s*TOTAL PSS:\s*(\d+)/m.exec(memory)||/^\s*TOTAL\s+(\d+)\s+\d+\s+\d+/m.exec(memory),rss=/^\s*TOTAL RSS:\s*(\d+)/m.exec(memory);const status=/Thermal Status:\s*(\d+)/i.exec(thermal),temp=/^\s*temperature:\s*(-?\d+)\s*$/m.exec(battery),batteryStatus=/^\s*status:\s*(\d+)\s*$/m.exec(battery);return{available:!!pss,chromePssKiB:pss?Number(pss[1]):null,chromeRssKiB:rss?Number(rss[1]):null,thermalStatus:status?Number(status[1]):null,thermalAvailable:!!status,batteryTemperatureC:temp?Number(temp[1])/10:null,batteryStatus:batteryStatus?Number(batteryStatus[1]):null,temperatureScope:'Android battery temperature (tenths C); not SoC or ambient',error:pss?null:'CHROME_MEMORY_UNAVAILABLE',thermalError:status?null:'THERMAL_STATUS_UNAVAILABLE'};}
function bounds(seconds){if(!Number.isInteger(seconds)||seconds<1||seconds>MAX_SECONDS)throw Error('RESOURCE_SECONDS_BOUND');return{seconds,intervalMs:INTERVAL_MS,maxRecords:MAX_RECORDS};}
function commandRunner({spawn=cp.spawn,setTimer=setTimeout,clearTimer=clearTimeout}={}){const owned=new Map();let stopped=false;return{run(exe,args,timeoutMs=3000){if(stopped)return Promise.reject(Error('READ_STOPPED'));return new Promise((resolve,reject)=>{let child,timer,done=false,bytes=0,out='';const finish=(error)=>{if(done)return;done=true;clearTimer(timer);owned.delete(child);error?reject(Error(error)):resolve(out);};try{child=spawn(exe,args,{windowsHide:true,stdio:['ignore','pipe','ignore']});owned.set(child,finish);child.stdout.on('data',b=>{bytes+=b.length;if(bytes>262144){child.kill();finish('READ_OUTPUT_BOUND');}else out+=b.toString();});child.on('error',()=>finish('READ_START_FAILED'));child.on('close',code=>finish(code===0?null:'READ_FAILED'));timer=setTimer(()=>{child.kill();finish('READ_TIMEOUT');},timeoutMs);}catch{finish('READ_START_FAILED');}});},stop(){stopped=true;for(const [child,finish] of [...owned]){child.kill();finish('READ_STOPPED');}return{ownedSubprocessesStopped:owned.size===0};},get active(){return owned.size;}};}
function ownedWriter(out){const fd=fs.openSync(out,'wx');let closed=false;return{save(raw){if(closed)throw Error('RESOURCE_WRITER_CLOSED');const b=Buffer.from(raw);fs.writeSync(fd,b,0,b.length,0);fs.ftruncateSync(fd,b.length);},close(){if(!closed){closed=true;fs.closeSync(fd);}}};}
const PC_SCRIPT="$p=@(Get-Process -Name chrome -ErrorAction SilentlyContinue);$m=$p|Measure-Object CPU,WorkingSet64,PrivateMemorySize64 -Sum;[pscustomobject]@{count=$p.Count;cpuSeconds=($m|Where-Object Property -eq 'CPU').Sum;workingBytes=($m|Where-Object Property -eq 'WorkingSet64').Sum;privateBytes=($m|Where-Object Property -eq 'PrivateMemorySize64').Sum;diskFreeBytes=([System.IO.DriveInfo]::new('C:\\')).AvailableFreeSpace}|ConvertTo-Json -Compress";
async function collect(kind,runner,serial){if(kind==='pc')return pcParse(await runner.run('powershell.exe',['-NoProfile','-Command',PC_SCRIPT]));const shell=cmd=>runner.run(ADB,['-s',serial,'shell',...cmd],2000);const pid=(await shell(['pidof','com.android.chrome'])).trim();if(!/^\d+$/.test(pid))throw Error('CHROME_PID_SCOPE_UNAVAILABLE');const values=await Promise.allSettled([shell(['dumpsys','meminfo',pid]),shell(['dumpsys','thermalservice']),shell(['dumpsys','battery'])]);const parsed=androidParse(...values.map(v=>v.status==='fulfilled'?v.value:''));parsed.memoryScope='Chrome named main process PSS/RSS; renderer/GPU memory UNKNOWN';parsed.readErrors=values.map((v,i)=>v.status==='rejected'?['memory','thermal','battery'][i]+':'+v.reason.message:null).filter(Boolean);return parsed;}
async function execute(kind,name,seconds=240){bounds(seconds);if(!['pc','android'].includes(kind)||!/^[a-z0-9-]+\.json$/.test(name))throw Error('RESOURCE_ARGS');const out=path.join(__dirname,name),stopPath=out+'.stop';if(fs.realpathSync(__dirname)!==__dirname||fs.existsSync(out)||fs.existsSync(stopPath))throw Error('RESOURCE_OUTPUT_EXISTS_OR_LINKED');const runner=commandRunner(),serial=kind==='android'?process.env.Q3_ANDROID_SERIAL:null;let stopped=false,timer=null,resolveWait;const signal=()=>{stopped=true;if(timer){clearTimeout(timer);timer=null;}resolveWait?.();};process.on('SIGINT',signal);process.on('SIGTERM',signal);const wait=ms=>new Promise(resolve=>{resolveWait=resolve;timer=setTimeout(()=>{timer=null;resolveWait=null;resolve();},ms);});const started=performance.now(),report={schema:1,kind,scope:kind==='pc'?'Chrome aggregate; no Q3-specific peak attribution':'Chrome named main process; no Q3-specific peak attribution',diskScope:'Workspace C volume free space; not Q3 disk usage',gpuEncoderPeak:'UNKNOWN',thermalOrBatteryCausality:'UNKNOWN',startedAt:new Date().toISOString(),startedMonotonicMs:started,maximumSeconds:seconds,intervalMs:INTERVAL_MS,samples:[],failedSamples:0,ready:false,cleanup:null};
 const deadman=setTimeout(()=>{signal();runner.stop();},seconds*1000);let ownsFile=false;const writer=ownedWriter(out);const save=()=>writer.save(JSON.stringify(report,null,2)+'\n');
 try{save();ownsFile=true;if(kind==='android'){if(!serial||!/^[A-Za-z0-9._:-]{1,128}$/.test(serial))throw Error('PINNED_DEVICE_REQUIRED');const model=(await runner.run(ADB,['-s',serial,'shell','getprop','ro.product.model'])).trim(),version=(await runner.run(ADB,['-s',serial,'shell','getprop','ro.build.version.release'])).trim();if(model!=='SM-X800'||version!=='16')throw Error('PINNED_DEVICE_MISMATCH');report.deviceVerified=true;}
  save();let previous=null,previousAt=null;while(!stopped&&performance.now()-started<seconds*1000&&report.samples.length<MAX_RECORDS&&!fs.existsSync(stopPath)){const at=performance.now(),remaining=seconds*1000-(at-started);if(remaining<3000)break;let sample;try{sample=await collect(kind,runner,serial);if(kind==='pc')sample.cpu=cpuDelta(previous,sample,previousAt===null?0:at-previousAt);previous=sample;previousAt=at;}catch(e){sample={available:false,error:/^[A-Z0-9_]+$/.test(e.message)?e.message:'READ_FAILED'};previous=null;previousAt=null;}if(sample.available!==true||sample.readErrors?.length||sample.thermalError)report.failedSamples++;report.samples.push({ordinal:report.samples.length+1,wallTime:new Date().toISOString(),monotonicMs:at,elapsedMs:at-started,...sample});report.ready=true;save();await wait(Math.min(INTERVAL_MS,Math.max(0,seconds*1000-(performance.now()-started))));}
 }catch(e){report.error=/^[A-Z0-9_]+$/.test(e.message)?e.message:'RESOURCE_FAILED';throw e;}finally{report.stopRequested=stopped||fs.existsSync(stopPath);signal();clearTimeout(deadman);process.off('SIGINT',signal);process.off('SIGTERM',signal);report.cleanup={...runner.stop(),ownedTimerCleared:timer===null,ownedDeadlineCleared:true};report.endedAt=new Date().toISOString();report.endedMonotonicMs=performance.now();report.elapsedMs=report.endedMonotonicMs-started;report.deadlineReached=report.elapsedMs>=seconds*1000;report.rawLogsExported=false;report.deviceIdentifiersExported=false;try{if(ownsFile)save();}finally{writer.close();}}
 return{ready:report.ready,samples:report.samples.length,failedSamples:report.failedSamples,cleanup:report.cleanup};}
module.exports={pcParse,cpuDelta,androidParse,bounds,commandRunner,ownedWriter};
if(require.main===module){const a=process.argv.slice(2);if(a.length<3||a.length>4||a[0]!=='--execute'){console.error('RESOURCE_EXECUTION_REQUIRED');process.exitCode=1;}else execute(a[1],a[2],a[3]===undefined?240:Number(a[3])).then(r=>console.log(JSON.stringify(r))).catch(e=>{console.error(/^[A-Z0-9_]+$/.test(e.message)?e.message:'RESOURCE_FAILED');process.exitCode=1;});}
