'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{pcParse,cpuDelta,androidParse,bounds,commandRunner}=require('./resource-watch.cjs');
const {procCpuParse,androidCpuDelta,gpuBusyParse,deviceMemoryParse,deviceDiskParse}=require('./resource-watch.cjs');

test('device CPU counter deltas exclude guest duplicates and reject reset/core drift',()=>{const a=procCpuParse('cpu 10 0 10 80 0 0 0 0 5 0\ncpu0 1\n'),b=procCpuParse('cpu 20 0 20 160 0 0 0 0 500 0\ncpu0 1\n');assert.equal(androidCpuDelta(a,b).busyPercent,20);assert.equal(a.counters.length,8);assert(!androidCpuDelta(null,b).available);assert(!androidCpuDelta(b,a).available);assert(!androidCpuDelta(a,{...b,cores:2}).available);assert(!procCpuParse('cpu bad\ncpu0 1').available);assert(!androidCpuDelta(a,a).available);});
test('GPU absent/zero/invalid counters stay unknown rather than successful zero utilization',()=>{assert.equal(gpuBusyParse('20 100').reportedCounterRatioPercent,20);for(const raw of ['Permission denied','0 0','101 100','-1 100','9007199254740992 9007199254740993']){const x=gpuBusyParse(raw);assert(!x.available);assert.equal(x.reportedCounterRatioPercent,null);}assert(gpuBusyParse('0 100').available);});
test('device RAM/disk units and unavailable fields remain explicit',()=>{assert.equal(deviceMemoryParse('MemTotal: 1000 kB\nMemAvailable: 300 kB\n').availableKiB,300);assert(!deviceMemoryParse('MemTotal: 1000 kB').available);assert(!deviceMemoryParse('MemTotal: 1000 kB\nMemAvailable: 3000 kB').available);assert.equal(deviceDiskParse('Filesystem 1K-blocks Used Available Use% Mounted on\n/dev/data 1000 700 300 70% /data\n').freeKiB,300);assert(!deviceDiskParse('/dev/data 1000 700 300 70% /other').available);assert(!deviceDiskParse('Permission denied').available);});
test('owned new-file descriptor persists repeated shorter receipts without a path recheck',()=>{const fs=require('node:fs'),path=require('node:path'),{ownedWriter}=require('./resource-watch.cjs');const p=path.join(__dirname,'resource-writer-test-'+require('node:crypto').randomUUID()+'.json');const writer=ownedWriter(p);try{writer.save('long receipt');writer.save('short');assert.equal(fs.readFileSync(p,'utf8'),'short');assert.throws(()=>ownedWriter(p),e=>e.code==='EEXIST');writer.close();assert.throws(()=>writer.save('x'),/WRITER_CLOSED/);writer.close();}finally{writer.close();fs.unlinkSync(p);}});
test('an output name replacement cannot redirect the owned descriptor to another file',()=>{const fs=require('node:fs'),path=require('node:path'),{ownedWriter}=require('./resource-watch.cjs');const p=path.join(__dirname,'resource-writer-test-'+require('node:crypto').randomUUID()+'.json'),old=p+'.owned';const writer=ownedWriter(p);try{writer.save('first');fs.renameSync(p,old);fs.writeFileSync(p,'foreign',{flag:'wx'});writer.save('updated');assert.equal(fs.readFileSync(p,'utf8'),'foreign');assert.equal(fs.readFileSync(old,'utf8'),'updated');}finally{writer.close();if(fs.existsSync(p))fs.unlinkSync(p);if(fs.existsSync(old))fs.unlinkSync(old);}});
test('PC aggregate units and CPU reset/count drift are explicit',()=>{const p=pcParse(JSON.stringify({count:3,cpuSeconds:10,workingBytes:100,privateBytes:90,diskFreeBytes:1000}));assert(p.available);assert.equal(cpuDelta(p,{...p,cpuSeconds:11},5000).cpuPercent,20);assert(!cpuDelta(p,{...p,cpuSeconds:9},5000).available);assert(!cpuDelta(p,{...p,chromeProcessCount:4},5000).available);assert(!pcParse('{}').available);assert.equal(pcParse('bad').error,'PC_JSON');assert(!cpuDelta(null,p,5000).available);});
test('Android known memory/battery units; absent thermal and unknown temperature remain unknown',()=>{const p=androidParse(' TOTAL PSS: 123 TOTAL RSS: 456\n TOTAL RSS: 456','Thermal Status: 2',' temperature: 315\n status: 2');assert.equal(p.chromePssKiB,123);assert.equal(p.batteryTemperatureC,31.5);assert.equal(p.thermalStatus,2);const u=androidParse('TOTAL: 123 MB','Temperature: 40 units?','temperature: 31.5 Celsius');assert(!u.available);assert.equal(u.batteryTemperatureC,null);assert.equal(u.thermalStatus,null);assert.equal(u.thermalError,'THERMAL_STATUS_UNAVAILABLE');});
test('bounds reject unlimited/invalid runs',()=>{assert.equal(bounds(360).maxRecords,72);for(const x of [0,361,Infinity,1.5,'180'])assert.throws(()=>bounds(x),/SECONDS_BOUND/);});
test('owned read timeout and stop kill only spawned read child and clear timers',async()=>{const timers=new Map();let next=0,kills=0;function spawn(){const c=new EventEmitter();c.stdout=new EventEmitter();c.kill=()=>{kills++;};return c;}const r=commandRunner({spawn,setTimer:f=>{timers.set(++next,f);return next;},clearTimer:id=>timers.delete(id)});const pending=r.run('read',[]);assert.equal(r.active,1);timers.values().next().value();await assert.rejects(pending,/READ_TIMEOUT/);assert.equal(r.active,0);assert.equal(timers.size,0);assert.equal(kills,1);const stopped=r.run('read',[]);assert(r.stop().ownedSubprocessesStopped);await assert.rejects(stopped,/READ_STOPPED/);assert.equal(r.active,0);assert.equal(timers.size,0);assert.equal(kills,2);await assert.rejects(r.run('read',[]),/READ_STOPPED/);});
