'use strict';
// File-only reconciliation: no browser, account, network, media operation or test rerun.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),leaf='qa/rc27-saved-contract-reconciliation';
const read=p=>fs.readFileSync(path.join(root,p)),json=p=>JSON.parse(read(p)),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(...a)=>cp.execFileSync('git',a,{cwd:root,maxBuffer:12*1024*1024}),norm=b=>b.toString('utf8').replace(/\r\n/g,'\n');
const line=(p,needle)=>{const i=norm(read(p)).split('\n').findIndex(x=>x.includes(needle));if(i<0)throw Error('Missing pointer '+p+' '+needle);return {path:p,line:i+1,needle};};
const ids=['QA-TR-10','QA-FM-09','QA-UI-02','QA-UI-04','QA-UI-05','QA-AU-04'];
const planPath='qa/rc26-remaining-acceptance-plan/plan.json',plan=json(planPath),baselinePath=plan.baseline.path;
if(sha(read(baselinePath))!==plan.baseline.SHA256)throw Error('Original69 baseline drift');
const specPath=plan.rows[0].originalSpec.path,spec=norm(read(specPath)).split('\n');
const originals=ids.map(id=>{const row=plan.rows.find(r=>r.id===id);const s=spec[row.originalSpec.line-1];if(!s.startsWith('| '+id+' |'))throw Error('Spec line drift');return {...row.originalSpec,id,verbatim:s,baselineStatus:row.baselineStatus};});
const evidencePaths=[leaf+'/source-change-discriminator.cjs',leaf+'/source-change-discriminator.json',planPath,baselinePath,specPath,'qa/player-input-quality-audit.cjs','qa/player-input-quality/after/results.json','qa/rc19-actual-account/pointer-only.expression.js','qa/rc19-actual-account/pointer-only-summary.json','qa/rc19-actual-account/pointer-only-safe-record.json','qa/rc15-player-ui-qualification/qualification.cjs','qa/rc15-player-ui-qualification/results.json','qa/v2-ui-audit.cjs','qa/v2-ui/after/results.json','qa/rc20-image-owner-dispatch/post-review-controls.cjs','qa/rc20-image-owner-dispatch/post-review-negative-results.json','qa/rc20-image-owner-dispatch/checks.json','qa/q0-provider-product/native-results-manifest.json','qa/q0-provider-product/native-results-node.json','qa/q0-provider-product/native-audit.cjs','qa/q0-provider-product/native-results.json','qa/q2-general-product-integration/evidence-manifest.json','qa/q2-general-product-integration/native.cjs','qa/q2-general-product-integration/native.mjs','qa/q2-general-product-integration/native-results.json','qa/candidate-rc13-qualification/selected-6.tap','tests/q0-proxy.test.js','tests/q1-source.test.mjs','tests/account-state.test.js','tests/mutations.test.js','tests/image-owner-dispatch.test.js'];
const evidence=evidencePaths.map(p=>({path:p,sha256:sha(read(p)),bytes:read(p).length}));
const bindings=[];
function bind(p,expected,meaning){const actual=sha(read(p));bindings.push({path:p,expected,actual,matched:actual===expected,meaning});}
const discriminator=json(leaf+'/source-change-discriminator.json');bind(leaf+'/source-change-discriminator.cjs',discriminator.producerSHA256,'exact current controlled adapter producer');bind('app.js',discriminator.appSHA256,'current discriminator source freeze');
const ui=json('qa/player-input-quality/after/results.json');bind('qa/player-input-quality-audit.cjs',ui.producerSHA256,'exact executed trusted DOM producer');
const pointer=json('qa/rc19-actual-account/pointer-only-summary.json');
bind('qa/rc19-actual-account/pointer-only.expression.js',pointer.producerTrimSha256,'trimmed executed expression; raw comparison retained separately');
bindings.at(-1).actualTrimmed=sha(read(bindings.at(-1).path).toString().trim());bindings.at(-1).matched=bindings.at(-1).actualTrimmed===pointer.producerTrimSha256;
bind('qa/rc19-actual-account/pointer-only-safe-record.json',pointer.recordSha256,'exact safe record');
const negative=json('qa/rc20-image-owner-dispatch/post-review-negative-results.json');bind('qa/rc20-image-owner-dispatch/post-review-controls.cjs',negative.driverSha256,'exact malformed control producer');
const q0=json('qa/q0-provider-product/native-results-manifest.json');
for(const p of ['qa/q0-provider-product/native-audit.cjs','qa/q0-provider-product/native-results.json','qa/q0-provider-product/native-results-node.json','tests/q0-proxy.test.js'])bind(p,q0.files[p],'Q0 saved manifest binding');
// The maintained Q0 fixture changed for later controller-capability integration.
// Bind the actual historical producer from Git; retain the mismatch and delta.
const q0test=bindings.find(b=>b.path==='tests/q0-proxy.test.js');
q0test.currentProducerMatches=q0test.matched;q0test.historicalGitRef='067bcb9';
q0test.historicalGitSha256=sha(git('show','067bcb9:tests/q0-proxy.test.js'));
q0test.matched=q0test.historicalGitSha256===q0test.expected;
q0test.delta='ee0ac84 adds fixture video/client matchAll/type/url and changes cold controller claim to wait for correlated capability. Source-change test assertions are preserved; no current cold-controller proof inferred from old output.';
const q2manifest=json('qa/q2-general-product-integration/evidence-manifest.json');
for(const p of ['qa/q2-general-product-integration/native.cjs','qa/q2-general-product-integration/native.mjs','qa/q2-general-product-integration/native-results.json']){const e=q2manifest.files.find(e=>e.path===p);if(!e)throw Error('Q2 missing manifest '+p);bind(p,e.sha256,'Q2 saved manifest binding');}
const baseline=json(baselinePath);const q1run=baseline.runs.find(r=>r.raw==='selected-6.tap');bind('qa/candidate-rc13-qualification/selected-6.tap',q1run.sha256,'exact Q1 content-change proof output');
for(const p of ['tests/account-state.test.js','tests/mutations.test.js'])if(baseline.sources[p])bind(p,baseline.sources[p].executedSHA256,'dated AU04 test producer; unchanged producer is not whole app equivalence');
const currentApp=norm(read('app.js'));
function span(text,start,end){const a=text.indexOf(start);if(a<0)throw Error('Missing span '+start);const b=text.indexOf(end,a+start.length);if(b<0)throw Error('Missing end '+end);return text.slice(a,b);}
const comparisons=[];
function compare(ref,p,start,end,scope){const old=norm(git('show',ref+':'+p)),now=norm(read(p)),a=span(old,start,end),b=span(now,start,end);comparisons.push({scope,reference:ref,path:p,start,end,oldSha256:sha(a),currentSha256:sha(b),same:a===b,currentLine:line(p,start).line});}
compare('df1f94a','app.js','function resetControlsTimer(', 'function setupPlayerChrome(', 'UI02 timer/reveal owner');
compare('df1f94a','app.js',"  el.playerModal.addEventListener('pointermove'", "  el.playerModal.addEventListener('pointerdown'", 'UI02 move/leave route');
compare('eb8b6a5','app.js',"  el.playerModal.addEventListener('click'", "  el.playerModal.addEventListener('focusin'", 'UI05 pointer-button release/focus owner');
compare('eb8b6a5','app.js','function playerHasKeyboardFocus(', 'function setPlayerChromeVisible(', 'UI05 modality/native keyboard owner');
compare('eb8b6a5','app.js',"    if (event.key === ' ' || key === 'k')", "    if (key === 'm')", 'UI05 global Space playback branch');
compare('eb8b6a5','app.js','    if (index < 0 || (!event.shiftKey', "  window.addEventListener('blur'", 'UI05 normal Tab boundary/focus branch');
compare('e57d7b5','app.js','function clearDrivePreviewTimers(', 'function handleDrivePreviewLoad(', 'UI04 explicit preview/fallback owner');
compare('e57d7b5','app.js','function openSelectedInDrive(', 'function ', 'UI04 explicit external action');
compare('892722c','app.js','function sniffOriginalImageType(', 'async function tryOriginalTsPlayback(', 'FM09 raster admission and verified image ownership');
compare('067bcb9','app.js',"  if (classifyMediaProxyFailure(data) === 'source-pin')", '  if (isDriveSecurityRestriction(data)', 'TR10 Q0 terminal safe-recovery branch');
for(const p of ['media/revision-pin.js','media/drive-source.mjs','media/general-source.mjs']){
 const ref=p==='media/revision-pin.js'?'067bcb9':'ee0ac84';const a=norm(git('show',ref+':'+p)),b=norm(read(p));comparisons.push({scope:'TR10 source identity/cache/read ownership',reference:ref,path:p,oldSha256:sha(a),currentSha256:sha(b),same:a===b});
}
const nativeUI=json('qa/rc15-player-ui-qualification/results.json'),q2=json('qa/q2-general-product-integration/native-results.json'),identity=q2.results.find(r=>r.kind==='identityChangedOnSeek');
const corrupt=q2.results.find(r=>r.name==='worker-corrupt');
const assertions={original69Preserved:baseline.rows.length===69,uiFourViewports:ui.rows.length===4&&ui.rows.every(r=>r.inputAssertions==='passed'),pointerFiniteClause:pointer.passed&&pointer.allTrusted&&pointer.playPauseSeekClickKeyEvents===0&&pointer.finalHidden&&pointer.positionUnchanged,malformedAllPassed:negative.passed&&negative.results.length===3&&negative.results.every(r=>r.passed&&r.closed.cleanup.settled&&r.errors.length===0&&r.presentation.attempt==='failed'&&!r.presentation.viewed&&!r.presentation.iframe),nativeUISixClosed:nativeUI.passed&&nativeUI.results.length===6&&nativeUI.results.every(r=>r.errorDismiss.closed&&r.errorDismiss.cleanup.settled&&r.errorDismiss.selected===null),corruptClassifiedAndClosed:corrupt.passed&&corrupt.appends===0&&corrupt.terminal.error.message==='AUDIO_DECODE_FAILED'&&corrupt.terminal.error.audioMetrics.opened===1&&corrupt.terminal.error.audioMetrics.closed===1&&corrupt.cleanup.settled,q2SourceChanged:identity.passed&&identity.opens===2&&identity.aborts===2&&identity.cleanup.settled,allBoundProducerChecks:bindings.every(b=>b.matched)};
const pointers={
 q0:line('tests/q0-proxy.test.js','full-original recovery uses retained revision URI'),q0Terminal:line('tests/q0-proxy.test.js','actual application source-pin classification'),q1:line('tests/q1-source.test.mjs','content changes and permission loss'),q1Discard:line('tests/q1-source.test.mjs','postflight drift'),q2:line('qa/q2-general-product-integration/native.mjs','identityChangedOnSeek'),adapter:line('app.js','  const stopFailure = code => {'),malformed:line('qa/rc20-image-owner-dispatch/post-review-negative-results.json','"name": "html"'),pointer:line('qa/rc19-actual-account/pointer-only-summary.json','"hiddenAfterCenterMs"'),keyboard:line('qa/player-input-quality-audit.cjs','native button Space runs once'),clickSpace:line('qa/player-input-quality-audit.cjs',"await page.locator('#ctrlPlayPause').click();await page.keyboard.press('Space')"),errorClose:line('qa/rc15-player-ui-qualification/qualification.cjs','result.errorDismiss='),external:line('app.js','function openSelectedInDrive('),account:line('tests/account-state.test.js','account switch and request abort'),mutationAccount:line('tests/mutations.test.js','account switch after submission')};
const rows=[
 {id:'QA-TR-10',clauses:[{clause:'cache 혼합 금지',assessment:'saved controlled adopted-route proof retained',sources:[pointers.q0,pointers.q1,pointers.q1Discard,pointers.q2]},{clause:'변경 복구',assessment:'Q0 continues retained revision A including full-original recovery; unavailable revision produces explicit terminal source-pin. Q1 fails before/discards changed bytes without replacing baseline; Q2 changed seek aborts both owners and settles. Current exact controlled app error adapter3/3 retires the current Q1/Q2 owner and shows terminal explicit recovery without automatic retry; stale errors do nothing. These are safe recovery modes, not automatic adoption of latest.',sources:[pointers.q0,pointers.q0Terminal,pointers.q2,pointers.adapter]}],remainingCriticalUnknowns:[],wholeRowPromotion:false,scope:'Adopted Q0/native/full-original/Q1/Q2 controlled source-change ledger. Successful newest-version playback after user reopen is not inferred or added to the original no-mix/safe-recovery criterion.'},
 {id:'QA-FM-09',clauses:[{clause:'원인 분류',assessment:'HTML/JSON/truncated PNG native actual-app controls reach failed state; corrupt EAC3 is separately bounded with zero append and decoder close.',sources:[pointers.malformed]},{clause:'전체 앱 오류/무한 작업 없음',assessment:'three malformed native controls have empty page-error sets, no image/viewed/iframe, bounded failed state and settled close; saved native corrupt EAC3 zero append/opened=closed.',sources:[pointers.malformed]}],remainingCriticalUnknowns:[],wholeRowPromotion:false,scope:'Controlled malformed-source acceptance only. Real-corpus coverage is FM01/G5 and cannot be inferred. Original FM09 does not require deliberate real private media corruption.'},
 {id:'QA-UI-02',clauses:[{clause:'중앙 hidden, 하단 reveal, 이탈 후 hide',assessment:'Saved trusted actual Chrome move-only record observes hidden→revealed→hidden in331.7ms, zero click/key/play/pause/seek and unchanged owner/position. Timer/move/leave implementation compared with exact rc19.',sources:[pointers.pointer]}],remainingCriticalUnknowns:[],wholeRowPromotion:false,scope:'Finite PC clause satisfied; no new Android clause added to this PC row.'},
 {id:'QA-UI-04',clauses:[{clause:'닫을 수 없는 별도 아일랜드 없음',assessment:'Saved native6/6 exhausted-original presentation injection: one visible recovery, no separate iframe/source, trusted close button clears selection and settles. Preview actions share chrome owner in saved2/2 UI fixture; explicit external button uses user-invoked noopener/noreferrer browser action.',sources:[pointers.errorClose,pointers.external]}],remainingCriticalUnknowns:[],wholeRowPromotion:false,scope:'Saved finite owner/dismissibility proof plus current source inspection. Actual exhausted network induction/physical external-action matrix is not an extra clause in original1763.'},
 {id:'QA-UI-05',clauses:[{clause:'버튼 click 후 Space → playback, 중복 없음',assessment:'Trusted desktop click pause once then Space play once; mobile-sized rotate stays once while Space pauses once.',sources:[pointers.clickSpace]},{clause:'Tab button Space → native button 동작, 중복 없음',assessment:'Trusted Tab reveals native controls, focused native button Space executes exactly once; four saved viewports. No mock DOM keyboard event is relabeled trusted.',sources:[pointers.keyboard]}],remainingCriticalUnknowns:[],wholeRowPromotion:false,scope:'Finite trusted browser keyboard clauses satisfied; G5 current device-wide focus remains separately owned.'},
 {id:'QA-AU-04',clauses:[{clause:'이전 파일·쓰기·state 격리',assessment:'Retain original passed virtual-account branch: catalog/old owner completion cannot dispatch/install old state; submitted mutation remains with origin account and cannot be read/replayed by new account.',sources:[pointers.account,pointers.mutationAccount]}],remainingCriticalUnknowns:[],wholeRowPromotion:false,scope:'Original1730 explicitly 실제/가상. Real other-account selection is optional branch, not an added requirement.'}
].map(r=>({...r,original:originals.find(o=>o.id===r.id)}));
assertions.currentControlledAdapter=discriminator.passed&&discriminator.rows.length===3&&discriminator.rows.every(r=>r.passed)&&discriminator.dispatcherNonCodecElseVerified;
const report={schema:'drive-original.rc27-saved-contract-reconciliation/1',generatedUtc:new Date().toISOString(),gitHead:git('rev-parse','HEAD').toString().trim(),branch:git('branch','--show-current').toString().trim(),currentRuntime:Object.fromEntries(['app.js','sw.js','index.html','styles.css','version.json'].map(p=>[p,sha(read(p))])),execution:'File/JSON/hash/Git source inspection plus one controlled VM adapter discriminator3/3. Root owns current665 broad test proof and account/browser/device evidence; no broad rerun claimed.',original69Count:69,baselineStatusCounts:plan.baseline.counts,wholeRowPromotions:0,rows,pointers,evidence,bindings,implementationComparisons:comparisons,assertions,counterevidence:['rc20 initial post-review aggregate=false was a retained QA original-mode assertion failure; final negative controls are distinct passing record.','Native Q2 noncooperative cleanup scenario remains GENERAL_CLEANUP_UNCONFIRMED with settled=false; this is a tested safe refusal, not successful cleanup.','Prior UI02 overlay required pointer-only leave observation; rc19 later supplies it.','Prior overlays added actual-corruption/full-device/exhausted-network requirements beyond these finite original rows; those stay broader corpus/G5 work, not silent changes to original acceptance.'],limits:['No real-account/device/whole-format/p95/production promotion.','Whole app/source equality is not claimed. Exact scoped comparisons are evidence; changed enclosing code cannot be blanket-promoted.','Immutable spec/baseline/prior evidence untouched. Only this new leaf is task-owned.']};
fs.writeFileSync(path.join(__dirname,'review.json'),JSON.stringify(report,null,2)+'\n');
const files=[leaf+'/reconcile.cjs',leaf+'/review.json',leaf+'/source-change-discriminator.cjs',leaf+'/source-change-discriminator.json'];fs.writeFileSync(path.join(__dirname,'staging-manifest.json'),JSON.stringify({scope:'Exact new leaf files only; no staging performed. Include staging-manifest.json itself as the fifth explicit path; manifest does not self-hash.',files:files.map(p=>({path:p,sha256:sha(read(p))})),manifestPath:leaf+'/staging-manifest.json'},null,2)+'\n');
console.log(JSON.stringify({rows:rows.map(r=>({id:r.id,unknowns:r.remainingCriticalUnknowns.length})),assertions,changedComparisons:comparisons.filter(c=>!c.same).map(c=>c.scope),bindingsFailed:bindings.filter(b=>!b.matched).map(b=>b.path)}));
