import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {binding} from './fixture.mjs';
const source=await readFile(new URL('runner.function.js',import.meta.url),'utf8'),create=vm.runInNewContext('('+source+')',{Date,setTimeout,clearTimeout,JSON,Error,Number,Boolean,Set,Object,Array});
const opts={maxJobs:1,deadlineMs:10000,stopBeforeAt:10000};
function summary({failed=0,pending=0,retry=0,fatal=null,fileCode='POSTFLIGHT_FAILED'}={}){
 const files=[{complete:true,failure:null,identityPreflight:true,identityPostflight:true,kind:'iso-bmff',mediaRequests:1,mediaBytes:940,id:'PRIVATE_ID',name:'PRIVATE_NAME'}];if(failed)files.push({complete:false,failure:fileCode,identityPreflight:true,identityPostflight:false,kind:'iso-bmff',mediaRequests:1,mediaBytes:940});
 return {complete:fatal===null,catalogStable:fatal===null,released:true,failure:fatal,metadataRequests:20,metadataBytes:1234,mediaRequests:files.length,mediaBytes:files.length*940,writeRequests:0,files,coverage:{denominator:1+failed+pending,classified:1,failed,ineligible:0,unattempted:pending,queuedFresh:pending,queuedRetries:retry,queuedTotal:pending+retry,retryPending:retry,retryExhausted:failed-retry,maxFreshAttemptsPerFile:2,ledgerEntries:1+failed,ledgerLimit:8192,freshPerFileChecked:1,allEligiblePrefixesValidated:failed===0&&pending===0,PRIVATE_KEY:123,kindCounts:{'PRIVATE_ID':321,'iso-bmff':1}},metadataDiagnostic:{lastFailure:{requestMs:10000,receivedBytes:0,PRIVATE_KEY:123,url:'PRIVATE_URL',code:'POSTFLIGHT_FAILED'}},privateToken:'PRIVATE_TOKEN'};
}
function fixture(rows,pending=false){
 let time=0,next=0,changed=false,cleared=0,renewed=0;const timers=new Map(),calls=[],handles=new Set(),controller={state:'activated'},proof={get:()=>({...binding,controller:changed?{state:'activated'}:controller})};
 const context=JSON.stringify({accountKey:'PRIVATE_ACCOUNT',generation:1,rootId:'PRIVATE_ROOT',priorityFileId:'PRIVATE_FILE'});
 const factory=(ctx,p,prior,options)=>{assert.equal(ctx,context);assert.equal(p,proof);if(prior)assert(handles.has(prior));const epoch=renewed,row=rows[Math.min(calls.length,rows.length-1)],handle={};handles.add(handle);calls.push({options,prior,epoch});let cancel=false;return {cancel(){cancel=true;},continuity:()=>row.complete?handle:null,poll:()=>pending&&!cancel&&epoch===renewed?{done:false}:{done:true,summary:cancel?summary({fatal:'CANCELLED'}):epoch!==renewed?summary({fatal:'OWNER_CHANGED'}):row}};};
 factory.clearContinuity=h=>{assert(handles.has(h));handles.delete(h);cleared++;};const deps={now:()=>time,schedule:(f,ms)=>{timers.set(++next,{f,at:time+ms});return next;},unschedule:id=>timers.delete(id)};
 const runner=create(factory,context,proof,binding,deps),tick=(ms=100)=>{time+=ms;for(const[id,t]of [...timers].filter(([,x])=>x.at<=time)){timers.delete(id);t.f();}};
 return {runner,tick,calls,timers,change:()=>{changed=true;},renew:()=>{renewed++;},cleared:()=>cleared};
}
test('partial success retains only opaque new capsule and explicit root start advances after idle renewal',()=>{
 const f=fixture([summary({failed:1,retry:1,pending:10}),summary({pending:10})]);assert.equal(f.calls.length,0);f.runner.start(opts);f.tick();let r=f.runner.read();assert.equal(r.stopped,null);assert.equal(r.jobs[0].summary.files[1].complete,false);assert.equal(r.jobs[0].summary.coverage.failed,1);assert.equal(r.jobs[0].summary.coverage.queuedTotal,11);assert.equal(r.burst.done,true);assert.equal(r.wholeCorpusComplete,false);assert(!JSON.stringify(r).includes('PRIVATE_'));f.renew();f.runner.start({...opts,stopBeforeAt:12000});f.tick();assert.equal(f.calls.length,2);assert(f.calls[1].prior);assert.equal(f.calls[1].epoch,1);assert.equal(f.calls[1].options.phase,'representatives');assert.equal(f.cleared(),1);f.runner.cleanup();assert.equal(f.cleared(),2);assert.equal(f.runner.read().disposed,true);
});
test('exhausted files stop queue without false all-eligible success and cannot restart or automatically retry',()=>{
 const f=fixture([summary({failed:1}),summary({failed:1})]);f.runner.start({maxJobs:8,deadlineMs:10000,stopBeforeAt:10000});f.tick();f.tick();const r=f.runner.read();assert.equal(f.calls.length,2);assert.equal(f.calls[1].options.phase,'videos');assert.equal(r.progressExhausted,true);assert.equal(r.burst.done,true);assert.equal(r.burst.eligibleVideoPrefixesComplete,false);assert.equal(r.jobs[1].summary.coverage.retryExhausted,1);assert.equal(r.jobs[1].summary.coverage.queuedTotal,0);assert.equal(r.stopped,null);assert.throws(()=>f.runner.start(opts),/RUNNER_NOT_RESTARTABLE/);f.runner.cleanup();assert.equal(f.runner.read().disposed,true);
});
test('all-eligible success requires failed0 and unattempted0; complete registry swaps before release cleanup',()=>{
 const f=fixture([summary(),summary()]);f.runner.start({maxJobs:8,deadlineMs:10000,stopBeforeAt:10000});f.tick();f.tick();const r=f.runner.read();assert.equal(r.burst.eligibleVideoPrefixesComplete,true);assert.equal(r.progressExhausted,true);assert.equal(r.wholeCorpusComplete,false);assert.equal(f.calls.length,2);assert.equal(f.cleared(),1);f.runner.cleanup();assert.equal(f.cleared(),2);assert.equal(f.timers.size,0);
});
test('fatal job, catalog, cleanup, current owner and source failures stop before later jobs and reject restart',()=>{
 for(const code of ['OWNER_CHANGED','CATALOG_DRIFT','CLEANUP_FAILED','CLEANUP_TIMEOUT','METADATA_LIMIT','IDENTITY_MISMATCH']){const f=fixture([summary({fatal:code})]);f.runner.start({maxJobs:8,deadlineMs:10000,stopBeforeAt:10000});f.tick();assert.equal(f.runner.read().stopped,'FATAL_FACTORY_OR_CONTRACT_FAILURE');assert.equal(f.calls.length,1);assert.throws(()=>f.runner.start(opts),/RUNNER_NOT_RESTARTABLE/);f.runner.cleanup();assert.equal(f.runner.read().disposed,true);}
 const f=fixture([summary()],true);f.runner.start(opts);f.change();f.tick();assert.equal(f.runner.read().stopped,'SOURCE_OWNER_CHANGED');assert.equal(f.calls.length,1);f.runner.cleanup();const g=fixture([summary()],true);g.runner.start(opts);g.renew();g.tick();assert.equal(g.runner.read().stopped,'FATAL_FACTORY_OR_CONTRACT_FAILURE');g.runner.cleanup();
});
test('malformed dispositions, budgets, failure classes or strong-success flags never advance continuity',()=>{
 for(const mutate of [r=>r.coverage.failed++,r=>r.coverage.queuedTotal++,r=>r.coverage.ledgerEntries=8193,r=>r.coverage.maxFreshAttemptsPerFile=3,r=>r.files[0].identityPostflight=false,r=>r.metadataRequests=513,r=>r.metadataBytes=67108865,r=>r.mediaRequests=65,r=>r.writeRequests=1,r=>r.files[1].failure='IDENTITY_MISMATCH',r=>r.files[1].failure='POSTFLIGHT_DRIFT']){const raw=summary({failed:1,retry:1});mutate(raw);const f=fixture([raw]);f.runner.start(opts);f.tick();assert.equal(f.runner.read().stopped,'FATAL_FACTORY_OR_CONTRACT_FAILURE');assert.equal(f.cleared(),0);f.runner.cleanup();assert.equal(f.cleared(),0);}
});
test('finite8 job and80minute explicit burst caps, fresh cutoff, cancel drain and cleanup are preserved',()=>{
 const f=fixture([summary({pending:1})]);for(const o of [{...opts,maxJobs:9},{...opts,deadlineMs:4800001},{...opts,stopBeforeAt:0},{...opts,extra:1}])assert.throws(()=>f.runner.start(o),/BURST_OPTIONS/);assert.equal(f.calls.length,0);f.runner.start({maxJobs:8,deadlineMs:10000,stopBeforeAt:10000});for(let i=0;i<8;i++)f.tick();assert.equal(f.calls.length,8);assert.equal(f.runner.read().burst.done,true);assert.equal(f.runner.read().stopped,null);f.runner.cleanup();
 const g=fixture([summary()],true);g.runner.start({...opts,stopBeforeAt:150});g.tick(200);assert.equal(g.runner.read().stopped,'BURST_DEADLINE');assert.equal(g.runner.read().active,false);g.runner.cleanup();const h=fixture([summary()],true);h.runner.start(opts);h.runner.cleanup();assert.equal(h.runner.read().disposed,false);h.tick();assert.equal(h.runner.read().disposed,true);assert.equal(h.timers.size,0);assert.equal(h.calls.length,1);assert(!JSON.stringify(h.runner.read()).includes('PRIVATE_'));
});
