'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {frameReceipt,classifyFrameUrl}=require('./frame-owner-attempt3.cjs'),{gate,SOURCE,VERSION}=require('./gate-attempt3.cjs');
const origin='https://fixture.example';
const dormant={versionExpected:true,domFrameCount:1,knownPreviewOnly:true,previewHidden:true,previewSrcAbsent:true,previewSrcAboutBlank:false,previewSessionAbsent:true,previewInactive:true};
const tree=url=>({frame:{id:'main'},childFrames:[{frame:{id:'child',url}}]});
const owner={pageType:true,taskCreated:true,exactTarget:true,sameBrowserContext:true,mainFrame:true,mainFrameStable:true,...frameReceipt(tree('about:blank'),dormant,origin)};
function mock(changes={}){const calls=[];return{calls,a:{now:Date.now,bootstrap:async()=>{},toolCapabilities:async()=>({newPage:true,closePage:true,listPages:true}),pinOriginal:async()=>({version:VERSION,accountPresent:true,existingValidToken:true,playerClosed:true,authOnline:true,loaded:true}),createOwnedPage:async()=>{},attachOwnedPage:async()=>{},ownerReceipt:async()=>owner,send:async m=>calls.push(m),reloadOwned:async()=>owner,sourceAndAccountProof:async()=>({sourceCommit:SOURCE,version:VERSION,publicMatched:3,cacheMatched:40,rootAliasMatched:true,sameAccount:true,existingValidToken:true,controllerActivated:true,noGoogleIframe:true}),normalReplay:async()=>({normalNativeInput:true,noGoogleIframe:true,existingValidToken:true,sameAccount:true,exactSource31:true,originalBytePathQualified:true,ownedFrameAfterReplay:owner,routes:[{route:'q1',presentedFrames:2,progressed:true,seekTargetFrame:true,closedSettled:true,exactPageMainFrame:true,noIndependentCookieDependentMediaTarget:true}]}),closeOwnedPlayer:async()=>true,detachOwnedSession:async()=>{},closeOwnedPage:async()=>{},originalIntact:async()=>true,disconnect:async()=>{},...changes}};}
test('fixed31 declares exactly one dormant src-less hidden preview; reset uses aboutblank',()=>{const root=path.resolve(__dirname,'../..'),git=f=>execFileSync('git',['show',SOURCE+':'+f],{cwd:root,maxBuffer:4*1024**2}).toString(),index=git('index.html'),app=git('app.js');const frames=index.match(/<iframe\b[^>]*>/g);assert.equal(frames.length,1);assert(frames[0].includes('id="drivePreview"'));assert(frames[0].includes(' hidden'));assert(!/\bsrc=/.test(frames[0]));const reset=app.slice(app.indexOf('function clearDrivePreview()'),app.indexOf('function showDrivePreview'));assert(reset.includes("el.drivePreview.src = 'about:blank'"));assert(reset.includes('el.drivePreview.hidden = true'));assert(reset.includes('delete el.drivePreview.dataset.mediaSession'));});
test('known exactlyone dormant inherited blank preview admitted, no worker absence claim',()=>{const r=frameReceipt(tree('about:blank'),dormant,origin);assert.equal(r.frameScopeAdmitted,true);assert.equal(r.onlyKnownDormantPreview,true);assert.equal(r.childFrameCounts.aboutBlank,1);assert.equal(r.independentWorkerOverrideClaimed,false);assert(!JSON.stringify(r).includes('"child"'));});
test('crossGoogle/crossother/unknown/sameoriginnonblank classified and rejected with no raw URL export',()=>{for(const [url,kind]of [['https://drive.google.com/private-id','crossGoogle'],['https://another.example/private-token','crossOther'],['data:text/plain,private','unknown'],['https://fixture.example/frame','sameOrigin']]){assert.equal(classifyFrameUrl(url,origin),kind);const r=frameReceipt(tree(url),dormant,origin);assert.equal(r.childFrameCounts[kind],1);assert.equal(r.frameScopeAdmitted,false);assert(!JSON.stringify(r).includes('private'));}});
test('visible/session/unknown-source/multiple/nested blank frames never treated dormant',()=>{for(const d of [{...dormant,previewHidden:false},{...dormant,previewSessionAbsent:false},{...dormant,versionExpected:false},{...dormant,domFrameCount:2}])assert.equal(frameReceipt(tree('about:blank'),d,origin).frameScopeAdmitted,false);const t=tree('about:blank');t.childFrames[0].childFrames=[{frame:{url:'about:blank'}}];assert.equal(frameReceipt(t,dormant,origin).frameScopeAdmitted,false);});
test('no-frame DOM+tree case admitted; missing DOM/tree correspondence rejected',()=>{assert.equal(frameReceipt({frame:{}},{domFrameCount:0},origin).frameScopeAdmitted,true);assert.equal(frameReceipt({frame:{}},dormant,origin).frameScopeAdmitted,false);});
test('rejected owner receipt exists before assertion and no cookie command is issued',async()=>{const bad={...owner,frameScopeAdmitted:false,childFrameCounts:{total:1,crossGoogle:1}};const m=mock({ownerReceipt:async()=>bad}),r=await gate(m.a);assert.equal(r.failure,'FRAME_OWNER');assert.equal(r.failureStage,'owned-frame-receipt');assert.equal(r.receipts.find(s=>s.name==='dedicated-page-frame-owner').childFrameCounts.crossGoogle,1);assert.equal(m.calls.length,0);});
test('same known blank class admitted before and after reload/replay with mainframe stability',async()=>{const m=mock(),r=await gate(m.a);assert.equal(r.completed,true);assert.deepEqual(m.calls,['Network.enable','Network.setCookieControls']);assert(r.receipts.some(s=>s.name==='frame-owner-after-ordinary-reload'));assert(r.receipts.some(s=>s.name==='frame-owner-after-normal-native-replay'));});
test('changed mainframe after reload retains receipt and stops replay',async()=>{let replay=false;const m=mock({reloadOwned:async()=>({...owner,mainFrameStable:false}),normalReplay:async()=>{replay=true;}}),r=await gate(m.a);assert.equal(r.failure,'RELOAD_FRAME_OWNER');assert.equal(replay,false);assert.equal(r.receipts.find(s=>s.name==='frame-owner-after-ordinary-reload').mainFrameStable,false);});
test('v1/v2 frozen producers and source callback unchanged',()=>{for(const manifest of ['preparation-freeze.json','attempt2-preparation-freeze.json']){const p=JSON.parse(fs.readFileSync(path.join(__dirname,manifest)));for(const [file,sha]of Object.entries(p.files)){if(!file.endsWith('.cjs'))continue;assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,file))).digest('hex'),sha);}}const p=require('./attempt2-preparation-freeze.json');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'actual-android-cookie-gate-result.json'))).digest('hex'),p.preservedActualAttempt1Sha256);});
