'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {gate,VERSION,SOURCE}=require('./gate-attempt2.cjs');
const adapter=require('./android-adapter-attempt2.cjs');
const baseline={version:VERSION,accountPresent:true,existingValidToken:true,playerClosed:true,authOnline:true,loaded:true};
function mock(changes={}){const calls=[];return{calls,a:{now:Date.now,bootstrap:async()=>{},toolCapabilities:async()=>({newPage:true,closePage:true,listPages:true}),pinOriginal:async()=>baseline,createOwnedPage:async()=>calls.push('new-page'),attachOwnedPage:async()=>{},ownerReceipt:async()=>({pageType:true,taskCreated:true,exactTarget:true,sameBrowserContext:true,mainFrame:true,noIndependentFrames:true}),send:async m=>calls.push(m),reloadOwned:async()=>{},sourceAndAccountProof:async()=>({sourceCommit:SOURCE,version:VERSION,publicMatched:3,cacheMatched:40,rootAliasMatched:true,sameAccount:true,existingValidToken:true,controllerActivated:true,noGoogleIframe:true}),normalReplay:async()=>({normalNativeInput:true,noGoogleIframe:true,existingValidToken:true,sameAccount:true,exactSource31:true,originalBytePathQualified:true,routes:[{route:'q1',presentedFrames:2,progressed:true,seekTargetFrame:true,closedSettled:true,exactPageMainFrame:true,noIndependentCookieDependentMediaTarget:true}]}),closeOwnedPlayer:async()=>true,detachOwnedSession:async()=>{},closeOwnedPage:async()=>{},originalIntact:async()=>true,disconnect:async()=>{},...changes}};}
test('installed Playwright differentiates string expressions from function invocation; fixed baseline evaluates object',async()=>{
 const source=fs.readFileSync(path.resolve(__dirname,'../node_modules/playwright-core/lib/coreBundle.js'),'utf8');
 assert(source.includes('isFunction: typeof pageFunction === "function"'));
 assert(source.includes('if (isFunction === false) {\\n      result = result;'));
 const env={APP_VERSION:VERSION,state:{authAccountKey:'fixture',selected:null,authStatus:'online',accountStateLoaded:true},el:{playerSheet:{hidden:true}},hasUsableToken:()=>true};
 const old=vm.runInNewContext('() => '+adapter.PRIVACY_SAFE_EXPRESSION,env);assert.equal(typeof old,'function');
 const literal=[...source.matchAll(/source3 = ('(?:\\.|[^'\\])*');/g)].find(m=>m[1].includes('// packages/injected/src/utilityScript.ts'))?.[1];assert(literal);
 const injected=vm.runInNewContext(literal),box={module:{exports:{}}};vm.runInNewContext(injected,box);
 const utility=new box.UtilityScript({eval:expression=>vm.runInNewContext(expression,env)},false);
 const oldSerialized=utility.evaluate(false,true,'() => '+adapter.PRIVACY_SAFE_EXPRESSION,0);assert.equal(oldSerialized,undefined);
 const fixedSerialized=utility.evaluate(false,true,adapter.PRIVACY_SAFE_EXPRESSION,0);assert(fixedSerialized.o.some(r=>r.k==='accountPresent'&&r.v===true));
 const result=await adapter.evaluateOriginalBaseline({evaluate:async expression=>vm.runInNewContext(expression,env)});
 assert.equal(result.version,VERSION);assert.equal(result.existingValidToken,true);assert.equal(result.playerClosed,true);
});
test('attempt2 guards undefined baseline, retains stage/primitives, creates no tab',async()=>{const m=mock({pinOriginal:async()=>undefined});const r=await gate(m.a);assert.equal(r.completed,false);assert.equal(r.failureStage,'pin-original');assert.equal(r.failure,'ORIGINAL_PREFLIGHT');const receipt=r.receipts.find(s=>s.name==='original-baseline-primitive-admission');assert.equal(receipt.objectReturned,false);assert.equal(receipt.valueReturned,false);assert.equal(m.calls.length,0);});
test('unsafe underlying error message is never exported; class and stage survive cleanup',async()=>{const m=mock({pinOriginal:async()=>{throw TypeError('PRIVATE_URL_PRIVATE_ID_PRIVATE_TOKEN');}});const r=await gate(m.a);assert.equal(r.failureStage,'pin-original');assert.equal(r.safeErrorClass,'TypeError');assert.equal(r.failure,'STAGE_FAILED');assert(!JSON.stringify(r).includes('PRIVATE_'));assert.equal(r.cleanup.originalTabAccountIntact,true);assert.equal(r.cleanup.ownedConnectionsRemoved,true);});
test('fixed primitive baseline admits page and sole restriction route',async()=>{const m=mock(),r=await gate(m.a);assert.equal(r.completed,true);assert.deepEqual(m.calls,['new-page','Network.enable','Network.setCookieControls']);});
test('raw class names excluded and unsupported command precisely staged',async()=>{const e={name:'PRIVATE_CLASS',message:'PRIVATE_TOKEN'};const m=mock({send:async method=>{if(method==='Network.setCookieControls')throw e;},isUnsupportedCookieCommand:err=>err===e});const r=await gate(m.a);assert.equal(r.safeErrorClass,'OtherError');assert.equal(r.failureStage,'cookie-command');assert.equal(r.failure,'INSTALLED_COOKIE_COMMAND_UNSUPPORTED');assert(!JSON.stringify(r).includes('PRIVATE_'));});
test('frozen v1 and original replay report preserved byte-for-byte',()=>{const prior=require('./preparation-freeze.json');for(const file of ['gate.cjs','android-adapter.cjs','normal-replay.cjs','root-execute.cjs'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,file))).digest('hex'),prior.files[file]);const r=JSON.parse(fs.readFileSync(path.join(__dirname,'actual-android-cookie-gate-result.json')));assert.equal(r.failure,'GATE_FAILED');assert.equal(r.receipts.length,1);});
