'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {gate,SOURCE,VERSION,PARAMS}=require('./gate.cjs');
function mock(change={}) {
 const calls=[];let clock=0;
 const a={now:()=>clock,record:()=>{},bootstrap:async()=>calls.push('bootstrap'),toolCapabilities:async()=>({newPage:true,closePage:true,listPages:true,genericCDPCommand:false}),pinOriginal:async()=>({accountPresent:true,existingValidToken:true,playerClosed:true}),createOwnedPage:async()=>calls.push('new_page'),attachOwnedPage:async()=>calls.push('attach'),ownerReceipt:async()=>({pageType:true,taskCreated:true,exactTarget:true,sameBrowserContext:true,mainFrame:true,noIndependentFrames:true}),send:async(m,p)=>calls.push([m,p]),reloadOwned:async()=>calls.push('reload'),sourceAndAccountProof:async()=>({sourceCommit:SOURCE,version:VERSION,publicMatched:3,cacheMatched:40,rootAliasMatched:true,sameAccount:true,existingValidToken:true,controllerActivated:true,noGoogleIframe:true}),normalReplay:async()=>({normalNativeInput:true,noGoogleIframe:true,existingValidToken:true,sameAccount:true,exactSource31:true,originalBytePathQualified:true,PRIVATE_TOKEN:'SHOULD_NOT_EXPORT',routes:[{route:'q1',presentedFrames:20,progressed:true,seekTargetFrame:true,closedSettled:true,exactPageMainFrame:true,noIndependentCookieDependentMediaTarget:true,url:'PRIVATE_URL'}]}),closeOwnedPlayer:async()=>{calls.push('close-player');return true;},detachOwnedSession:async()=>calls.push('detach'),closeOwnedPage:async()=>calls.push('close-tab'),originalIntact:async()=>true,disconnect:async()=>calls.push('disconnect'),...change};
 return {a,calls,advance:ms=>clock+=ms};
}
test('recognized sole restrictive command follows enable, then reload, Q1 original path; finite receipts',async()=>{const {a,calls}=mock();const r=await gate(a);assert.equal(r.completed,true);assert.deepEqual(calls.slice(3,6),[['Network.enable',{}],['Network.setCookieControls',PARAMS],'reload']);assert.deepEqual(calls.slice(-4),['close-player','detach','close-tab','disconnect']);assert(!JSON.stringify(r).includes('PRIVATE'));assert.equal(r.originalQualified,true);assert.equal(r.derivedQualified,true);});
test('unsupported runtime preserves failure, no reload/replay/fallback, and cleans exact owners',async()=>{const fail=Error('not found');const {a,calls}=mock({send:async m=>{calls.push(m);if(m.endsWith('setCookieControls'))throw fail;},isUnsupportedCookieCommand:e=>e===fail});const r=await gate(a);assert.equal(r.completed,false);assert.equal(r.failure,'INSTALLED_COOKIE_COMMAND_UNSUPPORTED');assert(!calls.includes('reload'));assert.deepEqual(calls.slice(-4),['close-player','detach','close-tab','disconnect']);});
test('wrong public source cannot admit replay',async()=>{let replay=false;const {a}=mock({sourceAndAccountProof:async()=>({sourceCommit:'old'}),normalReplay:async()=>{replay=true;}});assert.equal((await gate(a)).completed,false);assert.equal(replay,false);});
test('independent frame rejected before override',async()=>{const {a,calls}=mock({ownerReceipt:async()=>({pageType:true,taskCreated:true,exactTarget:true,sameBrowserContext:true,mainFrame:true,noIndependentFrames:false})});assert.equal((await gate(a)).completed,false);assert(!calls.some(c=>Array.isArray(c)&&c[0]==='Network.setCookieControls'));});
test('deadline stops next phase and cleans',async()=>{const m=mock();m.a.createOwnedPage=async()=>m.advance(240000);const r=await gate(m.a);assert.equal(r.failure,'BOUNDED_DEADLINE');assert(!m.calls.includes('attach'));assert(m.calls.includes('close-tab'));});
test('cleanup failure prevents success but other owners still cleaned',async()=>{const {a,calls}=mock({detachOwnedSession:async()=>{throw Error('FAIL');}});const r=await gate(a);assert.equal(r.completed,false);assert.equal(r.cleanupFailure,'OWNED_CLEANUP_UNCONFIRMED');assert(calls.includes('close-tab'));assert(calls.includes('disconnect'));});
test('attempted original path and seek clock do not qualify missing original bytes/frame',async()=>{const m=mock();const good=await m.a.normalReplay();m.a.normalReplay=async()=>({...good,originalBytePathQualified:false,routes:good.routes.map(r=>({...r,seekTargetFrame:false}))});assert.equal((await gate(m.a)).completed,false);});
test('import adapter inert and exact immutable source exported',()=>{assert.equal(typeof require('./android-adapter.cjs'),'function');assert.equal(SOURCE,'4a484e6f839d2e6c3eb83503acb08147362cb011');assert.deepEqual(Object.keys(PARAMS),['enableThirdPartyCookieRestriction']);});
