'use strict';
// Build the bounded second phase from the exact first producer; no network.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const p=path.join(__dirname,'read-settings.cjs'),raw=fs.readFileSync(p),previous=JSON.parse(fs.readFileSync(path.join(__dirname,'results.json')));
if(crypto.createHash('sha256').update(raw).digest('hex')!==previous.sourceFences.producerSHA256||previous.failure!=='OBSERVABILITY_ABSENT'||previous.endpoints.length!==3)throw Error('FIRST_PHASE_REQUIRED');
let text=raw.toString('utf8');
function replace(a,b){if(text.split(a).length!==2)throw Error('PREPARE_PATTERN_MISMATCH');text=text.replace(a,b);}
replace("['deployments','script-settings','settings'].includes(suffix)||result.endpoints.length>=4","['deployments','default-environment-metadata'].includes(suffix)||result.endpoints.length>=5");
replace("const url=new URL(`https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/drive-original-v2-candidate/${suffix}`);","const url=new URL(suffix==='default-environment-metadata'?`https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/services/drive-original-v2-candidate/environments/production`:`https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/drive-original-v2-candidate/${suffix}`);");
replace("if(fs.existsSync(privateDir))throw fail('PRIVATE_TARGET_REJECTED');fs.mkdirSync(privateDir);", "if(!fs.existsSync(privateDir))throw fail('PRIVATE_TARGET_REJECTED');");
replace("const before=active(await api('active-deployment-before','deployments','deployment-before-private.json'));result.identity.activeBeforeMatched=true;", `const previous=JSON.parse(fs.readFileSync(path.join(__dirname,'results.json')));if(previous.failure!=='OBSERVABILITY_ABSENT'||previous.endpoints.length!==3||!previous.identity.activeBeforeMatched||!previous.auth.credentialStoreUnchanged)throw fail('RETAINED_IDENTITY_REJECTED');
 result.initialPhase={producerSHA256:previous.sourceFences.producerSHA256,recordedAt:previous.recordedAt,finishedAt:previous.finishedAt,requests:3,credentialStoreUnchanged:true};result.endpoints=previous.endpoints;result.identity.activeBeforeMatched=true;
 for(const [name,index] of [['deployment-before-private.json',0],['script-settings-private.json',1],['script-version-settings-private.json',2]])if(sha(fs.readFileSync(path.join(privateDir,name)))!==previous.endpoints[index].rawPrivateSHA256)throw fail('RETAINED_IDENTITY_REJECTED');
 const before=active(JSON.parse(fs.readFileSync(path.join(privateDir,'deployment-before-private.json'))).result);`);
replace("const a=settingsOf(await api('worker-script-settings','script-settings','script-settings-private.json')),b=settingsOf(await api('worker-script-and-active-version-settings','settings','script-version-settings-private.json'));", `const rawA=JSON.parse(fs.readFileSync(path.join(privateDir,'script-settings-private.json'))).result,rawB=JSON.parse(fs.readFileSync(path.join(privateDir,'script-version-settings-private.json'))).result;
 const a=settingsOf(rawA),b=settingsOf(rawB),environment=await api('candidate-default-environment-metadata','default-environment-metadata','default-environment-private.json');
 if(!environment.script||environment.script.id!=='drive-original-v2-candidate')throw fail('CANDIDATE_SCOPE_REJECTED');const c=settingsOf(environment.script);
 result.responseShape={scriptOnlyObservabilityFieldPresent:Object.hasOwn(rawA,'observability'),scriptOnlyObservabilityExplicitNull:rawA.observability===null,combinedObservabilityFieldPresent:Object.hasOwn(rawB,'observability'),environmentObservabilityFieldPresent:Object.hasOwn(environment.script,'observability'),environmentObservabilityExplicitNull:environment.script.observability===null};`);
replace("if(!a.observabilityPresent&&!b.observabilityPresent)throw fail('OBSERVABILITY_ABSENT');for(const key of Object.keys(a))if(key!=='observabilityPresent'&&a[key]!==null&&b[key]!==null&&a[key]!==b[key])throw fail('OBSERVABILITY_CONFLICT');", "for(const key of Object.keys(a))if(key!=='observabilityPresent'){const values=[a[key],b[key],c[key]].filter(x=>x!==null);if(new Set(values).size>1)throw fail('OBSERVABILITY_CONFLICT');}");
replace("result.settings={scriptOnly:a,scriptAndActiveVersion:b,merged:Object.fromEntries(Object.keys(a).map(k=>[k,a[k]===null?b[k]:a[k]]))};", "result.settings={scriptOnly:a,scriptAndActiveVersion:b,defaultEnvironment:c,merged:Object.fromEntries(Object.keys(a).map(k=>[k,k==='observabilityPresent'?[a[k],b[k],c[k]].some(Boolean):[a[k],b[k],c[k]].find(x=>x!==null)??null]))};");
replace("result.complete=true;", "result.complete=true;result.observabilityResolved=result.settings.merged.observabilityEnabled!==null;if(!result.observabilityResolved)result.unresolvedBoundary='OFFICIAL_READBACK_EXPLICIT_NULL_OR_OMITTED';");
fs.writeFileSync(path.join(__dirname,'finish-settings.cjs'),text,{flag:'wx'});
console.log(JSON.stringify({prepared:true,networkRequests:0}));
