'use strict';
// Offline evidence/requirements review only. No tests or prior producers are run.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),leaf='qa/rc28-finite-acceptance-matrix',pin='944f00607cf05e586b1c88e2876dd796ce114e82';
const read=p=>fs.readFileSync(path.join(root,p)),j=p=>JSON.parse(read(p)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),norm=b=>b.toString('utf8').replace(/\r\n/g,'\n'),git=(...a)=>cp.execFileSync('git',a,{cwd:root,maxBuffer:16*1024*1024});
const planPath='qa/rc26-remaining-acceptance-plan/plan.json',plan=j(planPath),base=j(plan.baseline.path),savedPath='qa/rc27-saved-contract-reconciliation/review.json',saved=j(savedPath),specPath=plan.rows[0].originalSpec.path,spec=norm(read(specPath)).split('\n');
if(sha(read(plan.baseline.path))!==plan.baseline.SHA256||plan.rows.length!==69||base.rows.length!==69)throw Error('Original69 baseline drift');
const source28=j('qa/candidate-rc28-delivery/results.json'),integration=j('qa/candidate-rc28-delivery/product-integration.json'),full=j('qa/candidate-rc27-delivery/product-tests.json'),static28=j('qa/candidate-rc28-delivery/product-tests.json');
if(source28.source!==pin||source28.version!=='1.22.0-rc.28'||!source28.passed||full.counts.pass!==665||static28.counts.pass!==20)throw Error('Source28 evidence mismatch');
const pointer=(p,needle)=>{const lines=norm(read(p)).split('\n'),i=lines.findIndex(l=>l.includes(needle));if(i<0)throw Error('Pointer absent '+p+' '+needle);return {path:p,line:i+1,needle};};
const owners={
 B:[plan.baseline.path,'qa/candidate-rc27-delivery/product-tests.json','qa/candidate-rc28-delivery/product-integration.json'],
 Q:[savedPath,'qa/rc27-saved-contract-reconciliation/source-change-discriminator.json'],
 C:['qa/rc24-corpus-actual/video-cohorts-safe-summary.json','qa/rc28-corpus-content-continuity/README.md'],
 F:['qa/v2-live-format-playback-rc12/README.md','qa/v2-live-webm-rc13/README.md','qa/q2-general-product-integration/README.md','qa/rc16-image-format/README.md','qa/rc18-webp-card/README.md'],
 N:['qa/rc23-renewal-night/pc-actual-rc24-v1-result.json','qa/rc23-renewal-night/pc-post-renewal-seek-close.json','qa/rc21-android-night/101-rc24-android-revision61-natural-watch-result.json'],
 S:['qa/v2-state-normal-sync/live-rc11-results.json','qa/v2-state-normal-sync/fresh-cache-live-results.json','qa/rc21-android-night/59-rc23-state-challenge-final-native-echo-result.json'],
 M:['qa/v2-disposable-live/live-rc10-results.json','qa/v2-disposable-live/build.cjs','memory/DISPOSABLE-20260928.md'],
 U:['qa/player-input-quality/after/results.json','qa/rc15-player-ui-qualification/results.json','qa/rc21-android-night/111-rc25-native-library-longpress-result.json','qa/rc21-android-night/115-rc25-native-stable-edge-discriminator-result.json','qa/rc21-android-night/117-rc25-native-input-editing-result.json','qa/rc21-android-night/142-rc28-native-forced-orientation-settings-result.json'],
 H:['qa/rc21-hosting-night/result.json','qa/rc24-hosting-readonly/coverage.json','qa/rc21-hosting-security/synthetic-owner.json','qa/rc25-hosted-session-negatives/actual-v1-result.json','qa/rc26-hosted-session-metadata/actual-cookie-metadata.json'],
 D:['qa/candidate-rc28-delivery/results.json','qa/candidate-rc28-delivery/deployment.json','qa/candidate-rc28-delivery/deploy-candidate.cjs','qa/rc27-28-pc-update-qualification/actual-normal-update-and-cleanup.json','qa/rc28-resume-20261001/actual-force28.json','qa/rc28-resume-20261001/actual-reopen-and-cleanup.json','qa/rc28-resume-20261001/current-source-proof.json','qa/rc21-android-night/136-rc28-current-core-cache-proof-result.json','qa/rc28-user-move-closeout/manifest.json'],
 R:['qa/rc16-native-resource/README.md','qa/rc16-native-resource/summary.json','qa/rc28-performance-preparation/README.md']
};
const artifactPaths=[...new Set([planPath,specPath,'memory/DECISIONS.md',...Object.values(owners).flat(),'qa/candidate-rc28-delivery/product-tests.json','qa/rc21-hosting-security/synthetic-owner.mjs','qa/candidate-rc27-delivery/run-product-tests.cjs'])];
const hashes=artifactPaths.map(p=>({path:p,sha256:sha(read(p)),bytes:read(p).length}));
const comparisons=[];
function span(s,start,end){const a=s.indexOf(start),b=s.indexOf(end,a+start.length);if(a<0||b<0)throw Error('Span absent '+start);return s.slice(a,b);}
for(const c of saved.implementationComparisons){const text=norm(read(c.path)),current=c.start?sha(span(text,c.start,c.end)):sha(text);comparisons.push({...c,savedCurrentSha256:c.currentSha256,currentSha256:current,same:current===c.currentSha256,reuse:'saved six-row review; no old check/producer rerun'});}
function fn(s,marker){const a=s.indexOf(marker);if(a<0)throw Error('Missing function '+marker);const rest=s.slice(a+marker.length),m=/\n(?:async )?function /.exec(rest);return s.slice(a,a+marker.length+(m?m.index+1:rest.length));}
for(const [ref,marker] of [['8a2894e','function installSessionCredential('],['8a2894e','function requestSessionCredential('],['b9d8739','async function initializeAccountMediaState('],['b9d8739','async function flushAccountMediaState('],['b9d8739','function normalizeAccountMediaState(']]){const old=fn(norm(git('show',ref+':app.js')),marker),now=fn(norm(read('app.js')),marker);comparisons.push({path:'app.js',reference:ref,scope:marker,oldSha256:sha(old),currentSha256:sha(now),same:old===now,interpretation:old===now?'exact LF-normalized implementation reuse':'No blanket historical reuse: later capability guards are verified by current controlled665 source/tests; project/client mapping remains open.'});}
const mutation=j(owners.M[0]),canonical=span(norm(read('app.js')),'const DRIVE_MUTATION_PREFIX =','function summarizeDriveMutationFailures(');
comparisons.push({scope:'Actual restricted canonical mutation controller',path:'app.js',reference:mutation.identity.productCommit,expectedSha256:mutation.producers.canonicalSHA256,currentSha256:sha(canonical),same:sha(canonical)===mutation.producers.canonicalSHA256});
const auth=j('qa/rc21-hosting-security/synthetic-owner.json');
for(const [p,expected] of Object.entries(auth.sourceHashes))comparisons.push({scope:'Hosted auth owner/route implementation',path:p,expectedSha256:expected,currentSha256:sha(read(p)),same:sha(read(p))===expected});
const tests=full.before.filter(e=>e.file.startsWith('tests/')).map(e=>({path:e.file,recordedSha256:e.sha256,currentSha256:sha(read(e.file)),same:sha(read(e.file))===e.sha256,versionOnlyStatic:e.file==='tests/static.test.js'}));
const core28=static28.before.filter(e=>['app.js','sw.js','index.html','styles.css','version.json'].includes(e.file)).map(e=>({path:e.file,recordedSha256:e.sha256,currentSha256:sha(read(e.file)),same:sha(read(e.file))===e.sha256}));
const dashboard=j('qa/rc21-hosting-night/result.json'),usage=j('qa/rc24-hosting-readonly/coverage.json'),denials=j('qa/rc25-hosted-session-negatives/actual-v1-result.json'),force28=j('qa/rc28-resume-20261001/actual-force28.json');
const deploymentCode=norm(read('qa/candidate-rc28-delivery/deploy-candidate.cjs'));
const ownedPrivacyPolicy={
 source28Public52:source28.assets.length===52&&source28.assets.every(a=>a.gitEqual),
 dashboardOwnedLogsOff:dashboard.observability.logsEnabled===false&&dashboard.observability.tracesEnabled===false&&dashboard.observability.issuesEnabled===false,
 selectedActualFree:dashboard.billing.subscriptionLabel==='Workers Free'&&dashboard.billing.subscriptionStatus==='Active'&&dashboard.billing.paymentMethodPresent===false,
 actualUsage:usage.observed,
 controlledExhaustion:auth.results?.find(r=>r.name==='storage-quota-failure')||auth.cases?.find(r=>r.name==='storage-quota-failure'),
 authModulesEqual:comparisons.filter(c=>c.scope==='Hosted auth owner/route implementation').every(c=>c.same),
 actualSessionDenials:denials.extended.cases.every(c=>c.passed)&&denials.totalRejectedRequests===12,
 deploymentArgVectorIsPublicPaths:deploymentCode.includes("[path.join(worker,'node_modules/wrangler/bin/wrangler.js'),'deploy','--config','wrangler.jsonc']"),
 candidateTargetOnly:deploymentCode.includes('CANDIDATE_EXTRA_OUTPUT')&&source28.base.includes('drive-original-v2-candidate'),
 diagnosticSourcePointers:[pointer('app.js','function sanitizeMediaDiagnosticDetails('),pointer('tests/sw.test.js','opt-in media trace correlates credential, headers, first byte and body completion without secrets'),pointer('worker/index.mjs',"'google_token_invalid_client'")],
 processScope:'Exact retained candidate deployment argv and maintained checked producers only; no all-history claim.',
 policyScope:'Actual selected Free/no-card plus actual operation and unchanged bounded synthetic503 route; no provider auto-upgrade control was observed, and no paid transition is selected or performed by the candidate. This does not claim an exposed disabled auto-upgrade flag.',
 excludedUnknowns:'Historical/provider-infrastructure log retention and hidden account controls are outside a claim about owned candidate logging/output/process paths; no new runtime or destructive inspection.'
};
for(const key of ['source28Public52','dashboardOwnedLogsOff','selectedActualFree','authModulesEqual','actualSessionDenials','deploymentArgVectorIsPublicPaths','candidateTargetOnly'])if(ownedPrivacyPolicy[key]!==true)throw Error('Owned finite privacy/policy proof absent: '+key);
if(!ownedPrivacyPolicy.controlledExhaustion?.passed||ownedPrivacyPolicy.controlledExhaustion.status!==503)throw Error('Finite controlled exhaustion proof absent');
const recordBindings=[{path:'qa/candidate-rc27-delivery/product-tests.json',expected:integration.full665Reused.sha256},{path:'qa/candidate-rc28-delivery/product-tests.json',expected:integration.static20New.sha256}].map(x=>({...x,actual:sha(read(x.path)),same:sha(read(x.path))===x.expected}));
if(!core28.every(x=>x.same)||!recordBindings.every(x=>x.same)||tests.some(x=>!x.same&&!x.versionOnlyStatic))throw Error('Current fixed28 reuse fence changed');
const specific={
 'QA-TR-01':['C,F,D','Actual large normal MP4 exists historically; current fixed28 cold-media first frame/progress and bytes-before-first-frame condition still need one honest trace.','actual','U2'],
 'QA-TR-02':['B,F','Existing57,944B tail-index seed topology is tested. Missing actual-app tail-index start/seek with bounded index access; approved synthetic/sparse larger tail fixture is sufficient for this row. Actual corpus tail representative, if found, remains separate FM01.','controlled-native','U2'],
 'QA-TR-03':['F,Q,U','Saved native Q0/Q2 and actual designated TS targetframes/settled seeks cover position/video/retirement slices. Missing normal audio on the same10/50/90% selected file/version in current PC+Android integration.','actual','U2'],
 'QA-TR-12':['N','Actual natural PC/Android old-expiry continuation and PC post-renewal targetframe/close saved. Missing actual screen-background/return plus laterRange/seek under normal OS lifecycle; a forced clock, synthetic420s or viewport iframe cannot substitute.','actual','U3'],
 'QA-FM-01':['C,F','Metadata root inventory observed8,596files/2,186videos on24; only151940B prefixes classified, zero deeper metadata. Missing fixed28 complete inventory/identity mapping and feasible bounded codec/config/track probes with unknown denominator retained, then representative actual route/evidence per discovered combination. No all-file real-playback requirement.','actual','U2'],
 'QA-FM-02':['C,F','Q1 supported encoded-video/container-copy contract and selected actual TS/MKV/AVI evidence saved. Missing mapped actual codec/container representatives outside current narrow admission and current PC+Android video/audio integration. Do not demand every2186file playback.','actual','U2'],
 'QA-FM-03':['C,F','Synthetic actual-app Q2 AC3/EAC3/nativeOpus and packet/pixel/audio oracles pass; original video is copied. Actual incompatible-audio presence/config remains unknown. Missing representative actual Q2 fit/audible sound when present; no invented production audio transformation claim from420s fixture.','conditional-actual','U2'],
 'QA-FM-04':['C,F','MPEG4→VP9 feasibility is synthetic and Q3 is not integrated. Missing actual unsupported-video admission/route discriminator followed by approved browser/service implementation and native app proof when necessary. Resource lack is incomplete, never automatic N/A.','conditional-product','U2'],
 'QA-FM-05':['C,F','Source clock/SAR/color proofs and actual SAR case saved. Missing discovered multi-audio/silent/subtitle/rotation/VFR selection/timing combinations; EXP03 allows controlled fixtures for absent hard cases, actual corpus representatives remain FM01/G5.','conditional-actual-or-controlled','U2'],
 'QA-FM-06':['C,F','Actual HDR/high-depth presence unresolved. Missing bounded config/side-data evidence to establish applicability; if present prove preserve/explicit transform labels. A synthetic SDR pass does not prove HDR absence or HDR-original output.','conditional-actual','U2'],
 'QA-FM-07':['F,Q','Native synthetic GIF/animatedWebP alpha/animation and static-card repair saved. Missing actual corpus/device representative animation/alpha/timing under current media integration; no universal animation-orientation/device matrix added.','actual','U2'],
 'QA-FM-08':['F,Q','Synthetic large PNG/BMP/nativealpha/wrong-MIME original-byte owner proof saved. Missing large JPEG/actual corpus representative current-PC+Android display and wrong-MIME branch mapping; controlled wrong-MIME fixture is allowed, no private metadata mutation needed.','actual-and-controlled','U2'],
 'QA-AU-06':['B,D','Direct reader and explicit iframe policy work. Missing the specific blocked-third-party-cookie condition in a safe isolated context with valid API session and original route; no global cookie/profile change needed.','controlled-browser-condition','U4'],
 'QA-AU-10':['S,D','Full legacy/state/writer union, exact raw-body preservation and recoverable backup saved; live record explicitly projectClientBindingVerified=false. Missing current reused OAuth project/client/new-origin appData binding/reconstruction verification. Original allows preserved state OR planned migration; no unnecessary new OAuth client/grant is mandated.','actual-read-only-binding','U5'],
 'QA-ST-01':['S','Actual23 native bidirectional like/unlike withoutreload/refocus saved (reverse≤57,795ms); those original clauses do not have a mandatory20second ceiling. Missing bidirectional viewed receipt in two continuously foreground PC+Android owners.','actual-two-device','U5'],
 'QA-MU-09':['M','Actual API readbacks saved. Missing same approved disposable ID/state comparison in Drive web andG:, with timestamps distinguishing desktop-sync delay. No fresh PATCH required.','actual-read-only','U6'],
 'QA-MU-10':['M','Roundtrip restore was real, but final file remains recoverablytrashed and two createdfolders remain. Missing exact authorized pre-state/recovery inspection and final bounded restore/cleanup. No permanentDELETE, sweeping old folders or reversal of later external edits.','actual-exact-allowlist','U6'],
 'QA-UI-01':['U,Q','Saved actual-browser DOM lifecycle signals and six native actual-app cases show ordinary state changes do not reveal chrome. Missing current source/frame/presentation equivalence review beyond the unchanged chrome owner; do not rerun all pointer/keyboard tests.','local-source-review-plus-current-observation','U4'],
 'QA-UI-03':['U','Trusted native touch emulation and44pxentry saved. Missing precise physicalAndroid player-bottom reveal and outside dismiss in current integrated candidate if not in the Android owner latest evidence. Library touch111 is not this player clause.','actual-Android','U4'],
 'QA-UI-06':['U','Trusted Tab/native entry/keyboard focus proofs saved. Only iOSVoiceOver is deferred byD066; missing current-PC/Android hidden-control trap/reentry observation if not already owned by UI05 finite keyboard evidence. Do not block current candidate on VoiceOver.','mixed-current-and-deferred','U4'],
 'QA-UI-07':['U','PhysicalAndroid111 stationaryhold selection and40pxmovement cancel; native context-menu observation retained. Missing physical multi-touch/cancel and no ghost/drag/menu conflict where relevant to player/library; controlled gesture contracts already pass.','actual-Android','U4'],
 'QA-UI-08':['U','Physical115 stable edge retreat/normalhistory close proves native edge owner; prior113failure retained. Missing interior swipe cancel/reentry one-owner/no duplicate navigation. Do not repeat stableedge merely because version-only28 delivered.','actual-Android','U4'],
 'QA-UI-09':['U,D','DOM resize/appfullscreen/simulatedsafearea and actual142 OS-forced landscape library/settings/restore pass. Missing player landscape/fullscreen/nativefullscreen close/seek access or explicit actual OS unsupported limitation. A hand/sensor rotation is not an added mandatory clause; OS rotation already real.','actual-Android-and-PC','U4'],
 'QA-UI-10':['U,S,D','Quiet ring/error/library owner implementation and actual state sync/update work saved. Missing finite current normal sync/original preparation visibility/toast/badge record if not already captured by ongoing actual-device work. No broad UI redesign or repeated loading suite.','actual-finite-observation','U4'],
 'QA-LF-01':['R,Q','Saved isolatednative50cycles/150seeks,170finalizedwrappers and worker/source close pass; failed observer controls retained. Current player/retirement layers have changed since16. Missing their precise disposal equivalence/changed-layer resource discriminator; if not equivalent, run current50controlled-native cycles/counts. Original does not mandate physical50cycles, total-nativeMiB ceiling or a zero-allocation rule.','controlled-native-changed-layer','U7'],
 'QA-SE-02':['H,D,B','Public52/ZIP/private404 and source diagnostic redaction pass; actual dashboard logs/traces/issuesoff, noexports, and candidate process deployment arguments are owned public paths/config. Missing a compact exact current owned diagnostic/process-output audit if these saved sources do not cover the invoked commands; no historical-all-process/provider-infrastructure-log scavenger gate.','source-and-owned-output-review','U8'],
 'QA-SW-01':['D,B','Current corrected local one/two-client normal/force/timeout contracts plus actualPCnormal28/Androidcache40/coldoffline pass. Actualforce28/reopen remains pending at savedmanifest cutoff. Reopened integration remains partial until root-owned in-flight result; do not rerun full665/static20/delivery.','actual-current-in-flight','U1'],
 'QA-RP-01':['C,F,D','Specific designatedMP4 same actualID/version must be mapped to PC+Android current traces: firstfailure layer/Qpath/firstframe/progress/audio/seek/close. User-deferred iPhoneChrome/PWA/Safari clauses are postdeployonly. OtherTS/syntheticnative/iframe cannot substitute for the designatedMP4.','actual-specific-file-PC-Android','U2'],
 'QA-SL-01':['N,B','Actual normal renewal and stable state saved; terminal invalid_grant/revoked-session preserved-data/reconnect fixtures pass. Missing actual user-authorized app-specific reconnect/revocation path if needed for this explicitly actual row; never infer global Google grant-revoke or force failure authority. Continue independent queue while boundary unresolved.','actual-authority-sensitive','U3'],
 'QA-SL-02':['H,N,B','Persisted durableowner lease/revision and20concurrentcaller fixtures pass. Missing actual two-device/serverless concurrent owner coordination/journal proving safe revision and refresh preservation; overlapping natural watch can discriminate without forced expiry/regrant.','actual-two-device','U3'],
 'QA-SL-03':['H,D,B','Exact13 local owner guards, actual25 session/account/CSRF/protocol/revision denials and26 cookie metadata saved. Current auth modules unchanged. Remaining privacy clause is shared withSE02 compact owned-output audit. No new spoofed realOrigin/wrong-account grant/forced expiry required when exact controlled guards plus actual owner integration cover them.','shared-owned-privacy-review','U8'],
 'QA-SL-04':['H,D,B','Actual selectedWorkersFree/no-payment, observed186requests/CPU2.177p50/6.223p99/storage466,944B and13controlled owner errors (storage503) saved. Original requires selected-plan operability and finite exhaustion, not actual quota burnout or impossible hiddenauto-upgradetoggle. Missing compact account-policy/candidate-source proof that no paidauto-transition path is selected if existingFree/no-card/source evidence is judged insufficient; reuse selectedplan/observedusage, do not stress.','bounded-policy-reconciliation','U8'],
 'QA-SL-05':['B','All iPhoneOAuth tab/PWA/Safari context clauses moved afterdeployment byD066. Saved iPhonehistorical evidence is dated; no Android-as-iOS claim.','user-deferred-iOS','POST'],
 'QA-SL-07':['S,D','Shares AU10: before/aftercounts,tombstones,writer/fullraw/backups and empty-cache reconstruction saved; project/client bindingfalse is critical. Missing owner binding/current neworigin reconstruction, never destructive oldstate removal/newOAuthclient by default.','actual-read-only-binding','U5'],
 'QA-SL-08':['H,D,B','Actual current private404/publiccache/currentanonymous and25existing-session denials plus same exact controlled auth guards cover authorization slices. Distinct candidate deployment excludesproduction target. Missing sharedSE02 ownedprivacy audit and boundedproduction-identity continuity if final integration cannot reuse existingrelease identity; no production deployment implied.','shared-owned-security-review','U8']
};
const extraPassed={
 'QA-AU-01':{owners:'N,B',reason:'Original actual natural-expiry normal-renewal branch already passed onPC24 andphysicalAndroid24; selection/source/account/revision/frames and oldexpiry+120s retained. Relevant install/request functions remain exact at28. Latestversion renewal rerun is broader current integration, not an added row clause.'},
 'QA-MU-01':{owners:'M',reason:'Original finite actual same-ID trashed postcondition is present in restricted canonical controller live proof; canonical SHA exactly unchanged. Normal gallery write delivery/globalwritesfalse is an independent product/G5 gap, not a reason to repeat proven controllertrash.'},
 'QA-MU-02':{owners:'M',reason:'Original finite actual parents postcondition independently confirmed in restricted canonical controller live proof; unchanged canonical SHA. Normal gallery UI permission/delivery remains a separate productG5gap.'}
};
extraPassed['QA-SE-02']={owners:'H,D,B',reason:'Original owned logging/public-build/process-argv clauses supported by exact source diagnostic redaction tests reused in665, actual owned logs/traces/issuesoff, Git-equal public52/ZIP/private exclusion, and exact candidate deployment public-path argv. No all-history/provider-infrastructure retention claim.'};
extraPassed['QA-SL-03']={owners:'H,D,B',reason:'Full original reader guards/memory/no-store/secret exclusion supported by unchanged13 controlled owner routes plus actual12 existing-session denials/cookie metadata/direct playback, public52/owned log+argv proof. Actual spoofedOrigin/newgrant is not an extra original clause.'};
extraPassed['QA-SL-04']={owners:'H,D,B',reason:'Selected actualWorkersFree/no-card, observed real requests/CPU/storage and unchanged bounded owner storage503/provider failure support the original operational finite-limit contract. No paid transition is selected or performed. Real quota exhaustion/hidden disabled-auto-upgrade control is not required; unknown account control visibility stays a limitation.'};
extraPassed['QA-SL-08']={owners:'H,D,B',reason:'Actual anonymous/session/private404 denials plus unchanged exact account/Origin/CSRF/path guards, safe public52 and distinct candidate-only deployment support original authorization/private/old-service-unchanged clauses. No current production promotion, source replacement or absent-interface claim.'};
const savedIds=new Set(saved.rows.map(r=>r.id));
const baselinePointers=Object.fromEntries(base.rows.map(r=>[r.id,pointer(plan.baseline.path,'"id": "'+r.id+'"')]));
const artifactAnchors={
 'qa/candidate-rc27-delivery/product-tests.json':'"pass": 665',
 'qa/candidate-rc28-delivery/product-integration.json':'"runtimeUnchangedExceptVersion": true',
 'qa/rc23-renewal-night/pc-actual-rc24-v1-result.json':'"complete": true',
 'qa/rc23-renewal-night/pc-post-renewal-seek-close.json':'"strictPreSeekOwnerStable":false',
 'qa/v2-state-normal-sync/live-rc11-results.json':'"projectClientBindingVerified": false',
 'qa/v2-state-normal-sync/fresh-cache-live-results.json':'"emptyStorageStart": true',
 'qa/v2-disposable-live/live-rc10-results.json':'"allCanonicalConfirmed": true',
 'qa/v2-disposable-live/build.cjs':'const canonical = section(',
 'qa/rc24-corpus-actual/video-cohorts-safe-summary.json':'"wholeCorpusComplete": false',
 'qa/rc21-hosting-night/result.json':'"logsEnabled": false',
 'qa/rc24-hosting-readonly/coverage.json':'"observed": {',
 'qa/rc21-hosting-security/synthetic-owner.json':'"name": "storage-quota-failure"',
 'qa/rc25-hosted-session-negatives/actual-v1-result.json':'"hostedOriginMismatchVerified":false',
 'qa/rc26-hosted-session-metadata/actual-cookie-metadata.json':'"sessionCookiePresent": true',
 'qa/rc28-resume-20261001/actual-force28.json':'"matched": 40',
 'qa/rc27-28-pc-update-qualification/actual-normal-update-and-cleanup.json':'"reopenPlaybackPending": true',
 'qa/candidate-rc28-delivery/deploy-candidate.cjs':'const run=cp.spawnSync',
 'qa/rc16-native-resource/README.md':'## Observer controls',
 'qa/rc28-performance-preparation/README.md':'failure-inclusive',
 'qa/rc28-corpus-content-continuity/README.md':'Unchanged limits:'
};
function evidencePointer(p,id){if(p===plan.baseline.path)return baselinePointers[id];if(p===savedPath&&savedIds.has(id))return pointer(p,'"id": "'+id+'"');const needle=artifactAnchors[p];if(!needle)return {path:p,line:1};const lines=norm(read(p)).split('\n');const found=lines.findIndex(l=>l.toLowerCase().includes(needle.toLowerCase()));if(found<0)throw Error('Evidence anchor absent '+p);return {path:p,line:found+1,needle};}
const rows=plan.rows.map(r=>{
 const literal=spec[r.originalSpec.line-1];if(!literal.startsWith('| '+r.id+' |'))throw Error('Spec pointerdrift '+r.id);
 let assessment='baseline-qualified-controlled-retained',missing=[],group='B',allowedScope='controlled',unit=null,proposePassed=false;
 if(r.id==='QA-SW-01'&&force28.source===pin&&force28.matched===40&&force28.missing===0&&force28.mismatch===0&&force28.controllerStable&&force28.accountSame&&force28.allProjectionPreserved){assessment='restored-current-integration-pass-proposal';group='D,B';allowedScope='Current actual normal28 + force28 account/cache40 preservation; actual Android cached40 and anonymous offline shell/public-only parity. Root reports current exact4GET proof and Q0 original reopen/frame/settled close; that further playback journal is root-owned and not silently imported as a savedartifact.';proposePassed=true;}
 else if(r.baselineStatus==='not-applicable'){assessment='conditional-not-applicable-retained';allowedScope='not-selected-architecture';}
 else if(savedIds.has(r.id)){const s=saved.rows.find(x=>x.id===r.id);assessment=r.baselineStatus==='passed'?'baseline-qualified-controlled-retained':'finite-original-pass-proposal';group='Q,B';allowedScope=s.scope||'Saved controlled adopted-route proof';proposePassed=r.baselineStatus!=='passed';}
 else if(extraPassed[r.id]){assessment='finite-original-pass-proposal';group=extraPassed[r.id].owners;allowedScope=extraPassed[r.id].reason;proposePassed=true;}
 else if(specific[r.id]){const s=specific[r.id];group=s[0];missing=[s[1]];allowedScope=s[2];unit=s[3];assessment=unit==='POST'?'user-deferred-iOS':'partial-exact-missing-clause';}
 else if(r.baselineStatus!=='passed')throw Error('Unmapped original row '+r.id);
 const paths=[...new Set(group.split(',').flatMap(g=>owners[g]||[]))];
 return {id:r.id,original:{...r.originalSpec,verbatim:literal},historical:{baselineStatus:r.baselineStatus,baselineEvidence:r.baselineEvidence,pointer:baselinePointers[r.id],historicalOutstanding42:r.historicalOutstanding42},currentAssessment:assessment,proposedScopedPassed:proposePassed,acceptanceAuthority:'Root owns final status; baseline/spec never modified.',allowedEvidenceScope:allowedScope,savedEvidence:paths.map(p=>({...evidencePointer(p,r.id),sha256:sha(read(p))})),exactMissingClauses:missing,nextUnit:unit,wholeGoalPassed:false};
});
const queue=[
 {id:'U1',rank:1,task:'Record root-owned actual fixed28 force/reopen/frame/close already observed',ids:['QA-SW-01'],owner:'root current browser',needsNewActual:false,why:'Current force28 artifact now preserves all40 hashes/account/projection and root reports originalQ0 frame/close. Current root journals are saved and hashed; restore the finite SW01 proposal without rerun.',excluded:'No repeated public52/cache40/freshanonymous/static20/full665 run.'},
 {id:'U2',rank:2,task:'Fresh fixed28 completeinventory + feasible bounded deepercombination probes + designated/representative PC+Android app playback',ids:rows.filter(r=>r.nextUnit==='U2').map(r=>r.id),owner:'root corpus plus Android',needsNewActual:true,why:'Actualcombination denominator and designatedMP4/audio/timing are explicit. Tail-index correctness may use controllednative fixture. ConditionalQ2/Q3/HDR driven by actual presence.',excluded:'No all-file realplayback, entirebody hydration, automaticQ3/HDR N/A, damaged original or metadata mutation.'},
 {id:'U3',rank:3,task:'Actual OSbackground/return and overlapping normal two-device renewal/coordination',ids:rows.filter(r=>r.nextUnit==='U3').map(r=>r.id),owner:'root plus Android',needsNewActual:true,why:'TR12/SL01/SL02 explicitly actual. AU01 naturalrenewal already saved; reuse exactcode proof.',excluded:'No forcedclock, refreshrevocation/regrant, global accountgrant withdrawal or timerinstalled by this offline review.'},
 {id:'U4',rank:4,task:'Finite uncovered Android playergesture/orientation/fullscreen plus isolatedblocked-cookie scenario',ids:rows.filter(r=>r.nextUnit==='U4').map(r=>r.id),owner:'Android and root',needsNewActual:true,why:'UI finite player clauses differ from savedlibrary/OSrotation; boundedcurrentobservation/source review can close quietUI/normalstate clauses.',excluded:'No repeat clickSpace/pointerhide/stableedge; no hand-sensor requirement or currentVoiceOver/iOS gate.'},
 {id:'U5',rank:5,task:'Twoforeground viewed receipt and exact existingproject/client/origin appData binding/reconstruction',ids:rows.filter(r=>r.nextUnit==='U5').map(r=>r.id),owner:'root plus Android state',needsNewActual:true,why:'ST01 explicitly twoforeground devices; migration live record bindingfalse is a concrete unresolved field.',excluded:'No unnecessarynewOAuthclient/login/regrant or forcedofflineconflict replay. OriginalST02 controlledoffline contract retained.'},
 {id:'U6',rank:6,task:'Exact approveddisposable API/web/G:comparison and pre-state recovery/final residualcleanup',ids:rows.filter(r=>r.nextUnit==='U6').map(r=>r.id),owner:'root exactprivateallowlist',needsNewActual:true,why:'MU09/10 expressly require observedcross-source state/finalprestate. ExistinglivecontrollerMU01/02 evidence reused.',excluded:'No additionaltrash/move merely to relabelrow; no permanentDELETE/generalflag; normalgallerywrite-delivery remains separate product task.'},
 {id:'U7',rank:7,task:'Changed disposal/resource layer review then only necessary controllednative50cycle count proof; separate honest performance distribution',ids:['QA-LF-01'],owner:'root localnative plus passiveperformance',needsNewActual:false,why:'50cycles and no decoder/job/listener/buffer accumulation are explicit. Old16resourceproof is observer-qualified; currentretirement changed. OBS03 distribution must include failures/timeouts and cold/warm labels.',excluded:'No inventedphysical50cycles/total-nativeMiB gate;20repeats recommended, approximate5/2/3sec initialtargets not rigidnewconstants; do notclaimp95from1or5.'},
 {id:'U8',rank:8,task:'Accept or amend completed compact owned privacy/process/plan-policy reconciliation',ids:['QA-SE-02','QA-SL-03','QA-SL-04','QA-SL-08'],owner:'root final evidence decision',needsNewActual:false,why:'Finite original clauses supported by ownedPrivacyPolicy/current exact authmodules plus saved selectedFree/actualusage/sessiondenials. No concrete uncovered ownedvariable warrants another hosted run here.',excluded:'No realquotaexhaustion/billingstorm, mythicalhiddenauto-upgradetoggle requirement, historicalallprocessargs/log/infrastructure scavenger or repeated12hosteddenials.'},
 {id:'PRODUCT-G5',rank:9,task:'Normal product disposable-action delivery and final current PC+Android representative integration',ids:[],owner:'root product finalacceptance',needsNewActual:true,why:'Globalwritesfalse/normalUI mutationsunverified remain product/G5 gap even if finiteMU01/02 postcondition rows already proven. Integrate exactallowlist withoutglobalwrites or baseline replay.',excluded:'No main/push/production/automation authorization inferred.'},
 {id:'POST',rank:null,task:'User-deferred iOS-only OAuth/Safari/PWA/VoiceOver followup',ids:['QA-SL-05','iOS portions QA-RP-01/QA-UI-06/QA-UI-09'],owner:'after authorized deployment',needsNewActual:true,why:'D066 supersedes predeployment iPhonegate;Android doesnotproveiOS.',excluded:'Not a currentcandidate blocker.'}
];
const counts={historical:plan.baseline.counts,currentAssessments:rows.reduce((a,r)=>(a[r.currentAssessment]=(a[r.currentAssessment]||0)+1,a),{}),scopedPassProposals:rows.filter(r=>r.proposedScopedPassed).length,actualRowsWithMissingClause:rows.filter(r=>r.nextUnit&&r.nextUnit!=='POST'&&r.allowedEvidenceScope.startsWith('actual')).length,originalRows:69,historicalOutstanding42:plan.baseline.historicalOutstandingMapped,wholeGoalPromotions:0};
const legacyClient = /const DEFAULT_OAUTH_CLIENT_ID = ['"]([^'"]+)['"]/.exec(norm(git('show','e08989a:app.js')))?.[1];
const configuredClient = j('worker/wrangler.jsonc').vars?.GOOGLE_CLIENT_ID;
const workerText=norm(read('worker/index.mjs')),googleText=norm(read('worker/google.mjs'));
const localClientBinding={configuredClientPresent:typeof configuredClient==='string'&&configuredClient.length>0,legacyDefaultClientPresent:!!legacyClient,configuredEqualsLegacyDefault:!!legacyClient&&configuredClient===legacyClient,configuredClientFlowsToVerifiedExchange:workerText.includes('clientId: env.GOOGLE_CLIENT_ID')&&workerText.includes('clientId: settings.clientId'),serverAudienceAndAuthorizedPartyBound:googleText.includes('claims.aud !== clientId')&&googleText.includes('claims.azp !== clientId'),serverRedirectBoundToConfiguredOrigin:workerText.includes('redirectUri: '+String.fromCharCode(96)+'${origin}${CALLBACK_PATH}'+String.fromCharCode(96))&&googleText.includes('redirect_uri: redirectUri'),runtimeProjectClientBindingVerified:false,scope:'Offline public configuration/source checks only. No identifiers/secrets exported; actual canonical appData reconstruction remains required.',sourcePointers:[pointer('worker/index.mjs','clientId: env.GOOGLE_CLIENT_ID'),pointer('worker/index.mjs','redirectUri:'),pointer('worker/google.mjs','claims.aud !== clientId'),pointer('worker/google.mjs','redirect_uri: redirectUri')],sourceHashes:['worker/wrangler.jsonc','worker/index.mjs','worker/google.mjs'].map(path=>({path,sha256:sha(read(path))}))};
for(const key of ['configuredClientPresent','legacyDefaultClientPresent','configuredEqualsLegacyDefault','configuredClientFlowsToVerifiedExchange','serverAudienceAndAuthorizedPartyBound','serverRedirectBoundToConfiguredOrigin'])if(!localClientBinding[key])throw Error('Offline client binding check absent: '+key);
const reopen28=j('qa/rc28-resume-20261001/actual-reopen-and-cleanup.json'),proof28=j('qa/rc28-resume-20261001/current-source-proof.json');
if(reopen28.source!==pin||!reopen28.closed||!reopen28.retirementSettled||proof28.source!==pin||!proof28.sourcePinned)throw Error('Current actual source/reopen fence absent');
const migrationRoute={localClientBinding,sourcePointers:[pointer('worker/index.mjs','clientId: env.GOOGLE_CLIENT_ID'),pointer('app.js','async function resolveDriveAccountId('),pointer('app.js','async function findAccountStateFile('),pointer('app.js','async function readRemoteAccountMediaState(')],steps:['Local configured-client equals e08989a legacy default and OIDC audience/redirect source checks now pass as booleans only. Runtime project/client/appData binding remains explicitly unverified.','Capture actual28 account/auth/data/revision/controller/writer fences. Through canonical ACCOUNT_STATE_READ transport capture complete current10document appData prestate privately. Compare full union/tombstones/writer/legacy bodies to actual projection/cache, not counts alone.','Reconstruct via isolated empty-cache read-only facade using exact current capability-aware initialize functions and existing actual owner; no writes/newgrant/newclient. Re-read/fence afterward, preserve private raw before/after, export boolean equality/counts only.'],noNewActualGrant:true,noMutationRequired:true};
const p={schema:'drive-original.rc28-finite-original69-review/1',generatedUtc:new Date().toISOString(),fixedSource:pin,version:source28.version,gitHead:git('rev-parse','HEAD').toString().trim(),executionState:'ACTIVE D066 per direct resumed user request; old move manifest WAIT is historical and revoked for execution.',sourceCutoff:'Saved db2f808/move manifest plus current actual-force28, actual-reopen-and-cleanup and current-source-proof artifacts. Android147 in-flight not imported.',noExecution:true,rows,counts,queue,hashes,ownedPrivacyPolicy,migrationRoute,sourceBindings:{core28,recordBindings,testProducerBindings:tests,implementationComparisons:comparisons,full665Scope:'Controlled regression source equality only; never a realaccount/device/wholeformat/performance pass.'},crossCuttingPointers:[pointer(specPath,'### CORPUS-06'),pointer(specPath,'### EXP-03'),pointer(specPath,'5개 시도만으로 p95'),pointer(specPath,'### EXP-06'),pointer(specPath,'| G5 실제 환경'),pointer('memory/DECISIONS.md','## D-066'),pointer('qa/v2-state-normal-sync/live-rc11-results.json','"projectClientBindingVerified": false'),pointer('qa/v2-disposable-live/live-rc10-results.json','"normalProductUiMutationsVerified": false')],limits:['Original baseline/spec/statuses/history preserved. Recommendations do not change canonical owner records.','Every savedscope remains controlled/native/actual precisely; no 665/delivery/count promotion to wholegoal.','No new browser/network/account/device/product/private-original operation, no priorproducer/check rerun or commit.','iOS afterdeployment; D067 moveWAIT is revoked only by direct userresume, not by this document.']};
fs.writeFileSync(path.join(__dirname,'review.json'),JSON.stringify(p,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'queue.json'),JSON.stringify({schema:p.schema+'-queue',counts,queue},null,2)+'\n');
const summary=['# Fixed rc28 finite original69 review','','Offline review; source '+pin+'. Original69 baseline/history unchanged. Root owns final statuses.','',...Object.entries(counts.currentAssessments).map(([k,v])=>'- '+k+': '+v),'',counts.scopedPassProposals+' scoped pass proposals cover finite original clauses only; broad product/G5 work remains. See review.json and queue.json for exact original rows, missing clauses, artifact hashes and implementation comparisons.','','Reuse: saved six-row review checked by exact scoped implementation hashes, not rerun. Natural renewal credential functions and canonical mutation controller remain exact; auth module hashes checked. State init/flush differ from11; client/project mapping remains explicitly missing.','','Actual proof needed: complete inventory and representative combinations/designated MP4; long return and two-device coordination; uncovered physical player input; foreground viewed receipt; migration binding; web/G: disposable comparison/restoration. Tail correctness/resource50cycles may use controlled native proof. Saved Free/usage/negative guards and current owned source/argv support finite hosting/privacy clauses without real quota exhaustion or historical infrastructure scavenging.','','Only this new leaf is task-owned. No browser/network/account/product/shared record mutation or commit.'];
fs.writeFileSync(path.join(__dirname,'README.md'),summary.join('\n')+'\n');
const files=['build.cjs','review.json','queue.json','README.md'].map(n=>leaf+'/'+n);fs.writeFileSync(path.join(__dirname,'staging-manifest.json'),JSON.stringify({scope:'Exact five newleaf paths only; no staging performed; manifest doesnotselfhash.',files:files.map(p=>({path:p,sha256:sha(read(p))})),manifestPath:leaf+'/staging-manifest.json'},null,2)+'\n');
console.log(JSON.stringify({counts,core28AllMatched:core28.every(x=>x.same),recordBindingsAllMatched:recordBindings.every(x=>x.same),changedComparisons:comparisons.filter(x=>!x.same).map(x=>x.scope),changedNonStaticTests:tests.filter(x=>!x.same&&!x.versionOnlyStatic).map(x=>x.path)}));
