'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const driver=require('./driver.cjs'),source=fs.readFileSync(path.join(__dirname,'browser.function.js'),'utf8');
const run='12345678-1234-4123-8123-123456789abc',tuple={primaries:'bt709',transfer:'bt709',matrix:'bt709',fullRange:false};
function mock(){const calls=[],eventMap=new Map(),frameCallbacks=new Map();let closedFrames=0,frameNext=0,metadataChange=false,monotonic=0,onGET=null,deadlineTimer=null,clockValues=[];
  const ctrl={state:'activated'},signal=new AbortController().signal,metadata={id:'mock-disposable-file-only',name:'DriveOriginal-QA-'+run+'-test-video-1',mimeType:'video/mp4',ownedByMe:true,trashed:false,parents:['mock-root-only'],version:'5',headRevisionId:'mock-revision-only',modifiedTime:'mock-date',size:'759643',md5Checksum:'4a49dfa52d67d5b4b391fe9bb7f836ae',sha256Checksum:'bc831b81953010036a7d931100dfd264fa14d8e22633b6518268f6c6dbfc2e2f',appProperties:{qaRun:run,qaRole:'test-video-1',qaFixtureSHA256:'bc831b81953010036a7d931100dfd264fa14d8e22633b6518268f6c6dbfc2e2f'},capabilities:{canTrash:true,canDownload:true}};
  const emitter={addEventListener:(name,fn)=>{if(!eventMap.has(name))eventMap.set(name,new Set());eventMap.get(name).add(fn);},removeEventListener:(name,fn)=>eventMap.get(name)?.delete(fn)};
  const video={...emitter,readyState:2,videoWidth:320,videoHeight:180,paused:true,error:null,hasAttribute:()=>false,
    requestVideoFrameCallback:fn=>{const id=++frameNext;frameCallbacks.set(id,fn);return id;},cancelVideoFrameCallback:id=>frameCallbacks.delete(id)};
  class Worker{constructor(){this.listeners=new Set();this.sent=[];}addEventListener(name,fn){this.listeners.add(fn);}removeEventListener(name,fn){this.listeners.delete(fn);}postMessage(m){this.sent.push(m);}terminate(){this.done=true;}emit(m){for(const fn of this.listeners)fn({data:m});}}
  const ctx={window:{Worker},APP_VERSION:'1.22.0-rc.37',location:{origin:'https://mock.invalid',href:'https://mock.invalid/'},navigator:{serviceWorker:{controller:ctrl,getRegistration:async()=>({active:ctrl,scope:'https://mock.invalid/'})}},document:{visibilityState:'visible'},
    state:{accountId:'mock-account-only',authAccountKey:'mock-key-only',authGeneration:4,driveSessionGeneration:7,accountStateAbortController:{signal},selected:null,authStatus:'online',accountStateLoaded:true,mediaSession:0,currentFolderId:'root',query:''},
    q0Playback:null,q1Playback:null,q0PinnedSource:null,playerTracksOwner:null,q1RetirementResult:{settled:true},playerTracksRetirementResult:{settled:true},mediaSourceGeneration:0,
    el:{playerSheet:{hidden:true},videoPlayer:video,playerTracksDialog:{open:false},playerAudioTrack:{...emitter,value:'',disabled:false}},URL,URLSearchParams,AbortController,AbortSignal,Uint8Array,TextDecoder,
    performance:{now:()=>{if(clockValues.length)monotonic=clockValues.shift();return monotonic;}},setTimeout:(fn,ms)=>{if(ms===180000)deadlineTimer=fn;return setTimeout(fn,ms);},clearTimeout,Date,DRIVE_API:'https://www.googleapis.com/drive/v3',
    hasUsableToken:()=>true,getActiveMediaElement:()=>video,isCurrentMediaEvent:()=>true,hasVerifiedOriginalTransport:()=>true,
    driveFetch:async u=>{calls.push(u);if(onGET)await onGET();const m=structuredClone(metadata);if(metadataChange)m.version='6';return new Response(JSON.stringify(m));},
    VideoFrame:class{constructor(){this.format=ctx.q1Playback?'RGBA':'I420';this.colorSpace=tuple;this.visibleRect={width:320,height:180};}close(){closedFrames++;}},
    openPlayer:file=>{ctx.state.selected=file;ctx.state.mediaSession=1;ctx.mediaSourceGeneration=1;ctx.state.mediaDecodeVerified=true;ctx.el.playerSheet.hidden=false;ctx.q0Playback={fileId:file.id,session:1,account:'mock-key-only',accountGeneration:7,swGeneration:1,swController:ctrl,controller:new AbortController()};ctx.q0PinnedSource={mock:true};}};
  const input={schema:'rc37-android-exact-created-context/1',account:{accountId:'mock-account-only'},metadata,qaRunId:run};vm.createContext(ctx);
  const install=async v=>vm.runInContext('('+source+')('+JSON.stringify(v||input)+')',ctx);
  const frame=(mediaTime=0.5)=>{const [id,fn]=frameCallbacks.entries().next().value;frameCallbacks.delete(id);fn(0,{width:320,height:180,mediaTime,presentedFrames:1});};
  const close=()=>{ctx.state.selected=null;ctx.q0Playback=null;ctx.q1Playback=null;ctx.playerTracksOwner=null;ctx.q0PinnedSource=null;ctx.el.playerSheet.hidden=true;};
  const successor=()=>{const config={codec:'avc1.64000D',codedWidth:320,codedHeight:180,description:new Uint8Array([1,2,3])};ctx.q0Playback=null;ctx.mediaSourceGeneration=2;ctx.state.mediaTransportVerified=true;ctx.state.mediaTransportStarted=true;ctx.state.mediaPlaybackMode='original-repackaged';ctx.state.lastPresentedMediaTime=0.5;ctx.playerTracksOwner.selectedAudioTrackId=3;ctx.playerTracksOwner.nativeColorObservation={basis:'observed-native-frame',format:'I420',colorSpace:tuple};ctx.q1Playback={kind:'general',fileId:metadata.id,session:1,account:'mock-key-only',accountGeneration:7,swGeneration:2,swController:ctrl,controller:new AbortController(),selectedAudioTrackId:3,player:{stats:()=>({generation:1,outputColorObservation:{basis:'observed-native-frame',colorSpace:tuple}})}};
    const worker=new ctx.window.Worker('/media/general-worker.mjs',{type:'module'});worker.postMessage({kind:'start',generation:1,identity:{...metadata,fileId:metadata.id,accountKey:'mock-key-only',accountGeneration:7,canDownload:true}});worker.emit({kind:'window',generation:0,value:{selectedAudioTrackId:3,videoConfig:config,outputVideoConfig:{...config,colorSpace:tuple}}});assert.equal(ctx.window.__rc37AndroidActualAAC.read().statsReady,false);
    worker.emit({kind:'window',generation:1,value:{selectedAudioTrackId:3,videoConfig:config,outputVideoConfig:{...config,colorSpace:tuple}}});return worker;};
  return {ctx,input,install,frame,successor,close,calls,metadata,advance:ms=>monotonic+=ms,clockValues:(...values)=>clockValues=values,fireDeadline:()=>deadlineTimer(),setGET:fn=>onGET=fn,
    change:trusted=>{for(const fn of eventMap.get('change')||[])fn({type:'change',isTrusted:trusted});},setMetadataChange:()=>metadataChange=true,closedFrames:()=>closedFrames,eventCount:()=>[...eventMap.values()].reduce((n,s)=>n+s.size,0),callbackCount:()=>frameCallbacks.size};}
function nativeDefaultInventory(m){m.ctx.playerTracksOwner={current:()=>true,cleanupOk:true,switching:false,inventory:{defaultAudioTrackId:2,audioTracks:[{trackId:2,codec:'aac',route:'q1'},{trackId:3,codec:'aac',route:'q1'}]}};m.ctx.el.playerAudioTrack.value='2';}
test('static preparation reads only local producers and exact existing delivery and fingerprinted combined fixture',()=>{const p=driver.preparation();assert.equal(p.manifest.actualExecution,false);assert.equal(p.manifest.privateInputCreated,false);assert.equal(p.binding.sourceCommit,'051dc3456f5000b958a18593848769b3687991e5');assert.equal(p.binding.cache.length,50);assert.equal(p.manifest.fixture.bytes,759643);assert.equal(p.manifest.fixture.sha256,'bc831b81953010036a7d931100dfd264fa14d8e22633b6518268f6c6dbfc2e2f');assert.equal(p.manifest.fixture.md5,'4a49dfa52d67d5b4b391fe9bb7f836ae');assert.equal(p.manifest.fixture.initialAudioTrackId,2);assert.equal(p.manifest.fixture.selectedAudioTrackId,3);const code=fs.readFileSync(path.join(__dirname,'driver.cjs'),'utf8');assert.ok(code.includes("{flag:'wx'}"));assert.ok(code.includes("'-consumed-private.json'"));assert.equal(code.includes('chromium.connectOverCDP'),false);assert.equal(code.includes('browser.close('),false);assert.equal(code.includes('ServiceWorker.setForceUpdateOnPageLoad'),false);});
test('exact private schema refuses token/extra ownership data, wrong run tag and placeholder contexts',()=>{const m=mock();assert.equal(driver.validateInput(m.input),m.input);for(const v of [{...m.input,token:'never-export'},{...m.input,account:{...m.input.account,token:'never-export'}},{...m.input,metadata:{...m.metadata,appProperties:{qaRun:'different'}}},{schema:m.input.schema}])assert.throws(()=>driver.validateInput(v),/AAC_PRIVATE_CONTEXT_SHAPE/);});
test('wrong PC account rejects before helper, frames or metadata requests',async()=>{const m=mock();await assert.rejects(m.install({...m.input,account:{accountId:'other-mock-account'}}),/AAC_PC_ACCOUNT_MISMATCH/);assert.equal(m.ctx.window.__rc37AndroidActualAAC,undefined);assert.equal(m.calls.length,0);assert.equal(m.callbackCount(),0);});
test('full mock lifecycle observes current frames, native I420/output RGBA tuple separately and closes every frame/resource',async()=>{const m=mock();await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;assert.equal(m.callbackCount(),1);assert.equal(m.eventCount(),3);assert.equal((await h.locate()).exactOneMetadataGET,true);await assert.rejects(h.locate(),/AAC_LOCATE_ONCE/);h.open();m.frame();assert.equal(h.read().phases[0].first.good,true);assert.equal(h.captureNative().format,'I420');
  nativeDefaultInventory(m);m.ctx.el.playerTracksDialog.open=true;assert.equal(h.selectionReady().trackId,3);const worker=m.successor();m.ctx.el.playerTracksDialog.open=false;m.ctx.el.playerAudioTrack.value='3';
  // Native input is simulated in this VM only; this is not physical-device proof.
  for(const fn of worker.listeners)assert.equal(typeof fn,'function');m.ctx.el.playerAudioTrack.addEventListener('change',()=>{});m.change(true);m.frame();const r=await h.verify();assert.equal(r.trustedAAC3Change,true);assert.equal(r.tuplePass,true);assert.equal(r.originalMetadataUnchanged,true);assert.equal(r.sourceConfigPreserved,true);assert.equal(r.nativeFormat,'I420');assert.equal(r.presentedFormat,'RGBA');assert.equal(r.unlikeFormatVisibleYUV,'UNKNOWN');assert.equal(r.encoders,null);assert.equal(r.windowMetadataOnly,true);assert.equal(m.closedFrames(),2);assert.equal(m.calls.length,2);assert.equal(m.calls.some(u=>new URL(u).pathname.endsWith('/files')),false);
  worker.terminate();m.close();const clean=h.stop();assert.equal(Object.values(clean).every(v=>v===true),true);assert.equal(m.ctx.window.__rc37AndroidActualAAC,undefined);assert.equal(m.callbackCount(),0);assert.equal(worker.listeners.size,0);assert.equal(m.eventCount(),1);});
test('owner/controller drift cannot qualify a presented frame or verify; cleanup refuses live ownership then can settle',async()=>{const m=mock();await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;await h.locate();h.open();m.ctx.mediaSourceGeneration=3;m.frame();assert.equal(h.read().phases[0].first,null);assert.throws(()=>h.captureNative(),/AAC_NATIVE_ADMISSION/);assert.throws(()=>h.stop(),/AAC_CLOSE_UNSETTLED/);m.close();assert.equal(h.stop().helperAbsent,true);});
test('root metadata mismatch is retained and helper cleanup is available before any playback',async()=>{const m=mock();await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;m.setMetadataChange();await assert.rejects(h.locate(),/AAC_ROOT_METADATA_CHANGED/);assert.equal(m.calls.length,1);assert.equal(h.stop().helperAbsent,true);assert.equal(m.callbackCount(),0);assert.equal(m.eventCount(),0);});
test('AAC3 requires two qualified tracks and actual native default2; already3 or single AAC no-change refuses before arming',async()=>{const faults=[m=>{m.ctx.el.playerAudioTrack.value='3';},m=>{m.ctx.playerTracksOwner.inventory.audioTracks.pop();},m=>{m.ctx.playerTracksOwner.inventory.defaultAudioTrackId=3;},m=>{m.ctx.playerTracksOwner.selectedAudioTrackId=3;}];for(const fault of faults){const m=mock();await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;await h.locate();h.open();m.frame();nativeDefaultInventory(m);m.ctx.el.playerTracksDialog.open=true;fault(m);try{assert.throws(()=>h.selectionReady(),/AAC_SELECTION_ADMISSION/);assert.equal(h.read().phases.length,1);}finally{m.close();assert.equal(h.stop().helperAbsent,true);}}});
test('trusted change2 and untrusted change3 cannot satisfy native change3 receipt; trusted change3 qualifies',async()=>{const m=mock();await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;await h.locate();h.open();m.frame();h.captureNative();nativeDefaultInventory(m);m.ctx.el.playerTracksDialog.open=true;assert.equal(h.selectionReady().initialValue,2);m.change(true);assert.equal(h.read().events.find(e=>e.type==='change').aac3,false);const worker=m.successor();m.ctx.el.playerTracksDialog.open=false;m.ctx.el.playerAudioTrack.value='3';m.change(false);m.frame();try{assert.equal((await h.verify()).trustedAAC3Change,false);m.change(true);assert.equal((await h.verify()).trustedAAC3Change,true);assert.equal(m.closedFrames(),3);}finally{worker.terminate();m.close();assert.equal(h.stop().helperAbsent,true);}});
test('QA connector guard differs only in three exact fixture constants; prior failed actors and receipts stay byte-identical',()=>{const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),old=fs.readFileSync(path.resolve(__dirname,'../rc37-color-disposable-integration/connector-file-guard.function.js'),'utf8');assert.equal(fs.readFileSync(path.join(__dirname,'connector-file-guard.function.js'),'utf8'),old.replaceAll('659966','759643').replaceAll('d9a1cc3f12a7a3b3a91f408e59da8e1f9b8dfb2e4ec26dd8d969cedc27893037','bc831b81953010036a7d931100dfd264fa14d8e22633b6518268f6c6dbfc2e2f').replaceAll('cc7a0da5f6e2b89a9fdee916d259d285','4a49dfa52d67d5b4b391fe9bb7f836ae'));const archive=path.join(__dirname,'prior-actor-aac2'),manifest=JSON.parse(fs.readFileSync(path.join(archive,'manifest.json')));for(const row of [...manifest.copied,...manifest.immutableReceipts])assert.equal(hash(fs.readFileSync(path.join(archive,row.file))),row.sha256);
  for(const row of manifest.immutableReceipts){const receipt=JSON.parse(fs.readFileSync(path.join(archive,row.file)));assert.equal(receipt.producerSHA256,manifest.copied.find(x=>x.file==='driver.cjs').sha256);assert.equal(receipt.binding.helper.sha256,manifest.copied.find(x=>x.file==='browser.function.js').sha256);}});
async function readyAAC(m){await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;await h.locate();h.open();m.frame();h.captureNative();nativeDefaultInventory(m);m.ctx.el.playerTracksDialog.open=true;h.selectionReady();const worker=m.successor();m.ctx.el.playerTracksDialog.open=false;m.ctx.el.playerAudioTrack.value='3';m.change(true);m.frame();return {h,worker};}
test('fresh GET must not reuse evidence after same-account playback/source/pipeline/selection turnover',async()=>{
  const changes=[m=>{m.ctx.q1Playback={...m.ctx.q1Playback};},m=>{m.ctx.mediaSourceGeneration++;m.ctx.q1Playback.swGeneration=m.ctx.mediaSourceGeneration;},
    m=>{m.ctx.q1Playback.player={stats:()=>({generation:2,outputColorObservation:{basis:'observed-native-frame',colorSpace:tuple}})};},
    m=>{m.ctx.q1Playback.selectedAudioTrackId=2;m.ctx.playerTracksOwner.selectedAudioTrackId=2;}];
  for(const change of changes){const m=mock(),{h,worker}=await readyAAC(m);m.setGET(()=>change(m));try{await assert.rejects(h.verify(),/AAC_VERIFY_OWNER_CHANGED_DURING_GET/);assert.equal(m.closedFrames(),1);assert.equal(m.ctx.state.accountId,m.input.account.accountId);assert.equal(m.calls.length,2);}
    finally{worker.terminate();m.close();assert.equal(h.stop().helperAbsent,true);assert.equal(m.callbackCount(),0);}}
});
test('V3 exact producers, immutable failure and unchanged guard remain reproducible',()=>{const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),archive=path.join(__dirname,'prior-actor-aac3'),manifest=JSON.parse(fs.readFileSync(path.join(archive,'manifest.json')));
  for(const row of manifest.copied)assert.equal(hash(fs.readFileSync(path.join(archive,row.file))),row.sha256);const row=manifest.immutableReceipt;assert.equal(hash(fs.readFileSync(path.join(archive,row.file))),row.sha256);
  const receipt=JSON.parse(fs.readFileSync(path.join(archive,row.file)));assert.equal(receipt.producerSHA256,manifest.copied.find(x=>x.file==='driver.cjs').sha256);assert.equal(receipt.binding.helper.sha256,manifest.copied.find(x=>x.file==='browser.function.js').sha256);
  assert.equal(hash(fs.readFileSync(path.join(__dirname,'connector-file-guard.function.js'))),manifest.guardUnchangedSHA256);});
test('passive state/frame trace discriminates retirement precursor from current second-generation startup without changing verdict',async()=>{const m=mock(),{h,worker}=await readyAAC(m);
  const stats={generation:2,phase:'opening',mapping:null,appends:0,disposed:false};m.ctx.q1Playback.player={stats:()=>stats};m.ctx.state.mediaDecodeVerified=false;m.ctx.state.mediaTransportVerified=false;m.ctx.state.mediaTransportStarted=false;m.ctx.state.lastPresentedMediaTime=null;
  m.ctx.el.videoPlayer.readyState=2;m.frame(0.021333);let r=h.read(),frame=r.phases[1].frames.at(-1);assert.equal(frame.good,false);assert.equal(frame.generation,2);assert.equal(frame.predicateBits.verified,false);assert.equal(frame.predicateBits.transport,false);assert.equal(frame.predicateBits.selectedRoute,false);
  m.ctx.mediaSourceGeneration=3;m.ctx.q1Playback.swGeneration=3;m.ctx.el.videoPlayer.readyState=0;worker.emit({kind:'window',generation:1,value:{privateMarker:'MUST_NOT_EXPORT'}});r=h.read();const latest=r.passiveTrace.transitions.filter(x=>x.kind==='state').at(-1);
  assert.equal(latest.phase,'opening');assert.equal(latest.source,3);assert.equal(latest.mapping,null);assert.equal(latest.appends,0);assert.equal(latest.ready,0);assert.equal(r.currentWorkerWindow,false);assert.equal(r.passiveTrace.transitions.filter(x=>x.kind==='worker-window').at(-1).reason,'SOURCE_CHANGED');
  stats.phase='buffering';stats.mapping={sourceOrigin:0,sourceEnd:6,targetSource:0.5,targetElement:0.5,commonShift:0};stats.appends=1;r=h.read();assert.equal(r.passiveTrace.transitions.filter(x=>x.kind==='state').at(-1).phase,'buffering');assert.equal(r.passiveTrace.transitions.filter(x=>x.kind==='state').at(-1).mapping.targetElement,0.5);
  worker.terminate();m.close();assert.equal(h.stop().traceCleared,true);assert.equal(m.callbackCount(),0);assert.equal(worker.listeners.size,0);});
test('worker passive start/window/terminal reasons and finite ring never export raw identity or chunks',async()=>{const m=mock(),{h,worker}=await readyAAC(m);let r=h.read();assert.equal(r.passiveTrace.counts.startAccepted,1);assert.equal(r.passiveTrace.counts.windowRejected,1);assert.equal(r.passiveTrace.counts.windowAccepted,1);
  for(let i=0;i<150;i++)worker.emit({kind:'terminal',generation:1,error:{message:'PRIVATE_RAW_ERROR'},identity:{fileId:m.metadata.id},buffer:new Uint8Array([99])});r=h.read();assert.equal(r.passiveTrace.transitions.length,128);assert.ok(r.passiveTrace.counts.evicted>0);assert.equal(r.passiveTrace.counts.terminalAccepted,150);
  m.ctx.q1Playback.swGeneration++;const other=new m.ctx.window.Worker('/media/general-worker.mjs');other.postMessage({kind:'start',generation:3,identity:{fileId:'PRIVATE_OTHER'}});other.emit({kind:'window',generation:3,value:{}});r=h.read();assert.equal(r.passiveTrace.counts.startRejected,1);assert.equal(r.passiveTrace.transitions.findLast(x=>x.kind==='worker-start').reason,'ROUTE_NOT_CURRENT');assert.equal(r.passiveTrace.transitions.findLast(x=>x.kind==='worker-window').reason,'NO_START_BINDING');
  const text=JSON.stringify(r.passiveTrace);for(const secret of [m.metadata.id,m.input.account.accountId,'PRIVATE_RAW_ERROR','PRIVATE_OTHER','buffer','identity'])assert.equal(text.includes(secret),false);assert.equal(r.passiveTrace.allWorkerCoverage,'UNKNOWN');
  worker.terminate();other.terminate();m.close();assert.equal(Object.values(h.stop()).every(v=>v===true),true);assert.equal(other.listeners.size,0);});
function networkMock(failEnable=false,failDisable=false){const listeners=new Set(),sent=[];return {listeners,sent,onEvent(fn){listeners.add(fn);return ()=>listeners.delete(fn);},async send(method){sent.push(method);if(method==='Network.enable'&&failEnable)throw Error('CDP_ORIGINAL_ENABLE_FAILURE');if(method==='Network.disable'&&failDisable)throw Error('CDP_DISABLE_FAILURE');},emit(method,params){for(const fn of listeners)fn(method,params);}};}
test('target-to-non-target same-requestId redirect cannot attribute its response to the exact QA file',async()=>{const cdp=networkMock(),n=driver.networkTrace(cdp,'mock-exact-file','https://mock.invalid');await n.enable();
  cdp.emit('Network.requestWillBeSent',{requestId:'PRIVATE_REUSED_ID',timestamp:1,request:{method:'GET',url:'https://www.googleapis.com/drive/v3/files/mock-exact-file'}});
  cdp.emit('Network.requestWillBeSent',{requestId:'PRIVATE_REUSED_ID',timestamp:2,redirectResponse:{status:302},request:{method:'GET',url:'https://foreign.invalid/PRIVATE_REDIRECT'}});
  cdp.emit('Network.responseReceived',{requestId:'PRIVATE_REUSED_ID',timestamp:3,response:{status:200,headers:{'Content-Length':'999'}}});cdp.emit('Network.loadingFinished',{requestId:'PRIVATE_REUSED_ID',timestamp:4,encodedDataLength:999});
  const r=n.snapshot();assert.equal(r.counts.requests,1);assert.equal(r.counts.nonTargetReassignments,1);assert.equal(r.counts.pending,0);assert.equal(r.counts.responses,0);assert.equal(r.counts.finished,0);assert.deepEqual(r.rows.at(-1),{event:'coverage-loss',reason:'NON_TARGET_REQUEST_REASSIGNMENT'});
  for(const secret of ['PRIVATE_REUSED_ID','PRIVATE_REDIRECT','foreign.invalid','mock-exact-file'])assert.equal(JSON.stringify(r).includes(secret),false);await n.stop();assert.equal(cdp.listeners.size,0);});
test('exact-file page Network trace admits only owned requests with finite sanitized latency/status/length records',async()=>{const cdp=networkMock(),n=driver.networkTrace(cdp,'mock-exact-file','https://mock.invalid');assert.equal(cdp.listeners.size,1);await n.enable();
  const request=(id,url,headers={})=>cdp.emit('Network.requestWillBeSent',{requestId:id,timestamp:10,request:{method:'GET',url,headers}});
  request('private-id1','https://www.googleapis.com/drive/v3/files/mock-exact-file?fields=PRIVATE_QUERY',{Authorization:'PRIVATE_TOKEN'});
  request('private-id2','https://mock.invalid/__drive_media/mock-exact-file?sourceGeneration=9&resourceKey=PRIVATE_RESOURCE',{Range:'bytes=0-939'});
  request('unrelated','https://www.googleapis.com/drive/v3/files/mock-other-file');request('suffix','https://mock.invalid/__drive_media/mock-exact-file-suffix');request('corpus','https://www.googleapis.com/drive/v3/files');
  cdp.emit('Network.responseReceived',{requestId:'private-id2',timestamp:10.5,response:{status:206,headers:{'Content-Length':'940',Authorization:'PRIVATE_TOKEN'},fromServiceWorker:true}});
  cdp.emit('Network.loadingFinished',{requestId:'private-id2',timestamp:10.75,encodedDataLength:940});cdp.emit('Network.loadingFailed',{requestId:'private-id1',timestamp:11,errorText:'PRIVATE_FAILURE',canceled:true});
  let r=n.snapshot();assert.equal(r.counts.requests,2);assert.equal(r.rows.find(x=>x.event==='response').elapsedMs,500);assert.equal(r.rows.find(x=>x.event==='response').length,940);assert.equal(r.rows.find(x=>x.event==='response').fromServiceWorker,true);assert.equal(r.rows.find(x=>x.event==='failed').failureSHA256,crypto.createHash('sha256').update('PRIVATE_FAILURE').digest('hex'));
  for(let i=0;i<140;i++)request('private-next'+i,'https://mock.invalid/__drive_media/mock-exact-file',{Range:'bytes=0-939'});r=n.snapshot();assert.equal(r.rows.length,128);assert.equal(r.counts.pending,64);assert.ok(r.counts.evicted>0);assert.ok(r.counts.pendingEvicted>0);
  const text=JSON.stringify(r);for(const secret of ['mock-exact-file','mock-other-file','private-id','PRIVATE_QUERY','PRIVATE_TOKEN','PRIVATE_RESOURCE','PRIVATE_FAILURE','headers','url','body'])assert.equal(text.includes(secret),false);assert.equal(r.allWorkerNetworkCoverage,'UNKNOWN');assert.equal(r.responseBodiesRetained,false);
  assert.equal(Object.values(await n.stop()).every(v=>v===true),true);assert.equal(cdp.listeners.size,0);assert.equal(n.snapshot().counts.pending,0);const count=n.snapshot().counts.requests;request('late','https://mock.invalid/__drive_media/mock-exact-file');assert.equal(n.snapshot().counts.requests,count);assert.deepEqual(cdp.sent,['Network.enable','Network.disable']);});
test('Network enable failure keeps original exception and still removes exact listener/pending before disable failure',async()=>{const cdp=networkMock(true,true),n=driver.networkTrace(cdp,'mock-exact-file','https://mock.invalid');let original;try{await n.enable();}catch(e){original=e;}assert.equal(original.message,'CDP_ORIGINAL_ENABLE_FAILURE');
  await assert.rejects(n.stop(),/CDP_DISABLE_FAILURE/);assert.equal(cdp.listeners.size,0);assert.equal(n.snapshot().counts.pending,0);assert.equal(original.message,'CDP_ORIGINAL_ENABLE_FAILURE');await assert.rejects(n.enable(),/AAC_NETWORK_OBSERVER_STOPPED/);
  const code=fs.readFileSync(path.join(__dirname,'driver.cjs'),'utf8');assert.ok(code.indexOf('await bounded(network.enable()')<code.indexOf("operation='install exact private context and observers'"));assert.ok(code.indexOf('network.stop()')<code.indexOf('cdp.close()'));assert.match(code,/report\.mainFailure=safeFailure\(e,operation\)/);assert.match(code,/report\.networkCleanupFailure=safeFailure/);});
test('passive credential fields and same-candidate request status discriminate auth wait without refreshing credentials',async()=>{const m=mock();m.ctx.state.expiresAt=Date.now()+60000;m.ctx.state.tokenRevision=4;await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;
  let r=h.read();assert.equal(r.passiveTrace.initialCredential.revisionChanged,false);assert.ok(r.passiveTrace.initialCredential.tokenRemainingMs>59000);assert.equal(r.credentialObservation.credentialPending,false);
  m.ctx.credentialRequestPromise=Promise.resolve();m.ctx.credentialRequestOutcome={generation:4,responseOk:false,retryable:true};m.ctx.state.tokenRevision=5;r=h.read();assert.equal(r.credentialObservation.credentialPending,true);assert.equal(r.credentialObservation.responseOK,false);assert.equal(r.credentialObservation.retryable,true);assert.equal(r.credentialObservation.outcomeCurrent,true);assert.equal(r.credentialObservation.revisionChanged,true);assert.equal(m.calls.length,0);assert.equal(h.stop().traceCleared,true);
  const cdp=networkMock(),n=driver.networkTrace(cdp,'mock-exact-file','https://mock.invalid');await n.enable();cdp.emit('Network.requestWillBeSent',{requestId:'PRIVATE_CREDENTIAL_ID',timestamp:20,request:{method:'POST',url:'https://mock.invalid/api/session/credential?PRIVATE_QUERY',postData:'PRIVATE_BODY',headers:{Cookie:'PRIVATE_COOKIE'}}});
  cdp.emit('Network.requestWillBeSent',{requestId:'foreign',timestamp:20,request:{method:'POST',url:'https://foreign.invalid/api/session/credential'}});cdp.emit('Network.responseReceived',{requestId:'PRIVATE_CREDENTIAL_ID',timestamp:21,response:{status:503,headers:{}}});
  const v=n.snapshot();assert.equal(v.counts.requests,1);assert.equal(v.rows[0].kind,'CREDENTIAL');assert.equal(v.rows[1].status,503);assert.equal(v.rows[1].elapsedMs,1000);for(const secret of ['PRIVATE_CREDENTIAL_ID','PRIVATE_QUERY','PRIVATE_BODY','PRIVATE_COOKIE','foreign.invalid'])assert.equal(JSON.stringify(v).includes(secret),false);await n.stop();assert.equal(cdp.listeners.size,0);});
test('owned socket event dispatch removes every listener after normal or already-closed cleanup without a real connection',async()=>{const Original=global.WebSocket;let instance;
  class MockSocket{static CLOSED=3;constructor(){instance=this;this.readyState=1;this.listeners=new Map();queueMicrotask(()=>this.emit('open',{}));}addEventListener(kind,fn,options){if(!this.listeners.has(kind))this.listeners.set(kind,new Map());this.listeners.get(kind).set(fn,options);}removeEventListener(kind,fn){this.listeners.get(kind)?.delete(fn);}emit(kind,event){for(const [fn,options]of [...(this.listeners.get(kind)||[])]){if(options?.once)this.removeEventListener(kind,fn);fn(event);}}send(text){const {id}=JSON.parse(text);queueMicrotask(()=>this.emit('message',{data:JSON.stringify({id,result:{ok:true}})}));}close(){this.readyState=3;this.emit('close',{});}}
  global.WebSocket=MockSocket;try{for(const closedEarly of [false,true]){const s=await driver.socket('ws://mock.invalid'),seen=[];const remove=s.onEvent((method,p)=>seen.push({method,p}));instance.emit('message',{data:JSON.stringify({method:'Network.loadingFinished',params:{encodedDataLength:7}})});assert.equal(seen.length,1);assert.equal((await s.send('Network.enable')).ok,true);remove();instance.emit('message',{data:JSON.stringify({method:'Network.loadingFinished',params:{}})});assert.equal(seen.length,1);if(closedEarly)instance.close();assert.equal(await s.close(),true);assert.equal([...instance.listeners.values()].reduce((n,set)=>n+set.size,0),0);}}
  finally{global.WebSocket=Original;}});
test('monotonic helper deadline stops frame/input qualification but permits exact-owner ordinary cleanup',async()=>{
  for(const expiryPath of ['read','frame','timer','callback-entry-to-read']){const m=mock();await m.install();const h=m.ctx.window.__rc37AndroidActualAAC;await h.locate();h.open();m.frame();assert.equal(h.read().current,true);
    if(expiryPath==='callback-entry-to-read'){m.clockValues(179999,180001);m.frame();}else{m.advance(180001);if(expiryPath==='timer')m.fireDeadline();else if(expiryPath==='frame')m.frame();}
    const r=h.read();assert.equal(r.deadlineExpired,true);assert.equal(r.fence,false);assert.equal(r.current,false);assert.equal(r.routeCurrent,false);assert.equal(r.cleanupCurrent,true);assert.equal(m.callbackCount(),0);
    assert.throws(()=>h.captureNative(),/AAC_NATIVE_ADMISSION/);assert.throws(()=>h.selectionReady(),/AAC_SELECTION_ADMISSION/);assert.throws(()=>h.open(),/AAC_OPEN_ADMISSION/);await assert.rejects(h.verify(),/AAC_VERIFY_ADMISSION/);
    assert.throws(()=>h.stop(),/AAC_CLOSE_UNSETTLED/);m.close();assert.equal(Object.values(h.stop()).every(v=>v===true),true);assert.equal(m.eventCount(),0);}
  const code=fs.readFileSync(path.join(__dirname,'driver.cjs'),'utf8');assert.match(code,/if\(!r\.cleanupCurrent\)throw Error\('AAC_CLEANUP_OWNER_CHANGED'\)/);assert.match(code,/if\(!current\.cleanupCurrent\)throw Error\('AAC_CLEANUP_OWNER_CHANGED'\)/);
});
