import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const base=new URL('./',import.meta.url),json=async p=>JSON.parse(await readFile(new URL(p,base),'utf8'));
const pcm=await json('pcm-results.json'),start=await json('startup-and-progress-results.json'),trace=await json('trace-results.json'),bg=await json('background-attempt-results.json'),seek=await json('keyboard-seek-result.json'),close=await json('close-results.json');
assert.equal(pcm.result.passed,true);assert.equal(pcm.result.revoked,true);assert.equal(pcm.result.events.at(-1).event,'ended');assert.equal(pcm.result.events.at(-1).time,0.5);assert(pcm.result.events.every(e=>!e.errorCode));
const first=trace.events.find(e=>e.stage==='first-decoded-frame');assert(first);assert(!trace.events.some(e=>/error|unavailable|failure/.test(e.stage)));
assert.equal(start.stable.q1,true);assert.equal(start.stable.readyState,4);assert.equal(start.stable.paused,false);assert(start.stable.frames>0);assert(start.beforeBackgroundAttempt.currentTime>start.stable.currentTime);
assert.equal(bg.passed,false);assert.equal(bg.code,'REAL_HIDDEN_STATE_NOT_OBSERVED');assert.equal(bg.result.visibility.length,0);assert(bg.result.samples.length>0);assert(bg.result.samples.every(e=>e.visible==='visible'&&e.ownerCurrent&&e.q1&&!e.errorCode));assert(bg.result.frames.length>0);assert(bg.result.frames.every(e=>e.ownerCurrent&&e.visible==='visible'));
assert.equal(seek.result.readyState,4);assert.equal(seek.result.errorCode,null);assert(Math.abs(seek.result.currentTime-seek.beforeTime-seek.requestedDeltaSeconds)<0.001);assert.equal(close.resumeProgress.paused,false);assert(close.resumeProgress.currentTime>seek.result.currentTime);assert.equal(close.cleanup.playerHidden,true);assert.equal(close.cleanup.selected,false);assert.equal(close.cleanup.q1,false);assert.equal(close.cleanup.retirementSettled,true);assert.equal(close.cleanup.sourcePresent,false);assert.equal(close.cleanup.traceSink,false);
const producers=['pcm.expression.js','native-events.expression.js','trace.expression.js','sample.expression.js','sample-corrected.expression.js','background-observer.expression.js','validate.mjs'];const producerSHA256={};for(const p of producers)producerSHA256[p]=createHash('sha256').update(await readFile(new URL(p,base))).digest('hex');assert.equal(producerSHA256['pcm.expression.js'],pcm.producerSha256);assert.equal(producerSHA256['background-observer.expression.js'],bg.producerSha256);
const records=['pcm-results.json','startup-and-progress-results.json','trace-results.json','background-attempt-results.json','keyboard-seek-result.json','close-results.json','native-before-seek.json'];const recordSHA256={};for(const p of records){const bytes=await readFile(new URL(p,base));assert(!/Bearer |accessToken"\s*:|refreshToken"\s*:|www.googleapis.com\/drive\/v3\/files\/|accounts.google.com|drive.google.com/.test(bytes.toString()));recordSHA256[p]=createHash('sha256').update(bytes).digest('hex');}
const result={schema:'drive-original.pc-postreboot-rc11/1',recordedAt:new Date().toISOString(),candidateSource:pcm.source,version:pcm.version,scope:'Actual intended user Chrome; post-reboot PCM and original Q1 playback/keyseek/close; real hidden-return unperformed',pcmPassed:true,q1StartupPassed:true,firstDecodedFrameMs:first.elapsedMs,presentedFrameCallbacks:bg.result.frames.length,visibleProgress:{from:bg.result.frames[0].mediaTime,to:bg.result.frames.at(-1).mediaTime},keyboardSeekPassed:true,closePassed:true,actual30sBackgroundReturn:'not-run: hidden state never observed',lowerPreRebootAudioCause:'unknown',outputSettingsChanged:false,originalMediaChanged:false,productChanged:false,scopeLimits:['One priority MPEG-TS/H264/AAC file; no whole format/audio-output audibility/physical-device claims','No actual OS sleep/wake or hidden return','Initial invalid field projections excluded; corrected samples own conclusions','Trace max512 events and180s ownership; no full traffic/continuous walltime or historic299s claim'],producerSHA256,recordSHA256};await writeFile(new URL('results.json',base),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
