import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {build} from './build.mjs';
const base=new URL('./',import.meta.url),hash=x=>createHash('sha256').update(x).digest('hex');
const result=await build();await writeFile(new URL('factory.expression.js',base),result.expression);await writeFile(new URL('sw-proof.expression.js',base),result.swProof);await writeFile(new URL('provenance.json',base),JSON.stringify(result.provenance,null,2)+'\n');
assert.equal(hash(await readFile(new URL('factory.expression.js',base))),result.provenance.expressionSHA256);assert.equal(typeof vm.runInNewContext(result.expression,{}),'function');
const focused=execFileSync(process.execPath,['--test','--test-reporter=tap','qa/rc22-corpus-headers/probe.test.mjs'],{encoding:'utf8',timeout:30000});assert.match(focused,/# tests 21/);assert.match(focused,/# pass 21/);assert.match(focused,/# fail 0/);await writeFile(new URL('local-tests.tap',base),focused);
const paths=['qa/v2-07a-bounded-probe/bounded-probe.test.mjs','qa/v2-07a-bounded-probe/drive-browser-adapter.test.mjs','qa/v2-07a-root-inventory/root-inventory.test.mjs','qa/v2-07a-root-inventory/drive-browser-adapter.test.mjs','qa/v2-07a-representative-selection/representative-selector.test.mjs'];
const affected=execFileSync(process.execPath,['--test','--test-reporter=tap',...paths],{encoding:'utf8',timeout:30000});const affectedCount=Number(/# tests (\d+)/.exec(affected)[1]);assert.match(affected,/# fail 0/);await writeFile(new URL('affected-contract-tests.tap',base),affected);
const normalizerSource=await readFile(new URL('../v2-07a-root-inventory/root-inventory.mjs',base),'utf8'),copies=await readFile(new URL('inventory-normalizers.mjs',base),'utf8');for(const name of ['normalizeIntegerString','normalizeCapability','stableItemRow']){const match=normalizerSource.match(new RegExp('function '+name+'\\([\\s\\S]*?\\n\\}'));assert.ok(copies.includes(match[0].replace('function '+name,'export function '+name)));}
const owned=['binding.json','inventory-normalizers.mjs','selection.mjs','continuity.mjs','probe.mjs','facade.function.js','sw-proof.function.js','build.mjs','bind-source.mjs','probe.test.mjs','factory.expression.js','sw-proof.expression.js','provenance.json','README.md','verify.mjs','local-tests.tap','affected-contract-tests.tap'];
const files=Object.fromEntries(await Promise.all(owned.map(async p=>[p,hash(await readFile(new URL(p,base)))])));
const record={schema:'drive-original.bounded-corpus-headers-local-verification/1',sourceHEAD:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),bound:result.provenance.bound,expectedVersion:result.provenance.binding.version,expressionSHA256:result.provenance.expressionSHA256,swProofSHA256:result.provenance.swProofSHA256,files,focused:{passed:21,failed:0},affectedContracts:{passed:affectedCount,failed:0},synthetic500ObjectProgression:true,syntheticRenewalPendingRevalidation:true,actualExecution:false,wholeCorpusComplete:false,productChanges:false,genericUpstreamCleanup:'unknown'};
await writeFile(new URL('local-verification.json',base),JSON.stringify(record,null,2)+'\n');await writeFile(new URL('curated-savepoint.json',base),JSON.stringify({schema:'drive-original.bounded-corpus-headers-savepoint/1',exactOwnedFiles:[...owned,'local-verification.json','curated-savepoint.json'].map(p=>'qa/rc22-corpus-headers/'+p),commitOwner:'root',excluded:['all actual browser results','all source product/shared docs','all rc16/rc21 producers/evidence','private contexts/tokens/manifests/media','binding to an unfixed source identity']},null,2)+'\n');
console.log(JSON.stringify({bound:record.bound,expectedVersion:record.expectedVersion,expressionSHA256:record.expressionSHA256,swProofSHA256:record.swProofSHA256,focused:record.focused,affectedContracts:record.affectedContracts}));
