'use strict';
// Existing credential in memory only. Canonical CLI may refresh the same OAuth session; no login/grant/token creation.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),wd=path.join(root,'worker'),workerVersion='c57f634a-377d-487e-aa81-61875598dd1d',source='8a2894ee2c7aa85c9cb2ff992879f4580e15e2e7';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),bool=v=>typeof v==='boolean'?v:null,num=v=>typeof v==='number'&&Number.isFinite(v)?v:null;
const result={schema:'drive-original.rc24-hosting-readonly/1',source,workerVersion,producerSha256:sha(fs.readFileSync(__filename)),startedAt:new Date().toISOString(),readOnly:true,browserUsed:false,candidateRequests:0,logsRead:false,individualRequestsRead:false,settingsWrites:0,authRefresh:false,rawBodiesSaved:false,endpoints:[],complete:false};
let token,accountId,authBytes,authFile,total=0;const started=Date.now();
function settings(v){const o=v?.observability;return {observabilityPresent:Object.hasOwn(v||{},'observability'),observabilityExplicitNull:o===null,enabled:bool(o?.enabled),logsEnabled:bool(o?.logs?.enabled),tracesEnabled:bool(o?.traces?.enabled),logsPersist:bool(o?.logs?.persist),tracesPersist:bool(o?.traces?.persist),logsSampling:num(o?.logs?.head_sampling_rate),tracesSampling:num(o?.traces?.head_sampling_rate),logpush:bool(v?.logpush),tailConsumerCount:Array.isArray(v?.tail_consumers)?v.tail_consumers.length:null,cpuLimitMs:num(v?.limits?.cpu_ms),usageModel:['standard','bundled','unbound'].includes(v?.usage_model)?v.usage_model:null};}
async function read(category,suffix,query){
 if(result.endpoints.length>=12||Date.now()-started>150000)throw Error('READ_BUDGET');
 const allowed=new Set(['workers/scripts/drive-original-v2-candidate/deployments?per_page=1&page=1','workers/scripts/drive-original-v2-candidate/script-settings','workers/scripts/drive-original-v2-candidate/settings',`workers/scripts/drive-original-v2-candidate/versions/${workerVersion}`,'workers/account-settings','subscriptions','billing/usage']);if(!query&&!allowed.has(suffix))throw Error('ENDPOINT_SCOPE');
 const event={category,status:null,success:false,bytes:0,errorCodes:[],readOnly:true};result.endpoints.push(event);const signal=AbortSignal.timeout(15000);
 const response=await fetch(query?'https://api.cloudflare.com/client/v4/graphql':`https://api.cloudflare.com/client/v4/accounts/${accountId}/${suffix}`,{method:query?'POST':'GET',headers:{Authorization:`Bearer ${token}`,Accept:'application/json',...(query?{'Content-Type':'application/json'}:{})},...(query?{body:JSON.stringify(query)}:{}),redirect:'error',cache:'no-store',credentials:'omit',signal});event.status=response.status;
 const reader=response.body.getReader(),chunks=[];try{for(;;){const x=await reader.read();if(x.done)break;event.bytes+=x.value.length;total+=x.value.length;if(event.bytes>262144||total>1048576){await reader.cancel();throw Error('BODY_LIMIT');}chunks.push(Buffer.from(x.value));}const raw=Buffer.concat(chunks);let j;try{j=JSON.parse(raw.toString());}finally{raw.fill(0);chunks.forEach(b=>b.fill(0));}event.errorCodes=(j.errors||[]).map(e=>num(e.code)).filter(x=>x!==null);event.graphqlErrorCount=query?j.errors?.length||0:null;event.success=response.status===200&&(query?!j.errors?.length:j.success===true);return event.success?(query?j.data:j.result):null;}finally{reader.releaseLock();}
}
const active=v=>{const versions=v?.deployments?.[0]?.versions;return Array.isArray(versions)&&versions.length===1&&versions[0].version_id===workerVersion&&versions[0].percentage===100;};
(async()=>{try{
 const cfg=JSON.parse(fs.readFileSync(path.join(wd,'wrangler.jsonc')));if(cfg.name!=='drive-original-v2-candidate'||cfg.vars.CANDIDATE_DRIVE_WRITES_ENABLED!=='false')throw Error('CONFIG_SCOPE');
 accountId=JSON.parse(fs.readFileSync(path.join(wd,'node_modules/.cache/wrangler/wrangler-account.json'))).account?.id;if(!/^[a-f0-9]{32}$/.test(accountId))throw Error('ACCOUNT_SCOPE');
 authFile=[path.join(os.homedir(),'.wrangler/config/default.toml'),path.join(process.env.APPDATA||'','xdg.config/.wrangler/config/default.toml')].find(f=>fs.existsSync(f));if(!authFile)throw Error('EXISTING_AUTH_UNAVAILABLE');authBytes=fs.readFileSync(authFile);let authText=authBytes.toString();let expiration=/^expiration_time\s*=\s*"([^"]+)"/m.exec(authText)?.[1];result.existingCredentialExpired=expiration?Date.parse(expiration)<=Date.now():null;
 if(result.existingCredentialExpired){const command=cp.spawnSync(process.execPath,[path.join(wd,'node_modules/wrangler/bin/wrangler.js'),'whoami','--config','wrangler.jsonc','--install-skills','false'],{cwd:wd,encoding:'utf8',timeout:30000,maxBuffer:65536,windowsHide:true,env:{...process.env,WRANGLER_WRITE_LOGS:'false',WRANGLER_SEND_METRICS:'false',CI:'true'}});command.stdout=null;command.stderr=null;result.canonicalRefreshCommandSucceeded=command.status===0&&!command.error;const newer=fs.readFileSync(authFile);result.credentialStoreChangedViaCanonicalOwner=!authBytes.equals(newer);authText=newer.toString();newer.fill(0);expiration=/^expiration_time\s*=\s*"([^"]+)"/m.exec(authText)?.[1];result.authRefresh=true;result.credentialExpiredAfterCanonicalOwner=expiration?Date.parse(expiration)<=Date.now():true;if(!result.canonicalRefreshCommandSucceeded||result.credentialExpiredAfterCanonicalOwner)throw Error('EXISTING_AUTH_EXPIRED');}
 token=/^oauth_token\s*=\s*"([^"]+)"/m.exec(authText)?.[1];authText=null;if(!token||token.length>16384)throw Error('EXISTING_AUTH_UNAVAILABLE');
 result.fixedDeploymentBefore=active(await read('fixed-deployment-before','workers/scripts/drive-original-v2-candidate/deployments?per_page=1&page=1'));if(!result.fixedDeploymentBefore)throw Error('DEPLOYMENT_SCOPE');
 const a=await read('script-settings','workers/scripts/drive-original-v2-candidate/script-settings'),b=await read('combined-settings','workers/scripts/drive-original-v2-candidate/settings'),v=await read('fixed-version-settings',`workers/scripts/drive-original-v2-candidate/versions/${workerVersion}`);if(v?.id!==workerVersion)throw Error('VERSION_SCOPE');result.settings={script:settings(a),combined:settings(b),version:settings(v.resources?.script||v)};
 const acct=await read('account-settings','workers/account-settings');result.accountSettings={available:!!acct,defaultUsageModel:['standard','bundled','unbound'].includes(acct?.default_usage_model)?acct.default_usage_model:null};
 const subs=await read('subscriptions','subscriptions');result.subscription={available:Array.isArray(subs),workersFreeActive:Array.isArray(subs)?subs.some(x=>/workers.*free/i.test(x.rate_plan?.public_name||x.rate_plan?.name||'')&&x.state==='active'):null};
 const bill=await read('billing-usage','billing/usage');result.billing={available:!!bill,currentBillingPeriodUsageKnown:false,automaticBilling:null,automaticUpgrade:null};
 const end=new Date().toISOString(),start=end.slice(0,10)+'T00:00:00.000Z';result.metricWindow={start,end,scope:'Current UTC day aggregate, not billing-period exact usage or version-only traffic'};
 const q='query($tag:string,$start:string,$end:string,$script:string){viewer{accounts(filter:{accountTag:$tag}){candidate:workersInvocationsAdaptive(limit:1,filter:{scriptName:$script,datetime_geq:$start,datetime_leq:$end}){sum{requests errors subrequests}quantiles{cpuTimeP50 cpuTimeP99}}accountTotal:workersInvocationsAdaptive(limit:1,filter:{datetime_geq:$start,datetime_leq:$end}){sum{requests errors subrequests}}durableObjectsPeriodicGroups(limit:1,filter:{datetime_geq:$start,datetime_leq:$end}){sum{rowsRead rowsWritten exceededCpuErrors}}durableObjectsSqlStorageGroups(limit:1,filter:{datetime_geq:$start,datetime_leq:$end}){max{storedBytes}}}}}';
 const data=await read('aggregate-metrics',null,{query:q,variables:{tag:accountId,start,end,script:'drive-original-v2-candidate'}});const metrics=data?.viewer?.accounts?.[0];result.metrics=metrics?{candidate:metrics.candidate.map(x=>({requests:num(x.sum.requests),errors:num(x.sum.errors),subrequests:num(x.sum.subrequests),cpuP50:num(x.quantiles.cpuTimeP50),cpuP99:num(x.quantiles.cpuTimeP99)})),account:metrics.accountTotal.map(x=>({requests:num(x.sum.requests),errors:num(x.sum.errors),subrequests:num(x.sum.subrequests)})),durableObjects:metrics.durableObjectsPeriodicGroups.map(x=>({rowsRead:num(x.sum.rowsRead),rowsWritten:num(x.sum.rowsWritten),exceededCpuErrors:num(x.sum.exceededCpuErrors)})),sqlStorage:metrics.durableObjectsSqlStorageGroups.map(x=>({maxStoredBytes:num(x.max.storedBytes)})),cpuUnits:'GraphQL schema unit must be verified; numeric metrics are not cost',adaptiveSampling:true,sqlInterpretation:'maximum storedBytes aggregate during window, not exact instantaneous billing storage'}:null;
 result.fixedDeploymentAfter=active(await read('fixed-deployment-after','workers/scripts/drive-original-v2-candidate/deployments?per_page=1&page=1'));result.complete=result.fixedDeploymentBefore&&result.fixedDeploymentAfter&&!!metrics;
 result.unknowns=['effective observability when API returns null/omitted','retention/history/provider infrastructure logging','automatic billing/automatic upgrade','exact current billing period usage','real quota-exhaustion behavior'];
 }catch(e){result.failure=['READ_BUDGET','ENDPOINT_SCOPE','BODY_LIMIT','CONFIG_SCOPE','ACCOUNT_SCOPE','EXISTING_AUTH_UNAVAILABLE','EXISTING_AUTH_EXPIRED','DEPLOYMENT_SCOPE','VERSION_SCOPE'].includes(e.message)?e.message:'READ_FAILED';}finally{result.credentialStoreUnchanged=authBytes&&authFile?authBytes.equals(fs.readFileSync(authFile)):null;authBytes?.fill(0);token=null;accountId=null;result.finishedAt=new Date().toISOString();result.elapsedMs=Date.now()-started;fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({complete:result.complete,endpointCount:result.endpoints.length,statuses:result.endpoints.map(x=>({category:x.category,status:x.status,success:x.success})),failure:result.failure}));}})();
