'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const fixtureRows=[{name:'q2',file:'qa/q2-audio-compatibility/eac3-source-build/synthetic-avc-eac3-stereo.mp4',sha256:'40ce156ee1a209d87e81c227fa2aaf7fa54558f31708d52bdbae3714e879796f',width:320,height:180},{name:'q3',file:'qa/q3-browser-execution/synthetic-mpeg4.mp4',sha256:'4f9a6394d01776a88e198a90e829b7b369c8303ec1fe86d386637439a00585da',width:320,height:180}];
const maintained=['qa/q1-q2-app-integration/native-eac3-auto.cjs','qa/q1-q2-app-integration/native-aac-preserve.cjs','qa/q3-product-integration/browser-audit.cjs','qa/q3-product-integration/fixture.mjs'];
const files=()=>[...require('../../scripts/public-files.cjs'),...maintained,'qa/rc38-normalized-position-native/actor.cjs','qa/rc38-normalized-position-native/browser.function.js'];
const hashes=()=>Object.fromEntries(files().map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]));
function preparation(){const fixtures=fixtureRows.map(row=>{const b=fs.readFileSync(path.join(root,row.file));assert.equal(sha(b),row.sha256);assert.ok(b.length<=1048576);return {...row,size:b.length};});return {schema:'normalized-position-native-preparation/1',version:JSON.parse(fs.readFileSync(path.join(root,'version.json'))).version,producers:hashes(),fixtures,position:1,seek:.5,limits:{phaseMs:15000,totalMs:160000,requestsPerCase:512,bodyBytesPerCase:24*1024*1024},scope:'Full local app/SW, synthetic read-only provider, isolated owned Chrome; app Q2 entry and normal labelled Q3 choice; no real account/device/p95/fidelity claim',runtimeReadyClaimed:false};}
function qualify(initial,seek,name){
 assert.ok(initial.valid&&!initial.overflow&&initial.paused,'INITIAL_OWNER_PAUSED');assert.equal(initial.stats.generation,1,'INITIAL_GENERATION');assert.equal(initial.workers.length,1,'INITIAL_SINGLE_WORKER');const worker=initial.workers[0];assert.equal(worker.starts.length,1,'INITIAL_SINGLE_START');assert.equal(worker.starts[0].generation,1);assert.equal(worker.starts[0].targetTime,0);assert.equal(worker.starts[0].initialPresentationTime,1);assert.equal(worker.windows.length,1);assert.ok(Number.isFinite(worker.windows[0].initialSourceTime));
 assert.ok(Math.abs(initial.stats.mapping.targetSource-(initial.stats.mapping.sourceOrigin+1))<.001);assert.ok(Math.abs(worker.windows[0].initialSourceTime-initial.stats.mapping.targetSource)<.001);assert.ok(initial.frames.some(f=>f.current&&Math.abs(f.sourceTime-initial.stats.mapping.targetSource)<.13&&f.width===320&&f.height===180));assert.ok(Math.abs(initial.sourceTime-initial.stats.mapping.targetSource)<.13);
 assert.ok(seek.valid&&seek.paused&&!seek.overflow,'SEEK_OWNER_PAUSED');assert.equal(seek.stats.generation,2);assert.equal(seek.workersAfterSeek,1);assert.equal(seek.workers.length,2);assert.equal(seek.workers[1].starts.length,1);assert.equal(seek.workers[1].starts[0].initialPresentationTime,undefined);assert.equal(seek.workers[1].starts[0].targetTime,seek.requestedAbsolute);assert.ok(seek.frames.some(f=>f.current&&Math.abs(f.sourceTime-seek.requestedAbsolute)<.13));
 if(name==='q2'){assert.equal(initial.stats.status.level,'Q2');assert.equal(initial.stats.pipeline.videoCodec,'avc');assert.equal(initial.stats.pipeline.videoEncodersCreated,0);assert.ok(initial.stats.pipeline.audioMetrics.transferredPcmBytes>0);}else{assert.equal(initial.stats.status.level,'Q3');assert.equal(initial.workers[0].windows[0].audioCodec,null);assert.ok(initial.labelLossy);}
}
function range(header,size){const m=/^bytes=(\d+)-(\d*)$/.exec(header||'');if(!m)return null;const start=Number(m[1]),end=m[2]?Number(m[2]):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||end>=size||end-start+1>1048576)throw Error('RANGE_ADMISSION');return {start,end};}
function requestCategory(method,url,headers={}) {
 const u=new URL(url);const exact=u.origin==='https://www.googleapis.com'&&['/drive/v3/files/fixture','/drive/v3/files/fixture/download','/drive/v3/files/fixture/revisions/A'].includes(u.pathname);const category=u.pathname.endsWith('/download')?'download':u.searchParams.get('alt')==='media'?'media':'metadata';
 if(method==='OPTIONS'){const requested=headers['access-control-request-method'],names=(headers['access-control-request-headers']||'').toLowerCase().split(',').map(v=>v.trim()).filter(Boolean);return {category:'preflight',valid:exact&&requested==='GET'&&names.every(v=>['authorization','range','x-goog-drive-resource-keys'].includes(v)),requestedCategory:category};}
 return {category,valid:exact&&method==='GET'};
}
function routeAdmission(req,count,max){
 const c=requestCategory(req.method(),req.url(),req.headers());if(count>max)return {action:'abort',classification:c};
 if(!c.valid)return {action:'reject',classification:c};
 if(req.method()==='OPTIONS')return {action:'preflight',classification:c,response:{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET','access-control-allow-headers':'Authorization, Range, X-Goog-Drive-Resource-Keys','cache-control':'no-store'},body:''}};
 return {action:'get',classification:c};
}
function safeError(e){const value=e?.message;return typeof value==='string'&&/^[A-Z0-9_]+$/.test(value)?value:e?.code==='ERR_ASSERTION'?'ASSERTION_'+String(e.actual===undefined?'MISSING':'MISMATCH'):'CASE_FAILURE';}
async function bounded(p,ms,label){let t;try{return await Promise.race([p,new Promise((_,reject)=>t=setTimeout(()=>reject(Error(label)),ms))]);}finally{clearTimeout(t);}}
async function run(prep,out){
 assert.deepEqual(prep.producers,hashes(),'PREPARED_SOURCE_CHANGED');assert.deepEqual(prep.fixtures,preparation().fixtures);const resultFd=fs.openSync(out,'wx');const report={schema:'normalized-position-native-result/1',scope:prep.scope,version:prep.version,producerBefore:hashes(),startedAt:new Date().toISOString(),cases:[],cleanup:{},passed:false};fs.writeSync(resultFd,JSON.stringify({schema:report.schema,startedAt:report.startedAt,passed:false,inProgress:true})+'\n');
 let server,browserServer,browser,context;const allowed=new Set(require('../../scripts/public-files.cjs')),end=Date.now()+prep.limits.totalMs;
 try{
  const {chromium}=require('../node_modules/playwright');
  server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(req.method!=='GET'||!allowed.has(name))return res.writeHead(404).end();const b=fs.readFileSync(path.join(root,name));res.writeHead(200,{'Content-Type':name.endsWith('.wasm')?'application/wasm':/\.(?:mjs|js)$/.test(name)?'text/javascript':name.endsWith('.html')?'text/html':name.endsWith('.json')?'application/json':name.endsWith('.css')?'text/css':'application/octet-stream','Cache-Control':'no-store'}).end(b);});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
  browserServer=await chromium.launchServer({channel:'chrome',headless:true,timeout:7000});browser=await chromium.connect(browserServer.wsEndpoint());report.browser=browser.version();
  for(const f of prep.fixtures){assert.ok(Date.now()<end,'UNIT_DEADLINE');const bytes=fs.readFileSync(path.join(root,f.file)),row={name:f.name,fixture:f,requests:0,mediaBytes:0,requestClasses:{GET:0,OPTIONS:0,other:0,metadata:0,media:0,download:0,preflight:0,rejected:0,localMedia:0},phase:'context',errors:[],passed:false};report.cases.push(row);let page;
   try{
    context=await browser.newContext();await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===origin){if(u.pathname.includes('/__drive_media/'))row.requestClasses.localMedia++;return route.continue();}if(u.origin!=='https://www.googleapis.com')return route.fulfill({status:403,body:'{}'});row.requests++;const c=requestCategory(req.method(),req.url(),req.headers());row.requestClasses[['GET','OPTIONS'].includes(req.method())?req.method():'other']++;row.requestClasses[c.category]++;if(!c.valid)row.requestClasses.rejected++;const admission=routeAdmission(req,row.requests,prep.limits.requestsPerCase);if(admission.action==='abort')return route.abort();if(admission.action==='reject')return route.fulfill({status:403,body:'{}'});if(admission.action==='preflight')return route.fulfill(admission.response);const headers={'access-control-allow-origin':'*','access-control-expose-headers':'content-range,content-length,content-type','cache-control':'no-store'};if(!u.searchParams.has('alt'))return route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify({id:'fixture',headRevisionId:'A',version:'1',size:String(bytes.length),mimeType:'video/mp4',modifiedTime:'A',sha256Checksum:f.sha256,trashed:false,capabilities:{canDownload:true,canReadRevisions:true}})});let r;try{r=range(req.headers().range,bytes.length);}catch{return route.fulfill({status:416,body:''});}const body=r?bytes.subarray(r.start,r.end+1):bytes;row.mediaBytes+=body.length;if(row.mediaBytes>prep.limits.bodyBytesPerCase)return route.abort();return route.fulfill({status:r?206:200,headers:{...headers,'content-length':String(body.length),...(r?{'content-range':`bytes ${r.start}-${r.end}/${bytes.length}`}:{})},contentType:'video/mp4',body});});
    await context.route(/^https:\/\/www\.googleapis\.com\/drive\/v3\/files\/fixture\/download(?:\?.*)?$/,async route=>{const req=route.request();row.requests++;const c=requestCategory(req.method(),req.url(),req.headers());row.requestClasses[c.category]++;row.requestClasses[['GET','OPTIONS'].includes(req.method())?req.method():'other']++;if(!c.valid)row.requestClasses.rejected++;const admission=routeAdmission(req,row.requests,prep.limits.requestsPerCase);if(admission.action==='abort')return route.abort();if(admission.action==='reject')return route.fulfill({status:403,body:'{}'});if(admission.action==='preflight')return route.fulfill(admission.response);return route.fulfill({status:200,headers:{'access-control-allow-origin':'*','cache-control':'no-store'},contentType:'application/json',body:JSON.stringify({name:'synthetic/op',done:true,response:{'@type':'type.googleapis.com/google.apps.drive.v3.DownloadFileResponse',partialDownloadAllowed:true,downloadUri:'https://www.googleapis.com/drive/v3/files/fixture/revisions/A?alt=media'}})});});
    row.phase='page-admission';page=await context.newPage();page.on('pageerror',()=>row.errors.push('PAGE_ERROR'));await page.goto(origin);await page.waitForFunction(()=>navigator.serviceWorker.controller&&state.serviceWorkerRegistration?.active===navigator.serviceWorker.controller&&!state.serviceWorkerRegistration.waiting&&!state.serviceWorkerRegistration.installing&&typeof tryOriginalTsPlayback==='function',null,{timeout:15000});
    await page.evaluate(`(${fs.readFileSync(path.join(__dirname,'browser.function.js'),'utf8')})(${JSON.stringify({...f,position:prep.position,seek:prep.seek})})`);
    row.phase='prepare';if(f.name==='q2')await page.evaluate(()=>window.__normalizedCase.arm());row.choice=await bounded(page.evaluate(()=>window.__normalizedCase.prepare()),15000,'CHOICE_DEADLINE');
    if(f.name==='q3'){assert.ok(row.choice.choiceReady&&row.choice.labelLossy&&row.choice.paused&&row.choice.snapshotTime===1);await page.evaluate(()=>window.__normalizedCase.arm());await page.locator('#videoCompatButton').click();}
    row.phase='initial';row.initial=await bounded(page.evaluate(()=>window.__normalizedCase.initial()),15000,'INITIAL_DEADLINE');
    if(f.name==='q2'){row.audio=await bounded(page.evaluate(()=>window.__normalizedCase.audio()),3000,'AUDIO_DEADLINE');assert.ok(row.audio.nonzero>0&&row.audio.timeAdvanced&&row.audio.decodedPcmBytes>0);}
    row.phase='seek';row.seek=await bounded(page.evaluate(()=>window.__normalizedCase.seek()),15000,'SEEK_DEADLINE');row.phase='qualification';qualify(row.initial,row.seek,f.name);assert.equal(row.errors.length,0);row.passed=true;
   }catch(e){row.error=safeError(e);if(page)try{row.failureObservation=await bounded(page.evaluate(()=>window.__normalizedCase?.diagnose()),2000,'FAILURE_READ_DEADLINE');}catch{row.failureObservationUnavailable=true;}}
   finally{if(page)try{row.cleanup=await bounded(page.evaluate(()=>window.__normalizedCase?.close()),8000,'PLAYER_CLEANUP_DEADLINE');assert.ok(row.cleanup?.retirement?.settled&&row.cleanup.allWorkersTerminated&&row.cleanup.urlsRemaining===0&&row.cleanup.srcRemoved&&row.cleanup.q0Absent&&row.cleanup.q1Absent&&!row.cleanup.overflow);}catch{row.passed=false;row.cleanupUnconfirmed=true;}if(context){await bounded(context.close(),5000,'CONTEXT_CLOSE');context=null;row.contextClosed=true;}}
   if(!row.passed)break;
  }
 }catch(e){report.failure=/^[A-Z0-9_]+$/.test(e.message)?e.message:'RUN_FAILED';}
 finally{
  if(context)try{await bounded(context.close(),5000,'CONTEXT_CLOSE');report.cleanup.contextClosed=true;}catch{report.cleanup.contextClosed=false;}
  if(browser)try{await bounded(browser.close(),5000,'CONNECTION_CLOSE');report.cleanup.connectionClosed=true;}catch{report.cleanup.connectionClosed=false;}
  if(browserServer){try{await bounded(browserServer.close(),5000,'BROWSER_CLOSE');}catch{try{await bounded(browserServer.kill(),5000,'BROWSER_KILL');}catch{report.cleanup.browserKillUnconfirmed=true;}}report.cleanup.ownedBrowserProcessExited=browserServer.process().exitCode!==null||browserServer.process().signalCode!==null;}
  if(server){server.closeAllConnections?.();try{await bounded(new Promise(r=>server.close(r)),5000,'SERVER_CLOSE');report.cleanup.serverClosed=true;}catch{report.cleanup.serverClosed=false;}}
  report.producerAfter=hashes();report.producerStable=JSON.stringify(report.producerBefore)===JSON.stringify(report.producerAfter);report.passed=report.cases.length===2&&report.cases.every(r=>r.passed&&r.contextClosed)&&report.producerStable&&report.cleanup.connectionClosed&&report.cleanup.ownedBrowserProcessExited&&report.cleanup.serverClosed&&report.cleanup.contextClosed!==false&&Date.now()<=end;report.finishedAt=new Date().toISOString();fs.ftruncateSync(resultFd,0);fs.writeSync(resultFd,JSON.stringify(report,null,2)+'\n',0,'utf8');fs.closeSync(resultFd);console.log(JSON.stringify({passed:report.passed,out,cases:report.cases.map(r=>({name:r.name,passed:r.passed,error:r.error})),cleanup:report.cleanup}));if(!report.passed)process.exitCode=1;
 }
}
async function main(){const mode=process.argv[2],out=process.argv[process.argv.indexOf('--out')+1];assert.ok(['--prepare','--run'].includes(mode)&&process.argv.includes('--out')&&out&&!out.startsWith('--'),'EXPLICIT_MODE_OUTPUT');assert.equal(path.dirname(path.resolve(out)),__dirname,'OWNED_OUTPUT_ONLY');assert.ok(!fs.existsSync(out),'NO_OVERWRITE');if(mode==='--prepare'){const p=preparation();fs.writeFileSync(out,JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({prepared:true,out,version:p.version,fixtures:p.fixtures.map(f=>({name:f.name,size:f.size,sha256:f.sha256})),browserServerStarted:false}));}else{const arg=process.argv.indexOf('--prepared');assert.ok(arg>0);const p=JSON.parse(fs.readFileSync(process.argv[arg+1]));await run(p,out);}}
module.exports={range,qualify,preparation,requestCategory,routeAdmission,safeError};if(require.main===module)main().catch(()=>{console.error('NORMALIZED_ACTOR_FAILED');process.exitCode=1;});
