'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{range,qualify}=require('./actor.cjs');
function pair(name='q2',origin=0){const start={generation:1,targetTime:0,initialPresentationTime:1},window={initialSourceTime:origin+1,audioCodec:name==='q3'?null:'opus'},mapping={sourceOrigin:origin,targetSource:origin+1};const initial={valid:true,paused:true,overflow:false,sourceTime:origin+1,stats:{generation:1,mapping,status:{level:name==='q2'?'Q2':'Q3'},pipeline:{videoCodec:'avc',videoEncodersCreated:0,audioMetrics:{transferredPcmBytes:1024}}},workers:[{starts:[start],windows:[window]}],frames:[{current:true,sourceTime:origin+1,width:320,height:180}],labelLossy:true};const seek={valid:true,paused:true,overflow:false,requestedAbsolute:origin+.5,stats:{generation:2},workersAfterSeek:1,workers:[initial.workers[0],{starts:[{generation:2,targetTime:origin+.5}]}],frames:[{current:true,sourceTime:origin+.5}]};return {initial,seek};}
test('one normalized generation plus absolute seek qualifies at nonzero source origin',()=>{const p=pair('q2',17);qualify(p.initial,p.seek,'q2');});
test('Q3 noaudio native geometry and explicit loss label qualify scope',()=>{const p=pair('q3');qualify(p.initial,p.seek,'q3');});
test('old 0 initial then replacement generation cannot qualify',()=>{const p=pair();p.initial.workers.push(p.initial.workers[0]);p.initial.stats.generation=2;assert.throws(()=>qualify(p.initial,p.seek,'q2'));});
test('option presence with presented zero/stale target fails',()=>{for(const stale of [false,true]){const p=pair();p.initial.frames[0].sourceTime=0;p.initial.frames[0].current=!stale;assert.throws(()=>qualify(p.initial,p.seek,'q2'));}});
test('absolute seek cannot inherit normalized option',()=>{const p=pair();p.seek.workers[1].starts[0].initialPresentationTime=.5;assert.throws(()=>qualify(p.initial,p.seek,'q2'));});
test('Q2 must copy video and decode valid audio',()=>{for(const field of ['encoder','audio']){const p=pair();if(field==='encoder')p.initial.stats.pipeline.videoEncodersCreated=1;else p.initial.stats.pipeline.audioMetrics.transferredPcmBytes=0;assert.throws(()=>qualify(p.initial,p.seek,'q2'));}});
test('Range rejects overflow, suffix, beyond size and oversized read',()=>{assert.deepEqual(range('bytes=2-4',10),{start:2,end:4});assert.deepEqual(range('bytes=2-',10),{start:2,end:9});assert.equal(range('bytes=-4',10),null);assert.throws(()=>range('bytes=8-12',10));for(const h of ['bytes=9007199254740992-','bytes=0-1048576'])assert.throws(()=>range(h,2097152));});

const {requestCategory,safeError}=require('./actor.cjs');
test('synthetic preflight admits only GET and maintained auth/range headers',()=>{assert.equal(requestCategory('OPTIONS','https://www.googleapis.com/drive/v3/files/fixture',{'access-control-request-method':'GET','access-control-request-headers':'authorization, range'}).valid,true);for(const headers of [{'access-control-request-method':'POST'},{'access-control-request-method':'GET','access-control-request-headers':'x-unrelated'},{}])assert.equal(requestCategory('OPTIONS','https://www.googleapis.com/drive/v3/files/fixture',headers).valid,false);});
test('GET classification preserves metadata/media and rejects other methods',()=>{assert.deepEqual(requestCategory('GET','https://www.googleapis.com/drive/v3/files/fixture'),{category:'metadata',valid:true});assert.equal(requestCategory('GET','https://www.googleapis.com/drive/v3/files/fixture/revisions/A?alt=media').category,'media');assert.equal(requestCategory('POST','https://www.googleapis.com/drive/v3/files/fixture').valid,false);});
test('safe fixed assertion label retained without raw exception details',()=>{assert.equal(safeError(Error('INITIAL_SINGLE_WORKER')),'INITIAL_SINGLE_WORKER');assert.equal(safeError(Error('https://private.example/secret')),'CASE_FAILURE');});

const {routeAdmission}=require('./actor.cjs');
test('actual shared routing admission handles all preflights, GET and budgets',()=>{for(const suffix of ['', '/download','/revisions/A?alt=media']){const req={method:()=> 'OPTIONS',url:()=> 'https://www.googleapis.com/drive/v3/files/fixture'+suffix,headers:()=>({'access-control-request-method':'GET','access-control-request-headers':'authorization,range'})};const a=routeAdmission(req,1,512);assert.equal(a.action,'preflight');assert.equal(a.response.status,204);assert.equal(a.response.body,'');assert.equal(routeAdmission(req,513,512).action,'abort');assert.equal(routeAdmission({...req,method:()=> 'GET'},1,512).action,'get');assert.equal(routeAdmission({...req,method:()=> 'POST'},1,512).action,'reject');assert.equal(routeAdmission({...req,headers:()=>({'access-control-request-method':'GET','access-control-request-headers':'unapproved'})},1,512).action,'reject');assert.equal(routeAdmission({...req,url:()=>req.url().replace('fixture','foreign')},1,512).action,'reject');}});

test('maintained source parser admits exact synthetic metadata and normalized owner',async()=>{const {openDriveQ1Source}=await import('../../media/drive-source.mjs');const source=await openDriveQ1Source({fileId:'fixture',accountKey:'normalized-account',accountGeneration:1,isCurrent:()=>true,readMetadata:async()=>({id:'fixture',headRevisionId:'A',version:'1',size:'683128',mimeType:'video/mp4',modifiedTime:'A',sha256Checksum:'40ce156ee1a209d87e81c227fa2aaf7fa54558f31708d52bdbae3714e879796f',trashed:false,capabilities:{canDownload:true,canReadRevisions:true}}),readRange:async()=>{throw Error('UNEXPECTED_BODY');}});assert.equal(source.identity.headRevisionId,'A');assert.equal(source.identity.accountKey,'normalized-account');assert.equal((await source.abort()).settled,true);});
