'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const files=['REVIEW.md','prove-overlap.mjs','synthetic-overlap-proof.json','range-offset-observer.cjs','numeric-stats.function.js','diagnostic.test.cjs','finalize-review.cjs','checks.json'];
for(const p of files.filter(x=>/\.(cjs|mjs|js)$/.test(x))){const r=spawnSync(process.execPath,['--check',path.join(__dirname,p)],{windowsHide:true,timeout:10000});if(r.status!==0)throw Error('LOCAL_SYNTAX_FAILED');}
const r=spawnSync(process.execPath,['--test',path.join(__dirname,'diagnostic.test.cjs')],{windowsHide:true,encoding:'utf8',timeout:15000});if(r.status!==0||!/(?:pass|passed)\s+4\b/.test(r.stdout))throw Error('LOCAL_TEST_FAILED');
const proof=require('./synthetic-overlap-proof.json');if(proof.cases.length!==3||!proof.cases.every(c=>c.readStartInsideSelectedWindow&&c.identicalContinuousBootstrapOutput&&c.bootstrapFinished))throw Error('SYNTHETIC_PROOF_FAILED');
fs.writeFileSync(path.join(__dirname,'checks.json'),JSON.stringify({actualExecution:false,privateInputsRead:false,browserCalls:false,deviceCalls:false,networkCalls:false,productEdits:false,frozenQAEdits:false,localDiagnosticTestsPassed:4,localDiagnosticTestsFailed:0,syntaxPassed:true,canonicalSyntheticOverlapCases:3,canonicalByteEqualCases:3,nativeDecodeTested:false,leaseDesignImplemented:false},null,2)+'\n');
const result={sourceCommit:proof.sourceCommit,actualExecution:false,privateFilesIncluded:false,files:files.map(p=>{const b=fs.readFileSync(path.join(__dirname,p));return{path:p,bytes:b.length,sha256:sha(b)};})};const b=Buffer.from(JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(__dirname,'review-manifest.json'),b);
console.log(JSON.stringify({files:result.files.length,curatedBytes:result.files.reduce((n,r)=>n+r.bytes,0),manifestBytes:b.length,manifestSHA256:sha(b),report:result.files.find(r=>r.path==='REVIEW.md'),proof:result.files.find(r=>r.path==='synthetic-overlap-proof.json'),observer:result.files.find(r=>r.path==='range-offset-observer.cjs')}));
