'use strict';
const fs=require('fs'),cp=require('child_process'),crypto=require('crypto'),leaf='qa/rc29-finite-acceptance-reconciliation';
const read=p=>fs.readFileSync(p),j=p=>JSON.parse(read(p)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),git=(...a)=>cp.execFileSync('git',a,{maxBuffer:4000000}),norm=b=>b.toString().replace(/\r\n/g,'\n');
const pin=git('rev-parse','10f1dd2').toString().trim(),old='944f00607cf05e586b1c88e2876dd796ce114e82',priorPath='qa/rc28-finite-acceptance-matrix/review.json',prior=j(priorPath),specPath=prior.rows[0].original.path;
if(prior.rows.length!==69||prior.fixedSource!==old)throw Error('prior scope');
const pointer=(p,n)=>{let a=norm(read(p)).split('\n'),i=a.findIndex(l=>l.includes(n));if(i<0)throw Error('missing pointer '+p+' '+n);return{path:p,line:i+1,needle:n};};
const span=(s,m)=>{let a=s.indexOf(m);if(a<0)throw Error('missing function '+m);let rest=s.slice(a+m.length),e=/\n(?:async )?function /.exec(rest);return s.slice(a,a+m.length+(e?e.index+1:rest.length));};
const app23=norm(git('show','7591044:app.js')),app28=norm(git('show',old+':app.js')),app29=norm(git('show',pin+':app.js'));
const comparisons=['async function initializeAccountMediaState(','async function flushAccountMediaState(','function normalizeAccountMediaState(','function mergeAccountMediaStates(','function markFileViewed(','function queueAccountStateSync(','function updateAccountSyncStatus(','function canRefreshAccountState(','function scheduleAccountStateRefresh(','function noteViewedVideoPresentation(','function setPlayerChromeVisible(','function resetControlsTimer(','function revealPlayerChrome(','function setupPlayerChrome(','function retireQ0Playback(','function retireQ1Playback(','function confirmQ1WorkerRetirement(','function clearDirectMediaSources(','function closePlayer(','function installSessionCredential(','function requestSessionCredential('].map(scope=>{let a=span(app23,scope),b=span(app28,scope),c=span(app29,scope);return{path:'app.js',scope,sha23:sha(a),sha28:sha(b),sha29:sha(c),same23to28:a===b,same28to29:b===c};});
if(comparisons.some(c=>!c.same28to29))throw Error('29 relevant behavior drift');
const statePath='qa/rc28-resume-20261001/root-state-binding.json',state=j(statePath),stateSafe=state.actualStateReport.path;
if(!state.pointInTimeCompletedSnapshots||!state.localClientBinding.runtimeProjectClientBindingVerified||sha(read(stateSafe))!==state.actualStateReport.sha256)throw Error('state proof drift');
const resourcePath='qa/rc28-resource-retirement-local/review.json',resource=j(resourcePath);
const resourceCurrent=resource.mediaBindings.map(e=>({path:e.path,sha28:e.currentSHA256,sha29:sha(git('show',pin+':'+e.path)),same:e.currentSHA256===sha(git('show',pin+':'+e.path))}));
if(resourceCurrent.some(e=>!e.same)||!resource.controlled50.passed||resource.controlled50.cycles!==50)throw Error('resource drift');
const stateSourceBindings=state.localClientBinding.sourceHashes.map(e=>({path:e.path,expected:e.sha256,sha29:sha(git('show',pin+':'+e.path)),recordedEqualsWorktree:e.sha256===sha(read(e.path)),same:e.sha256===sha(read(e.path))&&norm(read(e.path))===norm(git('show',pin+':'+e.path)),comparison:'recorded raw working-tree hash bound, then LF-normalized Git content equivalence'}));if(stateSourceBindings.some(e=>!e.same))throw Error('runtime binding source drift');
const stPath='qa/rc21-two-foreground-state/root-state-result.json',st=j(stPath);
if(!st.viewedForward.firstAndroidReceiptAt||!st.viewedReverse.firstPcReceiptAt||st.forcedReloadOrRefocusForEcho||!st.finalRemoteComparison.freshReverseViewedExact)throw Error('twoforeground proof');
const android='qa/rc21-android-night/',find=n=>android+fs.readdirSync(android).find(f=>f.startsWith(n+'-')&&f.endsWith('-result.json'));
const evidence=[priorPath,specPath,statePath,stateSafe,stPath,'qa/rc21-android-night/61-rc23-viewed-challenge-passive-read-result.json',resourcePath,'qa/rc28-resource-retirement-local/results.json','qa/rc28-resource-retirement-local/first-attempt.json','qa/rc28-resume-20261001/actual-pc-natural-safe.json',...['144','146','148','149','150','151','152','153','156','157','158','159','161','163','165','166','167'].map(find),'qa/rc21-android-night/164-ui-common-rc28.cjs','qa/rc21-android-night/164-native-multipointer-control.cjs','qa/rc15-player-ui-qualification/results.json','qa/player-input-quality/after/results.json','qa/rc29-pc-player-layout/after/results.json','qa/candidate-rc29-delivery/local-integration-review.json','qa/candidate-rc29-delivery/product-tests.json','tests/auth-session.test.mjs','auth/session-owner.mjs','auth/routes.mjs','app.js'];
const hashes=[...new Set(evidence)].map(path=>({path,sha256:sha(read(path))}));
const completed=['150','151','158','159','165','166'].map(n=>({path:find(n),completed:j(find(n)).completed}));if(completed.some(x=>!x.completed))throw Error('actual completion absent');
const producerBindings=['150','151','158','159','165','166'].map(n=>{let p=find(n),r=j(p),producer=p.replace('-result.json','.cjs');return{result:p,producer,recorded:r.producerSha256,current:sha(read(producer)),same:r.producerSha256===sha(read(producer))};});
if(producerBindings.some(x=>!x.same))throw Error('producer drift');
const pc=j('qa/rc28-resume-20261001/actual-pc-natural-safe.json').result,and=j(find('158')).steps.findLast(x=>x.schema==='drive-original.natural-renewal-observer/2');
if(!pc.complete||!and.complete||pc.failures.length||and.failures.length||!pc.afterOldExpiryFrames||!and.afterOldExpiryFrames)throw Error('natural proof');
const natural={pc:{frames:pc.frames,afterOldExpiryFrames:pc.afterOldExpiryFrames,credentialRequests:pc.credentialRequests,renewals:pc.renewals},android:{frames:and.frames,afterOldExpiryFrames:and.afterOldExpiryFrames,credentialRequests:and.credentialRequests,renewals:and.renewals},requestOverlap:true};
let pt=Date.parse(pc.startedAt)+pc.credentialRequests[0].elapsedMs,at=Date.parse(and.startedAt)+and.credentialRequests[0].elapsedMs;natural.requestOverlap=Math.max(pt,at)<=Math.min(pt+pc.credentialRequests[0].durationMs,at+and.credentialRequests[0].durationMs);natural.requestStartDeltaMs=Math.abs(pt-at);
const changes={
 'QA-AU-10':{pass:true,scope:'actual current28 point-in-time binding + current29 exact state/auth equivalence',paths:[statePath,stateSafe],reason:'Root accepted complete10-document/raw union/tombstone/writer/legacy/private recovery and exact empty-cache reconstruction. Existing project/client equality plus verified audience/origin binding; no new grant/client.'},
 'QA-SL-07':{pass:true,scope:'same preserved binding/recovery clause as AU10',paths:[statePath,stateSafe],reason:'Full original state preserved/restored under candidate origin and same appData namespace; current29 exact state/auth functions. Completed snapshots remain valid despite subsequent human playback changing owners.'},
 'QA-ST-01':{pass:true,scope:'actual PC+physicalAndroid foreground23 proof, exact current state behavior',paths:[stPath,'qa/rc21-android-night/61-rc23-viewed-challenge-passive-read-result.json'],reason:'Existing forward like14,927ms/reverse unlike57,795ms and forward viewed16,415ms/reverse viewed14,132ms, no forced reload/refocus. Exact state23→28→29 equality. Old wholeRowPromoted=false remaining offline/conflict/reconnect belongs to other rows; not an original ST01 clause or mandatory20s ceiling.'},
 'QA-TR-12':{pass:true,scope:'actual natural PC/Android28 + genuine OS Home/return + later decoded seek',paths:['qa/rc28-resume-20261001/actual-pc-natural-safe.json',find('158'),find('159'),find('150')],reason:'Both normal long watches crossed natural66→67 with121 postexpiry frames each and no faults. Android159 normal later pausedseek/close and150 genuine30s Home/recents return+frame/progression/seek. These are complementary saved actual clauses; no forced clock or invented combined expiry-during-background condition.'},
 'QA-UI-01':{pass:true,scope:'saved controlled/native lifecycle owner plus actual current28 pause/seek state + unchanged29 chrome',paths:['qa/rc15-player-ui-qualification/results.json',find('151'),find('159')],reason:'Saved playing/paused/loaded/seeked no-auto-reveal owner proofs retained; actual native pause hides until explicit entry. Chrome funcs28→29 exact. Changed29 CSS bounded current geometry checked; local checks are not29 delivery.'},
 'QA-UI-03':{pass:false,scope:'native current28 explicit bottom controls accessible; saved controlled dismiss behavior',paths:[find('151'),'qa/player-input-quality/after/results.json'],reason:'Current native bottom entry/close/seek access observed; original outside-dismiss requires its exact saved case pointer/equivalence or one narrow native dismiss observation. No full gesture suite or hand-sensor requirement.',next:'Bind existing outside-dismiss controlled/native producer to current unchanged chrome, or one normal native bottom-entry/outside-dismiss receipt.'},
 'QA-UI-06':{pass:true,scope:'original explicit keyboard-entry branch saved; VoiceOver user-deferred',paths:['qa/rc27-saved-contract-reconciliation/review.json','qa/player-input-quality/after/results.json'],reason:'Trusted Tab+Space explicit-entry/focus controller proof retained and chrome funcs exact28→29. No hidden-control trap is demonstrated; original keyboard branch uses enabled entry and focusable revealed controls. iOS VoiceOver remains deferred, not falsely proven by Android.'},
 'QA-UI-07':{pass:true,scope:'actual Android stationaryhold/movement + native OS two contacts/cancel',paths:['qa/rc21-android-night/111-rc25-native-library-longpress-result.json',find('165'),find('166')],reason:'Saved stationaryhold/movement plus165 two-contact recognizer cancellation, no unintended nav/zoom/menu, safe reentry;166 real nonempty selection/list return preserved. Native OS injection, not human-finger or synthetic-CDP touch proof.'},
 'QA-UI-08':{pass:true,scope:'saved native edge plus current native interior threshold/cancel/reentry',paths:['qa/rc21-android-night/115-rc25-native-stable-edge-discriminator-result.json',find('165')],reason:'Exact interior axis then below-threshold snapback, OS CANCEL, two-contact cancellation and subsequent reentry all settle same owner/no navigation. Prior edge failures retained.'},
 'QA-UI-09':{pass:true,scope:'actual Android28 portrait/OS-landscape/browserfullscreen explicitexit, current29 geometry controlled review',paths:[find('146'),find('148'),find('151'),'qa/rc29-pc-player-layout/after/results.json'],reason:'151 actual selected original portrait/landscape fullscreen explicit exit+seek/close geometry and restored native orientation.146/148 failed access/exit attempts remain. StandalonePWA/iOS unsupported scope not claimed.29 overflowclip/topbarfavorite CSS are changed: local bounded5viewport geometry retained; no actual29 delivery promotion.'},
 'QA-LF-01':{pass:true,scope:'historical native50 decoder proof + exact retirement reuse + current changed-layer controlled50',paths:[resourcePath,'qa/rc28-resource-retirement-local/results.json','qa/rc28-resource-retirement-local/first-attempt.json'],reason:'Original finite50 no accumulation covered by unchanged native retirement and targeted changed general/TS50 count/buffer-dispose checks, exact28→29 modules. Retired fixture callbacks2 retained each cycle are explicitly excluded from active count; no new native GC/process-memory measurement, physical50 or p95 claim.'},
 'QA-UI-10':{pass:false,scope:'actual165 quiet preparation + pending→idle/noerror; HTTP success attribution not recorded',paths:[find('165')],reason:'Actual normal original preparation shows no loaderlongtext/toast/badge and normal viewed pending→idle. Producer only samples pending/error; it does not retain normal appData HTTP success/lastSyncAt advancement. This is a narrow evidence attribution gap, not an added protocol or UI redesign.',next:'During next authorized normal viewed action, passively record canonical appData request successful status or lastSyncAt advancement + stable owner and quiet DOM; no forced flush/extra state mutation.'},
 'QA-SL-01':{pass:false,scope:'actual normal renewal/state retention; controlled terminal invalidgrant/revoked-session + reconnect',paths:['qa/rc28-resume-20261001/actual-pc-natural-safe.json',find('158'),'tests/auth-session.test.mjs'],reason:'Access expiry renewal and preserved state are actual. Original actual revocation/reconnect clause still unrun. App logout deletes only current B-auth session; disconnect deletes all sessions/servercredentials and calls Google revoke, so disconnect is outside allowed narrow route.',next:'Root may use normal current app logoutButton (one browser session only) after preserved state backup and owners settle, then normal beginAuthorization/login with existing client/grant and verify same-account projection/raw namespace. Stop at newgrant/humanlogin/2FA boundary. This proves app-session revocation/reconnection, not manufactured Google invalidgrant/global grant revoke; root owns whether this chosen actual revocation branch completes original row.'},
 'QA-SL-02':{pass:true,scope:'actual two foreground devices natural same66→67, bounded successful credential calls + unchanged Durable owner fixtures',paths:['qa/rc28-resume-20261001/actual-pc-natural-safe.json',find('158')],reason:'Actual two normal-device credential POSTs overlap with2ms start delta, bothHTTP200 adopt same66→67 and laterexpiry; account/media owner remains stable. Unchanged deployed Durable owner singleflight/atomic lease and existing refresh-token preservation fixtures establish the implementation supplying observed equivalent safe coordination. Original accepts equivalent safe coordination, so provider refresh execution counts are not an added mandatory gate. Upstream execution counts/individual serverless instance IDs are not observed.',next:'No repeat actual concurrency required for this finite proposal; root owns acceptance. Reuse exact owner fixtures and preserved request journals, do not claim observed upstream refresh count or expose credentials.'}
};
const rows=prior.rows.map(r=>{let d=changes[r.id];return{...r,priorAssessment:r.currentAssessment,currentAssessment:d?(d.pass?'finite-original-pass-proposal':'partial-exact-missing-clause'):r.currentAssessment,proposedScopedPassed:d?d.pass:r.proposedScopedPassed,delta:d?{...d,evidence:d.paths.map(p=>({path:p,line:1,sha256:sha(read(p))}))}:null,exactMissingClauses:d?(d.pass?[]:[d.reason]):r.exactMissingClauses,wholeGoalPassed:false};});
const counts={originalRows:rows.length,priorScopedPassProposals:prior.counts.scopedPassProposals,newPassProposals:Object.values(changes).filter(d=>d.pass).length,totalScopedPassProposals:rows.filter(r=>r.proposedScopedPassed).length,currentAssessments:rows.reduce((a,r)=>(a[r.currentAssessment]=(a[r.currentAssessment]||0)+1,a),{}),wholeGoalPromotions:0};
const queue=[{rank:1,unit:'Root currently running complete corpus/deeper mapping',ids:['QA-FM-01','QA-FM-02','QA-FM-03','QA-FM-04','QA-FM-05','QA-FM-06','QA-FM-07','QA-FM-08','QA-TR-01','QA-TR-02','QA-TR-03','QA-RP-01'],state:'RUNNING; no pass inferred from inventory or samples'},...['QA-UI-03','QA-UI-10','QA-SL-01'].map((id,i)=>({rank:i+2,unit:id,action:changes[id].next})),{rank:6,unit:'Candidate29 actual delivery and exact2 disposable normal UI/API/web/G comparison/cleanup',ids:['QA-SW-01','QA-MU-09','QA-MU-10','PRODUCT-G5'],state:'PENDING; prior28 SW01 finite result retained separately, no29 real delivery from local product tests'}, {rank:7,unit:'AU06 blocked3PC original condition',ids:['QA-AU-06'],state:'Prepared only; root actual under supported dedicated Network frame/session override + normal reload/session/playback'}, {rank:8,unit:'Honest performance distribution',ids:['OBS-03'],state:'PENDING; no p95 from saved small samples; keep failures/timeouts/cold/warm'}, {rank:null,unit:'iOS after user-authorized deployment',ids:['QA-SL-05'],state:'DEFERRED; Android is not iOS'}];
if(!natural.requestOverlap||natural.requestStartDeltaMs>5)throw Error('actual equivalent coordination overlap absent');
const out={schema:'drive-original.rc29-additive-original69-overlay/1',initialBuildFailure:{kind:'Evidence pointer selection used quote on JS test source',corrected:'JSON evidence defaults line1; dedicated meaningful source pointers retained',laterBindingFailure:'Raw Git LF versus recorded working-tree CRLF mismatch; recorded hashes match worktree and normalized immutable source is equal',productFailure:false},generatedUtc:new Date().toISOString(),source29:pin,source28:old,publicActualCutoff:'Saved28 records only; current29 delivery/disposable/performance/AU06 unrun; root corpus RUNNING.',prior:{path:priorPath,sha256:sha(read(priorPath)),unchanged:true},rows,counts,queue,implementationEquivalence:{comparisons,resourceCurrent,stateSourceBindings,authFiles:['auth/session-owner.mjs','auth/routes.mjs','worker/index.mjs','worker/google.mjs'].map(path=>({path,equal28to29:git('show',old+':'+path).equals(git('show',pin+':'+path))})),driveFetchReadScope:'29 adds separate disposable one-usepermit/write check; canonical ACCOUNT_STATE_READ/WRITE and normal GET/auth logic retained; no global flag broadening.',cssChange:'overflow:hidden→clip and duplicate video topbarFavorite hidden; changes are not called unchanged. Current local5viewport geometry proof retained, actual29 delivery pending.'},sourcePointers:[pointer('app.js','async function flushAccountMediaState('),pointer('app.js','state.accountStateLastSyncAt = Date.now()'),pointer('app.js','async function logout()'),pointer('app.js','async function disconnect()'),pointer('auth/session-owner.mjs','async logout('),pointer('auth/session-owner.mjs','async disconnect('),pointer('tests/auth-session.test.mjs',"test('invalid_grant closes refresh loop"),pointer('tests/auth-session.test.mjs',"test('logout ends one session")],evidenceHashes:hashes,producerBindings,naturalTwoDevice:natural,limits:['Additive review only; original69 spec/baseline/historical statuses untouched; root final status authority.','Root accepts statebinding point-in-time; later human playback is not corruption of prior completed snapshot.','No corpus completeness/format absence/p95/iOS/actual29 delivery or disposable PASS inferred.','Raw failures/native observer qualifications retained. No source/shared record/browser/network/stage/commit by this child.']};
fs.writeFileSync(leaf+'/review.json',JSON.stringify(out,null,2)+'\n');fs.writeFileSync(leaf+'/queue.json',JSON.stringify({counts,queue},null,2)+'\n');fs.writeFileSync(leaf+'/README.md','# Additive current original69 reconciliation\n\nFixed local29 '+pin+'; saved actual28 and historical precise scopes reused only after implementation comparison. No actual29 delivery promotion.\n\n'+counts.newPassProposals+' new finite pass proposals; '+counts.totalScopedPassProposals+' total scoped pass proposals across69 original rows. Root owns acceptance; original baseline unchanged. See review.json for exact clauses, original line pointers, current equivalence hashes, retained failures and narrowly missing UI03/UI10/SL01.\n\nST01 existing two foreground viewed receipts were already complete. UI10 quietactual165 lacks explicit HTTP success attribution. Normal logout revokes only current app session; disconnect invokes Google revoke and is excluded. LF50 remains qualified composite historical-native plus changed-layer controlled proof, no new native memory claim. Corpus/deeper RUNNING; delivery29/disposable/performance/AU06 pending, iOS deferred.\n');
const files=['build.cjs','review.json','queue.json','README.md'].map(n=>({path:leaf+'/'+n,sha256:sha(read(leaf+'/'+n))}));fs.writeFileSync(leaf+'/staging-manifest.json',JSON.stringify({scope:'Exact5 newleaf public analysis only, no staging',files,manifestPath:leaf+'/staging-manifest.json'},null,2)+'\n');console.log(JSON.stringify({counts,naturalRequestOverlap:natural.requestOverlap,requestStartDeltaMs:natural.requestStartDeltaMs,allRelevant28to29Equal:comparisons.every(c=>c.same28to29),producerBindingsAllMatch:producerBindings.every(c=>c.same)}));
