'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events'),crypto=require('node:crypto');
const d=require('./android.cjs'),w=require('./worker.cjs');
test('fixed35 binding/frozen helpers and single-literal common derivation, no runtime input',()=>{const b=d.verifyBound35();assert.equal(b.sourceCommit,'2c2b1244bee0f1a5e500318c83c6e126c5124e34');assert.equal(b.shellExpectedCount,49);assert.equal(b.shellWithRootAlias,50);assert.equal(b.publicFileCount,64);assert.equal(typeof d.common35(),'function');assert.equal(b.expectedScripts.length,2);});
function headerContext({range='bytes 0-16383/2147483648',status=206,brand='isom',extra=false}={}){const bytes=new Uint8Array(16384);new DataView(bytes.buffer).setUint32(0,20);bytes.set(Buffer.from('ftyp'),4);bytes.set(Buffer.from(brand),8);bytes.set(Buffer.from('mp42'),16);let reads=0,cancelled=0,cleared=0;const reader={async read(){return reads++?{done:true}:{value:extra?new Uint8Array(16385):bytes,done:false}},async cancel(){cancelled++},releaseLock(){}};const ctx={Uint8Array,DataView,Array,Buffer,URL,Error,state:{token:'synthetic'},crypto:crypto.webcrypto,AbortController,setTimeout:()=>1,clearTimeout:()=>cleared++,fetch:async()=>({status,headers:{get:k=>k==='Content-Range'?range:null},body:{getReader:()=>reader}})};vm.createContext(ctx);return{fn:vm.runInContext('('+d.boundedHeader.toString()+')',ctx),cleanup:()=>({cancelled,cleared})};}
test('actual bounded ftyp admitted before reload; bytes/identifiers not exported',async()=>{const x=headerContext(),r=await x.fn({target:{id:'fixture',headRevisionId:'r',size:2147483648}});assert(r.normalIsoMp4&&r.rangeMatched&&r.performedBeforeFreshReload);assert.equal(r.bytes,16384);assert.equal(r.rawHeaderExported,false);assert.equal(r.headerSHA256.length,64);assert.deepEqual(x.cleanup(),{cancelled:1,cleared:1});});
test('wrong range/status/oversized body or QuickTime major brand cannot qualify MP4',async()=>{for(const opts of [{range:null},{status:200},{extra:true}]){const x=headerContext(opts);await assert.rejects(x.fn({target:{id:'fixture',headRevisionId:'r',size:2147483648}}),/HEADER/);assert.equal(x.cleanup().cleared,1);}const x=headerContext({brand:'qt  '});assert.equal((await x.fn({target:{id:'fixture',headRevisionId:'r',size:2147483648}})).normalIsoMp4,false);});
function workerFixture(wrongHash=false){const session=new EventEmitter(),calls=[];let worker='worker';session.send=async(method,params)=>{calls.push(method);if(method==='Target.getTargets')return{targetInfos:[{type:'page',url:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/',browserContextId:'ctx'},{type:'service_worker',targetId:worker,url:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/sw.js',browserContextId:'ctx'}]};if(method==='Target.attachToTarget')return{sessionId:'child'};if(method==='Target.sendMessageToTarget'){const m=JSON.parse(params.message);queueMicrotask(()=>{if(m.method==='Debugger.enable')session.emit('Target.receivedMessageFromTarget',{sessionId:'child',message:JSON.stringify({method:'Debugger.scriptParsed',params:{scriptId:'script',url:'https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/sw.js'}})});session.emit('Target.receivedMessageFromTarget',{sessionId:'child',message:JSON.stringify({id:m.id,result:m.method==='Debugger.getScriptSource'?{scriptSource:wrongHash?'wrong':'synthetic-script'}:{}})});});}return{};};return{session,calls,setWorker:x=>worker=x};}
test('executing source bytes, unchanged target and owned cleanup discriminate real boundary',async()=>{const f=workerFixture(),h=await w.attachPrepared({browserSession:f.session},{id:'fixture',size:2147483648,revision:'r',expectedScripts:[{file:'sw.js',sha256:w.hash('synthetic-script')}]});assert((await h.verifyScripts()).actualWorkerScriptBytesMatched);f.setWorker('replacement');await assert.rejects(h.verify(),/WORKER_CHANGED/);const s=await h.stop();assert(s.ownedWorkerDetached&&s.ownedWorkerNetworkDisabled&&s.privateCorrelationCleared);assert.equal(f.session.listenerCount('Target.receivedMessageFromTarget'),0);});
test('executing worker hash mismatch fails and releases only its own session',async()=>{const f=workerFixture(true);await assert.rejects(w.attachPrepared({browserSession:f.session},{id:'fixture',size:2147483648,revision:'r',expectedScripts:[{file:'sw.js',sha256:w.hash('synthetic-script')}]}),/SCRIPT_HASH/);assert(f.calls.includes('Target.detachFromTarget'));assert.equal(f.session.listenerCount('Target.receivedMessageFromTarget'),0);});
test('complete byte proof retains independent frame/progress/SW agreement and denominator',()=>{const n={sourceWorker:true,requestCount:1,live:0,overflow:false,unqualified:false,preflight:{allQualified:true},all206RangeUpperBound:null,completeChunkObservation:true,postCloseTrafficEnvelope:100,actualBodyBytes:90},s={firstFrame:{},progressFrame:{},current:true,failure:null},t={overflow:false,starts:1,requestCount:1,terminalCount:0,finalReaderBytes:80};assert(d.qualify(s,n,2**30,t));for(const [a,b,c] of [[{...s,progressFrame:null},n,t],[s,{...n,postCloseTrafficEnvelope:2**30},t],[s,n,{...t,starts:2}],[s,{...n,live:1},t]])assert.equal(d.qualify(a,b,2**30,c),false);});
