import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {build} from './build.mjs';
const base=new URL('./',import.meta.url),hash=x=>createHash('sha256').update(x).digest('hex');
const result=await build(),saved=JSON.parse(await readFile(new URL('provenance.json',base),'utf8'));
assert.deepEqual(result.provenance,saved);assert.equal(hash(await readFile(new URL('browser.generated.js',base))),saved.expressionSHA256);assert.equal(hash(await readFile(new URL('sw-runtime-proof.expression.js',base))),saved.swProofSHA256);
const log=await readFile(new URL('local-tests.tap',base)),logText=log[0]===255&&log[1]===254?new TextDecoder('utf-16le').decode(log):new TextDecoder().decode(log);
assert.match(logText,/tests\s+15/);assert.match(logText,/pass\s+15/);assert.match(logText,/fail\s+0/);
const seed=JSON.parse(await readFile(new URL('seed-oracle-results.json',base),'utf8'));assert.equal(seed.passed,true);assert.equal(hash(await readFile(new URL('fixtures/synthetic-vp9-opus.webm',base))),seed.fixtureSHA256);
const files=['README.md','ebml-tracks.mjs','probe.mjs','facade.function.js','build.mjs','probe.test.mjs','browser.generated.js','sw-runtime-proof.expression.js','provenance.json','local-tests.tap','seed-oracle-results.json','verify.mjs'];
const hashes=Object.fromEntries(await Promise.all(files.map(async p=>[p,hash(await readFile(new URL(p,base)))])));
const publicSource=Object.fromEntries(await Promise.all(['app.js','sw.js','version.json'].map(async p=>[p,hash(await readFile(new URL('../../'+p,base)))])));
const head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const record={schema:'drive-original.rc16-corpus-tracks-local-verification/1',scope:'Local synthetic only; no browser/account/original/media writes',sourceHEAD:head,publicSource,files:hashes,focusedTests:{passed:15,failed:0},generatedExpressionValid:true,independentSeedOracle:true,actualExecution:false,privateMappingAvailable:false,continuity:'unknown'};
await writeFile(new URL('local-verification.json',base),JSON.stringify(record,null,2)+'\n');
await writeFile(new URL('curated-savepoint.json',base),JSON.stringify({schema:'drive-original.rc16-corpus-tracks-curated-savepoint/1',exactOwnedFiles:[...files,'local-verification.json','curated-savepoint.json'].map(p=>'qa/rc16-corpus-tracks/'+p),excluded:['regenerable fixtures/synthetic-vp9-opus.webm','duplicate build-output.json','private actual manifests/contexts','product/global/source originals','installed tools/cache'],commitOwner:'root'},null,2)+'\n');
console.log(JSON.stringify({focusedTests:record.focusedTests,generatedExpressionSHA256:saved.expressionSHA256,swProofSHA256:saved.swProofSHA256,actualExecution:false,curatedFiles:files.length+2}));
