'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{classifySourceArchives,downloadBudget}=require('./audit.cjs'),{verifiedDownload}=require('./verified-download.cjs');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(changes=[]){const files=Array.from({length:9},(_,i)=>'licenses/mock-source-'+i+'.tgz'),old=new Map(files.map((file,i)=>[file,Buffer.from('old-source-'+i)])),current=new Map(files.map(file=>[file,changes.includes(file)?Buffer.from('changed-source-'+file):old.get(file)]));
 const rows=map=>files.map(file=>({file,bytes:map.get(file).length,sha256:sha(map.get(file)),gitEqual:true}));return {files,old,current,before:rows(old),after:rows(current),bindings:rows(old).map(({file,sha256})=>({file,sha256}))};}
test('one changed archive requires full proof while eight unchanged archives retain ETag reuse',()=>{const f=fixture(['licenses/mock-source-8.tgz']),plan=classifySourceArchives(f.after,f.before,f.bindings,file=>f.old.get(file),file=>f.current.get(file));assert.equal(plan.length,9);assert.deepEqual(plan.filter(row=>row.changed).map(row=>row.file),['licenses/mock-source-8.tgz']);assert.equal(plan.filter(row=>!row.changed).length,8);assert.equal(plan[8].requiredProof,'BOUNDED_FULL_CURRENT_GIT_DOWNLOAD');assert.equal(plan[0].requiredProof,'UNCHANGED_GIT_CURRENT_CONTENT_ADDRESS_FRESH_STRONG_ETAG');assert.equal(downloadBudget(plan[8].file,plan[8].currentBytes),600000);});
test('finite exact plan supports multiple changes and rejects added archive or stale Git bindings',()=>{const f=fixture(['licenses/mock-source-0.tgz','licenses/mock-source-8.tgz']),plan=classifySourceArchives(f.after,f.before,f.bindings,file=>f.old.get(file),file=>f.current.get(file));assert.equal(plan.filter(row=>row.changed).length,2);
 assert.throws(()=>classifySourceArchives([...f.after,{file:'licenses/extra.tgz'}],f.before,f.bindings,file=>f.old.get(file),file=>f.current.get(file)),/EXACT_SOURCE_ARCHIVE_SET_REQUIRED/);
 const stale=f.after.map(row=>({...row}));stale[8].sha256=sha(Buffer.from('unapproved current bytes'));assert.throws(()=>classifySourceArchives(stale,f.before,f.bindings,file=>f.old.get(file),file=>f.current.get(file)),/CURRENT_ARCHIVE_GIT_BINDING_CHANGED/);
 const prior=f.bindings.map(row=>({...row}));prior[0].sha256='0'.repeat(64);assert.throws(()=>classifySourceArchives(f.after,f.before,prior,file=>f.old.get(file),file=>f.current.get(file)));});
test('changed archive mock full download verifies exact current bytes and rejects old bytes with reader cleanup',async()=>{const f=fixture(['licenses/mock-source-8.tgz']),expected=f.current.get(f.files[8]);let reads=0,canceled=0,released=0;
 const fetchBytes=bytes=>async()=>({status:200,body:{getReader:()=>({async read(){reads++;return reads===1?{done:false,value:bytes}:{done:true};},async cancel(){canceled++;},releaseLock(){released++;}})}});
 const result=await verifiedDownload('https://mock.invalid/archive',expected,{fetchImpl:fetchBytes(expected),totalMs:1000,progressMs:100});assert.equal(result.bytes,expected.length);assert.equal(canceled,1);assert.equal(released,1);
 reads=0;await assert.rejects(verifiedDownload('https://mock.invalid/archive',expected,{fetchImpl:fetchBytes(f.old.get(f.files[8])),totalMs:1000,progressMs:100}),/DELIVERY_GIT_BYTE_MISMATCH/);assert.equal(canceled,2);assert.equal(released,2);});
