'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const base=__dirname,root=path.resolve(base,'../..'),prior=path.join(base,'../rc30-performance-preparation'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),binding=JSON.parse(fs.readFileSync(path.join(prior,'binding.json')));
assert.equal(binding.sourceCommit,'aa46bd083ce8c21f55cf7d9a4759f0d6709188c2');assert.equal(binding.version,'1.22.0-rc.30');for(const [p,h] of Object.entries(binding.sourceSHA256))assert.equal(sha(execFileSync('git',['show',binding.sourceCommit+':'+p],{cwd:root,maxBuffer:4*1024**2})),h);
const continuation={schema:'drive-original.rc30-performance-continuation/1',priorPartialSHA256:'66b5f828175375a4f88a4817c53e2489d2f1258f6f60781e47ebf36589a59b9a',originalIdentityKnown:false,sampleNumbersAreBookkeeping:true,plan:[{sample:9,kind:'first-startup'},{sample:9,kind:'warm-startup'},{sample:9,kind:'seek90'},{sample:10,kind:'first-startup'},{sample:10,kind:'warm-startup'},{sample:10,kind:'seek10'}]};
let source=fs.readFileSync(path.join(prior,'observer.function.js'),'utf8');source=source.replace('function(binding, proof)', 'function(binding, proof, continuation)');
const oldPlan="const plan=[];for(let i=0;i<10;i++)for(const kind of ['first-startup','warm-startup','seek'+[10,50,90][i%3]])plan.push({sample:i+1,kind});";assert.ok(source.includes(oldPlan));
source=source.replace(oldPlan,"if(JSON.stringify(continuation)!=="+JSON.stringify(JSON.stringify(continuation))+")throw Error('QA_CONTINUATION_PLAN');\n  const plan=continuation.plan.map(p=>({...p}));");
source=source.replaceAll('slice(0,10)','slice(0,2)').replaceAll('privateFiles.length<10','privateFiles.length<2').replaceAll('privateFiles.length!==10','privateFiles.length!==2').replaceAll('QA_TEN_AVAILABLE_VIDEOS_REQUIRED','QA_TWO_AVAILABLE_VIDEOS_REQUIRED').replaceAll('privateFiles[p.sample-1]','privateFiles[p.sample-9]').replace('privateFiles.findIndex(f=>f.id===state.selected.id)+1','privateFiles.findIndex(f=>f.id===state.selected.id)+9');
source=source.replaceAll('index===30','index===plan.length').replaceAll('index>=30','index>=plan.length').replaceAll('rows.length===30','rows.length===plan.length').replaceAll('THIRTY_ATTEMPTS_FINISHED','SIX_CONTINUATION_ATTEMPTS_FINISHED').replaceAll('THIRTY_PLANNED_OUTCOMES_FINISHED','SIX_CONTINUATION_OUTCOMES_FINISHED');
source=source.replace("schema:'drive-original.rc29-performance-plan-outcomes/1',binding,done","schema:continuation.schema,binding,done,priorPartialSHA256:continuation.priorPartialSHA256,originalPlanRemainsIncomplete:true,continuedSamples:[9,10],originalIdentityKnown:false,sampleNumbersAreBookkeeping:true");
source=source.replaceAll('requiredOutcomes:30','requiredOutcomes:plan.length').replaceAll('requiredAttempts:30','requiredAttempts:plan.length').replaceAll('requiredStartupAttempts:20','requiredStartupAttempts:4').replaceAll('requiredPausedSeekAttempts:10','requiredPausedSeekAttempts:2').replaceAll('requestedStartupCount:20','requestedStartupCount:4').replaceAll('requestedSeekCount:10','requestedSeekCount:2').replaceAll('selectedSamples:10','selectedSamples:2');

source=source.replace('Ten metadata-selected files plan 20 startup and 10 paused seek outcomes','Independent continuation selects2 additional current rendered representative videos and plans4 startup and2 paused seek outcomes; samples9/10 are bookkeeping labels, original identity is unknown, and this cannot complete or relabel the prior incomplete30 plan');
fs.writeFileSync(path.join(base,'observer.function.js'),source);fs.writeFileSync(path.join(base,'observer.expression.js'),'('+source+')('+JSON.stringify(binding)+',window.__driveNightCorpus.proof,'+JSON.stringify(continuation)+')\n');fs.writeFileSync(path.join(base,'binding.json'),JSON.stringify({...binding,continuation,parentObserverSHA256:sha(fs.readFileSync(path.join(prior,'observer.function.js')))},null,2)+'\n');
let summarize=fs.readFileSync(path.join(prior,'summarize.cjs'),'utf8').replace("['drive-original.rc25-performance-passive/1','drive-original.rc29-performance-plan-outcomes/1']","['drive-original.rc30-performance-continuation/1']").replace('r.rows.length<=30','r.rows.length<=6').replace('requiredOutcomes:30','requiredOutcomes:6,priorPartialSHA256:r.priorPartialSHA256,originalPlanRemainsIncomplete:true,continuedSamples:[9,10]').replace('requestedStartupCount:20,requestedSeekCount:10','requestedStartupCount:4,requestedSeekCount:2');fs.writeFileSync(path.join(base,'summarize.cjs'),summarize);
console.log(JSON.stringify({observerSHA256:sha(fs.readFileSync(path.join(base,'observer.expression.js'))),sourceCommit:binding.sourceCommit,version:binding.version,independentContinuation:true}));
