'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {binding,observer,input,compare,run}=require('./driver.cjs');
const b={schema:'pc-image-binding/1',sourceCommit:'a'.repeat(40),version:'1.22.0-rc.34',sourceSHA256:{'app.js':'a'.repeat(64),'sw.js':'b'.repeat(64),'version.json':'c'.repeat(64)}};
const t={id:'synthetic-private-target',name:'synthetic-name',size:'1000',mimeType:'image/gif',modifiedTime:'2026-10-02',headRevisionId:'revision-1',parents:['synthetic-parent'],role:'gif'};
const p={schema:'pc-image-targets/1',account:{accountId:'synthetic-account',authAccountKey:'synthetic-key'},targets:[t]};
test('explicit binding replaces only frozen owner/source pins, preserves crop and same-owner logic',()=>{
 const s=observer(b);assert(s.includes('installPcImageObservation'));assert(s.includes("'"+b.sourceCommit+"'"));assert(s.includes('installedAccountGeneration'));assert(s.includes('sameOwner'));assert(s.includes('scale: 1 / devicePixelRatio'));assert(!s.includes('1.22.0-rc.32'));assert.throws(()=>binding({...b,sourceCommit:'HEAD'}));assert.throws(()=>binding({...b,sourceSHA256:{'app.js':'a'.repeat(64)}}));
});
test('protected input is bounded and metadata drift/missing authority fails',()=>{
 input(p);assert.throws(()=>input({...p,targets:[t,t]}));assert.throws(()=>input({...p,targets:Array.from({length:4},(_,i)=>({...t,id:String(i)}))}));
 assert(compare(t,{...t,trashed:false,capabilities:{canDownload:true}}));assert.throws(()=>compare(t,{...t,size:'999',trashed:false,capabilities:{canDownload:true}}));assert.throws(()=>compare(t,{...t,trashed:false,capabilities:{canDownload:false}}));
});
test('failure evidence stays safe, cleanup runs after deadline, existing output blocks activity',async()=>{
 const output=path.join(__dirname,'guard-owned-output.json');assert(!fs.existsSync(output));let reads=0,closed=0,restored=0,detached=0;
 const transport={evaluate:async()=>({observerRemoved:true}),prepareTarget:async()=>({normalUi:true,exactTarget:true}),openCard:async()=>{},captureCrop:async()=>{},readMetadata:async()=>{reads++;return{...t,size:'changed',trashed:false,capabilities:{canDownload:true}};},closePlayer:async()=>{closed++;return{closed:true,retired:true};},restoreNavigation:async()=>{restored++;return{restored:true};},closeOwned:async()=>{detached++;return{closed:true,ownedOnly:true};}};
 try{const r=await run({transport,binding:b,privateInput:p,output});assert.equal(r.passed,false);assert.equal(r.failure,'FRESH_METADATA_MISMATCH');assert.equal(reads,1);assert.equal(closed,1);assert.equal(restored,1);assert.equal(detached,1);const text=fs.readFileSync(output,'utf8');assert(!text.includes(t.id));assert(!text.includes(t.name));assert(!text.includes(p.account.accountId));await assert.rejects(run({transport,binding:b,privateInput:p,output}));assert.equal(reads,1);}finally{if(fs.existsSync(output))fs.unlinkSync(output);}
 const out2=path.join(__dirname,'guard-owned-deadline.json');try{const slow={...transport,prepareTarget:async()=>new Promise(r=>setTimeout(()=>r({normalUi:true,exactTarget:true}),30))};const r=await run({transport:slow,binding:b,privateInput:p,output:out2,totalMs:5});assert.equal(r.failure,'TOTAL_BOUND');assert(r.cleanup.ownedTransport.closed);}finally{if(fs.existsSync(out2))fs.unlinkSync(out2);}
});
test('normal card two lifetimes require six fenced crops within twelve-capture budget; cleanup failure prevents pass',async()=>{
 const zlib=require('node:zlib');let open=false,armed=false,captures=0,opens=0,closes=0;
 const chunk=(name,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);return b;};
 const png=()=>{const h=Buffer.alloc(13);h.writeUInt32BE(1,0);h.writeUInt32BE(1,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',h),chunk('IDAT',zlib.deflateSync(Buffer.from([0,captures%2?255:0,0,0,255]))),chunk('IEND',Buffer.alloc(0))]);};
 const snapshot=()=>({sourceQualified:true,accountSame:true,foreground:true,online:true,exactSelectedMetadata:true,imageReady:open,sameOwner:open&&armed,originalMode:true,transportVerified:true,noImageIframeFallback:true,videoHidden:true,videoControlsHidden:true,imageErrorHidden:true,closed:!open,selectionCleared:!open,sourcesCleared:!open,retired:!open});
 const tr={prepareTarget:async()=>({normalUi:true,exactTarget:true}),readMetadata:async()=>({...t,trashed:false,capabilities:{canDownload:true}}),openCard:async()=>{open=true;armed=false;opens++;return{normalCard:true,exactTarget:true};},closePlayer:async()=>{open=false;closes++;return{closed:true,retired:true};},restoreNavigation:async()=>({restored:true}),closeOwned:async()=>({closed:true,ownedOnly:true}),captureCrop:async o=>{assert(o.croppedOnly&&o.save===false&&o.clip.width===1&&o.clip.height===1);captures++;return png();},evaluate:async s=>{if(s.includes('.fence('))return{admitted:true,clip:{x:1,y:1,width:1,height:1,scale:1}};if(s.includes('.arm(')){armed=true;return snapshot();}if(s.includes('.snapshot('))return snapshot();if(s.includes('.dispose('))return{observerRemoved:true};return{installed:true};}};
 const out=path.join(__dirname,'guard-owned-success.json');try{const r=await run({transport:tr,binding:b,privateInput:p,output:out});assert(r.passed);assert.equal(captures,6);assert(captures<=12);assert.equal(opens,2);assert.equal(closes,3);assert.equal(r.rows[0].sampleCount,6);assert.equal(r.rows[0].alpha,'UNKNOWN');assert.equal(r.rows[0].loop,'UNKNOWN');assert.equal(r.qualityAcceptance,'UNKNOWN');}finally{if(fs.existsSync(out))fs.unlinkSync(out);}
 const failout=path.join(__dirname,'guard-owned-cleanup.json');try{const r=await run({transport:{...tr,prepareTarget:async()=>{throw Error('SYNTHETIC_FAILURE');},closeOwned:async()=>({closed:false,ownedOnly:true})},binding:b,privateInput:p,output:failout});assert.equal(r.passed,false);assert.equal(r.cleanupFailure,true);}finally{if(fs.existsSync(failout))fs.unlinkSync(failout);}
});
