// Bound root CUA adapter; private capsules are host-only; no standalone browser launch.
const closePlayer=async()=>{let s=await q3Eval(`({closed:el.playerSheet.hidden,selected:state.selected?.id===${JSON.stringify(pcImageTarget.id)},other:state.selected!==null&&state.selected?.id!==${JSON.stringify(pcImageTarget.id)},retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice})`);if(s.other)throw Error('FOREIGN_IMAGE_OWNER');if(!s.closed){await q3Tab.playwright.locator('#closePlayerButton').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}const until=Date.now()+5000;do{s=await q3Eval(`({closed:el.playerSheet.hidden&&state.selected===null,retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice,sourcesCleared:!el.imageViewer.getAttribute('src')&&!state.mediaBlobUrl})`);if(s.closed&&s.retired&&s.sourcesCleared)return s;await new Promise(x=>setTimeout(x,100));}while(Date.now()<until);throw Error('IMAGE_CLOSE_BOUND');};
const restoreNavigation=async()=>{for(let i=0;i<4;i++){const s=await q3Eval(`({same:state.currentFolderId===${JSON.stringify(pcImageNavigation.folder)},query:state.query===${JSON.stringify(pcImageNavigation.query)},filter:state.filter===${JSON.stringify(pcImageNavigation.filter)},stack:state.folderStack.length===${pcImageNavigation.stack.length}})`);if(s.same){await q3Eval(`window.scrollTo(${pcImageNavigation.scrollX},${pcImageNavigation.scrollY})`);pcImageDom=await q3Tab.playwright.domSnapshot();return{restored:s.same&&s.query&&s.filter&&s.stack,normalUi:true};}await q3Tab.playwright.locator('#folderUpButton').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}throw Error('IMAGE_NAVIGATION_RESTORE');};
const metadataExpression=t=>`(async()=>{const t=${JSON.stringify(t)},abort=new AbortController(),timer=setTimeout(()=>abort.abort(),10000);let reader;try{const h=t.resourceKey?{'X-Goog-Drive-Resource-Keys':t.id+'/'+t.resourceKey}:{};const fields='id,name,size,mimeType,modifiedTime,parents,version,headRevisionId,md5Checksum,sha256Checksum,trashed,capabilities(canDownload),imageMediaMetadata';const r=await driveFetch(DRIVE_API+'/files/'+encodeURIComponent(t.id)+'?fields='+encodeURIComponent(fields)+'&supportsAllDrives=true',{signal:abort.signal,headers:h});if(r.status!==200)throw Error('PC_IMAGE_METADATA_STATUS');reader=r.body.getReader();let n=0,chunks=[];for(;;){const x=await reader.read();if(x.done)break;n+=x.value.byteLength;if(n>1048576)throw Error('PC_IMAGE_METADATA_BOUND');chunks.push(x.value);}const b=new Uint8Array(n);let p=0;for(const c of chunks){b.set(c,p);p+=c.byteLength;}return JSON.parse(new TextDecoder().decode(b));}finally{clearTimeout(timer);try{await reader?.cancel();}catch{}reader?.releaseLock();abort.abort();}})()`;
const adapter={"evaluate":async(s)=>{if(pcImageAdapterClosed)throw Error('ADAPTER_CLOSED');return q3Eval(s);},
"prepareTarget":async t=>{const s=await q3Eval(`({idle:el.playerSheet.hidden&&state.selected===null,exact:state.currentFolderId===${JSON.stringify(pcImageLoadedPrivate.folder)}&&state.files.some(f=>f.id===${JSON.stringify(t.id)}),card:[...document.querySelectorAll('.file-card')].filter(n=>n.dataset.fileId===${JSON.stringify(t.id)}).length===1,account:state.accountId===${JSON.stringify(pcImageInput.account.accountId)}&&state.authAccountKey===${JSON.stringify(pcImageInput.account.authAccountKey)}})`);return{normalUi:s.idle&&s.card&&s.account,exactTarget:s.exact};},
"openCard":async t=>{await q3Tab.playwright.locator('.file-card[data-file-id="'+t.id+'"]').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();return await q3Eval(`({normalCard:!el.playerSheet.hidden,exactTarget:state.selected?.id===${JSON.stringify(t.id)}})`);},
"closePlayer":async()=>{let s=await q3Eval(`({closed:el.playerSheet.hidden,selected:state.selected?.id===${JSON.stringify(pcImageTarget.id)},other:state.selected!==null&&state.selected?.id!==${JSON.stringify(pcImageTarget.id)},retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice})`);if(s.other)throw Error('FOREIGN_IMAGE_OWNER');if(!s.closed){await q3Tab.playwright.locator('#closePlayerButton').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}const until=Date.now()+5000;do{s=await q3Eval(`({closed:el.playerSheet.hidden&&state.selected===null,retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice,sourcesCleared:!el.imageViewer.getAttribute('src')&&!state.mediaBlobUrl})`);if(s.closed&&s.retired&&s.sourcesCleared)return s;await new Promise(x=>setTimeout(x,100));}while(Date.now()<until);throw Error('IMAGE_CLOSE_BOUND');},
"captureCrop":async o=>{if(o.signal?.aborted)throw Error('CAPTURE_ABORTED');const r=await q3Cdp.send('Page.captureScreenshot',{format:'png',clip:o.clip,captureBeyondViewport:false},{timeoutMs:o.timeoutMs});const b=Buffer.from(r.data,'base64');if(b.length>o.maxEncodedBytes)throw Error('CAPTURE_BYTE_BUDGET');return b;},
"readMetadata":async t=>q3Eval(pcImageMetadataExpression(t)),
"restoreNavigation":async()=>{for(let i=0;i<4;i++){const s=await q3Eval(`({same:state.currentFolderId===${JSON.stringify(pcImageNavigation.folder)},query:state.query===${JSON.stringify(pcImageNavigation.query)},filter:state.filter===${JSON.stringify(pcImageNavigation.filter)},stack:state.folderStack.length===${pcImageNavigation.stack.length}})`);if(s.same){await q3Eval(`window.scrollTo(${pcImageNavigation.scrollX},${pcImageNavigation.scrollY})`);pcImageDom=await q3Tab.playwright.domSnapshot();return{restored:s.same&&s.query&&s.filter&&s.stack,normalUi:true};}await q3Tab.playwright.locator('#folderUpButton').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}throw Error('IMAGE_NAVIGATION_RESTORE');},
"closeOwned":async()=>{const r=await q3Eval(`(()=>{if(${pcImageProofOwned})delete window.__resumeSwProof;return{proofRemoved:!window.__resumeSwProof,observerRemoved:!window.__pcImageObservation,idle:el.playerSheet.hidden&&state.selected===null&&!q0Playback&&!q1Playback&&!q3Choice&&q1RetirementResult?.settled===true};})()`);pcImageAdapterClosed=true;return{closed:r.proofRemoved&&r.observerRemoved&&r.idle,ownedOnly:true,scope:'In-memory adapter and owned proof; existing user tab retained',...r};}};
