// Private host context is not serialized. Native full viewport exists in memory only; crop and total byte budget retained.
const adapter={"evaluate":s=>pcImageLive.evaluate(s),
"prepareTarget":async t=>pcImageLive.evaluate(`({normalUi:el.playerSheet.hidden&&state.selected===null,exactTarget:document.querySelectorAll('.file-card').length===1&&document.querySelector('.file-card').dataset.fileId===${JSON.stringify(t.id)}})`),
"openCard":async t=>{if(!await pcImageLive.evaluate(`document.querySelectorAll('.file-card').length===1&&document.querySelector('.file-card').dataset.fileId===${JSON.stringify(t.id)}`))throw Error('NORMAL_EXACT_CARD_REQUIRED');await pcImageLive.tab.playwright.locator('.file-card').click({timeoutMs:5000});await pcImageLive.tab.playwright.domSnapshot();return pcImageLive.evaluate(`({normalCard:!el.playerSheet.hidden,exactTarget:state.selected?.id===${JSON.stringify(t.id)}})`);},
"closePlayer":async()=>{const s=await pcImageLive.evaluate(`(()=>{const n=el.closePlayerButton,r=n.getBoundingClientRect(),h=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return{closed:el.playerSheet.hidden,other:state.selected!==null&&state.selected.id!==${JSON.stringify(pcImageLive.target.id)},hit:n===h||n.contains(h)};})()`);if(s.other)throw Error('FOREIGN_IMAGE_OWNER');if(!s.closed){if(!s.hit){await pcImageLive.tab.playwright.locator('#playerControlsEntry').click({timeoutMs:5000});await pcImageLive.tab.playwright.domSnapshot();}await pcImageLive.tab.playwright.locator('#closePlayerButton').click({timeoutMs:5000});await pcImageLive.tab.playwright.domSnapshot();}return pcImageLive.evaluate('({closed:el.playerSheet.hidden&&state.selected===null,retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice,sourcesCleared:!el.imageViewer.getAttribute("src")&&!state.mediaBlobUrl})');},
"captureCrop":async o=>{const start=performance.now(),mark=stage=>pcCaptureStages.push({stage,elapsedMs:Math.round(performance.now()-start)});if(o.signal?.aborted)throw Error('CAPTURE_ABORTED');mark('begin');const m=await pcImageLive.cdp.send('Page.getLayoutMetrics',{}, {timeoutMs:Math.min(2000,o.timeoutMs)});const v=await pcImageLive.evaluate('({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scale:visualViewport.scale})');const geometry=pcNativeSampler.captureGeometry(o.clip,m,v.dpr);mark('geometry');const r=await pcImageLive.cdp.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},{timeoutMs:o.timeoutMs});mark('native-viewport');const png=Buffer.from(r.data,'base64');if(png.length>o.maxEncodedBytes)throw Error('CAPTURE_BYTE_BUDGET');const after=await pcImageLive.cdp.send('Page.getLayoutMetrics',{}, {timeoutMs:Math.min(2000,o.timeoutMs)});const av=await pcImageLive.evaluate('({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scale:visualViewport.scale})');if(JSON.stringify(v)!==JSON.stringify(av)||JSON.stringify(pcNativeSampler.captureGeometry(o.clip,after,av.dpr))!==JSON.stringify(geometry))throw Error('PAINT_GEOMETRY_CHANGED');const result=pcNativeSampler.cropViewport(png,geometry,v,pcLiveAdapter.readPNG,image=>pcPNG.sync.write(image));mark('cropped-discarded');return result;},
"readMetadata":async t=>pcImageLive.evaluate(pcImageMetadataExpression(t)),
"restoreNavigation":async()=>{await pcImageLive.tab.playwright.locator('#searchInput').fill(pcImageLive.navigation.query,{timeoutMs:5000});await pcImageLive.tab.playwright.domSnapshot();for(let i=0;i<4;i++){const s=await pcImageLive.evaluate(`({same:state.currentFolderId===${JSON.stringify(pcImageLive.navigation.folder)},query:state.query===${JSON.stringify(pcImageLive.navigation.query)},filter:state.filter===${JSON.stringify(pcImageLive.navigation.filter)}})`);if(s.same){await pcImageLive.evaluate(`window.scrollTo(${pcImageLive.navigation.scrollX},${pcImageLive.navigation.scrollY})`);await pcImageLive.tab.playwright.domSnapshot();return{restored:s.same&&s.query&&s.filter,normalUi:true};}await pcImageLive.tab.playwright.locator('#folderUpButton').click({timeoutMs:5000});await pcImageLive.tab.playwright.domSnapshot();}throw Error('LIVE_NAVIGATION_RESTORE');},
"closeOwned":async()=>{const r=await pcImageLive.evaluate(`(()=>{if(${pcImageLive.proofOwned})delete window.__resumeSwProof;return{proofRemoved:!window.__resumeSwProof,observerRemoved:!window.__pcImageObservation,idle:el.playerSheet.hidden&&state.selected===null&&!q0Playback&&!q1Playback&&!q3Choice&&q1RetirementResult?.settled===true};})()`);await pcImageLive.tab.close();pcImageLive.closed=true;await q3Cdp.send('Page.bringToFront');pcImageDom=await q3Tab.playwright.domSnapshot();return{closed:r.proofRemoved&&r.observerRemoved&&r.idle,ownedOnly:true,ownedTabClosed:true,originalUserTabKept:true,...r};},
"readPNG":png=>pcPNG.sync.read(png,{checkCRC:true})};
