// Normal prepared single-card input, source/account remain host-private.
const restore=async()=>{const q=await q3Eval('state.query');if(q!==pcImageNavigation.query){await q3Tab.playwright.locator('#searchInput').fill(pcImageNavigation.query,{timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}return pcImageRestore();};
const close=async()=>{let s=await q3Eval(`(()=>{const n=el.closePlayerButton,r=n.getBoundingClientRect(),h=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return{closed:el.playerSheet.hidden,other:state.selected!==null&&state.selected.id!==${JSON.stringify(pcRareCtx.target.id)},hit:n===h||n.contains(h)};})()`);if(s.other)throw Error('FOREIGN_IMAGE_OWNER');if(!s.closed){if(!s.hit){await q3Tab.playwright.locator('#playerControlsEntry').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}await q3Tab.playwright.locator('#closePlayerButton').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}const until=Date.now()+5000;do{s=await q3Eval(`({closed:el.playerSheet.hidden&&state.selected===null,retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice,sourcesCleared:!el.imageViewer.getAttribute('src')&&!state.mediaBlobUrl})`);if(s.closed&&s.retired&&s.sourcesCleared)return s;await new Promise(x=>setTimeout(x,100));}while(Date.now()<until);throw Error('IMAGE_CLOSE_BOUND');};
const adapter={"evaluate":async s=>{if(pcRareCtx.closed)throw Error('ADAPTER_CLOSED');return q3Eval(s);},
"prepareTarget":async t=>q3Eval(`({normalUi:el.playerSheet.hidden&&state.selected===null,exactTarget:state.files.some(f=>f.id===${JSON.stringify(t.id)})&&document.querySelectorAll('.file-card').length===1&&document.querySelector('.file-card').dataset.fileId===${JSON.stringify(t.id)}})`),
"openCard":async t=>{const c=await q3Eval(`document.querySelectorAll('.file-card').length===1&&document.querySelector('.file-card').dataset.fileId===${JSON.stringify(t.id)}`);if(!c)throw Error('EXACT_NORMAL_CARD_REQUIRED');await q3Tab.playwright.locator('.file-card').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();return q3Eval(`({normalCard:!el.playerSheet.hidden,exactTarget:state.selected?.id===${JSON.stringify(t.id)}})`);},
"closePlayer":async()=>{let s=await q3Eval(`(()=>{const n=el.closePlayerButton,r=n.getBoundingClientRect(),h=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2);return{closed:el.playerSheet.hidden,other:state.selected!==null&&state.selected.id!==${JSON.stringify(pcRareCtx.target.id)},hit:n===h||n.contains(h)};})()`);if(s.other)throw Error('FOREIGN_IMAGE_OWNER');if(!s.closed){if(!s.hit){await q3Tab.playwright.locator('#playerControlsEntry').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}await q3Tab.playwright.locator('#closePlayerButton').click({timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}const until=Date.now()+5000;do{s=await q3Eval(`({closed:el.playerSheet.hidden&&state.selected===null,retired:q1RetirementResult?.settled===true&&!q0Playback&&!q1Playback&&!q3Choice,sourcesCleared:!el.imageViewer.getAttribute('src')&&!state.mediaBlobUrl})`);if(s.closed&&s.retired&&s.sourcesCleared)return s;await new Promise(x=>setTimeout(x,100));}while(Date.now()<until);throw Error('IMAGE_CLOSE_BOUND');},
"captureCrop":async o=>{if(o.signal?.aborted)throw Error('CAPTURE_ABORTED');const r=await q3Cdp.send('Page.captureScreenshot',{format:'png',clip:o.clip,captureBeyondViewport:false},{timeoutMs:o.timeoutMs});const b=Buffer.from(r.data,'base64');if(b.length>o.maxEncodedBytes)throw Error('CAPTURE_BYTE_BUDGET');return b;},
"readMetadata":async t=>q3Eval(pcImageMetadataExpression(t)),
"restoreNavigation":async()=>{const q=await q3Eval('state.query');if(q!==pcImageNavigation.query){await q3Tab.playwright.locator('#searchInput').fill(pcImageNavigation.query,{timeoutMs:5000});pcImageDom=await q3Tab.playwright.domSnapshot();}return pcImageRestore();},
"closeOwned":async()=>{const r=await q3Eval(`(()=>{if(${pcRareCtx.proofOwned})delete window.__resumeSwProof;return{proofRemoved:!window.__resumeSwProof,observerRemoved:!window.__pcImageObservation,idle:el.playerSheet.hidden&&state.selected===null&&!q0Playback&&!q1Playback&&!q3Choice&&q1RetirementResult?.settled===true};})()`);pcRareCtx.closed=true;return{closed:r.proofRemoved&&r.observerRemoved&&r.idle,ownedOnly:true,scope:'Owned proof/in-memory adapter; existing user tab retained',...r};}};
