import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {disposableUiJob} from './job.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),md5=b=>crypto.createHash('md5').update(b).digest('hex'),root=new URL('../../',import.meta.url),here=new URL('./',import.meta.url),fixed30='aa46bd083ce8c21f55cf7d9a4759f0d6709188c2';
const git=(commit,p)=>execFileSync('git',['show',commit+':'+p],{cwd:fileURLToPath(root),windowsHide:true,maxBuffer:4*1024**2});
const current=fs.readFileSync(new URL('app.js',root),'utf8'),old30=git(fixed30,'app.js').toString(),section=(text,start,end)=>{const a=text.indexOf(start),b=text.indexOf(end,a);assert.ok(a>=0&&b>a);return text.slice(a,b);};
const sections={normalUiCapability:['const disposableDriveMutations = (() => {','function driveMutationError('],genericMutationGate:['  const disposablePermit = requestOptions[DISPOSABLE_DRIVE_MUTATION];','  if (!hasUsableToken()) {']};
const unchanged={};for(const [name,[start,end]] of Object.entries(sections)){const a=section(current,start,end),b=section(old30,start,end);assert.equal(a,b);unchanged[name]=sha(a);}
assert.ok(current.includes("const APP_VERSION = '1.22.0-rc.31'"));
const explicit=process.argv[2]??process.env.RC31_SOURCE;assert.ok(process.argv.length<=3);if(process.argv[2]&&process.env.RC31_SOURCE)assert.equal(process.argv[2],process.env.RC31_SOURCE);let binding=null;
if(explicit!==undefined){assert.match(explicit,/^[a-f0-9]{40}$/);assert.equal(execFileSync('git',['rev-parse',explicit+'^{commit}'],{cwd:fileURLToPath(root),encoding:'utf8'}).trim(),explicit);assert.equal(JSON.parse(git(explicit,'version.json')).version,'1.22.0-rc.31');const committedApp=git(explicit,'app.js');assert.ok(committedApp.includes("const APP_VERSION = '1.22.0-rc.31'"));for(const [start,end] of Object.values(sections))assert.equal(section(committedApp.toString(),start,end),section(old30,start,end));binding={version:'1.22.0-rc.31',source:explicit,appHash:sha(committedApp)};}
function crc(b){let v=0xffffffff;for(const x of b){v^=x;for(let i=0;i<8;i++)v=(v>>>1)^((v&1)?0xedb88320:0);}return(v^0xffffffff)>>>0;}function chunk(type,data){const t=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);t.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([t,data])),data.length+8);return out;}function png(color){const head=Buffer.alloc(13);head.writeUInt32BE(2);head.writeUInt32BE(2,4);head[8]=8;head[9]=6;const pixels=Buffer.concat([Buffer.from([0]),...Array(2).fill(Buffer.from(color)),Buffer.from([0]),...Array(2).fill(Buffer.from(color))]);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',zlib.deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
const fixtures=[[30,120,220,255],[210,70,45,255]].map((color,i)=>{const bytes=png(color);assert.equal(bytes.length,74);fs.writeFileSync(new URL(`fixture-${i+1}.png`,here),bytes);return{bytes:[...bytes],md5:md5(bytes),sha256:sha(bytes),width:2,height:2};});assert.notEqual(fixtures[0].sha256,fixtures[1].sha256);
const factory=`(function(env,binding,options){return (${disposableUiJob.toString()})(env,binding,${JSON.stringify(fixtures)},options);})`;fs.writeFileSync(new URL('factory.expression.js',here),factory);
fs.writeFileSync(new URL('build.json',here),JSON.stringify({actualRun:false,source31Pinned:!!binding,binding,explicitCommitRequired:true,noHeadOrWorkingTreeBindingFallback:true,preparationAppHash:sha(current),preparationVersion:'1.22.0-rc.31',comparedCommitted30:fixed30,unchangedProductSections:unchanged,factorySHA256:sha(factory),fixtures:fixtures.map(({bytes,...f},i)=>({path:`fixture-${i+1}.png`,bytes:bytes.length,...f})),contract:'Unbound preparation until explicit full committed31 source provided; execution requires exact31 source/app hash/current controller proof. No actual uploads, UI or cleanup.'},null,2)+'\n');console.log(JSON.stringify({actualRun:false,source31Pinned:!!binding,fixtureBytes:fixtures.map(f=>f.bytes.length),factorySHA256:sha(factory),unchangedProductSections:unchanged}));
