'use strict';
// Adaptation of the existing product integration driver; one conversion only.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),cp=require('node:child_process');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),pin='5174485b3c17d047259701bbdd889f9b0740f555';
const fixture=fs.readFileSync(path.join(root,'qa/q3-product-integration/synthetic-640-180s.mp4')),info={sha256:sha(fixture),size:fixture.length,width:640,height:360,frames:5400,duration:180};
if(info.sha256!=='cda53855c53bf1d608491eb96aa3abb0ff774cca2aa24cfe01447e295c07ed7a'||info.size!==18075476)throw Error('INPUT_IDENTITY');
const allowed=new Set(require('../../scripts/public-files.cjs').filter(x=>x.startsWith('media/'))),assets={},assetBytes=new Map();
for(const name of allowed){const bytes=cp.execFileSync('git',['show',`${pin}:${name}`],{cwd:root,maxBuffer:16777216});assetBytes.set(name,bytes);assets[name]={bytes:bytes.length,sha256:sha(bytes)};}
const host=JSON.parse(cp.execFileSync('powershell.exe',['-NoProfile','-Command','Get-CimInstance Win32_OperatingSystem | Select-Object FreePhysicalMemory,FreeVirtualMemory | ConvertTo-Json -Compress'],{encoding:'utf8',windowsHide:true}));
if(host.FreePhysicalMemory<1048576||host.FreeVirtualMemory<2097152)throw Error('MEMORY_ADMISSION');
const receipt={scope:'Isolated local product Worker complete synthetic output; no physical-device quality or full-app qualification',runtimePin:pin,input:info,host,assets,producer:{node:process.version,playwright:require('playwright/package.json').version,sha256:sha(fs.readFileSync(__filename)),fixtureSha256:sha(fs.readFileSync(path.join(__dirname,'fixture.mjs')))},requests:0,peakReadBytes:0,errors:[],started:new Date().toISOString()};
let browser,page,timer,fd,bytes=0;
const server=http.createServer((req,res)=>{if(req.method!=='GET'||req.headers.host!==`127.0.0.1:${server.address().port}`)return res.writeHead(403).end();const name=new URL(req.url,'http://localhost').pathname.slice(1);
 if(name==='fixture-info.json')return res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify(info));
 if(name==='fixture.mp4'){const m=/^bytes=(\d+)-(\d+)$/.exec(req.headers.range||'');if(!m)return res.writeHead(416).end();const a=+m[1],b=+m[2],n=b-a+1;if(a<0||b<a||b>=fixture.length||n>1048576)return res.writeHead(416).end();receipt.requests++;receipt.peakReadBytes=Math.max(receipt.peakReadBytes,n);return res.writeHead(206,{'Content-Type':'video/mp4','Content-Range':`bytes ${a}-${b}/${fixture.length}`,'Content-Length':n}).end(fixture.subarray(a,b+1));}
 if(!allowed.has(name)&&!['qa/q3-full-output-quality/fixture.html','qa/q3-full-output-quality/fixture.mjs'].includes(name))return res.writeHead(404).end();
 res.writeHead(200,{'Content-Type':name.endsWith('.wasm')?'application/wasm':name.endsWith('.html')?'text/html':'text/javascript','Cache-Control':'no-store'}).end(assetBytes.get(name)||fs.readFileSync(path.join(root,name)));
});
(async()=>{try{fd=fs.openSync(path.join(__dirname,'output-640-180s.mp4'),'wx');await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({channel:'chrome',headless:true,timeout:15000});receipt.browser=browser.version();receipt.profile='Playwright-owned ephemeral isolated profile; no account/browser state reused';page=await browser.newPage();page.on('pageerror',e=>receipt.errors.push(e.message));await page.exposeFunction('saveChunk',(a,position)=>{const b=Buffer.from(a);if(position!==bytes||b.length>262144||bytes+b.length>134217728)throw Error('OUTPUT_SINK_BOUND');fs.writeSync(fd,b);bytes+=b.length;});await page.goto(`http://127.0.0.1:${server.address().port}/qa/q3-full-output-quality/fixture.html`);await page.waitForFunction(()=>typeof window.capture==='function');receipt.capture=await Promise.race([page.evaluate(()=>window.capture()),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('CAPTURE_600S_DEADLINE')),600000);})]);const c=receipt.capture;receipt.pass=!c.result.error&&c.result.result.metrics.decoded===5400&&c.result.result.metrics.encoded===5400&&c.result.transportCleanup.settled&&c.bytes===bytes&&receipt.errors.length===0;
 }catch(e){receipt.fatal=e.message;receipt.pass=false;}finally{clearTimeout(timer);if(page&&!receipt.pass){try{receipt.failureCleanup=await Promise.race([page.evaluate(()=>window.cancelOwned()),new Promise((_,reject)=>setTimeout(()=>reject(Error('CANCEL_BOUND')),8000))]);}catch(e){receipt.failureCleanupError=e.message;}}if(browser){await browser.close();receipt.browserClosed=true;}if(server.listening){server.closeAllConnections();await new Promise(r=>server.close(r));receipt.serverClosed=true;}if(fd!==undefined){fs.closeSync(fd);receipt.outputDescriptorClosed=true;}receipt.output={bytes,sha256:sha(fs.readFileSync(path.join(__dirname,'output-640-180s.mp4')))};receipt.ended=new Date().toISOString();fs.writeFileSync(path.join(__dirname,'capture-results.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({pass:receipt.pass,fatal:receipt.fatal,output:receipt.output,capture:receipt.capture}));if(!receipt.pass)process.exitCode=1;}})();
