'use strict';
// Native FFmpeg oracle: compressed files and frame metadata only; raw YUV stays in bounded filter buffers.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),sourceName=path.join(root,'qa/q3-product-integration/synthetic-640-180s.mp4'),outputName=path.join(__dirname,'output-640-180s.mp4'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const native=(exe,args)=>cp.execFileSync(exe,args,{cwd:__dirname,maxBuffer:16777216,timeout:180000,windowsHide:true,encoding:'utf8'});
const probe=f=>JSON.parse(native('ffprobe',['-v','error','-select_streams','v:0','-show_streams','-show_format','-show_entries','frame=best_effort_timestamp_time,duration_time,width,height,pix_fmt,color_range,color_space,color_primaries,color_transfer,interlaced_frame','-of','json',f]));
// Reuse the previously qualified independent MP4 geometry parser, without running its 3s oracle.
const oracleSource=fs.readFileSync(path.join(root,'qa/q3-product-integration/oracle.cjs'),'utf8');
const geometry=new Function('fs',`${oracleSource.slice(oracleSource.indexOf('function geometry('),oracleSource.indexOf('const rows=[];'))};return geometry;`)(fs);
const receipt={scope:'Independent native all-5400-frame local synthetic source/output oracle; no Android quality, thermal/performance or patent clearance',producerSha256:sha(fs.readFileSync(__filename)),geometryProducerSha256:sha(Buffer.from(oracleSource)),started:new Date().toISOString()};
try{
 receipt.tools={ffmpeg:native('ffmpeg',['-version']).split('\n')[0],ffprobe:native('ffprobe',['-version']).split('\n')[0]};
 const capture=JSON.parse(fs.readFileSync(path.join(__dirname,'capture-results.json')));if(!capture.pass)throw Error('CAPTURE_UNQUALIFIED');
 receipt.source={bytes:fs.statSync(sourceName).size,sha256:sha(fs.readFileSync(sourceName))};receipt.output={bytes:fs.statSync(outputName).size,sha256:sha(fs.readFileSync(outputName))};
 if(receipt.output.sha256!==capture.output.sha256||receipt.source.sha256!==capture.input.sha256)throw Error('IDENTITY');
 const a=probe(sourceName),b=probe(outputName);fs.writeFileSync(path.join(__dirname,'source-probe.json'),JSON.stringify(a,null,2)+'\n');fs.writeFileSync(path.join(__dirname,'output-probe.json'),JSON.stringify(b,null,2)+'\n');
 const command=['-hide_banner','-loglevel','info','-i',sourceName,'-i',outputName,'-filter_complex','[0:v:0]settb=expr=1/30,setpts=N[ref];[1:v:0]settb=expr=1/30,setpts=N[out];[ref][out]psnr=stats_file=psnr-frames.log:stats_version=2','-an','-fps_mode','passthrough','-f','null','-'];receipt.comparisonCommand=command;receipt.comparisonAlignment='Decoded frame ordinal; source/product actual timestamps checked independently for all frames before quality acceptance';
 const run=cp.spawnSync('ffmpeg',command,{cwd:__dirname,windowsHide:true,timeout:180000,maxBuffer:2097152,encoding:'utf8'});fs.writeFileSync(path.join(__dirname,'ffmpeg-comparison.log'),run.stderr||'');if(run.error||run.status!==0)throw Error(`NATIVE_COMPARE:${run.error?.message||run.status}`);
 const lines=fs.readFileSync(path.join(__dirname,'psnr-frames.log'),'utf8').trim().split(/\r?\n/).filter(x=>x.startsWith('n:')),values=lines.map(x=>Number(/psnr_avg:([\d.inf]+)/.exec(x)[1])),summary=/PSNR y:([\d.inf]+) u:([\d.inf]+) v:([\d.inf]+) average:([\d.inf]+) min:([\d.inf]+) max:([\d.inf]+)/.exec(run.stderr);
 if(!summary)throw Error('PSNR_SUMMARY');receipt.psnr={allYuv:Number(summary[4]),y:Number(summary[1]),u:Number(summary[2]),v:Number(summary[3]),minimumFrame:Number(summary[5]),minimumFrameStatsRounded:Math.min(...values),frames:lines.length,statsPrecision:'per-frame FFmpeg stats rounded to 2 decimals; native summary 6 decimals',thresholds:{allYuv:38,minimumFrame:33}};
 const meta=b.streams[0],reference=a.streams[0],color=['color_space','color_primaries','color_transfer','color_range'];let maxTimestampError=0,maxCadenceError=0,frameMetadata=true;
 if(a.frames.length!==b.frames.length)throw Error('FRAME_COUNT_MISMATCH');for(let i=0;i<b.frames.length;i++){const f=b.frames[i];maxTimestampError=Math.max(maxTimestampError,Math.abs(Number(f.best_effort_timestamp_time)-Number(a.frames[i].best_effort_timestamp_time)));if(i)maxCadenceError=Math.max(maxCadenceError,Math.abs(Number(f.best_effort_timestamp_time)-Number(b.frames[i-1].best_effort_timestamp_time)-1/30));frameMetadata&&=f.width===640&&f.height===360&&f.pix_fmt==='yuv420p'&&f.interlaced_frame===0&&color.every(k=>f[k]===reference[k]);}
 receipt.geometry=geometry(outputName);receipt.metadata=meta;receipt.timeline={sourceFrames:a.frames.length,outputFrames:b.frames.length,maxTimestampErrorSeconds:maxTimestampError,maxCadenceErrorSeconds:maxCadenceError,sourceDuration:a.format.duration,outputDuration:b.format.duration,allFrameMetadata:frameMetadata,precision:'FFprobe 6-decimal presentation timestamps'};
 const g=receipt.geometry;receipt.checks={exactIdentity:true,complete5400:lines.length===5400&&a.frames.length===5400&&b.frames.length===5400,quality:receipt.psnr.allYuv>=38&&receipt.psnr.minimumFrame>=33,clock:maxTimestampError<=0.000001001&&maxCadenceError<=0.000001001&&Math.abs(Number(b.format.duration)-180)<=0.000001001,codec:meta.codec_name==='vp9',geometry:g.codedWidth===640&&g.codedHeight===360&&g.displayWidth===640&&g.displayHeight===360&&g.effectiveSar==='1:1'&&g.effectiveDar==='16:9',streamMetadata:meta.width===640&&meta.height===360&&meta.pix_fmt==='yuv420p'&&color.every(k=>meta[k]===reference[k])&&meta.avg_frame_rate===reference.avg_frame_rate&&!meta.side_data_list?.length,allFrameMetadata:frameMetadata};receipt.pass=Object.values(receipt.checks).every(Boolean);
}catch(e){receipt.error=e.message;receipt.pass=false;}
receipt.ended=new Date().toISOString();fs.writeFileSync(path.join(__dirname,'oracle-results.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));if(!receipt.pass)process.exitCode=1;
