'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),cp=require('node:child_process');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),pin='5174485b3c17d047259701bbdd889f9b0740f555';
const fixture=fs.readFileSync(path.join(root,'qa/q3-product-integration/synthetic-640-180s.mp4')),info={sha256:sha(fixture),size:fixture.length,width:640,height:360,frames:5400,duration:180};
if(info.sha256!=='cda53855c53bf1d608491eb96aa3abb0ff774cca2aa24cfe01447e295c07ed7a')throw Error('INPUT_IDENTITY');
const allowed=new Set(require('../../scripts/public-files.cjs').filter(x=>x.startsWith('media/'))),assetBytes=new Map(),assets={};for(const name of allowed){const b=cp.execFileSync('git',['show',`${pin}:${name}`],{cwd:root,maxBuffer:16777216});assetBytes.set(name,b);assets[name]={bytes:b.length,sha256:sha(b)};}
const original=assetBytes.get('media/video-q3-pipeline.mjs').toString(),replacements=[];
function replace(s,a,b){if(s.split(a).length!==2)throw Error('INSTRUMENT_ANCHOR');replacements.push(a);return s.replace(a,b);}
function instrument(mode){let s=original;
 s=replace(s,'metrics={decoded:0','metrics={phaseTimes:{readMs:0,decodeCopyMs:0,frameEncodeCallMs:0,flushMs:0,muxMs:0,ackMs:0,encodeOutputMs:0,encodeOutputs:0},decoded:0');
 s=replace(s,'let m,decoder=0','let qaEncodeStart=0;let m,decoder=0');
 s=replace(s,'output(chunk,metadata){','output(chunk,metadata){metrics.phaseTimes.encodeOutputMs+=performance.now()-qaEncodeStart;metrics.phaseTimes.encodeOutputs++;');
 s=replace(s,'const p=input.packets[i],bytes=await rpc.exact(p.start,p.size);rpc.check();inspectQ3Packet(bytes,p.key);','const p=input.packets[i];let qaT=performance.now();const bytes=await rpc.exact(p.start,p.size);metrics.phaseTimes.readMs+=performance.now()-qaT;qaT=performance.now();rpc.check();inspectQ3Packet(bytes,p.key);');
 s=replace(s,"demand(m._q3_packet_drained(decoder)===1,'DECODE_BUFFER_UNQUALIFIED');","demand(m._q3_packet_drained(decoder)===1,'DECODE_BUFFER_UNQUALIFIED');metrics.phaseTimes.decodeCopyMs+=performance.now()-qaT;qaT=performance.now();");
 s=replace(s,'try{encoder.encode(frame,','qaEncodeStart=performance.now();try{encoder.encode(frame,');
 s=replace(s,'await cancellable(encoder.flush(),signal);','metrics.phaseTimes.frameEncodeCallMs+=performance.now()-qaT;qaT=performance.now();await cancellable(encoder.flush(),signal);metrics.phaseTimes.flushMs+=performance.now()-qaT;');
 s=replace(s,'await video.add(encoded.packet,first?{decoderConfig:finalConfig}:undefined);','qaT=performance.now();await video.add(encoded.packet,first?{decoderConfig:finalConfig}:undefined);metrics.phaseTimes.muxMs+=performance.now()-qaT;');
 s=replace(s,'await cancellable(Promise.resolve(onChunk({generation,bytes,position:offset+p,batchSize:data.length,batchEnd:p+bytes.length===data.length})),signal);','const qaAckT=performance.now();await cancellable(Promise.resolve(onChunk({generation,bytes,position:offset+p,batchSize:data.length,batchEnd:p+bytes.length===data.length})),signal);metrics.phaseTimes.ackMs+=performance.now()-qaAckT;');
 if(mode==='no-preference')s=replace(s,"hardwareAcceleration:'prefer-software'","hardwareAcceleration:'no-preference'");return Buffer.from(s);
}
const result={scope:'QA-instrumented unchanged product tail170..180s, null output; no full180 conversion/native playback/device/realtime qualification',pin,input:info,assets,originalPipelineSha256:sha(Buffer.from(original)),producerSha256:sha(fs.readFileSync(__filename)),fixtureProducerSha256:sha(fs.readFileSync(path.join(__dirname,'timing-fixture.mjs'))),started:new Date().toISOString(),cases:[]};
let browser,page,timer,mode='prefer-software';
const server=http.createServer((req,res)=>{if(req.method!=='GET'||req.headers.host!==`127.0.0.1:${server.address().port}`)return res.writeHead(403).end();const name=new URL(req.url,'http://localhost').pathname.slice(1);if(name==='fixture-info.json')return res.end(JSON.stringify(info));if(name==='fixture.mp4'){const m=/^bytes=(\d+)-(\d+)$/.exec(req.headers.range||'');if(!m)return res.writeHead(416).end();const a=+m[1],b=+m[2];if(a<0||b<a||b>=fixture.length||b-a+1>1048576)return res.writeHead(416).end();return res.writeHead(206,{'Content-Range':`bytes ${a}-${b}/${fixture.length}`}).end(fixture.subarray(a,b+1));}if(!allowed.has(name)&&!['qa/q3-full-output-quality/timing-fixture.html','qa/q3-full-output-quality/timing-fixture.mjs'].includes(name))return res.writeHead(404).end();const data=name==='media/video-q3-pipeline.mjs'?instrument(mode):assetBytes.get(name)||fs.readFileSync(path.join(root,name));res.writeHead(200,{'Content-Type':name.endsWith('.wasm')?'application/wasm':name.endsWith('.html')?'text/html':'text/javascript','Cache-Control':'no-store'}).end(data);});
async function run(kind){mode=kind;page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/qa/q3-full-output-quality/timing-fixture.html`);await page.waitForFunction(()=>typeof window.capture==='function');const c={mode:kind,instrumentedPipelineSha256:sha(instrument(kind)),measurement:await page.evaluate(()=>window.capture())},m=c.measurement,r=m.result;result.cases.push(c);c.pass=!r.error&&r.result.metrics.decoded===300&&r.result.metrics.encoded===300&&r.transportCleanup?.settled===true&&m.windows.length===1&&m.windows[0].videoStartTimestamp===170&&m.windows[0].sourceEndTimestamp===180;await page.close();page=null;return c;}
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({channel:'chrome',headless:true,timeout:10000});result.browser=browser.version();await Promise.race([(async()=>{const c=await run('prefer-software');if(c.pass&&c.measurement.result.result.metrics.phaseTimes.flushMs/c.measurement.workerElapsedMs>=0.6&&Date.now()-Date.parse(result.started)<30000){result.comparisonReason='baseline flush>=60% worker elapsed; QA-only exact hardwareAcceleration preference comparison';await run('no-preference');}})(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('TOTAL_55S_BOUND')),55000);})]);result.pass=result.cases.length>=1&&result.cases.every(c=>c.pass);
 }catch(e){result.error=e.message;result.pass=false;}finally{clearTimeout(timer);if(page){try{result.failedWorkerCleanup=await page.evaluate(()=>window.cancelOwned());}catch(e){result.failedCleanupError=e.message;}}if(browser){await browser.close();result.browserClosed=true;}server.closeAllConnections();if(server.listening)await new Promise(r=>server.close(r));result.serverClosed=true;result.ended=new Date().toISOString();result.totalElapsedMs=Date.parse(result.ended)-Date.parse(result.started);result.uniqueInstrumentAnchors=[...new Set(replacements)];fs.writeFileSync(path.join(__dirname,'tail-timing-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pass:result.pass,error:result.error,totalElapsedMs:result.totalElapsedMs,cases:result.cases.map(c=>({mode:c.mode,pass:c.pass,elapsedMs:c.measurement.workerElapsedMs,times:c.measurement.result.result?.metrics.phaseTimes,source:c.measurement.pageSource,metrics:c.measurement.result.result?.metrics,cleanup:c.measurement.result.transportCleanup})),browserClosed:result.browserClosed,serverClosed:result.serverClosed}));if(!result.pass)process.exitCode=1;}})();
