'use strict';
const fs=require('node:fs'),cp=require('node:child_process'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const base=__dirname,repo=path.resolve(base,'../..'),r=JSON.parse(fs.readFileSync(path.join(base,'results.json'))),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
assert.equal(r.publicSource,'54654ce1efb2dbe0296a9641ed01182e9e1a8322');assert.equal(r.version,'1.22.0-rc.17');
for(const [file,hash] of [['app.js',r.appCacheSha256],['index.html',r.indexCacheSha256]])assert.equal(sha(cp.execFileSync('git',['show',`${r.publicSource}:${file}`],{cwd:repo})),hash);
const observer=fs.readFileSync(path.join(base,'seek-observer.expression.js'),'utf8');assert(observer.endsWith('\n'));assert.equal(sha(observer.slice(0,-1)),r.executedSeekObserverSha256);
assert.equal(r.pausedSeeks.length,4);for(const [i,s] of r.pausedSeeks.entries()){assert.equal(s.percent,[10,50,90,50][i]);assert(Math.abs(s.frameTime-s.target)<=r.seekInput.targetToleranceSeconds);assert(Math.abs(s.target-r.duration*s.percent/100)<1e-9);assert.equal(s.ownerCurrent,true);assert.equal(s.loading,false);assert.equal(s.paused,true);assert.equal(s.seeking,false);assert.equal(s.appSeeking,false);assert.equal(s.watchdog,false);assert.equal(s.ready,4);assert.equal(s.errorCode,null);assert.equal(s.completedDecodedProof,true);assert.equal(s.presentationKey,null);}
assert.equal(r.pausedSeeks[1].seekingAtFrame,true);assert.equal(r.pausedSeeks[3].seekingAtFrame,true);assert.equal(r.pausedDwell.frames,r.pausedSeeks[3].frames);assert.equal(r.pausedDwell.loading,false);assert.equal(r.resumeRequiredAfterSeek,false);assert.equal(r.close.retirementSettled,true);assert.equal(r.close.completedPresentationProof,false);assert.equal(r.close.observerDeleted,true);assert.equal(r.scopedAcceptancePassed,true);
const files=['results.json','README.md','verify-record.cjs','seek-observer.expression.js'];const manifest={schema:'drive-original.rc17-actual-record-verification/1',recordIntegrity:true,scopedActualAcceptance:true,replayPerformed:false,publicSource:r.publicSource,files:Object.fromEntries(files.map(p=>[p,sha(fs.readFileSync(path.join(base,p)))]))};fs.writeFileSync(path.join(base,'evidence-manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify({recordIntegrity:true,scopedActualAcceptance:true,replayPerformed:false}));
