'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('../node_modules/playwright');const root=path.resolve(__dirname,'../..'),SOURCE='5174485b3c17d047259701bbdd889f9b0740f555',VERSION='1.22.0-rc.33',sha=b=>crypto.createHash('sha256').update(b).digest('hex'),blob=p=>cp.execFileSync('git',['show',SOURCE+':'+p],{cwd:root,maxBuffer:64*1024*1024,windowsHide:true});
const harness=blob('qa/functional-audit.cjs').toString(),harnessSHA=sha(Buffer.from(harness));assert.equal(harnessSHA,'0cd7f7abe6798c63ba755fdebb5091916d986a2f2eb47e3fde606316fcbb535b');
const install=harness.slice(harness.indexOf('function installQaSlowTailFixture()'),harness.indexOf('const qaSlowTailServiceWorkerFixture'));
// QA-only adaptation to current immutable Q0 revision URL. All product SW bytes remain exact.
const adapted=install.replace("const fileId = decodeURIComponent(url.pathname.split('/').pop() || '');","const fileId = decodeURIComponent(/^\\/drive\\/v3\\/files\\/([^/]+)(?:\\/revisions\\/[^/]+)?$/.exec(url.pathname)?.[1] || '');\n    if(url.pathname.includes('/revisions/')&&!url.pathname.endsWith('/revisions/fixture-r1'))throw Error('QA_REVISION_MISMATCH');");assert.notEqual(adapted,install);
const parsing=harness.slice(harness.indexOf('function parseIsoBmffTopLevelBoxes'),harness.indexOf('function appendFaststartTrailingFreeBox'));
const parsers=vm.runInNewContext(parsing+';({parseIsoBmffTopLevelBoxes,expandTailIndexFixture})',{assert,Buffer});
const configureText=harness.slice(harness.indexOf('async function configureSlowTailFixture'),harness.indexOf('(async()=>{\n  await new Promise'));const configure=vm.runInNewContext(configureText+';configureSlowTailFixture');
const seed=blob('qa/tail-index-h264-aac.mp4');assert.equal(sha(seed),'c3e75a4d8e234a8864940bfe498fb7ee49ad3305bf0790879e636e607fee595f');const fixture=parsers.expandTailIndexFixture(seed,16*1024*1024-seed.length);assert.equal(fixture.bytes.length,16*1024*1024);assert(fixture.bytes.subarray(0,55314).equals(seed.subarray(0,55314)));assert(fixture.bytes.subarray(fixture.indexStart).equals(seed.subarray(55314)));
const fixturePath=path.join(__dirname,'tail-index-16m.mp4');if(fs.existsSync(fixturePath))assert(fs.readFileSync(fixturePath).equals(fixture.bytes));else fs.writeFileSync(fixturePath,fixture.bytes,{flag:'wx'});
const report={schema:1,sourceCommit:SOURCE,version:VERSION,scope:'Controlled isolated native Chrome actual-app; synthetic auth/source only. No real Drive/device/account acceptance.',passed:false,harnessSHA256:harnessSHA,qaFixtureAdapterSHA256:sha(adapted),seedSHA256:sha(seed),fixtureSHA256:sha(fixture.bytes),fixtureBytes:fixture.bytes.length,moovStart:fixture.indexStart,moovEnd:fixture.indexEnd,boxes:fixture.boxes,phases:[],cleanup:{},productAssets:[]};
const publicFiles=vm.runInNewContext(blob('scripts/public-files.cjs').toString()+';module.exports',{module:{exports:null}}),assets=new Map();let browser,context,page,base,configured=false,stage='setup';const errors=[],api=[],requests=[];const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.wasm':'application/wasm'};
const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost'),name=u.pathname.replace(/^\/drive-original\//,'')||'index.html';if(!publicFiles.includes(name))return res.writeHead(404).end();if(!assets.has(name)){const b=blob(name);assets.set(name,b);report.productAssets.push({file:name,sha256:sha(b)});}const b=assets.get(name);res.writeHead(200,{'Content-Type':mime[path.extname(name)]||'application/octet-stream','Cache-Control':'no-store'});res.end(name==='sw.js'?Buffer.concat([b,Buffer.from('\n;('+adapted.replace(/^function installQaSlowTailFixture/,'function')+')();')]):b);}catch{res.writeHead(500).end();}});
const file={id:'tail-fixture',name:'controlled-tail-index.mp4',mimeType:'video/mp4',size:String(fixture.bytes.length),version:'1',headRevisionId:'fixture-r1',modifiedTime:'2026-10-02T00:00:00.000Z',parents:['root'],trashed:false,capabilities:{canDownload:true},videoMediaMetadata:{width:320,height:180,durationMillis:'3000'}};
function unionBytes(streams){const intervals=streams.filter(x=>x.deliveredBytes>0).map(x=>[x.start,x.start+x.deliveredBytes-1]).sort((a,b)=>a[0]-b[0]),merged=[];for(const i of intervals){const last=merged.at(-1);if(!last||i[0]>last[1]+1)merged.push(i);else last[1]=Math.max(last[1],i[1]);}return merged.reduce((n,i)=>n+i[1]-i[0]+1,0);}
async function snapshot(){const x=await page.evaluate(async()=>({fixture:(await __driveOriginalQaSlowTailRequest('DRIVE_ORIGINAL_QA_SLOW_TAIL_STATE')).state,frames:window.__tailFrames,mode:state.mediaPlaybackMode,attempt:state.mediaAttempt,fullRequestCount:state.mediaFullRequestCount,storage:state.mediaBufferStorageMode,transportVerified:state.mediaTransportVerified,sourceGeneration:mediaSourceGeneration,seekGeneration:mediaSeekGeneration,paused:el.videoPlayer.paused,currentTime:el.videoPlayer.currentTime,duration:el.videoPlayer.duration,width:el.videoPlayer.videoWidth,height:el.videoPlayer.videoHeight,previewHidden:el.drivePreview.hidden,q0Current:Boolean(q0Playback&&isCurrentQ0Playback(q0Playback,state.selected?.id,mediaSourceGeneration))}));x.totalDelivered=x.fixture.streams.reduce((n,s)=>n+s.deliveredBytes,0);x.uniqueDelivered=unionBytes(x.fixture.streams);return x;}
(async()=>{const deadman=setTimeout(()=>{report.deadline=true;browser?.close().catch(()=>{});},90000);try{report.nativeProbe=JSON.parse(cp.execFileSync('ffprobe',['-v','error','-show_entries','stream=codec_name,width,height:format=duration,size','-of','json',fixturePath],{encoding:'utf8',timeout:10000,windowsHide:true}));await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/drive-original/';browser=await chromium.launch({channel:'chrome',headless:true});report.browserVersion=browser.version();context=await browser.newContext({viewport:{width:1280,height:800}});await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.origin===new URL(base).origin)return route.continue();if(u.origin!=='https://www.googleapis.com')return route.abort();const entry={method:r.method(),media:u.searchParams.get('alt')==='media',fromSW:Boolean(r.serviceWorker())};api.push(entry);if(r.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'*'}});if(entry.media){entry.unexpected=true;return route.abort();}if(r.method()==='POST'&&u.pathname==='/drive/v3/files/tail-fixture/download'&&u.searchParams.get('revisionId')==='fixture-r1')return route.fulfill({status:200,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'},body:JSON.stringify({name:'operations/controlled-tail',done:true,response:{'@type':'type.googleapis.com/google.apps.drive.v3.DownloadFileResponse',partialDownloadAllowed:true,downloadUri:'https://www.googleapis.com/drive/v3/files/tail-fixture/revisions/fixture-r1?alt=media'}})});if(r.method()!=='GET')return route.abort();return route.fulfill({status:200,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'},body:JSON.stringify(file)});});page=await context.newPage();page.on('pageerror',()=>errors.push('PAGE_ERROR'));stage='app-load';await page.goto(base+'?demo=1');await page.waitForFunction(()=>typeof openPlayer==='function');await page.evaluate(()=>navigator.serviceWorker.ready);if(!await page.evaluate(()=>navigator.serviceWorker.controller))await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller);
 stage='fixture-config';await configure(page,{fileId:file.id,bytes:fixture.bytes,mode:'tail-index',mimeType:'video/mp4',prefixBytes:65536,indexStart:fixture.indexStart,indexEnd:fixture.indexEnd});configured=true;
 await page.evaluate(file=>{state.demo=false;state.token='synthetic-test-token';state.expiresAt=Date.now()+3600000;state.authAccountKey='synthetic-account';state.accountId='synthetic-account';state.tokenRevision=1;state.authCapabilities={version:1,driveRead:true,driveWrite:false,appData:false};state.accountStateLoaded=true;state.files=[file];window.__tailFrames=[];window.__tailRvf=0;const v=el.videoPlayer;const observe=(now,m)=>{if(__tailFrames.length<120)__tailFrames.push({mediaTime:m.mediaTime,width:m.width,height:m.height,sourceGeneration:mediaSourceGeneration,seekGeneration:mediaSeekGeneration,currentOwner:isCurrentMediaEvent(v)&&Boolean(q0Playback&&isCurrentQ0Playback(q0Playback,state.selected?.id,mediaSourceGeneration))});__tailRvf=v.requestVideoFrameCallback(observe);};__tailRvf=v.requestVideoFrameCallback(observe);renderFiles();},file);
 stage='native-open';await page.locator('[data-file-id="tail-fixture"] .file-card-open').click();await page.waitForFunction(()=>window.__tailFrames.some(f=>f.currentOwner&&f.width===320&&f.height===180)&&el.videoPlayer.currentTime>.1,null,{timeout:15000});const startup=await snapshot();assert.equal(startup.mode,'original-range');assert(startup.q0Current&&startup.transportVerified&&startup.previewHidden);assert.equal(startup.fullRequestCount,0);assert.equal(startup.storage,'');assert(startup.totalDelivered<fixture.bytes.length);assert(startup.fixture.streams.some(s=>s.isTailIndexRequest&&s.bodyComplete&&s.start<=fixture.indexStart&&s.end>=fixture.indexEnd));report.phases.push({name:'startup',...startup});
 stage='native-seek';await page.keyboard.press('Space');await page.locator('#playerControlsEntry').click();await page.waitForFunction(()=>!el.playerModal.classList.contains('controls-idle')&&el.videoPlayer.paused,null,{timeout:2000});const g=await page.locator('#seekBarContainer').boundingBox();assert(g);const target=2.4;const prior=await page.evaluate(()=>({count:__tailFrames.length,generation:mediaSeekGeneration}));await page.mouse.click(g.x+g.width*.8,g.y+g.height/2);await page.waitForFunction(t=>window.__tailFrames.slice(t.count).some(f=>f.currentOwner&&f.mediaTime>=2.34&&f.mediaTime<=2.46&&f.seekGeneration>t.generation)&&Math.abs(el.videoPlayer.currentTime-2.4)<.08,prior,{timeout:15000});const seek=await snapshot();assert(seek.q0Current&&seek.previewHidden&&seek.totalDelivered<fixture.bytes.length);report.phases.push({name:'seek80',target,...seek});
 stage='native-close';await page.keyboard.press('Escape');await page.waitForFunction(()=>el.playerSheet.hidden&&!q0Playback&&!q1Playback&&q1RetirementResult.settled,null,{timeout:5000});await page.waitForFunction(async()=>(await __driveOriginalQaSlowTailRequest('DRIVE_ORIGINAL_QA_SLOW_TAIL_STATE')).state.streams.every(s=>s.terminal),null,{timeout:5000});report.closed=await snapshot();assert(api.every(x=>!x.unexpected));assert.equal(errors.length,0);report.passed=true;
 }catch(e){report.failure={stage,message:String(e.message).slice(0,300)};if(page&&configured)try{report.failedLive=await snapshot();report.failedUi=await page.evaluate(()=>({selected:state.selected?.id||null,playerHidden:el.playerSheet.hidden,loadingText:el.playerLoading?.textContent,message:el.playerMessage?.textContent,videoSrc:el.videoPlayer.currentSrc,readyState:el.videoPlayer.readyState,error:el.videoPlayer.error?.code||null}));}catch(x){report.failedRead=String(x.message).slice(0,160);}process.exitCode=1;}finally{clearTimeout(deadman);if(page){try{await page.evaluate(()=>{el.videoPlayer.cancelVideoFrameCallback(window.__tailRvf);delete window.__tailRvf;if(!el.playerSheet.hidden)closePlayer();});report.cleanup.frameObserver=true;}catch{report.cleanup.frameObserver=false;}if(configured)try{const d=await page.evaluate(()=>__driveOriginalQaSlowTailRequest('DRIVE_ORIGINAL_QA_SLOW_TAIL_DISPOSE'));report.cleanup.fixtureDisposed=d.state.configured===false;}catch{report.cleanup.fixtureDisposed=false;}}try{await context?.close();report.cleanup.context=true;}catch{report.cleanup.context=false;}try{await browser?.close();report.cleanup.browser=true;}catch{report.cleanup.browser=false;}await new Promise(r=>server.close(r));report.cleanup.server=true;report.apiCounts={requests:api.length,unexpectedMedia:api.filter(x=>x.unexpected).length};report.pageErrors=errors.length;report.producerSHA256=sha(fs.readFileSync(__filename));fs.writeFileSync(path.join(__dirname,'result.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:report.passed,failure:report.failure,phases:report.phases.map(p=>({name:p.name,totalDelivered:p.totalDelivered,uniqueDelivered:p.uniqueDelivered,frames:p.frames.length})),cleanup:report.cleanup}));}})();
