'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const expanded=process.argv[2]==='--640',fixture=fs.readFileSync(expanded?path.join(__dirname,'synthetic-640.mp4'):path.join(root,'qa/q3-browser-execution/synthetic-mpeg4.mp4'));
if(!expanded&&sha(fixture)!=='4f9a6394d01776a88e198a90e829b7b369c8303ec1fe86d386637439a00585da')throw Error('Q3_FIXTURE_IDENTITY');
const info={sha256:sha(fixture),size:fixture.length,width:expanded?640:320,height:expanded?360:180,frames:expanded?90:72};
const host=JSON.parse(execFileSync('powershell.exe',['-NoProfile','-Command','Get-CimInstance Win32_OperatingSystem | Select-Object FreePhysicalMemory,FreeVirtualMemory | ConvertTo-Json -Compress'],{encoding:'utf8',windowsHide:true}));
if(host.FreePhysicalMemory<1048576||host.FreeVirtualMemory<2097152)throw Error('Q3_LOCAL_MEMORY_ADMISSION');
const result={scope:'isolated synthetic product runtime; no account/device acceptance',input:info,host,browser:null,native:null,cases:[],errors:[],requests:0,peakReadBytes:0};
let browser;
async function deadline(promise){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Q3_CASE_DEADLINE')),30000);})]);}finally{clearTimeout(timer);}}
const allowed=new Set(require('../../scripts/public-files.cjs').filter(x=>x.startsWith('media/')));
const server=http.createServer((req,res)=>{if(req.method!=='GET'||req.headers.host!==`127.0.0.1:${server.address().port}`)return res.writeHead(403).end();const name=new URL(req.url,'http://localhost').pathname.slice(1);
 if(name==='fixture-info.json')return res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify(info));
 if(name==='fixture.mp4'){const match=/^bytes=(\d+)-(\d+)$/.exec(req.headers.range||'');if(!match)return res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':fixture.length}).end(fixture);const a=+match[1],b=+match[2],n=b-a+1;if(a<0||b<a||b>=fixture.length||n>1048576)return res.writeHead(416).end();result.requests++;result.peakReadBytes=Math.max(result.peakReadBytes,n);return res.writeHead(206,{'Content-Type':'video/mp4','Content-Range':`bytes ${a}-${b}/${fixture.length}`,'Content-Length':n}).end(fixture.subarray(a,b+1));}
 if(!allowed.has(name)&&!['qa/q3-product-integration/fixture.html','qa/q3-product-integration/fixture.mjs'].includes(name))return res.writeHead(404).end();
 res.writeHead(200,{'Content-Type':name.endsWith('.wasm')?'application/wasm':name.endsWith('.html')?'text/html':'text/javascript','Cache-Control':'no-store'}).end(fs.readFileSync(path.join(root,name)));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{browser=await chromium.launch({channel:'chrome',headless:true,timeout:15000});result.browser=browser.version();const page=await browser.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.exposeFunction('saveOutput',a=>fs.writeFileSync(path.join(__dirname,expanded?'output-640.mp4':'output-320.mp4'),Buffer.from(a)));await page.goto(`http://127.0.0.1:${server.address().port}/qa/q3-product-integration/fixture.html`);result.native=await page.evaluate(()=>window.nativeFailure());
 for(const [name,arg] of [['qualify',null],['playback',0],['playback',2.2],['cancel',null]]){const c={name,arg};try{c.result=await deadline(page.evaluate(([name,arg])=>window[name](arg),[name,arg]));c.pass=name==='qualify'?c.result.admission.route==='q3'&&c.result.result.result.metrics.decoded===info.frames&&c.result.result.transportCleanup.settled:name==='cancel'?c.result.chunks===1&&c.result.result.transportCleanup.settled&&c.result.result.metrics.terminated:c.result.width===info.width&&c.result.height===info.height&&c.result.cleanup.settled&&c.result.created===c.result.terminated&&c.result.srcRemoved;}catch(e){c.error=e.message;c.pass=false;}result.cases.push(c);if(!c.pass)break;}
 }catch(e){result.fatal=e.message;}finally{await browser?.close();await new Promise(r=>server.close(r));result.browserClosed=true;result.pass=result.native?.error===4&&result.cases.length===4&&result.cases.every(x=>x.pass)&&result.errors.length===0;fs.writeFileSync(path.join(__dirname,expanded?'browser-640-results.json':'browser-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pass:result.pass,native:result.native,cases:result.cases.map(x=>({name:x.name,arg:x.arg,pass:x.pass,error:x.error})),errors:result.errors,fatal:result.fatal}));if(!result.pass)process.exitCode=1;}})();
