'use strict';
// Independent native comparison only; never a product decoder/encoder dependency.
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const probe=f=>JSON.parse(cp.execFileSync('ffprobe',['-v','error','-select_streams','v:0','-show_streams','-show_entries','frame=best_effort_timestamp_time','-of','json',f],{maxBuffer:2097152,windowsHide:true}));
const decode=f=>cp.execFileSync('ffmpeg',['-v','error','-i',f,'-map','0:v:0','-an','-pix_fmt','yuv420p','-fps_mode','passthrough','-f','rawvideo','-'],{maxBuffer:67108864,windowsHide:true});
// FFprobe does not report square SAR for this VP9 MP4. Independently inspect
// presentation geometry; the muxer omits pasp specifically when SAR is 1:1.
function geometry(file){const b=fs.readFileSync(file);const children=(s,e)=>{const a=[];for(let p=s;p<e;){const n=b.readUInt32BE(p);if(n<8||p+n>e)throw Error('Q3_ORACLE_BOX');a.push({p,end:p+n,type:b.toString('latin1',p+4,p+8)});p+=n;}return a;};const one=(a,t)=>{const matches=a.filter(x=>x.type===t);if(matches.length!==1)throw Error('Q3_ORACLE_TRACK');return matches[0];};const child=x=>children(x.p+8,x.end),moov=one(children(0,b.length),'moov'),trak=one(child(moov),'trak'),tkhd=one(child(trak),'tkhd'),mdia=one(child(trak),'mdia'),minf=one(child(mdia),'minf'),stbl=one(child(minf),'stbl'),stsd=one(child(stbl),'stsd'),entry=one(children(stsd.p+16,stsd.end),'vp09'),extensions=children(entry.p+86,entry.end),pasp=extensions.filter(x=>x.type==='pasp'),gcd=(a,c)=>c?gcd(c,a%c):a;
 const width=b.readUInt16BE(entry.p+32),height=b.readUInt16BE(entry.p+34),displayWidth=b.readUInt32BE(tkhd.p+84)/65536,displayHeight=b.readUInt32BE(tkhd.p+88)/65536,ratio=pasp.length?`${b.readUInt32BE(pasp[0].p+8)}:${b.readUInt32BE(pasp[0].p+12)}`:'1:1';if(pasp.length>1)throw Error('Q3_ORACLE_SAR');return {codedWidth:width,codedHeight:height,displayWidth,displayHeight,effectiveSar:ratio,effectiveDar:`${displayWidth/gcd(displayWidth,displayHeight)}:${displayHeight/gcd(displayWidth,displayHeight)}`,explicitPasp:pasp.length===1};}
const rows=[];for(const [width,height,frames,sourceName] of [[320,180,72,path.join(root,'qa/q3-browser-execution/synthetic-mpeg4.mp4')],[640,360,90,path.join(__dirname,'synthetic-640.mp4')]]){
 const outputName=path.join(__dirname,`output-${width}.mp4`),source=decode(sourceName),output=decode(outputName),sourceInfo=probe(sourceName),outputInfo=probe(outputName),meta=outputInfo.streams[0],reference=sourceInfo.streams[0],frameBytes=width*height*3/2,containerGeometry=geometry(outputName);
 let sum=0,minPsnr=Infinity;for(let p=0;p<output.length;p+=frameBytes){let square=0;for(let i=p;i<Math.min(p+frameBytes,output.length);i++)square+=(source[i]-output[i])**2;sum+=square;minPsnr=Math.min(minPsnr,10*Math.log10(255**2/(square/frameBytes)));}
 const psnr=10*Math.log10(255**2/(sum/output.length)),maxTimestampError=outputInfo.frames.length===sourceInfo.frames.length?Math.max(...outputInfo.frames.map((f,i)=>Math.abs(Number(f.best_effort_timestamp_time)-Number(sourceInfo.frames[i].best_effort_timestamp_time)))):Infinity;
 const row={width,height,frames,sourceSha256:sha(fs.readFileSync(sourceName)),outputSha256:sha(fs.readFileSync(outputName)),psnrAllYuv:psnr,minimumFramePsnr:minPsnr,maxTimestampErrorSeconds:maxTimestampError,containerGeometry,metadata:{codec:meta.codec_name,pixelFormat:meta.pix_fmt,colorSpace:meta.color_space,colorPrimaries:meta.color_primaries,colorTransfer:meta.color_transfer,colorRange:meta.color_range,sar:meta.sample_aspect_ratio,dar:meta.display_aspect_ratio,frameRate:meta.avg_frame_rate},pass:source.length===output.length&&output.length===frames*frameBytes&&psnr>=38&&minPsnr>=33&&maxTimestampError<=0.000001001&&meta.codec_name==='vp9'&&meta.width===width&&meta.height===height&&meta.pix_fmt==='yuv420p'&&['color_space','color_primaries','color_transfer','color_range'].every(k=>meta[k]===reference[k])&&containerGeometry.codedWidth===width&&containerGeometry.codedHeight===height&&containerGeometry.displayWidth===width&&containerGeometry.displayHeight===height&&containerGeometry.effectiveSar===reference.sample_aspect_ratio&&containerGeometry.effectiveDar===reference.display_aspect_ratio&&meta.avg_frame_rate===reference.avg_frame_rate&&!meta.side_data_list?.length};rows.push(row);
}
const result={scope:'Independent native oracle of synthetic product-generated VP9 MP4; no long-form or device quality certification',producerSha256:sha(fs.readFileSync(__filename)),rows,pass:rows.every(x=>x.pass)};fs.writeFileSync(path.join(__dirname,'oracle-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(!result.pass)process.exitCode=1;
