import fs from 'node:fs';
import {getEventListeners} from 'node:events';
import {boundary} from '../rc19-ts-probe-reuse/boundary-harness.mjs';
const targets=[];let activeWorkers=0,createdWorkers=0,terminatedWorkers=0,createdURLs=0,revokedURLs=0;
class CountedTarget extends EventTarget{constructor(){super();this.names=new Set();targets.push(this);}addEventListener(name,...args){this.names.add(name);super.addEventListener(name,...args);}};
import assert from 'node:assert/strict';
import {createGeneralRapIndex,createGeneralPlayer} from '../../media/general-player.mjs';
import {streamGeneralQ1} from '../../media/general-pipeline.mjs';
import {fixture} from '../../tests/general-q1-fixture.mjs';
import {Input,BufferSource,MP4,EncodedPacketSink,EncodedVideoPacketSource,EncodedAudioPacketSource,EncodedPacket,Output,Mp4OutputFormat,BufferTarget} from '../../media/mediabunny-q1.mjs';
const cat=(...a)=>new Uint8Array(Buffer.concat(a.map(x=>Buffer.from(x))));
const word=n=>{const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n);return b;};
const box=(type,...data)=>{const b=cat(...data);return cat(word(b.length+8),Buffer.from(type),b);};
const init=()=>box('moov',box('trak',box('tkhd',word(0),word(0),word(0),word(1)),box('mdia',box('mdhd',word(0),word(0),word(0),word(12000)),box('hdlr',word(0),word(0),Buffer.from('vide')))),box('mvex',box('trex',word(0),word(1),word(1),word(1000),word(1),word(0x02000000))));
const fragment=(time,{cto=0,flags=0x02000000}={})=>cat(box('moof',box('traf',box('tfhd',word(0),word(1)),box('tfdt',word(0),word(Math.round(time*12000)-cto)),box('trun',word(0x01000c00),word(1),word(flags),word(cto)))),box('mdat',new Uint8Array(19)));
const trackInit=(id,handler)=>box('trak',box('tkhd',word(0),word(0),word(0),word(id)),box('mdia',box('mdhd',word(0),word(0),word(0),word(12000)),box('hdlr',word(0),word(0),Buffer.from(handler))));
const avInit=(audioId=2,audioHandler='soun')=>box('moov',trackInit(1,'vide'),trackInit(audioId,audioHandler),box('mvex',box('trex',word(0),word(1),word(1),word(1000),word(1),word(0x02000000))));
// Numeric metadata observed on Android107: known audio-only moof116B,
// tfhd0x20038, tfdtv1, trunv1/0x201/count4, followed by mdat3675B.
const audioTraf=(id=2,count=4,sampleFlags=0x02000000)=>box('traf',box('tfhd',word(0x20038),word(id),word(1024),word(0),word(sampleFlags)),box('tfdt',word(0x01000000),word(0),word(645013504)),box('trun',word(0x01000201),word(count),word(0),...[913,914,915,925].map(word)));
const audioMoof=(...trafs)=>box('moof',box('mfhd',word(0),word(1)),...(trafs.length?trafs:[audioTraf()]));
const audioTail=()=>cat(audioMoof(),box('mdat',new Uint8Array(3667)));

async function pageOwnerScenario(mode='resume'){
 const previous={MS:globalThis.MediaSource,create:URL.createObjectURL,revoke:URL.revokeObjectURL};let sb,worker;
 class SB extends CountedTarget{constructor(){super();this.updating=false;this.start=0;this.end=0;this.removes=[];}get buffered(){return {length:this.end?1:0,start:()=>this.start,end:()=>this.end};}appendBuffer(bytes){this.updating=true;const p=Buffer.from(bytes).indexOf('mdat');if(p>=0)this.end=mode==='budget'?(this.count??0)+1:[18.333333333333,39.094666,mode==='audioTail'?39.094666:60][this.count??0],this.count=(this.count??0)+1;queueMicrotask(()=>{this.updating=false;this.dispatchEvent(new Event('updateend'));});}remove(a,b){this.removes.push([a,b]);this.start=[0,18.333333333333,39.166666666667].find(t=>t>=b);queueMicrotask(()=>this.dispatchEvent(new Event('updateend')));}abort(){} }
 class MS extends CountedTarget{static isTypeSupported(){return true;}constructor(){super();this.readyState='open';}addSourceBuffer(){return sb=new SB();}removeSourceBuffer(){}endOfStream(){this.eosCalls=(this.eosCalls??0)+1;} }
 class W extends CountedTarget{constructor(){super();createdWorkers++;activeWorkers++;}postMessage(m){if(m.kind==='cancel'){queueMicrotask(()=>this.send({kind:'terminal'}));return;}if(m.kind==='reply'&&m.error){queueMicrotask(()=>this.send({kind:'terminal',error:{message:m.error}}));return;}if(m.kind==='start'){this.generation=m.generation;this.id=0;this.queue=[{kind:'window',value:{sourcePacketOrigin:0,windowOrigin:0,sourceEndTimestamp:mode==='audioTail'?39.094666:60,videoStartTimestamp:0,videoConfig:{codec:'avc1.42c00a'}}},...(mode==='budget'?[init(),...[0,1,2,3].map(t=>{const tiny=fragment(t);const split=Buffer.from(tiny).indexOf('mdat')-4;return cat(tiny.subarray(0,split),box('mdat',new Uint8Array(7*1024*1024-split-8)));})]:mode==='audioTail'?[avInit(),fragment(0),fragment(18.333333333333),audioTail()]:[init(),fragment(0),fragment(18.333333333333),fragment(39.166666666667)]).flatMap(bytes=>{const chunks=[];for(let p=0;p<bytes.length;p+=262144){const c=bytes.slice(p,p+262144);chunks.push({kind:'chunk',buffer:c.buffer,batchSize:bytes.length,batchEnd:p+c.length===bytes.length});}return chunks;})];}if(m.kind==='start'||m.kind==='reply')queueMicrotask(()=>{const n=this.queue.shift();this.send(n?{...n,id:++this.id}:{kind:'terminal'});});}send(m){this.dispatchEvent(Object.assign(new Event('message'),{data:{generation:this.generation,...m}}));}terminate(){if(!this.terminated){this.terminated=true;activeWorkers--;terminatedWorkers++;this.queue=[];}} }
 const video=new CountedTarget();Object.assign(video,{currentTime:mode==='budget'?0:8.593685,paused:true,playbackRate:1,disableRemotePlayback:false,getAttribute:()=>video.src,removeAttribute:()=>{video.src='';},pause(){this.paused=true;},load(){queueMicrotask(()=>media.dispatchEvent(new Event('sourceopen')));}});let media;globalThis.MediaSource=MS;URL.createObjectURL=m=>{createdURLs++;media=m;return 'blob:owned-test';};URL.revokeObjectURL=()=>{revokedURLs++;};
 let player;
 try{player=createGeneralPlayer({video,initialTime:mode==='budget'?0:8.593685,openSource:async()=>({identity:{size:1},read:async()=>Uint8Array.of(0),abort:async()=>({settled:true})}),isCurrent:()=>true,workerFactory:()=>worker=new W()});await player.ready;await new Promise(r=>setImmediate(r));if(mode==='budget'){await player.completion();assert.equal(player.stats().failure,'GENERAL_RETENTION_LIMIT');assert.ok(player.stats().peakRetainedAppendBytes<=24*1024*1024);assert.deepEqual(sb.removes,[]);await player.dispose();return;}if(mode==='cancel'){assert.equal(player.stats().waits,1);const appends=player.stats().appends;assert.equal((await player.dispose()).settled,true);video.currentTime=27.2;video.dispatchEvent(new Event('timeupdate'));await player.completion();assert.equal(player.stats().appends,appends);assert.deepEqual(sb.removes,[]);assert.equal(worker.terminated,true);return;}assert.deepEqual(sb.removes,[]);assert.equal(player.stats().waits,1);
  video.currentTime=27.2;video.dispatchEvent(new Event('timeupdate'));await player.completion();assert.equal(player.stats().failure,null);assert.equal(player.stats().phase,'buffered-to-end');assert.equal(media.eosCalls,1);assert.equal(sb.removes.length,1);assert.ok(sb.removes[0][1]<18.333333333333);assert.ok(sb.start<video.currentTime&&sb.end>video.currentTime);assert.ok(player.stats().peakRetainedAppendBytes<=24*1024*1024);assert.equal((await player.dispose()).settled,true);assert.equal(worker.terminated,true);
 }finally{await player?.dispose();if(player)assert.equal(player.stats().disposed,true);globalThis.MediaSource=previous.MS;URL.createObjectURL=previous.create;URL.revokeObjectURL=previous.revoke;}
}

const samples=[];for(let cycle=1;cycle<=50;cycle++){await pageOwnerScenario(cycle%3===0?'cancel':cycle%3===1?'resume':'audioTail');const retiredWorkerCallbacks=targets.filter(t=>t.terminated).reduce((n,t)=>n+[...t.names].reduce((sum,name)=>sum+getEventListeners(t,name).length,0),0);const listeners=targets.filter(t=>!t.terminated).reduce((n,t)=>n+[...t.names].reduce((sum,name)=>sum+getEventListeners(t,name).length,0),0);assert.equal(activeWorkers,0);assert.equal(createdWorkers,terminatedWorkers);assert.equal(createdURLs,revokedURLs);assert.equal(listeners,0);const ts=await boundary({fault:cycle%2===0?'503':undefined});assert(ts.sources.every(s=>s.cleanupSettled));assert.equal(ts.state.bootstrap.state,'aborted');samples.push({cycle,listeners,retiredWorkerCallbacks,activeWorkers,outstandingURLs:createdURLs-revokedURLs,tsSourcesSettled:true,generalDisposed:true});targets.length=0;}
fs.writeFileSync(new URL('./results.json',import.meta.url),JSON.stringify({passed:true,cycles:50,generalModes:['resume','audioTail','cancel'],tsProbeModes:['ordinary','503-reader-replacement'],counts:{createdWorkers,terminatedWorkers,createdURLs,revokedURLs},closedSamples:samples,scope:'Controlled Node EventTarget/Worker/MSE facades with actual current general/TS player code; terminated Worker facade callbacks remain visible only in deliberately retained test targets, excluded from active-resource count and recorded per-cycle; no native decoder allocations or process-memory measurement; historical isolated native50 proof retained separately.'},null,2)+'\n');console.log(JSON.stringify({passed:true,cycles:50,createdWorkers,terminatedWorkers,createdURLs,revokedURLs}));
