 'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('../node_modules/playwright');const root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const names=['app.js','sw.js','index.html','styles.css','media/revision-pin.js'],hashes=()=>Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(root,n)))]));
const report={scope:'Native exact app/SW one fixed update and repeated same-byte check/reload, routing vs no-routing, no media/account/auth injection; isolates harness lifecycle behavior only',producerStart:hashes(),producerSha256:sha(fs.readFileSync(__filename)),cases:[]};
(async()=>{for(const routing of [true,false]){const r={routing,scriptResponses:[],versions:[],stages:[]};report.cases.push(r);let browser,replace=false;const start=Date.now();const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local'),f=path.resolve(root,'.'+u.pathname+(u.pathname==='/'?'index.html':''));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory())return res.writeHead(404).end();const body=u.pathname==='/sw.js'&&replace?Buffer.concat([fs.readFileSync(f),Buffer.from('\n// Unit21 isolated replacement marker.\n')]):fs.readFileSync(f);if(['/sw.js','/media/revision-pin.js'].includes(u.pathname))r.scriptResponses.push({ms:Date.now()-start,category:u.pathname==='/sw.js'?'main-worker':'imported-revision-pin',sha256:sha(body),replacement:replace,destination:req.headers['sec-fetch-dest']||null});res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.mjs':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream','Cache-Control':'no-store'});res.end(body);});
try{await new Promise(x=>server.listen(0,'127.0.0.1',x));const origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({channel:'chrome',headless:true,args:['--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1']});report.browser=browser.version();const context=await browser.newContext();if(routing)await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.fulfill({status:403,body:'{}'}));const page=await context.newPage(),cdp=await context.newCDPSession(page),aliases=new Map();cdp.on('ServiceWorker.workerVersionUpdated',e=>{for(const v of e.versions){if(!aliases.has(v.versionId))aliases.set(v.versionId,'worker-'+(aliases.size+1));r.versions.push({ms:Date.now()-start,worker:aliases.get(v.versionId),status:v.status,running:v.runningStatus});}});await cdp.send('ServiceWorker.enable');const sample=async stage=>r.stages.push({stage,ms:Date.now()-start,versions:aliases.size,...await page.evaluate(()=>({controllerState:navigator.serviceWorker.controller?.state,activeState:state.serviceWorkerRegistration?.active?.state,installing:!!state.serviceWorkerRegistration?.installing,waiting:!!state.serviceWorkerRegistration?.waiting,selected:!!state.selected,q1:!!q1Playback,cleanup:q1RetirementResult}))});const ready=()=>page.waitForFunction(()=>navigator.serviceWorker.controller?.state==='activated'&&state.serviceWorkerRegistration?.active===navigator.serviceWorker.controller&&el.setupView?.getAttribute('aria-busy')==='false');
await page.goto(origin+'/?demo=1');await ready();await page.waitForTimeout(2600);await sample('initial-startup-check-complete');await page.evaluate(()=>window.qaOld=navigator.serviceWorker.controller);replace=true;await page.evaluate(()=>state.serviceWorkerRegistration.update());await page.waitForFunction(()=>navigator.serviceWorker.controller!==qaOld&&navigator.serviceWorker.controller.state==='activated');await sample('one-fixed-update');await page.evaluate(()=>checkForAppUpdate({manual:false}));await page.waitForTimeout(2600);await sample('same-bytes-explicit-check');await page.reload({waitUntil:'domcontentloaded'});await ready();await page.waitForTimeout(3500);await sample('same-bytes-reload-startup-check');r.completed=true;
}catch(e){r.failure={name:e.name,message:e.message.split('\n')[0]};process.exitCode=1;}finally{await browser?.close();r.browserClosed=true;await new Promise(x=>server.close(x));r.serverClosed=true;}}
report.producerEnd=hashes();assert.deepEqual(report.producerStart,report.producerEnd);report.completed=true;fs.writeFileSync(path.join(__dirname,'routing-control-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.cases.map(r=>({routing:r.routing,stages:r.stages.map(s=>({stage:s.stage,versions:s.versions})),failure:r.failure}))));})().catch(e=>{console.error(e.name);process.exitCode=1;});
