import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {build} from './build.mjs';
const base=new URL('./',import.meta.url),hash=x=>createHash('sha256').update(x).digest('hex');
const result=await build();
await writeFile(new URL('factory-v2.expression.js',base),result.expression);
await writeFile(new URL('provenance.json',base),JSON.stringify(result.provenance,null,2)+'\n');
assert.equal(hash(await readFile(new URL('factory-v2.expression.js',base))),result.provenance.expressionSHA256);
assert.equal(typeof vm.runInNewContext(result.expression,{}),'function');
const focused=['qa/rc21-corpus-night/cache.test.mjs','qa/rc21-corpus-night/probe.test.mjs'];
const core=['qa/v2-07a-bounded-probe/bounded-probe.test.mjs','qa/v2-07a-bounded-probe/drive-browser-adapter.test.mjs','qa/v2-07a-isobmff-index/isobmff-index.test.mjs'];
const log=(paths)=>execFileSync(process.execPath,['--test','--test-reporter=tap',...paths],{encoding:'utf8',timeout:30000});
const focusedLog=log(focused),coreLog=log(core);
assert.match(focusedLog,/# tests 23/);assert.match(focusedLog,/# pass 23/);assert.match(focusedLog,/# fail 0/);assert.match(coreLog,/# tests 148/);assert.match(coreLog,/# pass 148/);assert.match(coreLog,/# fail 0/);
await writeFile(new URL('local-tests.tap',base),focusedLog);await writeFile(new URL('affected-contract-tests.tap',base),coreLog);
const paths=['metadata-read-cache.mjs','sparse-moov.mjs','probe.mjs','build.mjs','cache.test.mjs','probe.test.mjs','factory-v2.expression.js','provenance.json','README.md','verify.mjs','local-tests.tap','affected-contract-tests.tap'];
const files=Object.fromEntries(await Promise.all(paths.map(async p=>[p,hash(await readFile(new URL(p,base)))])));
const record={schema:'drive-original.rc21-corpus-night-verification/1',sourceHEAD:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),expressionSHA256:result.provenance.expressionSHA256,files,focusedTests:{passed:23,failed:0},affectedContractTests:{passed:148,failed:0},syntheticLatency:{oldRequests:38,newRequests:30,oldBytes:555,newBytes:555,perRequestFakeMs:1100,oldFakeMs:41800,newFakeMs:33000},actualExecution:false,privateContextInArtifact:false,productChanges:false,genericUpstreamCleanup:'unknown'};
await writeFile(new URL('local-verification.json',base),JSON.stringify(record,null,2)+'\n');
console.log(JSON.stringify({expressionSHA256:record.expressionSHA256,focusedTests:record.focusedTests,affectedContractTests:record.affectedContractTests,actualExecution:false}));
