'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const files=fs.readdirSync(__dirname).filter(n=>/\.(?:cjs|expression\.js)$|(?:-result|rows|clauses|-(?:binding|derivation|repair))\.json$|^README\.md$/.test(n)).filter(n=>!n.includes('private'));
const commonModules=files.filter(n=>/^android-(?:common|inspect-common|transition-common)/.test(n)).map(n=>({path:n,sha256:hash(path.join(__dirname,n))}));
const reports=files.filter(n=>n.endsWith('-result.json')).map(n=>{const r=JSON.parse(fs.readFileSync(path.join(__dirname,n),'utf8'));return{path:n,sha256:hash(path.join(__dirname,n)),producerSha256:r.producerSha256,commonSha256:r.commonSha256,commonVersion:commonModules.find(c=>c.sha256===r.commonSha256)?.path||null,completed:r.completed,failure:r.failure||null};});
fs.writeFileSync(path.join(__dirname,'provenance.json'),JSON.stringify({schema:'drive-original.android-attempt-provenance/1',recordedAt:new Date().toISOString(),curatorSha256:hash(__filename),commonModules,reports,files:files.map(n=>({path:n,sha256:hash(path.join(__dirname,n))}))},null,2)+'\n');
const clauses={schema:'drive-original.android-scoped-acceptance-clauses/1',baselineRuntime:'1.22.0-rc.21',currentRuntime:'1.22.0-rc.26',currentSource:'3eea49a4853052275582979ab205eee8026c4691',identity:'121-rc26-device-update-identity-result.json',actualPlatform:'physical Android tablet native input',wholeRowPromotions:0,original69RowsPreserved:true,remaining42MapPreserved:true,clauses:[
 {ids:['QA-UI-01','QA-UI-03'],clause:'D056 pause-independent reveal/dismiss and native summary controls',status:'passed-android-tablet-clause',result:'37-rc22-native-controls-result.json',baseline:'03-touch-playback-result.json',confirmation:'41-rc22-native-presented-transitions-result.json'},
 {ids:['QA-TR-03'],clause:'paused native10/50/90 presented targetframes',status:'passed-one-actual-Q0-source-clause',result:'15-native-qualified-controls-result.json'},
 {ids:['QA-TR-03'],clause:'native paused Q1 10/50/90 presented targets',status:'passed-one-actual-Q1-source-clause',result:'47-rc23-native-q1-seek-return-result.json',freshCredentialDiscriminator:'45-rc22-native-q1-seek-discriminator-result.json',failure:'43-rc22-native-q1-seek-return-result.json',failureDiscriminator:'44-rc22-native-q1-seek-failure-result.json',remaining:'Earlier rc22 failure machinecode/cause unknown; other Q1 sources and full expiry continuity not inferred'},
 {ids:['QA-FM-01','QA-FM-02'],clause:'four bounded original declared-label sources on actual Android',status:'passed-limited-original-source-clause',result:'42-rc22-rare-native-container-result.json',remaining:'MOV/MKV/AVI labels were admitted TS; true-container and Q2 coverage not inferred'},
 {ids:['QA-TR-12'],clause:'OSHome34.107s genuinely hidden return',status:'passed-one-actual-Q0-source-clause',result:'11-native-detached-return-ready-result.json'},
 {ids:['QA-TR-12'],clause:'OSHome30.573s genuinely hidden Q1 owner-preserving return',status:'passed-one-actual-Q1-source-clause',result:'47-rc23-native-q1-seek-return-result.json',foregroundDetectorCorrection:'49-native-foreground-detector-result.json',remaining:'47 mResumedActivity package booleans unqualified; passive hidden visibility journal is actual,49 independently verifies current Chrome topResumedActivity'},
 {ids:['QA-UI-07'],clause:'horizontal native swipe expected source/new frame',status:'passed-limited-clause',result:'15-native-qualified-controls-result.json'},
 {ids:['QA-UI-07','QA-UI-08'],clause:'subthreshold native first move retains cancelability and expected presented source',status:'corrected-actual-native-rc22-clause',result:'41-rc22-native-presented-transitions-result.json',failure:'17-sequential-vertical-discriminator-result.json',discriminator:'16-vertical-discriminator-result.json',localCorrection:'21-local-reservation-browser-result.json',remaining:'Full OS edge/cancel/reentry and enduring gesture matrix'},
 {ids:['QA-UI-07'],clause:'native second contact cancels active drag',status:'passed-android-native-clause',result:'38-rc22-native-two-contact-result.json',baseline:'22-native-two-contact-result.json'},
 {ids:['QA-UI-09'],clause:'portrait renderer fullscreen entry exit and native Back',status:'passed-limited-android-clause',result:'19-native-visible-fullscreen-back-result.json',remaining:'System-chrome hiding, physical rotation, OS edge and iPhone safe areas'},
 {ids:['QA-AU-01','QA-AU-09'],clause:'existing bootstrap credential resource failure then ordinary reload recovery',status:'historical503-normal-reload200-current-ready',result:'29-auth-status-result.json',recovery:'31-native-normal-startup-recovery-result.json',library:'32-recovered-library-readiness-result.json',remaining:'Natural automatic expiry continuity remains failed/unverified; reload recovery is a narrower clause'},
 {ids:['QA-LF-01'],clause:'bounded normal close owners cleared',status:'passed-indicators-only-clause',result:'14-native-controls-cleanup-result.json',remaining:'50cycles and independent worker/memory proof'},
 {ids:['QA-ST-01'],clause:'foreground operational same-account and fresh canonical favorite PC to Android',status:'passed-actual-two-device-operational-clause',result:'57-rc23-state-challenge-passive-read-result.json',canonicalCacheBypass:'58-rc23-state-challenge-remote-read-result.json',baseline:'52-rc23-state-challenge-ready-result.json',reverseNative:'59-rc23-state-challenge-final-native-echo-result.json',reverseObservationOwner:'coordinator normal PC evidence required',timing:'PC to Android14,927ms; reverse exact false received by coordinator57.795s after action, earlier PC sampler timeout retained',remaining:'No raw identity comparison; full row still needs both viewed directions'},
 {ids:['QA-ST-01'],clause:'normal PC playback viewed to Android foreground normal account poll',status:'passed-one-viewed-direction-clause',result:'61-rc23-viewed-challenge-passive-read-result.json',canonicalCacheBypass:'62-rc23-viewed-challenge-remote-read-result.json',cleanup:'63-rc23-state-challenge-cleanup-result.json',timing:'16,415ms with250ms passive observer resolution',remaining:'Android to PC fresh viewed not yet observed; favoritefalse restored semantically with newer tombstone, viewedtrue preserved with newer normal playback timestamp'},
 {ids:['QA-ST-01'],clause:'normal Android actual presented playback creates reverse viewed canonical challenge',status:'passed-Android-writer-clause-PC-observation-owned-by-coordinator',result:'66-rc23-reverse-viewed-read-recovery-result.json',failure:'65-rc23-reverse-viewed-native-play-result.json',canonicalCacheBypass:'67-rc23-reverse-viewed-remote-read-result.json',cleanup:'68-rc23-reverse-viewed-cleanup-result.json',remaining:'65 first independent callback failed wrong QA selected identifier;66 later actual frames qualify same playback, no second tap; coordinator owns PC receipt and unrelated-state preservation comparison'},
 {ids:['QA-FM-03'],clause:'automatic actual Android synthetic AVC/AC3 Q2 normal native6s endpoint and settled close',status:'passed-actual-Android-synthetic-clause',result:'78-rc24-native-synthetic-q2-end-result.json',earlyCounterFailure:'77-rc24-native-synthetic-q2-script-journal-result.json',controllerFailures:['74-rc24-native-synthetic-q2-short-result.json','75-rc24-native-synthetic-q2-settled-result.json','76-rc24-native-synthetic-q2-controller-result.json'],transportFailures:['71-rc24-native-synthetic-q2-result.json','72-rc24-native-synthetic-q2-result.json','73-rc24-native-synthetic-q2-cdp-result.json'],remaining:'Original AC3 source, audible quality, independent native encoder-clock observer and420s Android duration not qualified; pipeline reportsvideoEncodersCreated0 andclosedaudio contexts'},
 {ids:['QA-AU-09'],clause:'earlier actual original Q1 natural watch invalidated by selected-source change before expiry',status:'historical-failed-same-owner-continuity-clause',result:'81-rc24-android-natural-renewal-watch-result.json',currentStateDiscriminator:'83-rc24-renewal-owner-failure-read-result.json',remaining:'OWNER_CHANGED before old expiry; later revision61 on a different source did not prove same-owner continuity. Exact source-change cause remains unknown; separate101 subsequently qualifies a fresh61 boundary'},
 {ids:['QA-AU-09'],clause:'actual physical Android same-original Q1 natural61 to62 renewal through old expiry plus120s and subsequent native seek/settled close',status:'passed-one-original-source-actual-Android24-clause',result:'101-rc24-android-revision61-natural-watch-result.json',baseline:'100-rc24-original-revision61-prepare-result.json',laterSeekClose:'82-rc24-post-renewal-native-seek-close-result.json',observerPrivacyFixture:'98-renewal-observer-privacy-fixture-result.json',remaining:'Source24 evidence; no forced auth/clock/loop/UI, no trusted DOM inputs. Further candidate25 source/update verification and other platforms remain separate'},
 {ids:['QA-FM-03'],clause:'actual Android synthetic420s automatic Q2 fails when native MSE pruning removes current playback range',status:'failed-actual-Android-synthetic-long-clause',result:'93-rc24-native-synthetic-q2-420s-bt709-result.json',nativeMSEDiscriminator:'95-rc24-native-q2-passive-remove-discriminator-result.json',colorPreconditionCounterexample:'89-rc24-native-synthetic-q2-420s-result.json',fixture:'91-build-420s-bt709-synthetic-fixture-result.json',remaining:'GENERAL_REMOVE_CURRENT_RANGE after8.6s:remove(0,0.593685) moves bufferedstart0 to18.333333 whilecurrentTime8.604036. No product patch or420s success claimed'},
 {ids:['QA-FM-03'],clause:'actual Android25 synthetic420s automatic Q2 corrected native RAP pruning then near-EOF fragment failure',status:'failed-full-duration-with-corrected-native-pruning',result:'105-rc25-native-synthetic-q2-420s-result.json',sourceIdentity:'103-rc25-device-update-identity-result.json',controllerSettled:'104-rc25-controller-settle-result.json',publicRestored:'106-rc25-public-restored-source-proof-result.json',remaining:'19 native removals preserve current playback range; actual lastframe404.166666/presented4832/maxgap171ms then GENERAL_OUTPUT_FRAGMENT. No420s/nativeended/pipeline counters claim;105 failed before normal settled-close assertion'},
 {ids:['QA-FM-03'],clause:'actual native paused95percent Q2 seek isolates known audio-only final fragment rejection',status:'passed-diagnostic-reproducing-product-failure',result:'107-rc25-native-fragment-discriminator-result.json',observerFixture:'109-fragment-observer-fixture-result.json',remaining:'Native398.916666 frame then GENERAL_OUTPUT_FRAGMENT1110ms afterseek. Final116Bmoof only known audio2/trun4 with3675Bmdat; parseCode0. NormalBack/retirement settled and owned observer/provider/CDP/MCP/ADB cleanup; no full-duration success'},
 {ids:['QA-UI-07'],clause:'actual Android25 native library card longpress completion, native menu consumption and motion cancellation',status:'passed-actual-tablet-library-clause',result:'111-rc25-native-library-longpress-result.json',remaining:'1100ms hold selects1/release opensno player; trusted contextmenu defaultPreventedtrue; nativecancel restores0; native40px movement pointercancel/no selection. No originalmedia or canonicalstate writes. InputuserSelectauto onlyCSS property proof; actual native input editing remains separate'},
 {ids:['QA-UI-08','QA-UI-09'],clause:'temporary reduced-motion CSS contract and unqualified OSedge retreat sequence',status:'partial-pass-motion-failed-edge-expectation',result:'113-rc25-native-edge-reduced-motion-result.json',remaining:'Actual renderer0.16s to0.00001s restored/noOSsettings. Edge1to42to1 sequence native touchcancel closesplayer before retreat assertion; intendedcancel and stablecontact ownership unqualified, no productcause assigned. Native physicalrotation notperformed; rotatecontrol zero at824px tablet'},
 {ids:['QA-UI-07'],clause:'actual native search typing deletion insertion and normal input longpress selection',status:'passed-actual-tablet-input-editing-clause',result:'117-rc25-native-input-editing-result.json',remaining:'Safe14character QAtext typed/edited by trusted nativebeforeinput/input; nativehold selects14characters/contextmenu notprevented. Priorprivatequery restored/nativeBack/blur/observer cleanup; no canonical/mediawrite'},
 {ids:['QA-UI-08'],clause:'stable native subintent edge retreat preserves same original Q1 then committed edge performs one native browser history close',status:'passed-one-actual-tablet-edge-clause',result:'115-rc25-native-stable-edge-discriminator-result.json',earlierFailure:'113-rc25-native-edge-reduced-motion-result.json',remaining:'Stable scrcpycontact1to10to1 yields touchcancel but no popstate/appclose/mediaaxis; frames45to70/sourceowner retained. Separate1to260 yields touchcancel/one trustedpopstate/no apprequestClose; normal settlement allownersabsent. No other-platform or enduring edge matrix/physicalrotation claim'},
 {ids:['QA-FM-03'],clause:'actual Android26 qualified420s synthetic automatic Q2 final audio-only fragment ACK MSE EOS nativeended and settled close',status:'passed-actual-Android-synthetic420-duration-endpoint-clause',result:'124-rc26-native-synthetic-q2-420s-result.json',narrowTerminal:'123-rc26-native-terminal-fragment-result.json',sourceIdentity:'121-rc26-device-update-identity-result.json',activeController:'122-rc26-current-source-controller-proof-result.json',publicRestored:'125-rc26-public-restored-source-proof-result.json',earlierFailures:['93-rc24-native-synthetic-q2-420s-bt709-result.json','95-rc24-native-q2-passive-remove-discriminator-result.json','105-rc25-native-synthetic-q2-420s-result.json','107-rc25-native-fragment-discriminator-result.json'],remaining:'SyntheticAVC/AC3 input only, no originalAC3/audiblefidelity claim. Fullclipduration420/native420.0065/lastframe419.916666; normalinitialfallbacktarget0.205962 means not420pureQ2seconds. 19safeprunes/maxgap173ms/86chunks86ACK/EOSonce/workerterminated/sourcecleanupsettled/videoEncoder0/audioContext0/failures0/allownerretirementsettled'},
 {ids:['QA-SW-01'],clause:'actual normalAndroid25 to26 current activated controller and all immutable cachedcore responses',status:'passed-one-actual-Android-update-and-core-cache-clause',result:'127-rc26-current-core-cache-alias-proof-result.json',sourceIdentity:'121-rc26-device-update-identity-result.json',activeController:'122-rc26-current-source-controller-proof-result.json',localFailedPrecondition:'126-rc26-current-core-cache-proof-result.json',remaining:'All41requestpaths includingroot/index alias40uniqueassets exactcachedSHA/no network/refill/extras0. Does not override coordinatorPCnormalupdatefailure or promoteold/new/offlinewhole-row'},
],unverified:['Android-to-PC-fresh-viewed-observation-coordinator-owned','audio-fidelity','Q2-original-source-and-audiblefidelity-on-Android','full-hour-duration','other-platform-edge-and-enduring-matrix','physical-rotation-system-fullscreen','50cycle-memory','iPhone-Safari-standalone-VoiceOver']};
fs.writeFileSync(path.join(__dirname,'acceptance-clauses.json'),JSON.stringify(clauses,null,2)+'\n');
console.log(JSON.stringify({reports:reports.length,actualDeviceReports:reports.filter(r=>r.commonSha256).length,allRecordedCommonHashesRecoverable:reports.filter(r=>r.commonSha256).every(r=>r.commonVersion),wholeRowPromotions:0,upwardSwipe:'rc21-defect-preserved-rc22-native-corrected',seeks:'3/3 actual native presented frames',actualHiddenMs:34107}));
