const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const here=__dirname,root=path.resolve(here,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const source=process.argv[2];if(source!=='051dc3456f5000b958a18593848769b3687991e5')throw Error('EXPLICIT_FIXED37_FULL_SHA_REQUIRED');
const git=p=>execFileSync('git',['show',source+':'+p],{cwd:root,windowsHide:true,maxBuffer:32*1024*1024});
const app=git('app.js'),sw=git('sw.js'),version=git('version.json');
if(!app.includes("const APP_VERSION = '1.22.0-rc.37'")||!sw.includes("const VERSION = '1.22.0-rc.37'")||JSON.parse(version).version!=='1.22.0-rc.37')throw Error('FIXED37_VERSION_REQUIRED');
const fixturePath=path.join(root,'qa/fm05-controlled-diagnostic/subtitle.mp4'),bytes=fs.readFileSync(fixturePath);
const fixture={bytes:bytes.length,sha256:sha(bytes),md5:crypto.createHash('md5').update(bytes).digest('hex')};
if(fixture.bytes!==659966||fixture.sha256!=='d9a1cc3f12a7a3b3a91f408e59da8e1f9b8dfb2e4ec26dd8d969cedc27893037'||fixture.md5!=='cc7a0da5f6e2b89a9fdee916d259d285')throw Error('EXACT_COLOR_FIXTURE_REQUIRED');
const binding={version:'1.22.0-rc.37',source,sourceSHA256:{'app.js':sha(app),'sw.js':sha(sw),'version.json':sha(version)}};
const text=fs.readFileSync(path.join(here,'disposable-job.mjs'),'utf8').replace(/^export /m,'');
const factory=`(function(env,binding,options){${text}\nreturn q3DisposableJob(env,binding,${JSON.stringify(fixture)},options);})\n`;
const producers=['disposable-job.mjs','disposable-facade.function.js','disposable-file-input.function.js','disposable-build.cjs'];
const producerSHA256=Object.fromEntries(producers.map(p=>[p,sha(fs.readFileSync(path.join(here,p)))]));
const preparation={actualExecution:false,binding,fixture:{path:'qa/fm05-controlled-diagnostic/subtitle.mp4',...fixture},fixtureHeaderSHA256:'e8e8e98b9316acba11449c26a947281229bd481b8729fb21d4e34de2d3cded3e',factorySHA256:sha(factory),factoryBytes:Buffer.byteLength(factory),producerSHA256,contract:'Exactly1 task-created tagged folder +1 immutable video;2 generated IDs/2 POST; persisted intent before POST; GET-only unknown-outcome recovery; exact size/SHA256/MD5 receipt; separately recoverable trash only; no retry; root owns actual execution'};
fs.writeFileSync(path.join(here,'disposable-binding.json'),JSON.stringify(binding,null,2)+'\n');
fs.writeFileSync(path.join(here,'disposable-factory.expression.js'),factory);
fs.writeFileSync(path.join(here,'disposable-build.json'),JSON.stringify(preparation,null,2)+'\n');
console.log(JSON.stringify({source,version:binding.version,factorySHA256:preparation.factorySHA256,factoryBytes:preparation.factoryBytes,fixtureSHA256:fixture.sha256,fixtureMD5:fixture.md5,fixtureBytes:fixture.bytes,fixtureHeaderSHA256:preparation.fixtureHeaderSHA256,actualExecution:false}));
