'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),worker=path.join(root,'worker'),base='https://drive-original-v2-candidate.drive-original-cloudflare-candidate.workers.dev/';
const git=args=>cp.execFileSync('git',args,{cwd:root,maxBuffer:128*1024*1024}),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const load=name=>JSON.parse(fs.readFileSync(path.join(__dirname,name))),save=(name,row)=>fs.writeFileSync(path.join(__dirname,name),JSON.stringify(row,null,2)+'\n',{flag:'wx'});
const source=()=>git(['rev-parse','HEAD']).toString().trim(),blob=(ref,file)=>git(['show',`${ref}:${file}`]);
function requirePreparation(){const p=load('preparation.json');assert.equal(source(),p.source);assert.equal(git(['status','--porcelain']).length,0);assert.equal(sha(fs.readFileSync(__filename)),p.producerSha256);return p;}
function prepare(){
 const ref=source();assert.equal(git(['status','--porcelain']).length,0);assert.equal(git(['branch','--show-current']).toString().trim(),'main');
 const files=require('../../scripts/public-files.cjs'),publicAssets=files.map(file=>{const b=blob(ref,file);return{file,bytes:b.length,sha256:sha(b)}});publicAssets.push({file:'.nojekyll',bytes:0,sha256:sha(Buffer.alloc(0))});assert.equal(publicAssets.length,65);
 const prior=JSON.parse(blob(ref,'qa/candidate-rc38-delivery/source-readiness.json'));assert(prior.passed);const changes=files.filter(file=>!blob(ref,file).equals(blob(prior.sourceCommit,file)));assert.deepEqual(changes.sort(),['app.js','index.html','runtime-config.js','sw.js','version.json']);
 const mode={};vm.runInNewContext(blob(ref,'runtime-config.js').toString(),mode);assert.deepEqual(JSON.parse(JSON.stringify(mode.__DRIVE_ORIGINAL_RUNTIME__)),{candidate:false,driveMutationsEnabled:true,accountStateWritesEnabled:true});
 const local=load('local-checks.json');assert(local.passed&&local.tests===843);for(const row of local.inputs)assert.equal(sha(fs.readFileSync(path.join(root,row.file))),row.sha256);
 const site=path.join(path.dirname(root),'releases',`Drive-Original-v1.22.0-${ref.slice(0,7)}`);assert(site.startsWith(path.dirname(root)+path.sep+'releases'+path.sep));assert(!fs.existsSync(site));fs.mkdirSync(site);
 for(const row of publicAssets){const absolute=path.join(site,row.file);fs.mkdirSync(path.dirname(absolute),{recursive:true});fs.writeFileSync(absolute,row.file==='.nojekyll'?Buffer.alloc(0):blob(ref,row.file),{flag:'wx'});assert.equal(sha(fs.readFileSync(absolute)),row.sha256);}
 const config=JSON.parse(blob(ref,'worker/wrangler.jsonc'));assert.equal(config.vars.PUBLIC_ORIGIN,new URL(base).origin);assert.equal(config.vars.AUTH_ENABLED,'true');assert.equal(config.vars.AUTH_DIAGNOSTICS,'false');assert.equal(config.vars.CANDIDATE_DRIVE_WRITES_ENABLED,'true');assert.equal(config.observability.enabled,false);
 save('preparation.json',{source:ref,version:'1.22.0',base,site,publicAssets,priorRuntime:prior.sourceCommit,priorWorkerVersion:prior.workerVersion,changes,localChecksSha256:sha(fs.readFileSync(path.join(__dirname,'local-checks.json'))),producerSha256:sha(fs.readFileSync(__filename)),limits:{deployMs:300000,readbackMs:60000,verificationMs:150000,requestMs:20000,cleanupMs:15000},rollback:'Restore prior Worker8f0a21d7-45bb-4164-910e-b4e66db0f52a with the same existing DO/secrets if serving fails; no forced history overwrite',preparedAt:new Date().toISOString()});
 return{prepared:true,source:ref,assets:65,mediaUnchanged:true,site};
}
function deploy(){const p=requirePreparation();for(const row of p.publicAssets)assert.equal(sha(fs.readFileSync(path.join(p.site,row.file))),row.sha256);save('deployment-attempt.json',{source:p.source,startedAt:new Date().toISOString(),completed:false,noAutomaticRetry:true});
 const run=cp.spawnSync(process.execPath,[path.join(worker,'node_modules/wrangler/bin/wrangler.js'),'deploy','--config','wrangler.jsonc','--assets',p.site],{cwd:worker,env:{...process.env,WRANGLER_SEND_METRICS:'false',DO_NOT_TRACK:'1'},encoding:'utf8',timeout:p.limits.deployMs,maxBuffer:8*1024*1024,windowsHide:true});
 const raw=(run.stdout||'')+(run.stderr||'');fs.writeFileSync(path.join(__dirname,'deployment-private.log'),raw,{flag:'wx'});const workerVersion=/Current Version ID:\s*([a-f0-9-]{36})/i.exec(raw)?.[1]||null;const r={passed:run.status===0&&!run.signal&&!run.error&&!!workerVersion,source:p.source,version:p.version,base,workerVersion,exitCode:run.status,errorCode:run.error?.code||null,rawLogSha256:sha(Buffer.from(raw)),finishedAt:new Date().toISOString()};save('deployment.json',r);assert(r.passed,'PRODUCTION_DEPLOYMENT_FAILED');return r;
}
function readback(){const p=requirePreparation(),d=load('deployment.json');assert(d.passed);assert.equal(d.source,p.source);save('readback-attempt.json',{source:p.source,workerVersion:d.workerVersion,startedAt:new Date().toISOString(),noAutomaticRetry:true});
 const run=cp.spawnSync(process.execPath,[path.join(worker,'node_modules/wrangler/bin/wrangler.js'),'versions','view',d.workerVersion,'--json','--config','wrangler.jsonc'],{cwd:worker,env:{...process.env,WRANGLER_SEND_METRICS:'false',DO_NOT_TRACK:'1'},encoding:'utf8',timeout:p.limits.readbackMs,maxBuffer:8*1024*1024,windowsHide:true});fs.writeFileSync(path.join(__dirname,'readback-private.json'),run.stdout||'',{flag:'wx'});assert.equal(run.status,0);
 const current=JSON.parse(run.stdout),prior=JSON.parse(fs.readFileSync(path.join(root,'qa/candidate-rc38-delivery/version-readback-private.json')));assert.equal(current.id,d.workerVersion);const old=prior.resources.bindings,newRows=current.resources.bindings;assert.deepEqual(newRows.map(r=>r.name).sort(),old.map(r=>r.name).sort());
 const flags={AUTH_ENABLED:'true',AUTH_DIAGNOSTICS:'false',CANDIDATE_DRIVE_WRITES_ENABLED:'true'};for(const [name,value]of Object.entries(flags))assert.equal(newRows.find(r=>r.name===name).text,value);assert.equal(newRows.find(r=>r.name==='PUBLIC_ORIGIN').text,new URL(base).origin);
 for(const row of old.filter(r=>r.type==='secret_text'||r.type==='durable_object_namespace'||r.type==='durable_object'||r.name==='GOOGLE_CLIENT_ID'))assert.deepEqual(newRows.find(r=>r.name===row.name),row);
 const r={passed:true,source:p.source,workerVersion:d.workerVersion,bindings:newRows.length,flags,sameNamespaceSecretsClient:true,publicOriginPreserved:true,rawSha256:sha(Buffer.from(run.stdout)),recordedAt:new Date().toISOString()};save('readback.json',r);return r;
}
async function bounded(p,ms,label){let timer;try{return await Promise.race([p,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error(label)),ms))]);}finally{clearTimeout(timer);}}
async function verify(){const p=requirePreparation(),d=load('deployment.json'),control=load('readback.json');assert(d.passed&&control.passed);assert.equal(d.source,p.source);assert.equal(control.source,p.source);assert.equal(control.workerVersion,d.workerVersion);const started=Date.now(),remaining=()=>{const ms=p.limits.verificationMs-(Date.now()-started);assert(ms>0,'SERVING_TOTAL_DEADLINE');return ms;},r={passed:false,source:p.source,version:p.version,base,workerVersion:d.workerVersion,productionMode:false,publicAssets:65,assets:[],privateRoutes:[],cleanup:{},startedAt:new Date().toISOString(),scope:'Fresh production delivery/config/cold-offline proof; reuse unchanged finite rc38 PC/Android playback and exact unchanged corresponding-source archive proof. No new account/media mutation or pixel/population claim.'};
 save('verification-attempt.json',{...r,limits:p.limits,preparationSha256:sha(fs.readFileSync(path.join(__dirname,'preparation.json')))});let bs,browser,context;const requests=new Set(),errors=[];
 const request=async(url,options={})=>{const ms=Math.min(remaining(),p.limits.requestMs);const controller=new AbortController();requests.add(controller);let timer=setTimeout(()=>controller.abort(),ms);try{const response=await fetch(url,{...options,signal:controller.signal,cache:'no-store'});const bytes=options.method==='HEAD'?null:Buffer.from(await response.arrayBuffer());return{response,bytes};}finally{clearTimeout(timer);controller.abort();requests.delete(controller);}};
 try{const previous=JSON.parse(blob(p.source,'qa/candidate-rc38-delivery/results.json'));assert(previous.passed);const key=(bytes,file)=>require(path.join(worker,'node_modules/blake3-wasm')).hash(bytes.toString('base64')+path.extname(file).substring(1)).toString('hex').slice(0,32);
 for(let i=0;i<p.publicAssets.length;i+=4){const rows=await Promise.allSettled(p.publicAssets.slice(i,i+4).map(async row=>{const expected=row.file==='.nojekyll'?Buffer.alloc(0):blob(p.source,row.file);assert.equal(sha(expected),row.sha256);const archive=/\.tgz$|\.tar\.gz\.part\d+$/.test(row.file);let proof;
 if(archive){const prior=previous.assets.find(x=>x.file===row.file);assert(prior.gitEqual&&prior.sha256===row.sha256&&prior.bytes===row.bytes);assert(blob(p.priorRuntime,row.file).equals(expected));const {response}=await request(base+row.file+'?release='+Date.now(),{method:'HEAD',headers:{'Accept-Encoding':'identity'}});assert.equal(response.status,200);assert.equal(response.headers.get('etag'),'"'+key(expected,row.file)+'"');const length=response.headers.get('content-length');if(length!==null)assert.equal(length,String(row.bytes));proof={status:200,method:'HEAD',etag:response.headers.get('etag'),gitEqual:true,reused:true,byteProof:'prior-exact-full-bytes/unchanged-Git/fresh-production-strong-content-address'};
 }else{const {response,bytes}=await request(base+row.file+'?release='+Date.now());assert.equal(response.status,200);assert(bytes.equals(expected));proof={status:200,method:'GET',gitEqual:true,reused:false};}return{...row,...proof};}));for(const outcome of rows)if(outcome.status==='fulfilled')r.assets.push(outcome.value);else throw outcome.reason;}
 for(const file of ['memory/CHECKPOINT.md','qa/release-1.22.0/preparation.json','tests/app.test.js','worker/wrangler.jsonc','auth/session-owner.mjs','.git/config']){const {response}=await request(base+file);assert.equal(response.status,404);r.privateRoutes.push({file,status:404});}
 const {response:session,bytes:sessionBody}=await request(base+'api/session/credential',{method:'POST',headers:{Origin:new URL(base).origin,'Content-Type':'application/json','X-Drive-Original-CSRF':'1','Sec-Fetch-Site':'same-origin','Sec-Fetch-Mode':'cors','Sec-Fetch-Dest':'empty'},body:JSON.stringify({expectedAccount:null,credentialProtocol:2})});assert.equal(session.status,401);assert.match(session.headers.get('cache-control')||'',/no-store/);assert.equal(JSON.parse(sessionBody).error.code,'unauthorized');r.anonymousSession={status:401,noStore:true,cookieAbsent:true,backendAccountMutation:false};
 remaining();const {chromium}=require('../node_modules/playwright');bs=await chromium.launchServer({channel:'chrome',headless:true,timeout:Math.min(7000,remaining())});browser=await bounded(chromium.connect(bs.wsEndpoint()),Math.min(7000,remaining()),'BROWSER_CONNECT');context=await bounded(browser.newContext({viewport:{width:1280,height:800}}),Math.min(7000,remaining()),'CONTEXT_CREATE');const page=await context.newPage();page.on('pageerror',error=>errors.push(error.name));page.setDefaultTimeout(10000);await page.goto(base,{waitUntil:'domcontentloaded',timeout:Math.min(25000,remaining())});await page.waitForFunction(()=>navigator.serviceWorker.controller&&typeof APP_VERSION==='string',null,{timeout:Math.min(25000,remaining())});remaining();
 r.cold=await page.evaluate(()=>({version:APP_VERSION,candidate:globalThis.__DRIVE_ORIGINAL_RUNTIME__.candidate,writes:DRIVE_MUTATIONS_ENABLED,accountStateWrites:ACCOUNT_STATE_WRITES_ENABLED,accountPresent:!!state.accountId,controlled:!!navigator.serviceWorker.controller}));assert.deepEqual(r.cold,{version:'1.22.0',candidate:false,writes:true,accountStateWrites:true,accountPresent:false,controlled:true});r.productionMode=true;
 const match=blob(p.source,'sw.js').toString().match(/const SHELL_FILES = (\[[\s\S]*?\]);/);const shell=Array.from(vm.runInNewContext(match[1]));assert.equal(shell.length,51);r.cache=[];
 for(const file of shell){const actual=Buffer.from(await bounded(page.evaluate(async name=>{const c=await caches.open('drive-original-shell-1.22.0'),response=await c.match(new URL(name,location.href).href);if(!response)throw Error('CACHE_ASSET_MISSING');return Array.from(new Uint8Array(await response.arrayBuffer()));},file),Math.min(10000,remaining()),'CACHE_READ'));const name=file==='./'?'index.html':file.replace(/^\.\//,'');assert(actual.equals(blob(p.source,name)));r.cache.push({file:name,sha256:sha(actual),gitEqual:true});}
 r.sourceArchivesUncached=await bounded(page.evaluate(async()=>{const c=await caches.open('drive-original-shell-1.22.0');return !(await c.keys()).some(req=>/\.tgz$|\.tar\.gz\.part\d+$/.test(new URL(req.url).pathname));}),Math.min(10000,remaining()),'CACHE_KEYS');assert(r.sourceArchivesUncached);await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded',timeout:Math.min(15000,remaining())});r.offline=await page.evaluate(()=>({version:APP_VERSION,controlled:!!navigator.serviceWorker.controller,accountPresent:!!state.accountId}));assert.deepEqual(r.offline,{version:'1.22.0',controlled:true,accountPresent:false});remaining();assert.equal(errors.length,0);r.pageErrors=0;
 }catch(error){r.failure=/^[A-Z0-9_]+$/.test(error.message)?error.message:error.code||error.name;r.failureDetail=error instanceof assert.AssertionError?{expectedType:typeof error.expected,actualType:typeof error.actual,operator:error.operator}:undefined;}
 finally{for(const request of requests)request.abort();r.cleanup.requestsSettled=requests.size===0;if(context)try{await bounded(context.close(),5000,'CONTEXT_CLOSE');r.cleanup.contextClosed=true;}catch{}if(browser)try{await bounded(browser.close(),5000,'BROWSER_CLOSE');r.cleanup.connectionClosed=true;}catch{}if(bs){try{await bounded(bs.close(),5000,'PROCESS_CLOSE');}catch{try{await bounded(bs.kill(),5000,'PROCESS_KILL');}catch{}}r.cleanup.ownedProcessExited=bs.process().exitCode!==null||bs.process().signalCode!==null;}r.cleanup.passed=r.cleanup.requestsSettled&&(!bs||(r.cleanup.contextClosed&&r.cleanup.connectionClosed&&r.cleanup.ownedProcessExited));r.finishedAt=new Date().toISOString();r.elapsedMs=Date.now()-started;r.passed=!r.failure&&r.cleanup.passed&&r.assets.length===65&&r.productionMode&&r.pageErrors===0&&r.elapsedMs<p.limits.verificationMs+p.limits.cleanupMs;r.localChecksPassed=true;save('served.json',r);}
 assert(r.passed,'PRODUCTION_SERVING_FAILED');return{passed:true,source:r.source,workerVersion:r.workerVersion,public:65,cache:r.cache.length,archives:9,private404:6,cold:r.cold,offline:r.offline,elapsedMs:r.elapsedMs,cleanup:r.cleanup};
}
const action=process.argv[2];assert(['prepare','deploy','readback','verify'].includes(action));assert.equal(process.argv.slice(3).join(' '),action==='prepare'?'':'--execute');Promise.resolve().then(()=>({prepare,deploy,readback,verify}[action]())).then(text=>console.log(JSON.stringify(text))).catch(error=>{try{save(action+'-failure.json',{passed:false,action,source:source(),code:error.code||error.name,message:/^[A-Z0-9_]+$/.test(error.message)?error.message:undefined,recordedAt:new Date().toISOString(),noAutomaticRetry:true});}catch{}console.error(JSON.stringify({passed:false,action,error:error.code||error.name,message:/^[A-Z0-9_]+$/.test(error.message)?error.message:undefined}));process.exitCode=1;});
