'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {reduce}=require('./source-receipt-sanitize.cjs'),binding=require('../rc31-resume-20261001/sourcebinding.json');
function fixture(){const target={id:'PRIVATE_ID',name:'PRIVATE_NAME',size:100,mimeType:'video/mp2t',modifiedTime:'PRIVATE_DATE',parents:['PRIVATE_PARENT'],version:'1',headRevisionId:'PRIVATE_REV'},account={accountId:'PRIVATE_ACCOUNT',authAccountKey:'PRIVATE_KEY'},controller={state:'activated'},native={},stats={generation:2,phase:'ready',failure:null,disposed:false};
 const player={stats:()=>stats},owner={player,kind:'ts',controller:{signal:{aborted:false}},swGeneration:9,session:4,account:account.authAccountKey,accountGeneration:3,swController:controller};
 const context={window:{__resumeReplayTarget30:{target,account},__resumeSwProof:{get:()=>({controller,version:binding.version,sourceCommit:binding.sourceCommit,sourceSHA256:binding.sourceSHA256})}},APP_VERSION:binding.version,navigator:{serviceWorker:{controller}},document:{visibilityState:'visible'},state:{...account,selected:target,driveSessionGeneration:3,mediaSession:4,frameCallbackId:1,mediaBlobUrl:'PRIVATE_BLOB'},el:{playerSheet:{hidden:false}},q1Playback:owner,q0Playback:null,q1Retirement:null,q1RetirementResult:null,mediaSourceGeneration:9,getActiveMediaElement:()=>native,isCurrentMediaEvent:v=>v===native};vm.createContext(context);
 const install=()=>vm.runInContext('('+fs.readFileSync(path.join(__dirname,'source-receipt.function.js'),'utf8')+')('+JSON.stringify({sourceCommit:binding.sourceCommit,version:binding.version,sourceSHA256:binding.sourceSHA256})+')',context);
 const retire=(counts={readsStarted:3,readsCompleted:2,metadataRequests:7,rangeRequests:3,receivedBytes:1024,releasedBytes:768})=>{stats.source=counts;stats.disposed=true;stats.phase='cancelled';owner.controller.signal.aborted=true;owner.retirement=Promise.resolve({settled:true});context.q1Retirement=owner.retirement;context.q1RetirementResult={settled:true};context.q1Playback=null;context.state.selected=null;context.state.mediaSession++;context.mediaSourceGeneration++;context.state.frameCallbackId=null;context.state.mediaBlobUrl=null;context.el.playerSheet.hidden=true;};
 return{context,stats,owner,install,retire,api:()=>context.window.__rc31CookieSourceReceipt};}
test('real TS lifecycle publication anchors show no live-source stats before EOF/normal disposal',()=>{
 const source=fs.readFileSync(path.resolve(__dirname,'../../media/ts-player.mjs'),'utf8');
 assert.equal((source.match(/state\.source=/g)||[]).length,2);assert.ok(source.includes('state.source=reader?.stats()||state.source;reader=null'));assert.ok(source.includes('state.source=reader.stats()'));assert.ok(source.includes('stats(){return latest?.state??null;}'));
 const fields={readsCompleted:null,rangeRequests:null,receivedBytes:null};assert.equal(!!fields&&fields.readsCompleted>0&&fields.rangeRequests>0&&fields.receivedBytes>0,false);
});
test('live counters stay null; same retained generation after normal retirement qualifies original byte Q1',()=>{
 const f=fixture(),before=f.install();assert.equal(before.preClose.sourceStatsPresent,false);assert.equal(before.preClose.counters.readsCompleted,null);assert.equal(before.preClose.counters.receivedBytes,null);f.retire();const r=f.api().retired();assert.equal(r.originalBytePathQualified,true);assert.equal(r.preClose.counters.rangeRequests,null);assert.equal(r.postClose.counters.readsCompleted,2);assert.equal(r.postClose.counters.receivedBytes,1024);assert.equal(r.scope,'Q1_ORIGINAL_BYTE_READ_ONLY');assert.equal(r.q0CookieCoverage,'UNKNOWN');assert.equal(r.postClose.fences.sameRetainedGeneration,true);assert.ok(!JSON.stringify(r).includes('PRIVATE_'));f.api().stop();assert.throws(()=>f.api().retired(),/SOURCE_RECEIPT_DISPOSED/);
});
test('read before disposal and changed retained generation cannot qualify',()=>{for(const mode of ['live','generation']){const f=fixture();f.install();if(mode==='generation'){f.retire();f.stats.generation++;}assert.equal(f.api().retired().originalBytePathQualified,false);}});
test('zero/incomplete/missing source counts remain false rather than turn null into zero',()=>{for(const counts of [undefined,{}, {readsCompleted:0,rangeRequests:2,receivedBytes:100},{readsCompleted:2,rangeRequests:0,receivedBytes:100},{readsCompleted:2,rangeRequests:2,receivedBytes:0}]){const f=fixture();f.install();f.retire(counts);if(counts===undefined)delete f.stats.source;assert.equal(f.api().retired().originalBytePathQualified,false);}});
test('source/account/retirement-owner changes after close reject positive old counters',()=>{for(const mutate of [f=>{f.context.state.authAccountKey='CHANGED';},f=>{f.context.navigator.serviceWorker.controller={state:'activated'};},f=>{f.context.q1Retirement={};},f=>{f.context.q1Playback={};}]){const f=fixture();f.install();f.retire();mutate(f);assert.equal(f.api().retired().originalBytePathQualified,false);}});
test('native stale owner and wrong target/generation rejected before retaining anything',()=>{for(const mutate of [f=>{f.context.isCurrentMediaEvent=()=>false;},f=>{f.owner.swGeneration++;},f=>{f.context.state.selected={id:'OTHER'};},f=>{f.owner.controller.signal.aborted=true;}]){const f=fixture();mutate(f);assert.throws(()=>f.install(),/SOURCE_RECEIPT_OWNER_ADMISSION/);assert.equal(f.context.window.__rc31CookieSourceReceipt,undefined);}});
test('gate projection cannot export extra private fields/objects/unsafe counters',()=>{const f=fixture();f.install();f.retire();const r=f.api().retired();r.token='PRIVATE_TOKEN';r.postClose.counters.readsCompleted=Infinity;r.postClose.url='PRIVATE_URL';const o=reduce(r);assert.equal(o.postClose.counters.readsCompleted,null);assert.ok(!JSON.stringify(o).includes('PRIVATE_'));assert.equal(o.q0CookieCoverage,'UNKNOWN');});
test('native replay and gate only add lifecycle receipt; frozen command/classifier/thresholds retained',()=>{
 const d=fs.readFileSync(path.join(__dirname,'normal-replay-attempt4.cjs'),'utf8'),old=fs.readFileSync(path.resolve(__dirname,'../rc31-android-cookie-gate/normal-replay.cjs'),'utf8');
 for(const s of ['},45000)','},35000)','await tapGeometry(card)',"c.adb(['shell','input','swipe'",'await close()','freshRevisionChecksumSame'])assert.equal(d.includes(s),old.includes(s));
 const {PARAMS,BUDGET_MS}=require('./gate-attempt4.cjs');assert.deepEqual(PARAMS,{enableThirdPartyCookieRestriction:true});assert.equal(BUDGET_MS,240000);assert.equal(typeof require('./root-execute-attempt4.cjs').execute,'function');assert.ok(d.indexOf('retainedSource=true')<d.indexOf('const closedSettled=await close()'));assert.ok(d.indexOf('originalReceipt=await ev')>d.indexOf('const closedSettled=await close()'));
 const p=require('./derivation.json');for(const[name,hash]of Object.entries(p.preservedAttempt3)){const bytes=fs.readFileSync(path.resolve(__dirname,'../rc31-android-cookie-gate',name));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),hash);}
});
